### ISSUE TITLE
Using a Connection String with Azure.Redis.Cache

### ISSUE THREAD

**Issue by danielHalan** [ServiceStack/Issues#106]
Would be nice to be able to use a connection string to initiate Clients against Azure Redis Cache, currently supported way is by providing an "Uri", Azure Password uses special chars and needs to be HttpUtility.UrlEncoded to be able to pass into an Uri, but ServiceStack.Redis does not UrlDecode the password.

**Comment by pooran** [comment]
I am getting this error - "Input string was not in a correct format."
what should be the correct connection string?  I regenerated password so that there are no special characters except '='

Below is the code

```
 public class CacheObject
    {
        public object Obj { get; set; }
        public DateTime Date { get; set; }
        public int WarmUp { get; set; } = 1;
    }
    public class CacheService
    {
        private static  RedisClient redisClient;
        public static string ConnectionString { get; set; } = "redis://LOsVojLKfi9gnMvJL65vudAAzasymS4iITqLHfkxrSk=@{host}.redis.cache.windows.net?ssl=true";

        public static RedisClient Current()
        {
            if (redisClient == null)
            {
                redisClient = new RedisClient(ConnectionString);
                return redisClient;
            }
            else
                return redisClient;
        }
        public static CacheObject Get(string key)
        {
            return Current().Get<CacheObject>(key);
        }

        public static void Set(string key, CacheObject obj, DateTime liveTill)
        {
            Current().Set(key, obj,liveTill);
        }
    
```}

**Comment by mythz** [comment]
Here are the [supported connection string formats](https://github.com/ServiceStack/ServiceStack.Redis#redis-connection-strings), with more examples available from [ConfigTests.cs](https://github.com/ServiceStack/ServiceStack.Redis/blob/master/tests/ServiceStack.Redis.Tests/ConfigTests.cs).

If your password have special chars like `=`, you can [urlencode it in ?password={encodedpass}](https://github.com/ServiceStack/ServiceStack.Redis/blob/master/tests/ServiceStack.Redis.Tests/ConfigTests.cs#L100).
