### ISSUE TITLE
After upgrading to ServiceStack to 4.0.24.0, I started receiving this below error when trying to login using Google OAuth.

### ISSUE THREAD

**Issue by vijaysirigiri** [ServiceStack/Issues#124]
![azuregoogleoauth](https://cloud.githubusercontent.com/assets/7839742/3844609/c882288e-1e4a-11e4-90bc-68cb1407751b.png)

The same works locally on my dev machine. Has anything changed since the 4.0.21.0?

--The site is hosted on Azure as you can see from the address bar.
--I've the licensed version of SS
--Google OAuth Callback url is correctly registered http://somesite.azurewebsites.net/auth/GoogleOAuth
--Using ServiceStack.Authentication.OAuth2 4.0.24.0

**Comment by WoNd3RBoY** [comment]
Hi guys,

We are having the same issue here and it has to do with IIS integrated pipeline mode. When switching to classic mode GoogleOAuth works.

Now, in our situation we need to be running in integrated mode as there are advantages and plus we want to run run SignalR! It would be a bummer if ServiceStack that we carefully selected as our platform technology simply fails on this point.

I would consider this an important issue, or we are simply overlooking something and would really appreciate any help resolving it.

Thanks

**Comment by Formator** [comment]
Hi guys,

We are having the same issue here and it has to do with IIS integrated pipeline mode. When switching to classic mode GoogleOAuth works.

Now, in our situation we need to be running in integrated mode as there are advantages and plus we want to run run SignalR! It would be a bummer if ServiceStack that we carefully selected as our platform technology simply fails on this point.

I would consider this an important issue, or we are simply overlooking something and would really appreciate any help resolving it.

Thanks

**Comment by mythz** [comment]
@Formator Please open a new issue with a link to stand-alone project that can be run locally to repro the issue.

**Comment by Formator** [comment]
@mythz Thank you for your replay, I will setup new project to reproduce this error on Azure, because it can't be reproduce on local.
