### ISSUE TITLE
ServerEventsClient: After some time the clients won't receive any events

### ISSUE THREAD

**Issue by soernt** [ServiceStack/Issues#170]
ServerEventsClient: After some time the clients won't receive any events

ServiceStack: 4.0.32 (both client & server side)
Server: Windows 2012
Redis: 2.8.12 (64 BIT)

I create a service which sends events to authenticated clients.
I use Xamarain.Forms to create an iOS and Android project the app only displays the received events (OnException, OnConnect, OnCommand, OnHeartbeat and OnMessage) within a ListView.
Both clients authenticate with the same credentials and subscribe to the same channel. The clients received the events form the server - so far all works as expected.
The server sends events in irregular intervalls: There a periods where the server sends ~10 events very fast and there a periods (~2 minutes) where no events send at all.

I started the app at a Nexus 7 and an IPad Mini. At first both received the same events, but after sometime (5 ~ 10 minutes) one client won't receive any messages while the other did and if you wait long enough both won't receive any messages. I see that both client's are still react for the "onHeartbeat" Action. At the same time I didn't see any exceptions at the server side.

I can provide the sources for the client application.

Sörnt

**Comment by RobSchoenaker** [comment]
Trying this exact same thing on 4.0.38. Same issue.
It seems that the Heartbeat is never fired. So, no wonder the client gets disconnected.

I can send a test case if you want.
