### ISSUE TITLE
Different Servicestack path gets redirected to unexisting metadada root

### ISSUE THREAD

**Issue by sandrogentile** [ServiceStack/Issues#18]
Not sure if it's a real issue but when hosting servicestack on a different path and asking for the root url it gets redirected to unexisting metadada root.
Example:
hosting servicestack at "api" (web.config <location path="api">) and asking for
sitename:port/api (ex:localost:9752/api) you get redirected to /api/api/metadata (two times api) while the correct redirection path is /api/metadata.

Servicestack version 4.0.7

**Comment by SMASH1337** [comment]
My team is having an issue with this as well but would rather not use pre-release builds. Is there anything we can do outside of updating to an pre-release?

**Comment by mythz** [comment]
@SMASH1337 Not if it required code changes. But this has been resolved over a year old, so it's unlikely this issue. But I would check the MyGet packages to see if it's still an issue with the latest version.
