### ISSUE TITLE
Licence Registration of ServiceStack.Text throws a exception in Xamarin iOS

### ISSUE THREAD

**Issue by Vasbi** [ServiceStack/Issues#193]
When trying to register the licence in xamarin iOS, a null exception is thrown.

I am calling this in app delegate
Licensing.RegisterLicense(<LICENCETEXTHERE>);

System.TypeInitializationException: An exception was thrown by the type initializer for ServiceStack.LicenseUtils ---> System.NullReferenceException: Object reference not set to an instance of an object   at ServiceStack.LicenseUtils..cctor () [0x00000] in <filename unknown>:0    --- End of inner exception stack trace ---

**Comment by skimania** [comment]
I'm trying to do this on a Xamarin plain old .Net project and getting the same error. Is there a different PclExport I need to set up?
