### ISSUE TITLE
TypeScript ServiceStack Reference does not generate TEntity for request which implements IReturn<List<TEntity>>

### ISSUE THREAD

**Issue by GuillaumeSalles** [ServiceStack/Issues#212]
Hi

ServiceStack version : 4.0.34.0

Typescript Reference does not generate TEntity for request which implements IReturn < List< TEntity>>

For the following exemple, Customer is not generated : 

```
    public class Customer
    {
        public string Name { get; set; }
    }

    [Route("/customers")]
    public class GetCustomersRequest : IReturn<List<Customer>>
    {

    }
```

Maybe it will help, the type List< Customer> seems to be ignored by the condition line 153 in the file 
https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/NativeTypes/NativeTypesMetadata.cs

Thank you for your help.

**Comment by mythz** [comment]
Hi, this should now be fixed with this commit: https://github.com/ServiceStack/ServiceStack/commit/44be26e733d35655d25ba19679fa44f8bbf00fe9

Which is available from v4.0.36+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by bumblebeeman** [comment]
@mythz This is still an issue for me, using 4.0.46

**Comment by mythz** [comment]
I've added a new example [in this commit](https://github.com/ServiceStack/ServiceStack/commit/c9309f497a906b4a0a4b1cee425c500fa9c3c14f) which is correctly emitting the `OnlyInReturnListArg` Type:

```typescript
interface OnlyInReturnListArg
{
    result?: string;
}

interface HelloReturnList implements IReturn<OnlyInReturnListArg[]>
{
    names?: string[];
}
```

Can you provide an example that's not working?
