### ISSUE TITLE
When using SingleAsync sometimes I get an exception when trying to read a row with a byte array

### ISSUE THREAD

**Issue by wastaz** [ServiceStack/Issues#213]
This does not occur for me in 4.0.33, but it does occur in 4.0.35. I'm testing this on a SQL Server 2008 R2 - not sure if it is database-dependent or not.

It is depending on the size of the byte array, if I have a byte[256] then it passes, but with a byte [1024*1024] it fails. This also seems to be limited to SingleAsync, if I change SingleAsync to SelectAsync then it passes.

Gist with a failing test:
https://gist.github.com/wastaz/69f07a2ddd6fb63b2370

**Comment by mythz** [comment]
Hi Fredrik,

This should now be fixed and your test now passes [with this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/94ff51b0d69c8e24e51bbbac44f0b50269686346). This change is available from v4.0.36+ that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Thanks for the failing test!
