### ISSUE TITLE
OrmLite v4.0.35.0: SQLite select statement is incorrect when using Schema attibute

### ISSUE THREAD

**Issue by yuriy-nelipovich** [ServiceStack/Issues#215]
Preconditions:
* using SqliteOrmLiteDialectProvider
* Selecting multiple columns across joined tables
* joined tables have [Schema()] attribute defined

Result:
generated SELECT statement is malformed (System.Data.SQLite.SQLiteException: SQL logic error or missing database
no such column: Entity1.Id)
SELECT "Entity1"."Id" as "Entity1Id", "Entity2"."Id" as "Entity2Id" 
FROM "schema1_Entity1" INNER JOIN "schema1_Entity2" ON ("schema1_Entity1"."Entity2Fk" = "schema1_Entity2"."Id")

Here is a code to reproduce the bug:

		using System.Data;
		using Microsoft.VisualStudio.TestTools.UnitTesting;
		using ServiceStack.DataAnnotations;
		using ServiceStack.OrmLite;

		namespace FPT.BusinessLogic.Tests.Queries.GlobalContext
		{
			[TestClass]
			public class SqlLiteWithSchemaTest
			{
				private OrmLiteConnectionFactory _factory;
				private IDbConnection _connection;

				[TestMethod]
				public void ThisTestFails()
				{
					_connection.Select<PlainModel>(
						_connection.From<Entity1>()
							.Join<Entity2>((e1, e2) => e1.Entity2Fk == e2.Id));
				}

				[TestInitialize]
				public void Setup()
				{
					_factory = new OrmLiteConnectionFactory(":memory:", SqliteDialect.Provider, true)
					{
						AutoDisposeConnection = false,
					};

					_connection = _factory.CreateDbConnection();

					if (_connection.State == ConnectionState.Closed)
					{
						_connection.Open();
					}

					_connection.DropAndCreateTable<Entity1>();
					_connection.DropAndCreateTable<Entity2>();
				}

				[Schema("schema1")]
				public class Entity1
				{
					public int Id { get; set; } 

					public int Entity2Fk { get; set; } 
				}

				[Schema("schema1")]
				public class Entity2
				{
					public int Id { get; set; } 
				}

				public class PlainModel
				{
					public int Entity1Id { get; set; } 

					public int Entity2Id { get; set; } 
				}
			}
		}

**Comment by mythz** [comment]
Hi,

This should now be [resolved with this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/bd3ad95f1dddc57db9ee45aa656f5d0364dcf432) which is available from v4.0.36+ that's [now available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Thanks for the failing test!
