### ISSUE TITLE
Session Id is not preserved when using Digest provider.

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#217]
Inside DigestAuthProvider.TryAuthenticate session Id is overwritten when calling PopulateWith.

Can be resolved in the same way as in Credentials auth provider ( see "holdSessionId").

**Comment by mythz** [comment]
Thanks, this was [changed in this commit](https://github.com/ServiceStack/ServiceStack/commit/a7ba8a41a2808ff807647632cf53e3d7b0eecd66).

This change is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)

Thx for reporting!
