### ISSUE TITLE
ServiceStack.Text JsonObject.ArrayObjects returns invalid results for string arrays

### ISSUE THREAD

**Issue by svantreeck** [ServiceStack/Issues#218]
When using JsonObject.Parse(<value>), and if one of the subsequent properties has a string array of values, retrieving the values does not seem to work as expected.  In the example below, I'd expect that calling ArrayObjects would return "value1" and "value2"; however, it seems to strip the 'v' character off of the returned values.  I can work around it with JsonTo<string[]> (which might be the preferable way?), but the documentation is not clear on how you would consume this data.

            var data = new { key = new string[] { "value1", "value2" } };
            var result = JsonSerializer.SerializeToString(data);

            result.Should().Be(@"{""key"":[""value1"",""value2""]}");

            var value = JsonObject.Parse(result);
            //var dataObjects = value.JsonTo<string[]>("key");
            var dataObjects = value.ArrayObjects("key");

            // dataObjects.Keys = "alue1", "alue2"
            dataObjects.Should().Contain("value1");
            dataObjects.Should().Contain("value2");

**Comment by mythz** [comment]
It's not an array of objects, it's an array of string which you can parse with:

```csharp
var data = new { key = new[] { "value1", "value2" } };
var json = data.ToJson();

Assert.That(json, Is.EqualTo(@"{""key"":[""value1"",""value2""]}"));

var value = JsonObject.Parse(json);
var dataObjects = value.Get<string[]>("key");

Assert.That(dataObjects[0], Is.EqualTo("value1"));
Assert.That(dataObjects[1], Is.EqualTo("value2"));
```
