### ISSUE TITLE
HttpCompileException for Razor view after moving to Mono 3.12.0

### ISSUE THREAD

**Issue by jpasichnyk** [ServiceStack/Issues#219]
After upgrading to Mono 3.12.0, website fails to load and throws this for all Views.  No other changes were made.  Works fine on 3.10.0.

```
Response Status

    Error Code
        HttpCompileException
    Message
        External exception
    Stack Trace
        [DefaultRequest: 01/23/2015 22:51:36]: [REQUEST: {}] System.Web.HttpCompileException: External exception at ServiceStack.Razor.Compilation.RazorPageHost.Compile () [0x00000] in <filename unknown>:0 at ServiceStack.Razor.Managers.RazorViewManager.EnsureCompiled (ServiceStack.Razor.Managers.RazorPage page) [0x00000] in <filename unknown>:0 
    Errors
```

After trying to load a few times, I then get:
```
Response Status

    Error Code
        SystemException
    Message
        Error running mcs: Out of memory
    Stack Trace
        [GlobalProblemForMediaPublishersRequest: 01/23/2015 22:53:14]: [REQUEST: {}] System.SystemException: Error running mcs: Out of memory at Mono.CSharp.CSharpCodeCompiler.CompileFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromFileBatch (System.CodeDom.Compiler.CompilerParameters options, System.String[] fileNames) [0x00000] in <filename unknown>:0 at Mono.CSharp.CSharpCodeCompiler.CompileFromDomBatch (System.CodeDom.Compiler.CompilerParameters options, System.CodeDom.CodeCompileUnit[] ea) [0x00000] in <filename unknown>:0 at Mono.CSharp.CSharpCodeCompiler.CompileAssemblyFromDomBatch (System.CodeDom.Compiler.CompilerParameters options, System.CodeDom.CodeCompileUnit[] ea) [0x00000] in <filename unknown>:0 at System.CodeDom.Compiler.CodeDomProvider.CompileAssemblyFromDom (System.CodeDom.Compiler.CompilerParameters options, System.CodeDom.CodeCompileUnit[] compilationUnits) [0x00000] in <filename unknown>:0 at ServiceStack.Razor.Compilation.RazorPageHost.Compile () [0x00000] in <filename unknown>:0 at ServiceStack.Razor.Managers.RazorViewManager.EnsureCompiled (ServiceStack.Razor.Managers.RazorPage page) [0x00000] in <filename unknown>:0 at ServiceStack.Razor.Managers.RazorPageResolver.CreateRazorPageInstance (IRequest httpReq, IResponse httpRes, System.Object dto, ServiceStack.Razor.Managers.RazorPage razorPage) [0x00000] in <filename unknown>:0 at ServiceStack.Razor.Managers.RazorPageResolver.ExecuteRazorPage (IRequest httpReq, IResponse httpRes, System.Object model, ServiceStack.Razor.Managers.RazorPage razorPage) [0x00000] in <filename unknown>:0 at ServiceStack.Razor.Managers.RazorPageResolver.ProcessRequest (IRequest httpReq, IResponse httpRes, System.Object dto) [0x00000] in <filename unknown>:0 at ServiceStack.Formats.HtmlFormat+<>c__DisplayClass2.<SerializeToStream>b__0 (IViewEngine x) [0x00000] in <filename unknown>:0 at System.Linq.Enumerable.Any[IViewEngine] (IEnumerable`1 source, System.Func`2 predicate) [0x00000] in <filename unknown>:0 at ServiceStack.Formats.HtmlFormat.SerializeToStream (IRequest request, System.Object response, IResponse httpRes) [0x00000] in <filename unknown>:0 
    Errors```

Thoughts?

**Comment by mythz** [comment]
I've just a couple of the Razor Projects on the latest stable version of Xamarin Studio which uses the latest 3.12.0 and they're working fine:

![screen shot 2015-01-26 at 1 21 00 am](https://cloud.githubusercontent.com/assets/89361/5895918/d58dd60a-a4f9-11e4-922c-81b35183bfb1.png)

Can you put together a small app that exhibits this issue, thx.

**Comment by jpasichnyk** [comment]
Will do, might be a bit though...

**Comment by mythz** [comment]
ok no worries, re-open this thread when you have something.

**Comment by jpasichnyk** [comment]
@mythz - just to follow up on this...

It turns out it wasn't 3.12 related at all, and looks to be some error with one or more of my views compiling, that compile/run fine on windows/visual studio.  I haven't been able to isolate the compile issue, but we've had similar issues in the past.  It will run fine in xsp but for some reason, the same code fails when running via fastcgi-mono-server4.  Is there something different done here as far as batch compilation of views, and if so is there a way to control this behavior?

On a more positive note, I found https://github.com/ServiceStack/ServiceStack/wiki/Compiled-Razor-Views, and gave that a try, and it works perfectly!  One question I have is around the need to deploy the .cshtml view files, as my views all reside in my core website project (just loaded up with typeof(AppHost).Assembly.  The wiki says that it sets them all to Content and adds the build task to compile them, but assuming for a production site I can skip deployment of .cshtml files (seems to work if i delete them off a dev server)?  If so, whats the ideal work flow here?   Any downside with running on the compiled views, or is it preferred method as far as you're concerned?

**Comment by mythz** [comment]
There are a couple of options you might be able to try in [RazorFormat](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Razor/RazorFormat.cs) like disabling `LiveReload` and setting `WaitForPrecompilationOnStartup` but not sure if that's going to have any effect.

For the compiled razor views I just put them in a separate assembly and reference it like a normal project reference/dll. You shouldn't need to deploy the *.cshtml files. I've got a couple of example projs that use Compiled Razor views in Razor Rockstars:
https://github.com/ServiceStackApps/RazorRockstars/tree/master/src

And the embedded [ServiceStack.Gap](https://github.com/ServiceStack/ServiceStack.Gap) version of [Http Benchmarks Analayzer](https://github.com/ServiceStack/ServiceStack.Gap/tree/master/src/BenchmarksAnalyzer/BenchmarksAnalyzer.Resources)
