### ISSUE TITLE
Deserialization problem

### ISSUE THREAD

**Issue by riccardod** [ServiceStack/Issues#220]
Hi Demis,
I think there could be some problem in Servicestack deserialisation to dynamic objects.
I created a two small tests here where in one test I use the System.Web.Helpers.JsonDecode and it deserialises correcly while the other uses SS and gives an error.

https://gist.github.com/riccardod/2c778fb29a740b38963d

**Comment by mythz** [comment]
That's not valid JSON, which requires every property to be quoted. 
Correct JSON looks like:

```csharp
    var json = @"
        {
            ""projects"":[
                {
                    ""name"": ""Project1""
                },
                {
                    ""name"": ""Project2""
                },
                {
                    ""name"": ""Project3""
                }
            ]
        }";

    var projects = JsonObject.Parse(json).ArrayObjects("projects");

    var proj3Name = projects[2].Get("name");

    Assert.That(proj3Name, Is.EqualTo("Project3"));
```

Also `JsonObject` is the API that can be used to parse JSON dynamically. DynamicJson is only for simple json objects, i.e. it doesn't support traversing nested JSON objects.
