### ISSUE TITLE
Unable to deleteall under transaction

### ISSUE THREAD

**Issue by maxgrante** [ServiceStack/Issues#223]
Hi,
I can't delete all objects of type under transaction:
For example:

```csharp
public void StoreBrands(IList<BrandDTO> brands)
{
    using (var trans = _redis.CreateTransaction())
    {
        trans.QueueCommand(r => r.SetEntry(_listGetBrands, "OK", _longExpire));
        trans.QueueCommand(r => r.DeleteAll<BrandDTO>());
        trans.QueueCommand(r => r.StoreAll(brands));
        trans.Commit();
    }
}
```

The second statement doesn't work.
If I call the DeleteAll command out of transaction work fine.

I use ServiceStack.Redis version 4.0.36 with Windows 8.1 professional under IIS and .NET framework 4.5.1.

Can you help me?

**Comment by mythz** [comment]
The issue is because [transactions in Redis](http://redis.io/topics/transactions) doesn't allow reads, it only allows sending multiple operations which all gets batched and sent in one operation.

The [DeleteAll<T> API](https://github.com/ServiceStack/ServiceStack.Redis/blob/e4705e2402a812c61fe7b1f8a4fbcba4862ea233/src/ServiceStack.Redis/RedisClient.cs#L762) needs to get all the items ids from the backing set to delete all the items and the ids set, e.g:

```csharp
public void DeleteAll<T>()
{
    var typeIdsSetKey = this.GetTypeIdsSetKey<T>();
    var ids = this.GetAllItemsFromSet(typeIdsSetKey);
    if (ids.Count > 0)
    {
        var urnKeys = ids.ToList().ConvertAll(UrnKey<T>);
        this.RemoveEntry(urnKeys.ToArray());
        this.Remove(typeIdsSetKey);
    }
}
```

So you need to perform all your reads before the transactions and then you can add the writes apart of the transaction, e.g:

```csharp
public void StoreBrands(IList<BrandDTO> brands)
{
    var typeIdsSetKey = _redis.GetTypeIdsSetKey<BrandDTO>();
    var ids = _redis.GetAllItemsFromSet(typeIdsSetKey);
    var urnKeys = ids.ToList().ConvertAll(UrnKey<BrandDTO>).ToArray();

    using (var trans = _redis.CreateTransaction())
    {
        trans.QueueCommand(r => r.SetEntry(_listGetBrands, "OK", _longExpire));
        trans.QueueCommand(r => r.StoreAll(brands));
        if (urnKeys.Length)
        {
            trans.QueueCommand(r => r.RemoveEntry(urnKeys));
            trans.QueueCommand(r => r.Remove(typeIdsSetKey));
        }
        trans.Commit();
    }
}
```

**Comment by maxgrante** [comment]
I Mythz,
thank you and i'm sorry for the epic fail! :-)
I've modify my code with your but i've problems:
Error	1	'ServiceStack.Redis.IRedisClient' does not contain a definition for 'GetTypeIdsSetKey' and no extension method 'GetTypeIdsSetKey' accepting a first argument of type 'ServiceStack.Redis.IRedisClient' could be found (are you missing a using directive or an assembly reference?)

Method UrnKey<BrandDTO> doesn't exist.

I need some assembly?

**Comment by mythz** [comment]
ok sorry wrote this without a compiler, you'll need to cast it to the concrete `RedisClient`, and you can use the `T.CreateUrn()` extension method to create the urn string, i.e: 

```csharp
var typeIdsSetKey = (RedisClient)_redis.GetTypeIdsSetKey<BrandDTO>();
var ids = _redis.GetAllItemsFromSet(typeIdsSetKey);
var urnKeys = ids.ToList().ConvertAll(x => x.CreateUrn()).ToArray();

using (var trans = _redis.CreateTransaction())
{
    trans.QueueCommand(r => r.SetEntry(_listGetBrands, "OK", _longExpire));
    trans.QueueCommand(r => r.StoreAll(brands));
    if (urnKeys.Length > 0)
    {
        trans.QueueCommand(r => r.RemoveEntry(urnKeys));
        trans.QueueCommand(r => r.Remove(typeIdsSetKey));
    }
    trans.Commit();
}
```

**Comment by maxgrante** [comment]
Thank you, all work fine!
Best regards, Max
