### ISSUE TITLE
OrmLite.T4 templates don't process the size of nvarchar columns correctly for a SQL server table

### ISSUE THREAD

**Issue by wbrussell** [ServiceStack/Issues#224]
The OrmLite.T4 templates don't process the size of nvarchar columns correctly for a SQL server database table.  Example column type NVARCHAR(256).  Col.Size calculated is always -1, so the [StringLength(256)] attribute is never added to the POCO properties.

When the columns props are queried in sql (see image), the dataType only contains the "nvarchar" type but the code is expecting additional data in this field for size and precision.  The maxLength column should be the size.

I suspect the precision calculation might be wrong and maybe varchar types as well.
(ormlite.core.ttinclude)...
```
	List<Column> LoadColumns(Table tbl)
	{

		using (var cmd=_factory.CreateCommand())
		{
			cmd.Connection=_connection;
			cmd.CommandText=COLUMN_SQL;

			var p = cmd.CreateParameter();
			p.ParameterName = "@tableName";
			p.Value=tbl.Name;
			cmd.Parameters.Add(p);

			p = cmd.CreateParameter();
			p.ParameterName = "@schemaName";
			p.Value=tbl.Schema;
			cmd.Parameters.Add(p);

			var result=new List<Column>();
			using (IDataReader rdr=cmd.ExecuteReader())
			{
				while(rdr.Read())
				{
					Column col=new Column();
					col.Name=rdr["ColumnName"].ToString();
					col.PropertyName=CleanUp(col.Name);
					col.PropertyType=GetPropertyType(rdr["DataType"].ToString());
					col.Size=GetDatatypeSize(rdr["DataType"].ToString());
					col.Precision=GetDatatypePrecision(rdr["DataType"].ToString());
					col.IsNullable=rdr["IsNullable"].ToString()=="YES";
					col.IsAutoIncrement=((int)rdr["IsIdentity"])==1;
					col.IsComputed=((int)rdr["IsComputed"])==1;                    
					result.Add(col);
				}
			}

			return result;
		}
	}
```

![image](https://cloud.githubusercontent.com/assets/5246288/5944513/d12cf64e-a6e4-11e4-9bce-3468a1ba32d8.png)

**Comment by mythz** [comment]
Why do you need the `[StringLength]` attribute when generating types for existing tables? The `[StringLength]` attribute is used creating the tables, but why do you need them if they already exist?

**Comment by wbrussell** [comment]
My intent was to use the output POCO to generate SQLite tables from the legacy SQL.  I haven't tried, but I assume if there is no size specified, the column will be nvarchar(max) or the max size for other db providers.

I was also assuming that that attribute might be used in validation similar to how EF annotates properties, but that is probably not the case here.

I any case, what is in there in code isn't right (or at least not what I was expecting).  I was able to make the mods for SQL and get the expected output, but my changes probably would have broken other database provider output.

I'm new to OrmLite so bear with me...

**Comment by mythz** [comment]
Ok cool. No `[StringLength]` isn't used for validation, just for DDL in Create Table statements.

But happy to see the changes you've made to calculate it from SqlServer.

**Comment by mythz** [comment]
Feel free to add any custom logic you're using for SqlServer, but going to close this as adding `[StringLength]` for every property unnecessarily uglifies the generated POCO's for little value.
