### ISSUE TITLE
OrmLite throws "Potential illegal fragment detected" on CAST for SQL Server

### ISSUE THREAD

**Issue by farzadpanahi** [ServiceStack/Issues#227]
I am trying to `CAST` an integer column to varchar to do a `LIKE` comparison but OrmLite is throwing `Potential illegal fragment detected` exception even though the where clause is valid and runs on sql server fine.

This is the where clause:
               ` q.Where("cast(IntCol as varchar) LIKE '%2065%'");`

And here is the exception: 

    System.ArgumentException: Potential illegal fragment detected: cast(IntCol as varchar)  LIKE '%2065%'
    Result StackTrace:	
    at ServiceStack.OrmLite.OrmLiteUtils.SqlVerifyFragment(String sqlFragment, IEnumerable`1 illegalFragments)
       at ServiceStack.OrmLite.SqlExpression`1.Where(String sqlFilter, Object[] filterParams)

**Comment by mythz** [comment]
You can control what tokens are considered illegal by modifying the [OrmLiteUtils.IllegalSqlFragmentTokens](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite/OrmLiteUtils.cs#L184) collection.

In the latest [v4.0.37+ on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet) you can by-pass verification with the new `Unsafe*` API's, e.g:

```csharp
q. UnsafeWhere("cast(IntCol as varchar) LIKE '%2065%'");
```
