### ISSUE TITLE
CSV download UTF 8 format Config settings

### ISSUE THREAD

**Issue by jagjotocrex** [ServiceStack/Issues#228]
Hi,

I am getting some special characters in the data when I download it in csv format. When I checked, I found that it is in UTF without BOM. When I modified the encoding (using Notepad++) then the special characters were not there. I tried modified the configuration settings by using this code in AppHost.cs file.

SetConfig(new HostConfig
            {
                AppendUtf8CharsetOnContentTypes = new HashSet<string> { MimeTypes.Csv } 
            });

But I am still getting same results and file encoding is still UTF without BOM. Please let me know where I can make other changes to fix this issue. If more details are required, I can provide that.

Thanks,
Jagjot

**Comment by mythz** [comment]
FYI I've answered your initial question at: http://stackoverflow.com/a/28309960/85785

The Text Serializers are hardcoded to omit the UTF8 BOM as it causes several issues with clients and tools that treat the UTF8 BOM as a corrupted character.

I can add support to make it configurable but I would like to confirm that this is the issue and emitting the UTF8 BOM would resolve your issue?

**Comment by jagjotocrex** [comment]
Hi Mythz,

I have created a video of the issue which I am facing. I have detailed issue there. Please have a look.
http://screencast.com/t/tKmdgq75

**Comment by mythz** [comment]
Hi,

I've made the UTF8Encoding use configurable in this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/700a42dcc7e7f7bb3c8316f6f904fb068f72fcc9

This will let you enable the UTF8 BOM for the CSV Serializer with:

```csharp
CsvSerializer.UTF8Encoding = new UTF8Encoding(true);
```

This change is available from **v4.0.37+** that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
