### ISSUE TITLE
ServiceStack is not CLS compliant

### ISSUE THREAD

**Issue by heck4** [ServiceStack/Issues#229]
If I add this attribute to any project that uses ServiceStack, I get a bunch of warnings.
[assembly: CLSCompliant(true)]

Warnings:

\FrontApiService.cs(6,18,6,33): warning CS3009: 'FrontApiService': base type 'ServiceStack.Service' is not CLS-compliant

AppHost.cs(24,40,24,49): warning CS3001: Argument type 'Funq.Container' is not CLS-compliant

AppHost.cs(8,18,8,25): warning CS3009: 'AppHost': base type 'ServiceStack.AppHostBase' is not CLS-compliant

AppHost.cs(8,18,8,25): warning CS3009: 'AppHost': base type 'ServiceStack.ServiceStackHost' is not CLS-compliant

**Comment by mythz** [comment]
We've no desire to add any arbitrary artificial naming restrictions or imposed code-styles to our API's or code-base. 

ServiceStack already runs fine cross-platform on Windows/OSX/Linux and the [Service Clients support a number of client platforms](https://github.com/ServiceStackApps/HelloMobile). The CLSCompliant attribute doesn't help with this in practice.

**Comment by heck4** [comment]
Understood. Thanks for the quick response.
