### ISSUE TITLE
Headers have already been sent

### ISSUE THREAD

**Issue by asilvaubiquity** [ServiceStack/Issues#230]
I've a service working on Windows that when deployed on Linux gives the following error:

System.Web.HttpException
Headers have already been sent
Description: HTTP 500.Error processing request.
Details: Error processing request.
(exception stack trace at then end of this message)

This is the code that returns the response:
return new HttpResult("Not authenticated.", HttpStatusCode.Unauthorized);

And I noticed that if I send
return "Not authenticated."
it works.

Any clue on this?
Thanks

Exception stack trace:
  at System.Web.HttpResponse.Redirect (System.String url, Boolean endResponse, Int32 code) [0x00000] in <filename unknown>:0 
  at System.Web.HttpResponse.Redirect (System.String url, Boolean endResponse) [0x00000] in <filename unknown>:0 
  at System.Web.Security.FormsAuthenticationModule.OnEndRequest (System.Object sender, System.EventArgs args) [0x00000] in <filename unknown>:0 
  at (wrapper delegate-invoke) <Module>:invoke_void__this___object_EventArgs (object,System.EventArgs)
  at (wrapper delegate-invoke) <Module>:invoke_void__this___object_EventArgs (object,System.EventArgs)
  at (wrapper delegate-invoke) <Module>:invoke_void__this___object_EventArgs (object,System.EventArgs)
  at System.Web.HttpApplication.PipelineDone () [0x00000] in <filename unknown>:0

**Comment by mythz** [comment]
The exception says it's coming from ASP.NET's `FormsAuthenticationModule`. 

Some docs on disabling Forms hijacking are at: https://github.com/ServiceStack/ServiceStack/wiki/Form-Hijacking-Prevention

**Comment by asilvaubiquity** [comment]
I read the doc on disabling forms hijacking you referred and some other resources on the subject but I'm not able to put this to work.

public override void Configure(Funq.Container container)
{
    var appConfig = new AppConfig(AppSettings);
    container.Register(appConfig);  

    SetConfig(new HostConfig {
        HandlerFactoryPath = "/yourapipath",
    });

    //this is the configuration for Hijacking prevention
    SuppressFormsAuthenticationRedirectModule.PathToSupress = config.HandlerFactoryPath;
}

Some doubts:

1 - What is the assembly / namespace of AppConfig ? It doesn't seems to be from ServiceStack (I made a search on ServiceStack source) but I don't find it at .Net either

2 - Why is it necessary to register the AppConfig it in the container?

3 - Why to set a new config. How does it work if previous configuration were previously made? 

4 - To my knowledge would code something like this. What is it wrong with this?

public override void Configure(Funq.Container container)
{
            Config.HandlerFactoryPath = "/yourapipath";
            SuppressFormsAuthenticationRedirectModule.PathToSupress = Config.HandlerFactoryPath;
}

**Comment by mythz** [comment]
Yeah you don't need `AppConfig` that's just a custom strong-typed Config class which didn't have anything to do that with that example so I just removed it.

But you should use SetConfig() api, for changing configuration e.g:

```csharp
SetConfig(new HostConfig {
    HandlerFactoryPath = "/yourapipath",
});

//this is the configuration for Hijacking prevention
SuppressFormsAuthenticationRedirectModule.PathToSupress = config.HandlerFactoryPath;
```

**Comment by mythz** [comment]
Closing as this is due to default ASP.NET behavior happening after ServiceStack processes the request.

**Comment by asilvaubiquity** [comment]
The doc https://github.com/ServiceStack/ServiceStack/wiki/Form-Hijacking-Prevention has an error:

Instead of:

<system.web>
    <modules>
      <add name="FormsAuthenticationDisposition" type="ServiceStack.SuppressFormsAuthenticationRedirectModule, ServiceStack" />
    </modules>
</system.web>

It should be:
<system.web>
    <httpModules>
      <add name="FormsAuthenticationDisposition" type="ServiceStack.SuppressFormsAuthenticationRedirectModule, ServiceStack" />
    </httpModules>
</system.web>
