### ISSUE TITLE
Setting cookies forces Cache-Control header to "private"

### ISSUE THREAD

**Issue by rudism** [ServiceStack/Issues#231]
It seems like the Cache-Control header on the response always reverts to "private" if you also set response cookies during the same request. We're using ServiceStack 4.0.36. I am able to reproduce the problem reliably under Windows 7, hosting on either IIS Express from within Visual Studio 2013 or IIS 7.5, building against .NET 4.5.

It's simple to reproduce by creating a new "ServiceStack ASP.NET Empty" project from the templates. Adding the following to the `AppHost.Configure` method definition will work:

    GlobalResponseFilters.Add((req, resp, dto) =>
    {
        resp.AddHeader("Cache-Control", "no-cache");
    });

Making a GET request to the example service at `/hello/dude` will result in (among others) the following header being sent:

    Cache-Control: no-cache

If you modify the `AppHost.Configure` code to this instead, it no longer works:

    GlobalResponseFilters.Add((req, resp, dto) =>
    {
        resp.SetCookie("test", Guid.NewGuid().ToString(), TimeSpan.FromDays(1));
        resp.AddHeader("Cache-Control", "no-cache");
    });

Now making a GET request to the default service at `/hello/dude` results in (among others) these headers being sent:

    Cache-Control: private
    Set-Cookie: test=4fecf028-af32-4ca0-b42b-2638c2c71be6; expires=Thu, 12-Feb-2015 15:58:12 GMT; HttpOnly

Switching the order of `resp.SetCookie` and `resp.AddHeader` in the response filter does not make any difference. This behavior is also not limited to ResponseFilters--the same behavior is observed when we set the header and cookie directly within services or elsewhere in the code.

The expected behavior here is that adding a Cache-Control header should be consistently respected regardless of whether cookies are also set or not.

**Comment by mythz** [comment]
This behavior automatically done by the underlying ASP.NET Host, there's nothing we can do to prevent this, you're essentially writing directly to the ASP.NET Response object here. 

This works as expected in HttpListener Self-Hosts (i.e. which doesn't use ASP.NET).
