### ISSUE TITLE
Deploy Service to IIS

### ISSUE THREAD

**Issue by asilvaubiquity** [ServiceStack/Issues#233]
I'm deploying a service to IIS but still can't use it. The service works if launched from VisualStudio.

Source: https://groups.google.com/forum/#!msg/servicestack/1DMSevzrZfQ/56-YCuGCfacJ

Steps:
1 - Compile the service
2 - XCopy bin folder, global.asax and web.config to folder
3 - At IIS Manager create the application under default web site
4 - Call it from browser with http://localhost/ServiceStackPing

The result is an empty, white, canvas. I tried all the urls I remembered but still without success.

I think I need some extra file, some entry point, like the asmx, or some configuration on the IIS, but can figure what.

By the way, why to I need to copy web.config if inside bin folder already is dll_name.config? Are one of these unnecessary?

Details:
VisualStudio 2013 Community
ServiceStack 4
IIS 8.5

Web.config

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  For more information on how to configure your ASP.NET application, please visit
  http://go.microsoft.com/fwlink/?LinkId=169433
  -->
<configuration>
  <system.web>
    <compilation debug="true" targetFramework="4.0" />
    <httpRuntime />
    <httpHandlers>
      <add path="*" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" />
    </httpHandlers>
    <pages controlRenderingCompatibilityVersion="4.0" />
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true" />
    <validation validateIntegratedModeConfiguration="false" />
    <handlers>
      <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true" />
    </handlers>
  </system.webServer>
</configuration>
```

![image](https://cloud.githubusercontent.com/assets/10927863/6185280/7746f8a0-b364-11e4-8f18-9ac3d6ec6a6f.png)

![image](https://cloud.githubusercontent.com/assets/10927863/6185288/866c7990-b364-11e4-86d5-c8508bbf0727.png)

**Comment by mythz** [comment]
ServiceStack is a plain ASP.NET Web Application and is deployed using any of the recommended approaches to deploy any ASP.NET Web Application. The **Web.config** is required for all ASP.NET Web Applications, you may need to do some background reading on how ASP.NET Apps work - but this is beyond the scope of what ServiceStack provides. 

We do have some docs showing different ways to deploy ServiceStack (which also applies to any ASP.NET Web application):

 - [Using VS.NET's WebDeploy](https://github.com/ServiceStack/ServiceStack/wiki/Simple-Deployments-to-AWS-with-WebDeploy#deploy-using-publish-from-visual-studio)

We also guides on deploying with [Octopus Deploy](https://octopusdeploy.com/)
 - [Deploy Multiple Sites to single AWS Instance](https://github.com/ServiceStack/ServiceStack/wiki/Deploy-Multiple-Sites-to-single-AWS-Instance)
 - [Advanced Deployments with Octopus Deploy](https://github.com/ServiceStack/ServiceStack/wiki/Advanced-Deployments-with-OctopusDeploy)

As an alternative to Web Deploy from VS.NET we also have VS.NET templates that include using Grunt Tasks for deployment:

Our [React and AngularJS Single Page App templates](https://github.com/ServiceStack/ServiceStackVS) also offer a [built-in Grunt tasks for deployments MS Deploy](https://github.com/ServiceStack/ServiceStack/wiki/Simple-Deployments-to-AWS-with-WebDeploy#deploy-using-grunt).
