### ISSUE TITLE
TargetInvocationException when trying to create simple webservice in F#

### ISSUE THREAD

**Issue by wastaz** [ServiceStack/Issues#235]
I'm trying to make a simple example web service in F# with service stack. See gist:
(Not very good F# code, but I've been trying a lot of variations without any clear results)
https://gist.github.com/wastaz/19598dcc4d90bbba0cf6

When attempting to run this I get TargetInvocationException and then after a couple of those I get the ServiceStackHost.Intance has already been set exception that you usually get if you attempt to run multiple apphosts (which as you can see in the code, is not something I'm trying to do).

I'm running this on VS2015 preview, but as a .NET 4.5 project. I have a parallell C# project that does the exact same thing (except in C#) on the same port, and that one runs perfect so it shouldn't be a firewall related problem.

**Comment by mythz** [comment]
There's a problem with the F# source code, you need to specify a constructor by adding `()` at end of type name, also you need to call the constructor of your base type with `ServiceStack.Service()`, so the HelloService should be rewritten with:

```fsharp
type HelloService() =
    inherit ServiceStack.Service()
    member this.Get(req: Hello) = 
        let res = new HelloResponse()
        res.Result <- "Hello " + req.Name
        res
```

**Comment by wastaz** [comment]
Jesus christ, now I feel stupid. Sorry for not spotting that. Thanks for the help :)

**Comment by mythz** [comment]
np :) F# makes it easy to make mistakes like this.
