### ISSUE TITLE
Unable to send mail with ServiceStack.Logging.NLog

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#236]
Using the SS interface for logging and NLog as the logging provider I am unable to send email via the ServiceStack logger, yet the NLog loggers sends email.

Sample console:

using System;
	using NLog;
	using ServiceStack.Logging;
	using ServiceStack.Logging.NLogger;

	namespace ConsoleApplication5
	{
	    class Program
	    {
	        static readonly Logger NLogLogger = NLog.LogManager.GetLogger("ConsoleApplication5.NLogLogger");
	        static readonly ILog SSLogger = ServiceStack.Logging.LogManager.GetLogger("ConsoleApplication5.SSLogger");

	        static void Main(string[] args)
	        {
	            ServiceStack.Logging.LogManager.LogFactory = new NLogFactory();

	            SSLogger.Debug("init");
	            NLogLogger.Debug("init");

	            SSLogger.Error("Error Email SSLogger");
	            SSLogger.Error("Error Email SSLogger", new Exception("Exception details SSLogger"));

	            NLogLogger.Error("Error Email NLogLogger");
	            NLogLogger.Error("Error Email NLogLogger", new Exception("Exception details NLogLogger"));

	            Console.ReadKey();
	        }
	    }
	}

NLog config:

	<?xml version="1.0" encoding="utf-8" ?>
	<nlog xmlns="http://www.nlog-project.org/schemas/NLog.xsd"
	         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" >
	  <targets async="true">
	    <target name="mail" xsi:type="Mail" 
	         html="true" 
	         subject="Error Received" 
	         body="${message}"
	         to="stephen.patten@example.com"
	         from="${machinename}@example.com"
	         Encoding="UTF-8"
	         enableSsl="False"
	         smtpAuthentication="None"
	         smtpServer="cc-ana-smtp-01.example.com"
	         smtpPort="25" />

	    <target name="console" xsi:type="Console"
	        layout="${logger}:${level}:${threadid}:${message}:${exception}" />
	    
	  </targets>
	  <rules>
	    <logger name="*" level="Error" writeTo="mail" />
	    <logger name="*" minlevel="Debug" writeTo="console" />
	  </rules>
	</nlog>

Packages:

        <packages>
	  <package id="NLog" version="3.2.0.0" targetFramework="net45" />
	  <package id="ServiceStack.Interfaces" version="4.0.36" targetFramework="net45" />
	  <package id="ServiceStack.Logging.NLog" version="4.0.36" targetFramework="net45" />
	</packages>

**Comment by mythz** [comment]
This is an issue with NLog impl. The ServiceStack [NLogger](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Logging.NLog/NLogLogger.cs) is just a lightweight adapter for the NLog provider. Investigating NLog config issues is out of scope.

**Comment by stephenpatten** [comment]
Why does NLog send the emails then, and not SS?

**Comment by mythz** [comment]
You didn't mention that, no idea I'll have to debug it locally. It will be a while before I have time to look at it.

**Comment by stephenpatten** [comment]
Completely understand, thanks mythz

**Comment by mythz** [comment]
I've changed the NLog API's to use explicit named Log Level API's as used in your example instead of the generic API's in this commit: https://github.com/ServiceStack/ServiceStack/commit/e600b8f686b32d92a1fa4f9e80b683112154cd0d

Other than that the only difference is that it's not logged when `IsErrorEnabled=false`, can you check your example to make sure `IsErrorEnabled=true`.

I've also updated the NLog dependency to use the latest 3.2.0.0 on NuGet in-case it helps. Can you try again with the latest [v4.0.37 that's on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)?

**Comment by stephenpatten** [comment]
Tested quite a few scenarios and it's working great, you also fixed the call site bug, where we couldn't reliable filter the loggers. :100: 

I knew it had to be in the writelog method, it had to be, that was the only place it was using nlog, and thought this was going to be the one time where I could do a damn PR! So much for you getting to it later :)

**Comment by mythz** [comment]
Cool glad it's sorted. It's sad to see the different NLog API's have different behavior.
