### ISSUE TITLE
Session Id is vulnerable to session fixation attack.

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#240]
You should always assign new session id when authenticating. 
Possible attack: https://www.owasp.org/index.php/Session_fixation

How to reproduce in browser:
1. Login 
`/auth/credentials?username=me&password=test`
2. Logout
`/auth/logout`
3. Login again 
`/auth/credentials?username=me&password=test`

SessionId has not been changed.

**Comment by mythz** [comment]
The SessionId's are explained on https://github.com/ServiceStack/ServiceStack/wiki/Sessions

The default is to use a temporary session id which is lost when the browser session is ended.

**Comment by marko444** [comment]
The problem is that I can push my custom ss-id when calling Auth service and the server will return it back. The server should always generate new ss-id when calling login service. Even inside single browser session.

Example: I can push my own "ss-id" with fiddler and the server will return it.

    GET http://localhost/auth/credentials?username=me&password=test HTTP/1.1
    Cookie: ss-id=AAAAAAAAAAAAAAAAAAAA

**Comment by mythz** [comment]
Right, that's how cookies work, you can attach your own to the request. The server only creates a cookie if it doesn't already exist. When you logout there is no session, it doesn't matter if you re-use the cookie again, there is no session to hijack.

You can get the server to delete the cookies by removing them explicitly `OnLogout` event (on AuthUserSession or [Session Events](https://github.com/ServiceStack/ServiceStack/wiki/Sessions#session-events)):

```csharp
var httpRes = response as IHttpResponse;
if (httpRes != null)
{
    httpRes.Cookies.DeleteCookie(SessionFeature.SessionOptionsKey);
    httpRes.Cookies.DeleteCookie(SessionFeature.PermanentSessionId);
}
```

Or you can force creating new Session Ids with the API:

```csharp
httpRes.CreateSessionIds(httpReq);
```

**Comment by mythz** [comment]
Ok I don't think it hurts to delete the Session cookies when they logout so I'm automatically removing both Temporary/Permanent Session Ids when they logout in this commit: https://github.com/ServiceStack/ServiceStack/commit/a111e01a1b5a51c7ebded83796d343f3dc48d1c7

**Comment by mythz** [comment]
This default behavior does affect some existing features:

  - Being able to track a user via PermanentSessionId
  - Loss of dynamic SessionBag which is tied to SessionId and was previously able to maintain info about a user whether they were logged in or not.

As a result I've made it configurable on `AuthFeature.DeleteSessionCookiesOnLogout`.

**Comment by jeffgabhart** [comment]
Even with these changes, @marko444 will still be able to inject a custom value for `ss-id` prior to log in.

**Comment by mythz** [comment]
? You will always be able to specify your own Cookies. The difference is now when the user logs out the existing Session Cookies are deleted from the Browsers Session so next time a user logs in without browser they will be using new Session Cookies.

**Comment by jeffgabhart** [comment]
True, but it sounds like @marko444 is suggesting that the auth cookie value be regenerated/replaced after login so no previously issued server value or user-set value is used.

**Comment by mythz** [comment]
I know what's being requested, but I'm only adding clearing out the Session Cookies by default on Logout as it's less likely to cause regressions and breaking changes and is more in-line with expected behavior.

You can use the existing API's and hooks to add any other custom behavior.

**Comment by marko444** [comment]
I solved this by recreating session ids on successful authentication and it works as expected. 

I am also removing old session because (just to be sure it wasn't saved to the cache already with the old session ids) and overriding session options to temporary (just to be sure).

Could there be a problem I am not aware off?

```c#
    public class DefaultAuthEvents : IAuthEvents
    {
        public void OnAuthenticated(IRequest httpReq, IAuthSession session, IServiceBase authService, IAuthTokens tokens, Dictionary<string, string> authInfo)
        {
            RecreateSession(httpReq, session);
        }
        private static void RecreateSession(IRequest httpReq, IAuthSession session)
        {
            // Remove current session
            httpReq.RemoveSession();            
            // Override session options
            httpReq.AddSessionOptions(SessionOptions.Temporary);            
            // Create new session cookies
            session.Id = httpReq.Response.CreateSessionIds(httpReq);
        }	
        ...
    }
```

**Comment by mythz** [comment]
FYI, decided to add support for this in the end in this commit: https://github.com/ServiceStack/ServiceStack/commit/d0edc224c1b95f3be66338b46b6a9bf1eec23e3f

It's enabled by default from v4.0.43+ and can be disabled with `AuthFeature.GenerateNewSessionCookiesOnAuthentication = false`

All tests continue to pass so ideally shouldn't cause any issues, but can be disabled if needed.
