### ISSUE TITLE
Issue with SaveAsync with ProfiledDbConnection

### ISSUE THREAD

**Issue by dandcg** [ServiceStack/Issues#241]
Hi,
I seem to be getting an error occuring when using the inbuilt ProfiledDbConnection wrapper and calling SaveAsync. I have tested using the using the standard save and it works fine.

The following error occurs:
Unable to cast object of type 'ServiceStack.MiniProfiler.Data.ProfiledDbCommand' to type 'System.Data.SqlClient.SqlCommand'.

Can you shed any light?

**Comment by mythz** [comment]
Can you please include the code and configuration the reproduces the error?

**Comment by dandcg** [comment]
Hi Mythz,

Hopefully this demonstrates the issue - thanks for your help.

Dan

```csharp
  var cf =new OrmLiteConnectionFactory(cs, SqlServerDialect.Provider) {ConnectionFilter = c => new ProfiledDbConnection(c, Profiler.Current)};

            using (var c = cf.OpenDbConnection())
            {
                var n = new Node
                {
                    ModifiedOn = DateTime.UtcNow,
                    CreatedOn = DateTime.UtcNow,
                    NodeName = "dd",
                    NodeTypeEnum = NodeTypeEnum.Consumer
                };

                var r = c.SaveAsync(n).Result;
```

**Comment by dandcg** [comment]
Oh sorry I forgot to mention its the latest version of ServiceStack (on Nuget) and .Net 4.5.1....

**Comment by dandcg** [comment]
Hi Mythz, just wondered if you managed to reproduce at your end?

**Comment by mythz** [comment]
Yep, it took a few changes to fix and as I was in the middle of a mild re-factor, it only just finished deploying to MyGet now.

Should now work with the latest v4.0.39 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by dandcg** [comment]
Thanks Mythz - Very much appreciated!
