### ISSUE TITLE
ServiceStack VS Extension Angular crash

### ISSUE THREAD

**Issue by stronachconsult** [ServiceStack/Issues#243]
The Angular project template with ServiceStackVS crashes Visual Studio 2013 update 4 during project creation. This crash happens at random different times during the project creation cycle. The ReactJS template works fine in the same dev environment.

![image](https://cloud.githubusercontent.com/assets/1902384/6512312/3a83519e-c330-11e4-92d2-ac811b531dbb.png)

![image](https://cloud.githubusercontent.com/assets/1902384/6512328/4d5fff9c-c330-11e4-84bb-77f2e622e72e.png)

**Comment by mythz** [comment]
@Layoric can you investigate thx, thx

**Comment by stronachconsult** [comment]
Looking at a workaround where I just copy in the grunt tasks and stuff from
one of the botched project generations. Going to integrate into an existing
solution anyway that will require some customizations of the project
template defaults. Really want the grunt,gulp,npm etc workflow integration
though.



On Mar 5, 2015, at 12:44 PM, Demis Bellot <notifications@github.com> wrote:

@Layoric <https://github.com/Layoric> can you investigate thx, thx

—
Reply to this email directly or view it on GitHub
<https://github.com/ServiceStack/Issues/issues/243#issuecomment-77436729>.

**Comment by stronachconsult** [comment]
And all those node related client build tools are installed and working...



On Mar 5, 2015, at 12:44 PM, Demis Bellot <notifications@github.com> wrote:

@Layoric <https://github.com/Layoric> can you investigate thx, thx

—
Reply to this email directly or view it on GitHub
<https://github.com/ServiceStack/Issues/issues/243#issuecomment-77436729>.

**Comment by Layoric** [comment]
@stronachconsult Could you have a look in your event log to see if that has anything useful that might help track down why it's crashing. 

I think VS writes to Windows Logs/Applications.

Also noticed in the screenshot that you the solution name is different to the project names generated from the projects. Have you tried creating a new solution for the Angular and React templates separating?

Any more details on what your process is when creating the new projects would help.

**Comment by stronachconsult** [comment]
@Layoric I tried the angular template first in an existing solution, then a blank solution to rule out anything with the existing one. Added the React project afterwards. Even tried adding more Angular projects after the successful React one in case it was a matter of dependencies that had eventually been resolved.

This is the full error from VS from the event log. Installed version of .net frameork 4 is 4.5.1. This same error happens every time:

Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException
Stack:
   at System.Text.StringBuilder.AppendFormat(System.IFormatProvider, System.String, System.Object[])
   at System.String.Format(System.IFormatProvider, System.String, System.Object[])
   at System.String.Format(System.String, System.Object[])
   at ServiceStackVS.NPMInstallerWizard.OutputWindowWriter.Write(System.String, System.Object[])
   at ServiceStackVS.NPMInstallerWizard.NodeJsPackageWizard+<>c__DisplayClassf.<ProjectFinishedGenerating>b__e(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at ServiceStackVS.Wizards.CommandUtils+<>c__DisplayClass5.<StartCommand>b__3(System.Object, System.Diagnostics.DataReceivedEventArgs)
   at System.Diagnostics.Process.ErrorReadNotifyUser(System.String)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
   at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
   at System.Diagnostics.AsyncStreamReader.ReadBuffer(System.IAsyncResult)
   at System.IO.Stream+ReadWriteTask.InvokeAsyncCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.IO.Stream+ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task.FinishStageThree()
   at System.Threading.Tasks.Task.FinishStageTwo()
   at System.Threading.Tasks.Task.Finish(Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by Layoric** [comment]
It looks like output coming from npm is a causing a problem with the output to the VS window. Very strange I can't reproduce it. What language/region settings have you got on the machine you're using? 

Could you copy the following into a new folder and run 'npm install' via the command line and post the result?

**Comment by stronachconsult** [comment]
c:\Documents and Settings\sstronach\Documents\Visual Studio 2013\Projects\Servic
eStackVSTest\npm-test>npm install
npm WARN deprecated gulp-rimraf@0.1.1: Use npmjs.org/del instead, see https://gi
thub.com/gulpjs/gulp/blob/master/docs/recipes/delete-files-folder.md
npm WARN engine karma@0.12.31: wanted: {"node":"~0.8 || ~0.10"} (current: {"node
":"0.12.0","npm":"2.5.1"})
npm WARN optional dep failed, continuing fsevents@0.3.5
|


> ws@0.4.32 install c:\Documents and Settings\sstronach\Documents\Visual Studio
2013\Projects\ServiceStackVSTest\npm-test\node_modules\karma\node_modules\socket
.io\node_modules\socket.io-client\node_modules\ws
> (node-gyp rebuild 2> builderror.log) || (exit 0)


c:\Documents and Settings\sstronach\Documents\Visual Studio 2013\Projects\Servic
eStackVSTest\npm-test\node_modules\karma\node_modules\socket.io\node_modules\soc
ket.io-client\node_modules\ws>node "C:\Program Files\nodejs\node_modules\npm\bin
\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild
\
> phantomjs@1.9.16 install c:\Documents and Settings\sstronach\Documents\Visual
Studio 2013\Projects\ServiceStackVSTest\npm-test\node_modules\karma-phantomjs-la
uncher\node_modules\phantomjs
> node install.js

Download already available at C:\Users\SSTRON~1\AppData\Local\Temp\phantomjs\pha
ntomjs-1.9.8-windows.zip
Extracting zip contents
Removing C:\Users\sstronach\Documents\Visual Studio 2013\Projects\ServiceStackVS
Test\npm-test\node_modules\karma-phantomjs-launcher\node_modules\phantomjs\lib\p
hantom
Copying extracted folder C:\Users\SSTRON~1\AppData\Local\Temp\phantomjs\phantomj
s-1.9.8-windows.zip-extract-1425593526711\phantomjs-1.9.8-windows -> C:\Users\ss
tronach\Documents\Visual Studio 2013\Projects\ServiceStackVSTest\npm-test\node_m
odules\karma-phantomjs-launcher\node_modules\phantomjs\lib\phantom
Writing location.js file
Done. Phantomjs binary available at C:\Users\sstronach\Documents\Visual Studio 2
013\Projects\ServiceStackVSTest\npm-test\node_modules\karma-phantomjs-launcher\n
ode_modules\phantomjs\lib\phantom\phantomjs.exe
karma-chrome-launcher@0.1.7 node_modules\karma-chrome-launcher

ssvs-utils@0.1.2 node_modules\ssvs-utils

gulp-grunt@0.5.2 node_modules\gulp-grunt

karma-jasmine@0.2.3 node_modules\karma-jasmine

grunt-msbuild@0.2.2 node_modules\grunt-msbuild
└── async@0.2.10

karma-junit-reporter@0.2.2 node_modules\karma-junit-reporter
└── xmlbuilder@0.4.2

gulp-replace@0.4.0 node_modules\gulp-replace
├── replacestream@0.1.3 (through@2.3.6)
├── istextorbinary@1.0.2 (binaryextensions@1.0.0, textextensions@1.0.1)
└── event-stream@3.0.20 (stream-combiner@0.0.4, duplexer@0.1.1, from@0.1.3, paus
e-stream@0.0.11, map-stream@0.0.5, split@0.2.10, through@2.3.6)

gulp-if@1.2.5 node_modules\gulp-if
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── gulp-match@0.2.1 (minimatch@1.0.0)
└── ternary-stream@1.2.3 (merge-stream@0.1.7, fork-stream@0.0.4, duplexer2@0.0.2
)

gulp-rimraf@0.1.1 node_modules\gulp-rimraf
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── rimraf@2.3.1 (glob@4.4.2)
└── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, arra
y-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterp
olate@3.0.0, replace-ext@0.0.1, minimist@1.1.0, chalk@1.0.0, vinyl@0.4.6, lodash
.template@3.3.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-useref@1.0.2 node_modules\gulp-useref
├── is-absolute-url@1.0.0
├── strip-bom@0.3.1 (first-chunk-stream@0.1.0, is-utf8@0.2.0)
├── node-useref@0.3.8
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── brace-expand-join@0.1.0 (array-uniq@1.0.2, minimatch@1.0.0)
├── glob@4.4.2 (inherits@2.0.1, once@1.3.1, inflight@1.0.4, minimatch@2.0.1)
└── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, arra
y-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._ree
scape@3.0.0, replace-ext@0.0.1, minimist@1.1.0, chalk@1.0.0, vinyl@0.4.6, lodash
.template@3.3.0, multipipe@0.1.2, dateformat@1.0.11)

gulp-newer@0.3.0 node_modules\gulp-newer
├── kew@0.3.4
└── gulp-util@2.2.20 (lodash._reinterpolate@2.4.1, minimist@0.2.0, vinyl@0.2.3,
chalk@0.5.1, through2@0.5.1, multipipe@0.1.2, dateformat@1.0.11, lodash.template
@2.4.1)

grunt-karma@0.8.3 node_modules\grunt-karma
└── lodash@2.4.1

gulp-minify-css@0.3.13 node_modules\gulp-minify-css
├── memory-cache@0.0.5
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── bufferstreams@0.0.2 (readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, arra
y-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reescape@3.0.0, lodash._reinterp
olate@3.0.0, replace-ext@0.0.1, minimist@1.1.0, chalk@1.0.0, vinyl@0.4.6, lodash
.template@3.3.0, multipipe@0.1.2, dateformat@1.0.11)
└── clean-css@3.0.10 (commander@2.5.1, source-map@0.1.43)

gulp-uglify@1.0.2 node_modules\gulp-uglify
├── deepmerge@0.2.7
├── through2@0.6.3 (xtend@4.0.0, readable-stream@1.0.33)
├── vinyl-sourcemaps-apply@0.1.4 (source-map@0.1.43)
├── gulp-util@3.0.4 (array-differ@1.0.0, object-assign@2.0.0, beeper@1.0.0, arra
y-uniq@1.0.2, lodash._reevaluate@3.0.0, lodash._reinterpolate@3.0.0, lodash._ree
scape@3.0.0, replace-ext@0.0.1, minimist@1.1.0, chalk@1.0.0, vinyl@0.4.6, lodash
.template@3.3.0, multipipe@0.1.2, dateformat@1.0.11)
└── uglify-js@2.4.15 (uglify-to-browserify@1.0.2, async@0.2.10, optimist@0.3.7,
source-map@0.1.34)

requirejs@2.1.16 node_modules\requirejs

gulp@3.8.11 node_modules\gulp
├── v8flags@2.0.2
├── pretty-hrtime@0.2.2
├── interpret@0.3.10
├── deprecated@0.0.1
├── archy@1.0.0
├── minimist@1.1.0
├── semver@4.3.1
├── tildify@1.0.0 (user-home@1.1.1)
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0
.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── gulp-util@3.0.4 (array-differ@1.0.0, beeper@1.0.0, object-assign@2.0.0, arra
y-uniq@1.0.2, lodash._reinterpolate@3.0.0, lodash._reescape@3.0.0, lodash._reeva
luate@3.0.0, replace-ext@0.0.1, chalk@1.0.0, vinyl@0.4.6, lodash.template@3.3.0,
 through2@0.6.3, multipipe@0.1.2, dateformat@1.0.11)
├── orchestrator@0.3.7 (stream-consume@0.1.0, sequencify@0.0.7, end-of-stream@0.
1.5)
├── liftoff@2.0.2 (extend@2.0.0, flagged-respawn@0.3.1, resolve@1.1.5, findup-sy
nc@0.2.1)
└── vinyl-fs@0.3.13 (graceful-fs@3.0.5, defaults@1.0.0, vinyl@0.4.6, strip-bom@1
.0.0, mkdirp@0.5.0, through2@0.6.3, glob-stream@3.1.18, glob-watcher@0.0.6)

grunt-gulp@0.1.0 node_modules\grunt-gulp
├── gulp-concat@2.1.7 (through@2.3.6, gulp-util@2.2.20)
└── gulp@3.2.5 (pretty-hrtime@0.2.2, graceful-fs@2.0.3, map-stream@0.0.4, throug
h@2.3.6, mkdirp@0.3.5, semver@2.2.1, resolve@0.6.3, optimist@0.6.1, orchestrator
@0.3.7, glob-stream@3.1.18, gulp-util@2.2.20, glob-watcher@0.0.1, findup-sync@0.
1.3)

grunt-nuget@0.1.4 node_modules\grunt-nuget

grunt@0.4.5 node_modules\grunt
├── dateformat@1.0.2-1.2.3
├── which@1.0.9
├── eventemitter2@0.4.14
├── getobject@0.1.0
├── colors@0.6.2
├── rimraf@2.2.8
├── async@0.1.22
├── grunt-legacy-util@0.2.0
├── hooker@0.2.3
├── nopt@1.0.10 (abbrev@1.0.5)
├── exit@0.1.2
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── glob@3.1.21 (inherits@1.0.0, graceful-fs@1.2.3)
├── lodash@0.9.2
├── coffee-script@1.3.3
├── underscore.string@2.2.1
├── iconv-lite@0.2.11
├── findup-sync@0.1.3 (glob@3.2.11, lodash@2.4.1)
├── grunt-legacy-log@0.1.1 (underscore.string@2.3.3, lodash@2.4.1)
└── js-yaml@2.0.5 (esprima@1.0.4, argparse@0.1.16)

karma@0.12.31 node_modules\karma
├── di@0.0.1
├── graceful-fs@2.0.3
├── colors@0.6.2
├── rimraf@2.2.8
├── mime@1.2.11
├── q@0.9.7
├── minimatch@0.2.14 (sigmund@1.0.0, lru-cache@2.5.0)
├── optimist@0.6.1 (wordwrap@0.0.2, minimist@0.0.10)
├── glob@3.2.11 (inherits@2.0.1, minimatch@0.3.0)
├── source-map@0.1.43 (amdefine@0.1.0)
├── chokidar@0.12.6 (async-each@0.1.6, readdirp@1.3.0)
├── lodash@2.4.1
├── log4js@0.6.22 (semver@1.1.4, async@0.2.10, readable-stream@1.0.33)
├── useragent@2.0.10 (lru-cache@2.2.4)
├── http-proxy@0.10.4 (pkginfo@0.3.0, utile@0.2.1)
├── socket.io@0.9.16 (base64id@0.1.0, policyfile@0.0.4, redis@0.7.3, socket.io-c
lient@0.9.16)
└── connect@2.26.6 (cookie@0.1.2, fresh@0.2.4, cookie-signature@1.0.5, on-header
s@1.0.0, response-time@2.0.1, media-typer@0.3.0, pause@0.0.1, basic-auth-connect
@1.0.0, vhost@3.0.0, parseurl@1.3.0, bytes@1.0.0, depd@0.4.5, qs@2.2.4, cookie-p
arser@1.3.4, debug@2.0.0, connect-timeout@1.3.0, method-override@2.2.0, finalhan
dler@0.2.0, type-is@1.5.7, serve-favicon@2.1.7, express-session@1.8.2, multipart
y@3.3.2, csurf@1.6.6, errorhandler@1.2.4, serve-index@1.2.1, compression@1.1.2,
body-parser@1.8.4, serve-static@1.6.5, morgan@1.3.2)

karma-phantomjs-launcher@0.1.4 node_modules\karma-phantomjs-launcher
└── phantomjs@1.9.16 (which@1.0.9, progress@1.1.8, kew@0.4.0, request-progress@0
.3.1, adm-zip@0.4.4, npmconf@2.1.1, fs-extra@0.16.4, request@2.42.0)

c:\Documents and Settings\sstronach\Documents\Visual Studio 2013\Projects\Servic
eStackVSTest\npm-test>

**Comment by Layoric** [comment]
Thanks for all the details. I've applied a fix and packaged ServiceStackVS into a new VSIX which you can install over the top.

[Download here](https://github.com/ServiceStack/ServiceStackVS/raw/master/src/ServiceStackVS.vsix)

Could you please update ServiceStackVS with the new version and try the template again? As I'm not able to reproduce the error, I can't test it myself. I'm building a new machine with your node + npm version in the mean time to test, but if you could let me know if that now works or not, that would be appreciated.

Cheers.

**Comment by Layoric** [comment]
@stronachconsult I've reproduced the error on a system running the same nodejs + npm versions. 

The above update to ServiceStackVS fixed the problem on my test machine. Please remember to restart Visual studio after installing the updated VSIX if you had Visual Studio running at the time.

**Comment by stronachconsult** [comment]
Yep - looks good - thanks a bunch...

**Comment by Layoric** [comment]
No worries. Glad to hear it's sorted. Thanks for your debugging and prompt replies. :+1:
