### ISSUE TITLE
ToPostUrl() doesn't include base url from IIS

### ISSUE THREAD

**Issue by specimen151** [ServiceStack/Issues#245]
I have a some web-services hosted in IIS where there are many applications (different application pools). My services are under URI prefix /my/. My config is for * because as I see it the application is only SS, there is no mix with other frameworks, and this works. The only thing that doesn't work is the reverse routing, e.g. ToPostUrl() which gives relative URLs, but skips the /my/ prefix.

E.g. a service with Route "/service1", which in production has path "/my/service1", is reverse-routed as just "/service1".

Help please

**Comment by mythz** [comment]
Please provide the necessary configuration that is able to reproduce this issue.

What is your `BaseUrl`? What is your Route definition? Do you have ServiceStack registered at a `/custompath` if so please provide the configuration you're using to do this.

**Comment by specimen151** [comment]
My config is (removed appSettings for brewety)

  <configuration>
    <configSections>
      <sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor">
        <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor" requirePermission="false" />
        <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor" requirePermission="false" />
      </sectionGroup>
    </configSections>


    <system.web>
      <compilation targetFramework="4.5" debug="true">
        <buildProviders>
        <add extension=".cshtml" type="ServiceStack.Razor.CSharpRazorBuildProvider, ServiceStack.Razor" />
      </buildProviders>
    </compilation>
    <httpRuntime targetFramework="4.5" />
    <httpHandlers>
        <add path="*" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" />
      </httpHandlers>
    </system.web>
    <system.webServer>
      <validation validateIntegratedModeConfiguration="false" />
      <urlCompression doStaticCompression="true" doDynamicCompression="false" />
      <handlers>
        <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true" />
      </handlers>
    </system.webServer>

When I run in debug on my developer PC from VS with IIS express, my services are e.g.

  [Route("/assets/css", Verbs="GET")]   

But on my IIS in production, I have to create an ASP.NET application, with application pool etc, and then I have a prefix URL "Activity", so the same route becomes

/Activity/assets/css

When using ToGetUrl() I get only /assets/css.

**Comment by mythz** [comment]
This is the behavior of the ReverseRouting extension methods it doesn't have access to the Request Context and only returns the route from the Route Definition. 

You would need to either hard code the prefix or alternatively you can use `ToAbsoluteUri()` extension method to convert it to an absolute url which it tries to infer from the current request but it can be explicitly configured by setting `Config.WebHostUrl`:

```csharp
SetConfig(new HostConfig {
    WebHostUrl = "http://baseurl.com/path"
});
```

If you use `requestDto.ToAbsoluteUri()` you can customize the url by overriding `AppHost.ResolveAbsoluteUrl()`.

**Comment by specimen151** [comment]
Thank you for extremely quick answer, as always.
I changed to requestDto.ToAbsoluteUri(httpMethod:"xxxx"), and this solves my problem.

It would have been nice though (think of it as a feature request) if the relative-uri methods also had worked in all situations (not that uncommon to deploy an application at a path, which is not known beforehand), and one can get quite a surprise having based the URI's on reverse-lookup using the other methods (ToPostUrl, ToGetUrl, etc), when creating a web-site.
