### ISSUE TITLE
Connection pool issue in Redis using PooledRedisClientManager

### ISSUE THREAD

**Issue by nookalavanya** [ServiceStack/Issues#248]
Hi,

I want to achieve connection pooling while writing data from MSMQ / database into Redis. I have implemented 

PooledRedisClientManager pooledClientManager = new PooledRedisClientManager(50,5, xxx.xxx.x.xxx);
pooledClientManager.PoolTimeout = 10;
pooledClientManager.IdleTimeOutSecs = 3;

 using (var client = pooledClientManager.GetClient())
  {
         client.AddItemToSortedSet(setId, x, 1);
  }

By doing the above, the number of connections from Redis server to Application Server have come down. But, the connections with the Redis have increased significantly from a mere 4-5 to several hundreds. This is check by using 'client list' in Redis. 

What is the correct way to code to avoid have so many connections in Redis?
.Net Framework  - 4.5
ServiceStack version - 4.0.0.0

Thanks,
Lavanya

**Comment by mythz** [comment]
Can you please provide the source code that will reproduce the "several hundreds open connections" problem as you've described, this example wont do that.

**Comment by mythz** [comment]
This issue was due to creating a new instance of Redis Pool each time and not [using the RedisClientManager a singleton](https://github.com/ServiceStack/ServiceStack.Redis#redis-client-managers).
