### ISSUE TITLE
Change in redirect behaviour

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#249]
We moved from v4.0.33 to v4.0.38.

Authentication redirect behaviour has changed.

1) Our default login page is `/login`
2) After updating to v4.0.33, accessing `/`, redirects to `/login?redirect=http%3a`
3) In Chrome, the Response for `/` contains `Location:http:/login?redirect=http%3a`

I added a Custom AuthenticateAttribute class (copy of https://github.com/ServiceStack/ServiceStack/blob/b41e750d3a9d2be409620940e5b6e39c168d02f0/src/ServiceStack/AuthenticateAttribute.cs) to debug.

The two lines below are where the redirection part has changed

    var absoluteRequestPath = req.ResolveAbsoluteUrl("~" + req.PathInfo + ToQueryString(req.QueryString));
    url = url.AddQueryParam(HostContext.ResolveLocalizedString(LocalizedStrings.Redirect), absoluteRequestPath);

In v4.0.38 the two lines repectively evaluate to:
1) http:
2) http:/login?redirect=http%3a

In v4.0.33 the two lines repectively evaluate to:
1) http://localhost-docurec.com
2) http://localhost-docurec.com/login?redirect=http%3a%2f%2flocalhost-docurec.com

Is a different AppHost configuration required or is it a bug?

Tested on Win 8.1, IIS, .NET 4.5

**Comment by mythz** [comment]
I'll investigate to see if I can repro the issue, in the meantime you can control how the url is generated by:

 1. Explicitly setting the BaseUrl in `Config.WebHostUrl`
 2. Overriding [ResolveAbsoluteUrl](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/ServiceStackHost.cs#L608) in your AppHost

**Comment by mythz** [comment]
I'm not able to rerpo this behavior. Can you post your [Debug RequestInfo](https://github.com/ServiceStack/ServiceStack/wiki/Debugging#request-info), i.e: `?debug=requestinfo`

**Comment by mjdaly** [comment]
https://drive.google.com/file/d/0B5cglv2mrbC7bEFRTUNnSWFwYm8/view?usp=sharing

This is also happening on a Windows Server 2012 R1.

**Comment by mythz** [comment]
Great thx, this should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack/commit/e68da6e83878a3e45a694236d9a8c7597ddeb85b

This change is available from v4.0.39 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/commit/e68da6e83878a3e45a694236d9a8c7597ddeb85b).

**Comment by malat** [comment]
Great thanks :+1:
