### ISSUE TITLE
Batched request dont work using async service handler

### ISSUE THREAD

**Issue by malat** [ServiceStack/Issues#250]
Batched request seems to failed when the service handler is async

```csharp

[Route("/batch/async")]
    public class AsyncBatchRequest : IReturn<BatchResult>
    {
        public Guid Id { get; set; }
    }

    public class BatchResult
    {
        public Guid Id { get; set; }
    }

    public class AsyncBatchService : IService
    {
        public Task<BatchResult> Any(AsyncBatchRequest request)
        {
            return Task.FromResult(new BatchResult
            {
                Id = request.Id
            });
        }
    }

```

Failing test

```csharp
public class AsyncBatchTests
    {
        public async Task BatchRequestShouldWorkWithAsyncHandler()
        {
            var client = new JsonServiceClient("http://localhost:52784/");
            var batch = new[] { new AsyncBatchRequest { Id = Guid.NewGuid() }, new AsyncBatchRequest { Id = Guid.NewGuid() } };

            var results = await client.SendAllAsync(batch);
            var guids = results.Select(r => r.Id);

            Assert.IsTrue(guids.SequenceEqual(batch.Select(b => b.Id)));
        }
    }

```

**Comment by mythz** [comment]
AutoBatched Async requests was never a supported/documented but should now be supported from this commit: https://github.com/ServiceStack/ServiceStack/commit/78cfa280b1ef1dbce8b705a10b9446240b510dac

**Comment by malat** [comment]
Hi Mythz,

Thanks for this...

Base on your commit I understand that each handler will be executed concurrently, is that really the desire behavior ? I think it may be confusing ... On my side I saw the auto batched feature as a way to send a single unit of work that will be process sequentially ...

Thanks for your thought on this

**Comment by mythz** [comment]
Yeah you're right, except running tasks sequentially is problematic in .NET 4.0 without await support, but just remembered also needing to do this in OrmLite's Async support so was able to re-use an existing API for this, changed in this commit: https://github.com/ServiceStack/ServiceStack/commit/cdd41f4c596b677a2f62b4589ca99f061494d4fd

**Comment by malat** [comment]
Great but the cod is still looping againts the dtos and calling the handler directly without waiting for the previous task to finish, did I miss somehing ?

**Comment by mythz** [comment]
EachAsync is a custom extension method that does execute sequentially: https://github.com/ServiceStack/ServiceStack.Text/blob/master/src/ServiceStack.Text/TaskUtils.cs#L87

**Comment by malat** [comment]
Ok I probably miss something, my understanding is that by calling this code before the EachAsync part you will start x number of task directly ... 

foreach (var dto in (IEnumerable)dtos)
{
    var response = handlerFn(req, dto);
    ret.Add(response);
}


Thanks again for your help

**Comment by mythz** [comment]
ahh yeah good catch, wasn't even looking up there, just concentrating on how the task responses were chained. This commit should do it: https://github.com/ServiceStack/ServiceStack/commit/34bb81f9a9cc8b2a47a357edb66d2467002e91b6

**Comment by mythz** [comment]
FYI these change iss are now available from v4.0.39 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/commit/e68da6e83878a3e45a694236d9a8c7597ddeb85b)

**Comment by malat** [comment]
Great I have update and everything seems ok but now I realize that we got other issue using the auto batched feature... If one of the handler is raising a exception the client will receive a mix of good and exception response, and will not be able to deserialize the response... any workaround for that ?

Also is there a way to know if the current request processing pipeline is a AutoBatched one ? Maybe I could used this to dynamically disable GZIP at the service level...

And last did SS has any hook to let me transform the entire response ? a kind of GlobalResponseFilter that allowed to modify the response but at the transport level... I know I could properly do that in a custom http module but I will prefer to use SS if I can

Thanks again for your thoughts

**Comment by mythz** [comment]
This is just how it works, it short-circuits after the first exception. Have a look into [Custom Batched Requests Implementations](https://github.com/ServiceStack/ServiceStack/wiki/Auto-Batched-Requests#custom-batched-requests-implementations) for an example on how you can provide a custom implementation with `Any(Request[] request){}` to handle executing them all at once, but note the items are still executed one-at-a-time through the response pipeline so you can't return compressed bytes as mentioned earlier.

You can detect a if it's an AutoBatched Request by using the [IRequest.IsMultiRequest() extension method](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/HttpRequestExtensions.cs#L938) which just checks to see if the Request DTO type is an Array (its only an Array for AutoBatched Requests).

But honestly I think you're trying to over use this feature and make it more complex than it should be as it sounds like you're trying to co-erce it to behave like a normal single Request DTO in which case I would just recommend having your Request DTO inherit from `List<T>` which already does this. See the [Defining a Request DTO to accept a collection of Types](https://github.com/ServiceStack/ServiceStack/wiki/Auto-Batched-Requests#defining-a-request-dto-to-accept-a-collection-of-types) as an example.

**Comment by malat** [comment]
Hi Mythz

I understand at the server level that the request pipeline will be short-circuits but I don't expect the client to receive a serialization exception, I would rather expect the client to raise a WebServiceException saying that the AutoBatched was interrupt and maybe with some kind of information to know how many of them has been executed successfully...

Thanks for the info but I was already aware of the custom batched and typed collection feature

I agree, we may over use this feature... The idea was since that we have more than 500 requests, I was thinking that it may be a quick win for us to offer batch operation over the entire API, and then start adding the support of custom batched handler progressively... 

Is there a way to disable the AutoBatched behavior and keep the Custom Batched handler working ?

**Comment by mythz** [comment]
It shouldn't be throwing a Serialization Exception it should be [throwing a WebServiceException](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.WebHost.Endpoints.Tests/ReplyAllTests.cs#L439).

**Comment by malat** [comment]
I got something like that 

Test method TestApp.Tests.AcceptanceTests.IdsShouldNotBeReceivedMoreThanOnce threw exception: 
System.Runtime.Serialization.SerializationException: Type definitions should start with a '{', expecting serialized type 'BatchResult', got string starting with: Pair Request 5081d59c-92c8-4c46-96e1-dc213b533ba6 
    at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(TypeConfig typeConfig, String strType, EmptyCtorDelegate ctorFn, Dictionary`2 typeAccessorMap)
   at ServiceStack.Text.Common.DeserializeType`1.<>c__DisplayClass3.<GetParseMethod>b__1(String value)
   at ServiceStack.Text.Common.DeserializeListWithElements`2.ParseGenericList(String value, Type createListType, ParseStringDelegate parseFn)
   at ServiceStack.Text.Common.DeserializeList`2.<>c__DisplayClass3.<GetParseFn>b__0(String value)
   at ServiceStack.Text.Json.JsonReader`1.Parse(String value)
   at ServiceStack.Text.JsonSerializer.DeserializeFromString(String value)
   at ServiceStack.Text.JsonSerializer.DeserializeFromStream(Stream stream)
   at ServiceStack.Serialization.JsonDataContractSerializer.DeserializeFromStream(Stream stream)
   at ServiceStack.JsonServiceClient.DeserializeFromStream(Stream stream)
   at ServiceStack.ServiceClientBase.HandleResponse(WebResponse webResponse)
   at ServiceStack.ServiceClientBase.SendAll(IEnumerable`1 requests)
   at TestApp.Tests.AcceptanceTests.IdsShouldNotBeReceivedMoreThanOnce() in AcceptanceTests.cs: line 19

**Comment by mythz** [comment]
This should now be resolved in this commit: https://github.com/ServiceStack/ServiceStack/commit/70f15a0029af9d7930ba811e2db00be5b4bd6168

I'm also returning a custom `X-AutoBatch-Completed` HTTP Header in AutoBatched errors that contains how many items were completed before failing the first time.

These change is now available on MyGet. If you already had v4.0.39 MyGet installed earlier you'll need to clear your [NuGet Package Cache and delete your /packages folder](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) to fetch the latest version.

**Comment by malat** [comment]
Awesome, I Will have a try later today

Thanks
