### ISSUE TITLE
GZip Optimized response dont seems to work with batched request

### ISSUE THREAD

**Issue by malat** [ServiceStack/Issues#252]
Hi,

It seems that service handler returning optimize result could not be called using the new batched API

```csharp

public class BatchService : Service
    {

        public object Any(BatchRequest request)
        {
            return Request.ToOptimizedResult(new BatchResult
            {
                Id = request.Id
            });
        }
    }
```

Any workaround ?

**Comment by mythz** [comment]
No this isn't supported, batched requests builds up the Response DTO's into a typed collection, it can't do that when the response is compressed bytes.

**Comment by malat** [comment]
Ok thanks....

It will be great if we can compress the entire batch... Maybe using a custom handler or even better by having a configuration to let SS compressing the entire response...

Anyway thanks for your quick reply
