### ISSUE TITLE
Change name of downloaded csv file 

### ISSUE THREAD

**Issue by jagjotocrex** [ServiceStack/Issues#253]
Hi,

We are facing issues in downloading a CSV file with customised name using the csv format of ServiceStack.
If we add Response Headers inorder to set the filename, we get an error of Multiple Content-Disposition.
We also tried using CsvSerializer method of ServiceStack.Text(v4.0.38), and file downloads but cannot be opened , it says File not found.
Can you please suggest a way to download csv file with customised name?

Your help will be appreciated.

Below is the sample code we have tried.

public void Get(DownloadApprovedData request)
        {
            try
            {
                var data = GetDataFromDB(request);
                var fileName="NewFileName";
                Response.ContentType = "text/csv";
                Response.AddHeader("Content-Disposition", "attachment; filename="+fileName + " " + DateTime.UtcNow.ToString("yyyy-MM-dd") +".csv");

                CsvSerializer.SerializeToStream(ProcessData(data), Response.OutputStream);
               
            }
            catch (Exception ex)
            {
                logger_.Debug(ex);
                throw;
            }
        }

**Comment by mythz** [comment]
You're running into conflicts with the pre-registered [CsvFormat](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Formats/CsvFormat.cs), which adds this Global Request Filter:

```csharp
appHost.GlobalResponseFilters.Add((req, res, dto) =>
{
    if (req.ResponseContentType == MimeTypes.Csv)
    {
        res.AddHeader(HttpHeaders.ContentDisposition,
            string.Format("attachment;filename={0}.csv", req.OperationName));
    }
});
```

So you can change the name by setting `IRequest.OperationName`, otherwise you can remove the conflict by removing the CsvFormat in your AppHost with:

```csharp
Plugins.Remove(x => x is CsvFormat);
```
