### ISSUE TITLE
SwaggerUi not working with generic return types

### ISSUE THREAD

**Issue by halcwb** [ServiceStack/Issues#254]
The current swaggerui cannot be used with generic return types. This has been fixed in the latest release of swaggerui. At least I can open the service description in the petstore.swagger.io without the problems. I think it's version v2.1.8-M1 while version version 2.1.0-alpha.7 is in use with the latest servicestack swagger api (version 4.0.38).

**Comment by mythz** [comment]
Can you provide a source code example of a generic type that doesn't work.
Also do you have a screenshot of it working using the latest version of Swagger?

**Comment by mythz** [comment]
I've upgraded to the latest Swagger UI with this commit: https://github.com/ServiceStack/ServiceStack/commit/1648330cd771f7a9a5dc8e8b4ef2e37ccc91a318

This change is now available from v4.0.39 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by halcwb** [comment]
Thanks!
