### ISSUE TITLE
Update fluent validation library

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#255]
Is it possible to update fluent validation library?

I would like to use more recent version since it returns extra parameters with validation result (property "FormattedMessagePlaceholderValues" in ValidationFailure.cs)

Clients can then localize validation messages as desired (ErrorCode + Parameters).

Regards!

**Comment by mythz** [comment]
Please ask any feature requests on [ServiceStack's UserVoice](http://servicestack.uservoice.com/forums/176786-feature-requests).

**Comment by marko444** [comment]
I believe this is not a new feature.

Regards!
