### ISSUE TITLE
LoadPlugin is no longer virtual

### ISSUE THREAD

**Issue by ngauthier-orckestra** [ServiceStack/Issues#257]
Hi,

Since https://github.com/ServiceStack/ServiceStack/commit/0c3bfd1fce6c69ced80a7bfcf2f77413aed754d8, the ServiceStackHost.LoadPlugin is no longer virtual.

We need to be able to override it to put our own custom implementation.

We cannot use a previous commit because we also need the following fixes: 
https://github.com/ServiceStack/Issues/issues/250, https://github.com/ServiceStack/Issues/issues/251, https://github.com/ServiceStack/Issues/issues/252

Thanks

**Comment by malat** [comment]
Hi,

I think the old LoadPlugin method is now LoadPluginInternal, so we need to override it in our AppHost

Thanks in advance

**Comment by malat** [comment]
I think that you have rename the LoadPlugin for LoadPluginInternal... So if possible to change it for protected virtual and change LoadPlugin for public virtual ... This will let us keep the modification that we have made to the AppHost

Regards

**Comment by mythz** [comment]
Re-added in this commit: https://github.com/ServiceStack/ServiceStack/commit/3188a65eef210b8f7b8677a5acae4e0f59c04804

Was just lost in the refactor.
