### ISSUE TITLE
4.0.36  - OrmLite InsertAllAsync and UpdateAllAsync swallow exceptions

### ISSUE THREAD

**Issue by kkatsma** [ServiceStack/Issues#258]
When using InsertAllAsync and UpdateAllAsync, no exceptions are thrown if there are errors during the execution.   InsertAll and UpdateAll do throw exceptions properly.

This occurs in version 4.0.36, not sure if there is an update to resolve.

**Comment by mythz** [comment]
Do you have a repro?

**Comment by kkatsma** [comment]
The is reproducible.  We don't have test case that hits in memory DB to have it completely encapsulated, but essentially calling method like this below, where Comment is ORMLite mapper class and has an extra column that is not in the underlying table, calling the following method will not result in exception during either SaveAllAsync or UpdateAllAsync.   Removing await and changing to SaveAll or UpdateAll will throw the exception for the bad column.

 public async Task<List<Comment>> SaveCommentsAsync(Comment comment)
        {
            using (IDbConnection db = _factory.Open(ConnectionKeys.DB))
            {
                if (comment.Id > 0)
                    await db.UpdateAllAsync(new List<Comment>() {comment});
                else
                {
                    comment.MadeUpField = 1;
                    comment.InsertDt = DateTime.Now;
                    comment.InsertPartyId = UserIdentity.Id;
                    await db.InsertAllAsync(new List<Comment>() {comment});
                }
                return
                    await GetNotesByAsync(comment.ObjectId, comment.ObjectTypeId, comment.NoteTypeId);
            }
        }

ORMLite class:

 [Alias("Comments")]
    [Schema("dbo")]
    public partial class Comment : IHasId<int>
    {
        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        public int MadeUpField { get; set; }  //<- Field not in underlying table
        [Required]
        public int ObjectId { get; set; }
        [Required]
        public int ObjectTypeId { get; set; }
        [Required]
        public int NoteTypeId { get; set; }
        [Required]
        public string FullName { get; set; }
        [Required]
        public string NoteText { get; set; }
        [Required]
        public string InsertUser { get; set; }
        [Required]
        public DateTime InsertDt { get; set; }
        public int? InsertPartyId { get; set; }
    }

**Comment by mythz** [comment]
Thanks, this should now be fixed with this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/8611d01a70382fdd20737475460926128ab394db

This change is available from **v4.0.39+** that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
