### ISSUE TITLE
Update AppSettings Doc

### ISSUE THREAD

**Issue by camerontucker** [ServiceStack/Issues#259]
The AppSettings docs (https://github.com/ServiceStack/ServiceStack/wiki/AppSettings) indicate that this should work:
```
RedisConfig redisConf = appSettings.Get<RedisConfig>("RedisConf");
```
However all the tests (https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.Common.Tests/Configuration/AppSettingsTests.cs) show that you must include a default value:
```
var value = appSettings.Get<int>("IntKey", 1);
appSettings.Get<int>("BadIntegerKey", 1);
```

**Comment by mythz** [comment]
hmm must've got lost in a refactor, this API is now available from this commit: https://github.com/ServiceStack/ServiceStack/commit/bd832b1ceaaf02a031f4388a114afcf6ff02cd64
