### ISSUE TITLE
Regression: AppHost.Init() throws with requests returning value type

### ISSUE THREAD

**Issue by ngauthier-orckestra** [ServiceStack/Issues#260]
From the latest version on myget.

With the following request and service (or any request returning a value type):
```c#
[Route("/TestRequest/{Id}", Verbs = "GET")]
public class TestRequest : IReturn<int> { }
    
public class TestService : Service
{
    public int Any(TestRequest request)
    {
        return new Random().Next();
    }
}
```
I get the following exception:

```c#
System.ArgumentException occurred
  HResult=-2147024809
  Message=Expression of type 'System.Int32' cannot be used for return type 'System.Object'
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.ValidateLambdaArgs(Type delegateType, Expression& body, ReadOnlyCollection`1 parameters)
  InnerException: 
```
From this invocation:
```c#
new AppHost().Init();
```

**Comment by mythz** [comment]
The error says what the issue is, Request and Response DTO's need to be concrete types, never value types.

**Comment by malat** [comment]
Hi Mithz,

I understand but this is a regression from previous version, we was able to make this before...

I understands that is not an good practice but we have lots of client that uses our current API and I hope that we will not need to make breaking change in our existing deployment

Thanks again

**Comment by mythz** [comment]
What version was this supported? Change the return type to object.

**Comment by malat** [comment]
Our current deployed version is 4.0.36...

But as you say we will try your proposed workaround and let you know if we need further support

Thanks again
