### ISSUE TITLE
can't read the session-Id from  the user session (solved)

### ISSUE THREAD

**Issue by stefan2410** [ServiceStack/Issues#261]
We had tested  the code with version  4.0.36  and it worked . With the new version we have problem, The session-Id  returns empty. I  call  our  special service to  post  to the authenticate. and returns the custom session .  Session returns authenticated with data from the userAuth table and our  specific info but without SessionId.  Also the cookie in the client is without Id.
I hope we did not do any stupid error and we destroy our previous  correct code.
Ι had tried yesterday to save the session in Sql Server - CacheEntry, but the session saved with Id= urn:session without the Id.

**Comment by mythz** [comment]
Can you put this code into an example I can run locally to repro the issue?

It's hard to tell what the issue is exactly, are you saying `session.Id` doesn't have a value or `authResponse.SessionId` doesn't have a value or both?

**Comment by stefan2410** [comment]
both they have not value,  session and authResponse 
but the authResponse does not return null and session has all fields   with  values ( these from the UserAuth table  and our custom. It comes also Autheticated.  Now I try, reading other issues here,  to add the SessionId manually, before I save the Session. to see what happens. I will try  to send you code.

**Comment by stefan2410** [comment]
I don't know if  the following helps you.  I add in my service, 
a. SqlServer -CacheEntry
b.  o create my sessionId before saving  the session in my service (it does not need, as I see, it is  saved when it is authenticated.)
                        session.Id = Guid.NewGuid().ToString();
                       authResponse.SessionId = session.Id; 
                        this.SaveSession(session, new TimeSpan(, 3, 0, 0));
In SQL  was before    save                    
          urn:iauthsession:	{....APIAuthUserSession, .....ExpiryDate	2015-04-02  
   then added
           urn:iauthsession:cc4e2194-ff71-4458-9333-c20b4d99d90b	 Expiry in 3 yours  

But, In client , it  returns  only  one cookie the ss-id  EMPTY (even if I gave manually the value)
Also  does not return the 2nd cookie  the ss-pid, ( even with RememberMe = true)

**Comment by mythz** [comment]
Unless I can run the code, it doesn't help. The Session tests continue to pass so I expect it's something to do with your custom implementation but I can't tell what it is until I can verify the behavior locally. 

Not sure if you're doing this, but you should never set the sessionId, it should be automatically populated and matching the ServiceStack Session Id Cookies, so you should leave it to ServiceStack to create.

**Comment by stefan2410** [comment]
I never set the sessionId. now only for the test.  I try to prepare you the code

**Comment by stefan2410** [comment]
Try this please. 
https://gist.github.com/stefan2410/00bba6f0344c36439746

hope you will not suffer.

**Comment by stefan2410** [comment]
Demis,   I found it.    
It creates the session Id   (I can see it in the SQL Server)  only if the  login has  RememberMe = true
         SQLServer CacheEntry=?
![sqlcookie](https://cloud.githubusercontent.com/assets/1259393/6743804/89808136-cea7-11e4-9bf4-32dcec7ef8ca.PNG)
but the cookie (only one  the ss-id)  returns  empty
![cookie](https://cloud.githubusercontent.com/assets/1259393/6743814/ab4798b8-cea7-11e4-8c1a-d9bcfaad279d.PNG)

**Comment by mythz** [comment]
Really wished you sent me an actual VS.NET project that I could just run so I didn't have to waste time trying to stitch it all together. The code is also incomplete with `AuthTests.cs` missing its impl which presumably contained the code to register the users.

But is this issue just coming down to because you haven't specified `RememberMe = true`? This is required when using the ServiceClients otherwise the Cookies are not saved on the ServiceClient instnace?

Anyway this test works for me:

```csharp
[Test]
public void APIAuthenticate_Login_Test()
{
    var client = new JsonServiceClient(@"http://localhost:21092/");

    var registerResponse = client.Post(new Register
    {
        DisplayName = "DisplayName",
        FirstName = "FirstName",
        LastName = "LastName",
        UserName = "grmadmin",
        Password = "z9",
        AutoLogin = false
    });

    var loginResponse = client.Post<APIAuthenticateResponse>(new APIAuthenticate {
        UserName = "grmadmin",
        Password = "z9",
        RememberMe = true
    });

    Assert.That(loginResponse, Is.Not.Null);
    var response = client.Post<myHelloResponse>(new myHello {Name = "World"});
}
```

What's the test that doesn't?

**Comment by stefan2410** [comment]
I feel terrible right now , because  I wasted your time, with my ignorance about the RememberMe = true and the ServiceClients. I thought that  RememberMe influence only the life of  sessions in Server.
We use serviceStack authentication in Asp.Net Mvc5 application (instead of their Owin)  and we  have service calls, where we create  clients all time and we add them cookies with the  initial SessionId from the login. A programmer wrote code to save this sessionId in the Identity.Claims  to take it from there. I think there is an error also there and it  does not return it.
Again sorry, for your time,  I will make a lot of time to  ask again help
