### ISSUE TITLE
Signed Nuget Packages for ServiceStack.OrmLite.MySql  & ServiceStack.Logger.Log4Net

### ISSUE THREAD

**Issue by clairenicholson** [ServiceStack/Issues#262]
Hi,
I can see there are signed versions of various other ServiceStack and specifically OrmLite packages but I need signed versions of the following please?

1. ServiceStack.OrmLite.MySql
2. ServiceStack.Logger.Log4Net

Many thanks in advance

Claire

**Comment by mythz** [comment]
I've added a new `ServiceStack.OrmLite.MySql.Signed` package for MySql which is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

But wont be maintaining multiple NuGet packages for the Log4Net adapter, you can just copy the 2 classes into your project instead, which you can get from: https://github.com/ServiceStack/ServiceStack/tree/master/src/ServiceStack.Logging.Log4Net

**Comment by clairenicholson** [comment]
That's fantastic,  thanks so much Demis.
Best Claire

--- Original Message ---
