### ISSUE TITLE
Xamarin Forms support for ServiceStack client (targeting Windows Phone also)?

### ISSUE THREAD

**Issue by bumblebeeman** [ServiceStack/Issues#264]
Hey, love ServiceStack!

I see that I can use the ServiceStack client with Xamarin to target individual forms, but I can't use it with Xamarin Forms (unless I remove 'Windows Phone Silverlight' as a target).

Is this in the pipeline for future releases? Or is there a way to do it now (maybe some code on an experimental branch or something)?

Thanks

**Comment by mythz** [comment]
The different supported platforms for the PCL clients are listed at: https://github.com/ServiceStackApps/HelloMobile#portable-class-library-support

i.e. only ServiceStack.Interfaces is a pure PCL .dll that supports all platforms, Silverlight is a custom (i.e. non-PCL) build and Windows Phone ServiceClient isn't supported as it didn't have the required API's, we'll revisit Windows Phone after VS 2015 is released.

**Comment by bumblebeeman** [comment]
Thanks for the fast response!
