### ISSUE TITLE
ServiceStack.Text Env.ReferenceAssemblyPath throw exception on live server

### ISSUE THREAD

**Issue by Nness** [ServiceStack/Issues#265]
Reproduce project download link: https://mega.co.nz/#!TENXWYwa!ie4KiyhDOM3yZDKsNtRJpPgwu7dNH9NeqAEcm_FSKqk

Exception:
Could not infer .NET Reference Assemblies path, e.g 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\'.
Provide path manually 'Env.ReferenceAssembyPath'.
   at ServiceStack.Text.Env.get_ReferenceAssembyPath()
   at ServiceStack.Support.Markdown.Evaluator.ConstructEvaluator(IEnumerable`1 items)
   at ServiceStack.Support.Markdown.EvaluatorExecutionContext.Build()
   at ServiceStack.Support.Markdown.MarkdownPage.Write(TextWriter textWriter, PageContext pageContext)
   at ServiceStack.Support.Markdown.TemplateExtensions.RenderToString(MarkdownPage markdownPage, Dictionary`2 scopeArgs, Boolean renderHtml)
   at ServiceStack.Formats.MarkdownFormat.RenderDynamicPage(MarkdownPage markdownPage, Dictionary`2 scopeArgs, Boolean renderHtml, Boolean renderTemplate, String templatePath)
   at ServiceStack.Formats.MarkdownFormat.ProcessMarkdownPage(IRequest httpReq, MarkdownPage markdownPage, Object dto, IResponse httpRes)
   at ServiceStack.Support.Markdown.MarkdownHandler.ProcessRequest(IRequest httpReq, IResponse httpRes, String operationName)
   at System.Threading.Tasks.Task.Execute()"

What happen is if I have a markdown file in the server, when I try to access once deployed to live server, it does not work. ServiceStack.Text Env.ReferenceAssemblyPath try to look for "System.Core" under "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\". Where that folder only exist in development environment. If I change that property to "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\" it works. 

I have also tried to include system.core in main project, the error still same. From ServiceStack.Text code itself I cannot find anything that uses that property.

That reproduce project have a lot of useless code, but main point is that markdown file (changelog.md) and deploy to an environment without visualstudio dll reference folder.

**Comment by Nness** [comment]
System.Exception: Error Compiling Expression: Error Compiling Expression: Metadata file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319System.Core.dll' could not be found

   at ServiceStack.Support.Markdown.Evaluator.ConstructEvaluator(IEnumerable`1 items)
   at ServiceStack.Support.Markdown.EvaluatorExecutionContext.Build()
   at ServiceStack.Support.Markdown.MarkdownPage.Write(TextWriter textWriter, PageContext pageContext)
   at ServiceStack.Support.Markdown.TemplateExtensions.RenderToString(MarkdownPage markdownPage, Dictionary`2 scopeArgs, Boolean renderHtml)
   at ServiceStack.Formats.MarkdownFormat.RenderDynamicPage(MarkdownPage markdownPage, Dictionary`2 scopeArgs, Boolean renderHtml, Boolean renderTemplate, String templatePath)
   at ServiceStack.Formats.MarkdownFormat.ProcessMarkdownPage(IRequest httpReq, MarkdownPage markdownPage, Object dto, IResponse httpRes)
   at ServiceStack.Support.Markdown.MarkdownHandler.ProcessRequest(IRequest httpReq, IResponse httpRes, String operationName)
   at System.Threading.Tasks.Task.Execute()"

**Comment by Nness** [comment]
Just curious if its viable to check "C:\Windows\Microsoft.NET\Framework\" as part of ReferenceAssemblyPath discover logic. Code can try to find folder that's start with "v4."

**Comment by mythz** [comment]
it's already fixed in https://github.com/ServiceStack/ServiceStack.Text/commit/ffdf69c8da4a35215b1fa606400ec881df71e0a1

It's still deploying to MyGet, will let you know when it's finished.

**Comment by mythz** [comment]
FYI, just finished deploying to MyGet: https://github.com/ServiceStack/ServiceStack/wiki/MyGet

**Comment by Nness** [comment]
Tested and same result, still have to explicitly point ReferenceAssembyPath to "C:\\Windows\\Microsoft.NET\\Framework\\v4.0.30319\\"

On deploy server, following folder doesn't exist. "C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework.NETFramework\v4.0"

Just curious if those missing folder belong to .net client profile installation? Which means Markdown function in ServiceStack.dll is depend on .net client profile been installed instead of full version of .net.

https://msdn.microsoft.com/en-us/library/vstudio/ff462634%28v=vs.100%29.aspx

**Comment by mythz** [comment]
This wasn't required in .NET 3.5 or Mono, but it started throwing runtime exceptions after moving to .NET 4.0 where CodeDom now required a reference to the reference assemblies when using CodeDom for the code generation in MarkdownFormat.

I've changed it to use the latest `v4` folder in the reference assemblies folder in this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/65a540065509ca5cbe25e3daaa349def0c6eafbd

This change is now available on MyGet but you'll need to [clear your NuGet packages cache and delete your /packages folder](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) to get the latest libs.

**Comment by Nness** [comment]
I think it won't work. 

netFxReferenceBasePath is pointing to wrong directory. GAC is not locate at programfiles path.

Here should be proper path for last fallback:

if (!IsMono && referenceAssembyPath == null)
{
	var programFilesPath = PclExport.Instance.GetEnvironmentVariable("ProgramFiles(x86)") ?? @"C:\Program Files (x86)";
	var netFxReferenceBasePath = programFilesPath + @"\Reference Assemblies\Microsoft\Framework\.NETFramework\";
	if ((netFxReferenceBasePath + @"v4.5.2\").DirectoryExists())
		referenceAssembyPath = netFxReferenceBasePath + @"v4.5.2\";
	else if ((netFxReferenceBasePath + @"v4.5.1\").DirectoryExists())
		referenceAssembyPath = netFxReferenceBasePath + @"v4.5.1\";
	else if ((netFxReferenceBasePath + @"v4.5\").DirectoryExists())
		referenceAssembyPath = netFxReferenceBasePath + @"v4.5\";
	else if ((netFxReferenceBasePath + @"v4.0\").DirectoryExists())
		referenceAssembyPath = netFxReferenceBasePath + @"v4.0\";
	else
	{
		var sysRootPath = PclExport.Instance.GetEnvironmentVariable("SYSTEMROOT") ?? @"C:\Windows";
		var gac86Path = sysRootPath + @"\Microsoft.NET\Framework\";
		var v4Dirs = PclExport.Instance.GetDirectoryNames(gac86Path, "v4*");
		if (v4Dirs.Length > 0)
		{
			referenceAssembyPath = v4Dirs[v4Dirs.Length - 1]; //latest v4
		}
		else
		{
			throw new FileNotFoundException(
				"Could not infer .NET Reference Assemblies path, e.g '{0}'.\n".Fmt(netFxReferenceBasePath + @"v4.0\") +
				"Provide path manually 'Env.ReferenceAssembyPath'.");
		}
	}
}

**Comment by mythz** [comment]
This isn't looking for the GAC, it's looking for the Reference Assemblies. Can you just try it and confirm it doesn't work?

**Comment by Nness** [comment]
2015-03-25 08:06:34.7799,INFO,Application_Start,4.0.39.0 2015-03-24T20:56:22.9304323Z,
System.IO.FileNotFoundException: Could not infer .NET Reference Assemblies path, e.g 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.0\'.
Provide path manually 'Env.ReferenceAssembyPath'.
   at ServiceStack.Text.Env.get_ReferenceAssembyPath()
   at ServiceStack.Support.Markdown.Evaluator.ConstructEvaluator(IEnumerable`1 items)
   at ServiceStack.Support.Markdown.EvaluatorExecutionContext.Build()
   at ServiceStack.Support.Markdown.MarkdownPage.Write(TextWriter textWriter, PageContext pageContext)
   at ServiceStack.Support.Markdown.TemplateExtensions.RenderToString(MarkdownPage markdownPage, Dictionary`2 scopeArgs, Boolean renderHtml)
   at ServiceStack.Formats.MarkdownFormat.RenderDynamicPage(MarkdownPage markdownPage, Dictionary`2 scopeArgs, Boolean renderHtml, Boolean renderTemplate, String templatePath)
   at ServiceStack.Formats.MarkdownFormat.ProcessMarkdownPage(IRequest httpReq, MarkdownPage markdownPage, Object dto, IResponse httpRes)
   at ServiceStack.Support.Markdown.MarkdownHandler.ProcessRequest(IRequest httpReq, IResponse httpRes, String operationName)
   at System.Threading.Tasks.Task.Execute()"

![program files reference assembly](https://cloud.githubusercontent.com/assets/1712143/6812929/f2ddd5a6-d2d6-11e4-8699-9d1232708ed5.png)
![gac folder](https://cloud.githubusercontent.com/assets/1712143/6812930/f4834f94-d2d6-11e4-9bab-5d2727aa6c1c.png)

The problem is server doesn't have referenceassemblypath for .net 4.0 if you install any .net 4.5.2, 4.5.1, 4.5 full version.

**Comment by Nness** [comment]
I only updated servicestack.text, unless there are other code change in servicestack project.

**Comment by mythz** [comment]
How can it not have the reference assemblies installed? Do you have the full .NET Framework installed? ServiceStack is not supporting just the Client Framework.

**Comment by Nness** [comment]
Weird. AWS server doesn't come with 4.5.2 .net, that means I definitely installed it. While 4.5.2 I can only find one offline installer. 
http://www.microsoft.com/en-nz/download/details.aspx?id=42642
I just stand up a micro instance and I will install .net there to test out.

**Comment by mythz** [comment]
That download says it's a:

> in-place update to the Microsoft .NET Framework 4, Microsoft .NET Framework 4.5 and Microsoft .NET Framework 4.5.1.

So perhaps you need to update from an existing version?

**Comment by Nness** [comment]
2013r2 come with .net 4.5.1?
https://msdn.microsoft.com/en-us/library/5a4x27ek(v=vs.110).aspx

**Comment by Nness** [comment]
The one I want to test out is, those folder are not belong to developer package. 
http://www.microsoft.com/en-nz/download/details.aspx?id=42637

**Comment by Nness** [comment]
2013r2 refresh box from AWS:
![2013r2 fresh install](https://cloud.githubusercontent.com/assets/1712143/6814840/7765069a-d2e7-11e4-9039-be9f709ea9d4.png)
![2013r2 fresh install gac](https://cloud.githubusercontent.com/assets/1712143/6814842/7ad12f7a-d2e7-11e4-9d6e-7008ff237819.png)


2013r2 cannot install .net4.5 full package (230mb)
![2013r2 fresh cannot install net45](https://cloud.githubusercontent.com/assets/1712143/6814846/8889f048-d2e7-11e4-901b-c5ef7cb9b72c.png)

2013r2 refresh box comes with 4.5.2
![2013r2 installed 4 5 2 already](https://cloud.githubusercontent.com/assets/1712143/6814850/95304a90-d2e7-11e4-962b-d36b16e6a594.png)

2013r2 repair .net 4.5.2
![2013r2 repaired](https://cloud.githubusercontent.com/assets/1712143/6814855/a24f1918-d2e7-11e4-9d13-99f9a640bac9.png)

2013r2 program files after repair - reference assembly folder does not exist
![2013r2 program files after repair](https://cloud.githubusercontent.com/assets/1712143/6814860/ba970710-d2e7-11e4-8297-9a794beb02cd.png)

2013r2 install .net 4.5.2 developer package
![2013r2 program file exist after install developer version](https://cloud.githubusercontent.com/assets/1712143/6814865/ca55810e-d2e7-11e4-9b76-0413cfeab2d3.png)


As what they said on stackoverflow, Assembly references folder only exist if you install developer package. Its not part of standard package. You cannot expect 2013r2 to have those reference out of box.

**Comment by mythz** [comment]
Not sure what's going on with the new .NET installers, but every (full) .NET Framework had them installed until now. If you can confirm that it works with path to the GAC? I can add it as the last fallback.

**Comment by mythz** [comment]
FYI, now falling back to using your GAC assembly fallback in this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/a9cd318f86a86aa29fc1d59b42f09d7c5b0636fb

This change is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by Nness** [comment]
Cool, I will test it out in next few hours and let you know the result.

**Comment by Nness** [comment]
Metadata file 'C:\Windows\Microsoft.NET\Framework\v4.0.30319System.Core.dll' could not be found

The path is correct, but because you didn't use Path.Combine, the directory full path you get from DirectoryInfo doesn't have slash at end.

**Comment by mythz** [comment]
Crap, was missing the trailing `\`, updated in this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/bf7bf7e71b3ed8e99960652a8ee96e8d3a98d00e

and now finished deploying to MyGet.

**Comment by Nness** [comment]
Tested. All good :dancers: 

Thanks

**Comment by mythz** [comment]
Sweet, happy to hear it :+1:
