### ISSUE TITLE
Assemblies must be loaded before ServiceStack.Razor compile

### ISSUE THREAD

**Issue by hstravis** [ServiceStack/Issues#266]
We're using ServiceStack.Razor version 4.0.32. But I figured out what's happening by looking at the latest source code. The problem we have is that assemblies that should be found are not being found by the ServiceStack.Razor compiler.

The ServiceStack.Razor.Compilation.RazorPageHost only passes assemblies that have already been loaded into the compiler. This is the code that determines which assemblies get pass into the compiler (and can therefore be referenced by razor pages):

    var assemblies = CompilerServices
                .GetLoadedAssemblies()
                .Where(a => !a.IsDynamic);

However, our razor pages are using some assemblies that are not loaded before the razor compiler is invoked. Specifically, we're using Humanizer in our razor pages but no where else in the app. So "using Humanizer;" causes a compiler error.

Note that it works the FIRST time the page is requested. I think that is because Humanizer is in the web app's bin directory. But after the first request, it isn't found because, I suppose, the ASP.Net temp dir is not searched the same way as the bin directory is....that's just a guess.

With the Microsoft razor compiler, assemblies can be specified explicitly in the system.web\compiler\assemblies section of web.config. As far as I can tell, there is no corresponding option for the ServiceStack.Razor compiler.

The work-around (that also makes me fairly sure that I'm correct) is to explicitly load the assembly before the razor compiler is invoke. Adding this line to Global.asax fixes it: Assembly.Load("Humanizer");

BTW - Other than this issue, I really like ServiceStack.Razor. It suits our needs very well.

**Comment by mythz** [comment]
Will need a repro to be able to look into it, but have you added the namespace to Web.config, e.g:

```xml
<system.web.webPages.razor>
<pages pageBaseType="ServiceStack.Razor.ViewPage">
    <namespaces>
      ...
      <add namespace="Humanizer" />
    </namespaces>
</pages>
</system.web.webPages.razor>
```

Otherwise just creating an referencing the type in that assembly or creating an instance of it in `Configure()` should force load the Assembly.

**Comment by hstravis** [comment]
Yes that is the first thing I tried. As I said, I looked at the source code and it is clear what the problem is. I can live with my work-around. Good luck.

**Comment by mythz** [comment]
ok cool no worries, thx.

**Comment by hstravis** [comment]
Surprised you closed it. As far as I can tell, it is a real bug. I can live with my work-around but I thought you'd want to fix it anyway - if not for me, then for the next schmuck.

**Comment by mythz** [comment]
The solution is to statically reference the type so it's loaded on Startup. We definitely don't want to start force loading assemblies dynamically in the framework.

**Comment by mythz** [comment]
Also I'd prefer statically referencing the type over using a magic string, e.g something like:

```csharp
typeof(TypeInAssembly).Name.Print();
```

But since Humanizer is a collection of extension methods, just call the extension method, e.g:

```csharp
"Load Humanizer".Humanizer();
```

**Comment by mythz** [comment]
I've added a commit that should load any unloaded assemblies based on namespaces in Razor Web.Config in this commit: https://github.com/ServiceStack/ServiceStack/commit/69199008df46115c5597e6a4cfcd3cc077f42f86

Although this would only Load the assembly when the Namespace matches Assembly name.

**Comment by hstravis** [comment]
Then it ought to be documented. Explain that with the Microsoft razor
compiler there is a way in web.config to specify assemblies specifically
for razor pages - using compiler.assemblies. And the way to do it for the
ServiceStack razor compiler is to statically load all assemblies before
razor pages are compiled.

Just a friendly suggestion.
