### ISSUE TITLE
Filename passed in uri is getting clipped at the "." in the file extension.

### ISSUE THREAD

**Issue by RayGralak** [ServiceStack/Issues#267]
I'm not sure if this is a legitimate bug or misconfiguration on my part. I'm using ServiceStack 4.0.36 within a .Net 4.0 Winforms application on Windows 7 x64 Enterprise + Visual Studio 2013

I am trying to pass a filename string to my application by embedding in the URL but the filename's file extension is getting clipped. For example, if from a browser I enter the folowing 

http://127.0.0.1:12345/api/jetting/setup/waveform/printingwaveform/Ray1.csv

The filename property in my class below gets set to "Ray1", not "Ray1.csv". The Uri does show the entire string, including the ".csv", i.e.:

**this.Request.RawUrl** in my hook event call below contains ***"/api/jetting/setup/waveform/printingwaveform/Ray1.csv"***.

But, ***request***, which is an instance of class **SetGlobalPrintingWaveform**, shown below, has a member, ***filename***, which only contains ***"Ray1"*** instead of ***"Ray1.csv"***.

So, do you any ideas what I'm doing wrong?

The routing class I use looks like this:
```c#
		[Route("/api/printing/setup/globalwaveforms/printingwaveform/{filename}")]
		[DataContract]
		public class SetGlobalPrintingWaveform
		{
			[DataMember]
			public string regvalue { get; set; }
			[DataMember]
			public string filename { get; set; }
		}
		public class SetGlobalPrintingWaveformResponse
		{
			public ResponseStatus ResponseStatus { get; set; } //Automatic exception handling
			public string Result { get; set; }
		}
		public class SetGlobalPrintingWaveformService : Service
		{
			[AddHeader(ContentType = "text/plain")]
			public string Any(SetGlobalPrintingWaveform request)
			{
				string response = "";
				if (RestAPIHookEvent != null)
					RestAPIHookEvent(this.Request.RawUrl, "SetGlobalPrintingWaveform", out response, request);
				return response;
			}
		}
```

**Comment by mythz** [comment]
It's due to the built-in [Content Negotiation support in Routing](https://github.com/ServiceStack/ServiceStack/wiki/Routing#content-negotiation) where if the Route contains an extension for a registered ContentType ServiceStack automatically removes it from the PathInfo and sets the ContentType with it.

You can disable this feature with:

```csharp
SetConfig(new HostConfig { AllowRouteContentTypeExtensions = false });
```
