### ISSUE TITLE
In addition to Issue #239

### ISSUE THREAD

**Issue by OlegNadymov** [ServiceStack/Issues#268]
In addition to https://github.com/ServiceStack/Issues/issues/239 :

As I said, I have the following cases:
```C#
[Alias("base_table")]
public class BaseObject
{
    [AutoIncrement]
    [Alias("_id")]
    public int Id { get; set; }

    [Alias("_name")]
    [StringLength(250)]
    public string Name { get; set; }
}

[Alias("apply_table")]
public class ApplyObject : BaseObject
{
    [Alias("_some_property1")]
    [StringLength(250)]
    public string SomeProperty1 { get; set; }
}
```

And you advised me it:
```C#
class JoinedObject {
    public int Id { get; set; }
    public string Name { get; set; }
    public int ApplyObjectId { get; set; }
    public string ApplyObjectName { get; set; }
    public string SomeProperty1 { get; set; }
}
var results = db.From<BaseObject>()
    .Join<ApplyObject>((b,a) => b.Id == a.Id)
    .SelectInto<JoinedObject>();
results.PrintDump();
```
It's ok!

But I tried it:
```C#
public class FakeClass: ApplyObject
{
}

var results = db.Select<FakeClass>(con.From<BaseObject>()
                                     .Join<ApplyObject>((b, a) => b.Id == a.Id));
```

And this way is Ok also!

Can I use this way in my code?
If I can, I would like to use an easier way without creating FakeClass:
```C#
var results = db.Select<ApplyObject>(con.From<BaseObject>().
                                     .Join<ApplyObject>((b, a) => b.Id == a.Id));
```
Do you have plans to implement it?

And the last question. 
How I can use Create, Update, Delete operations for that objects?
If I try it:
```C#
db.Update<FakeClass>(obj);
```
or
```C#
db.Update<ApplyObject>(obj);
```

i have errors because ORM generate SQL in only once table ("apply_table" - alias for ```ApplyObject```)

Thanks in advance for any ideas!!

**Comment by mythz** [comment]
You can see this answer for an alternative way of changing the table alias at runtime: http://stackoverflow.com/a/29271142/85785

You can find docs explaining how the mapping works when selecting into another type on the [OrmLite Home Page](https://github.com/ServiceStack/ServiceStack.OrmLite#selecting-multiple-columns-across-joined-tables).

But there aren't any plans to add other API's, you can add any feature requests with proposed API's on [UserVoice](http://servicestack.uservoice.com/forums/176786-feature-requests).
