### ISSUE TITLE
RowCount fails on SqlServer if expression has Order By (OrmLite 4.0.38)

### ISSUE THREAD

**Issue by UriHendler** [ServiceStack/Issues#269]
If the SqlExpression has an ORDER BY, the SQL generated by the dialect provider for the RowCount statement is incorrect.
```
var query = db.From<User>()
    .Select(x => x.UserName)
    .OrderBy(x => x.Id);

var rowCount = db.RowCount(query);
```

The generated SQL will be:
```
SELECT COUNT(*)
FROM
(
	SELECT "UserName"
	FROM "User"
	ORDER BY "Id"
) AS "Count"
```
which gives the error:
> The ORDER BY clause is invalid in views, inline functions, derived tables, subqueries, and common table expressions, unless TOP, OFFSET or FOR XML is also specified.

**Comment by mythz** [comment]
Hi Uri,

Thanks for the test, ended up taking a [slightly different approach](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/ebf73b54232fc8d54156698a753c4a32612de91f).

This change just finished [deploying to MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by UriHendler** [comment]
Your solution is much cleaner.

I was trying to keep the solution in the SQL Server dialect provider.
