### ISSUE TITLE
  Signed Nuget Packages for ServiceStack.Interfaces

### ISSUE THREAD

**Issue by clairenicholson** [ServiceStack/Issues#270]
We have a requirement to use only signed assemblies so I've been happily switching to the .signed versions and thanks to you resolving my previous ticket (https://github.com/ServiceStack/Issues/issues/262) we're almost there.

However I have found another issue with ServiceStack.Common.Signed as it has a dependency on Interfaces (non signed). I've done a search to see if I could find a signed version of Interfaces but no joy so was hoping you could help please.

![servicestack-common-signed-dependencies](https://cloud.githubusercontent.com/assets/9721126/6845391/344896ea-d3ac-11e4-8ca3-b2bd3c74024c.PNG)

Many thanks in advance

**Comment by Layoric** [comment]
Hi @clairenicholson, the ServiceStack.Interfaces assembly is actually signed. You can check for yourself using the strong name tool 'sn.exe', check [here for instructions](http://blog.codingoutloud.com/2010/03/13/three-ways-to-tell-whether-an-assembly-dl-is-strong-named/).

Hope that helps.

**Comment by clairenicholson** [comment]
Thanks for quick response on this.
My bad... I had assumed as it didn't match the .signed convention it would not be.
