### ISSUE TITLE
Invalid auto-generated "order by" when using joins and limit

### ISSUE THREAD

**Issue by robertmiles3** [ServiceStack/Issues#272]
I recently found this issue when using a join + limit without explicity specifying the OrderBy. The gist below is a failing test to see the issue.

https://gist.github.com/robertmiles3/fb4e4487d338ca91ee70

As can be seen from the generated SQL, the generated "order by" clause uses the join model's name `FooBarJoin` instead of the proper one. The issue lies in `SqlServerOrmLiteDialectProvider.ToSelectStatement` when it calls `GetQuotedColumnName`...

    orderByExpression = string.Format("ORDER BY {0}",
                        this.GetQuotedColumnName(modelDef, modelDef.PrimaryKey));

Obviously this is an easy work-around with explicitly setting the `OrderBy`, but wanted to report it nonetheless. 

**Environment:**
ServiceStack 4.0.38
Windows 8.1
.NET 4.5
SQL Server 2014 Express

**Comment by mythz** [comment]
Hi Robert,

Can you switch to use the documented OrmLite SqlExpressions as `JoinSqlBuilder<>` is obsolete, it was a helper class contributed by the community but not a solution we've encouraged, documented or maintained. 

This should work when you rewrite your expression with SqlExpression:

```csharp
var jn = db.From<Foo>()
    .Join<Foo, Bar>((f,b) => f.BarId == b.Id)
    .Limit(1, 2);

var results = db.Select<FooBarJoin>(jn);
```

The entire test was added with this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/5da52b973cf4c3c846bd55455160ef59d3ace707

**Comment by robertmiles3** [comment]
Awesome! Sorry if I wasted your time or anything. I've been using SS for a few years now and didn't catch that JoinSqlBuilder was discouraged now. Thanks so much!
