### ISSUE TITLE
Invalid SQL generated when using join + limit when table or field has spaces in alias

### ISSUE THREAD

**Issue by robertmiles3** [ServiceStack/Issues#273]
I recently found this issue when using a join + limit when a table or field has spaces in the alias name. The gist below is a failing test to see the issue.

https://gist.github.com/robertmiles3/beca4f661c3bc11cffaa

You'll see that the test fails because inside `SqlServerOrmLiteDialectProvider.UseAliasesOrStripTablePrefixes` this section of code splits on spaces and therefore breaks it apart in the middle of an alias...

                var aliasParts = field.SplitOnLast(' ');
                if (aliasParts.Length > 1)
                {
                    sb.Append(" " + aliasParts[aliasParts.Length - 1]);
                    continue;
                }

If I comment out the above code, the test runs fine and generates the proper output. However, I didn't run all the other tests to see if they would fail. I'm not sure what scenario you're trying to catch in this code, so I'll let you figure out how to best handle it.

This is a breaking change for my setup, but I've worked around it in the meantime by creating a stored proc to use instead. I'd love to come back away from the proc as soon as I can to give more flexibility.

**Environment:**
ServiceStack 4.0.38
Windows 8.1
.NET 4.5
SQL Server 2014 Express

**Comment by mythz** [comment]
Likewise this works when you use SqlExpression, e.g:

```csharp
var jn = db.From<FooSpace>()
    .Join<FooSpace, BarSpace>((f,b) => f.BarId == b.Id)
    .OrderBy<FooSpace>(f => f.Id)
    .Limit(1, 2);

var results = db.Select<FooSpaceBarSpaceJoin>(jn);
```

Entire test is visible in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/8fedda7e5eb6fff131344d1ad97d8f3b86d66bb2

**Comment by robertmiles3** [comment]
Thanks! (see https://github.com/ServiceStack/Issues/issues/272#issuecomment-91313626)
