### ISSUE TITLE
Add Swift reference extension not working in XCode 6.3

### ISSUE THREAD

**Issue by specimen151** [ServiceStack/Issues#274]
I just downloaded 6.3, and the XCode extension doesn't seem to work. There is no menu entry.

Also, the generated code has lots of errors that probably has something to do with the new version of Swift. I guess there is no point of listing them here.

**Comment by Layoric** [comment]
@specimen151 The plugin has been updated to work with 6.3, [download the updated version here](https://github.com/ServiceStack/ServiceStack.Swift/raw/master/dist/ServiceStackXcode.dmg).

As for the compile issues with the generated code, could give some examples of the problems you are seeing when compiling with the new version of Xcode?

**Comment by specimen151** [comment]
Hi
I just created a new empty project (master detail) on XCode 6.3 (Yosemite).

The Add Servicestack reference now shows in the menu.

The errors I get are:


public protocol HasReflect {
    typealias T : HasReflect
    class func reflect() -> Type<T>
    init()
}

It doesn’t like “class func”: Class methods are only allowed within classes; use static to declare a static method. 


public protocol Convertible {
    typealias T
    class var typeName:String { get }
    class func fromObject(any:AnyObject) -> T?
}

Same here on “fromObject”. On “typeName” it says the same, just for “property”.



private enum State<T> {
    case Pending(Handlers)
    case Fulfilled(@autoclosure () -> T) //TODO use plain T, once Swift compiler matures
    case Rejected(Error)
}

Says that @autoclosure is not allowed for enum.

    func populateResponseStatusFields(inout errorInfo:[NSObject : AnyObject], withObject:AnyObject) {
        if let status = getItem(withObject as NSDictionary, key: "ResponseStatus") as? NSDictionary {
            if let errorCode = getItem(status, key: "errorCode") as? NSString {
                errorInfo["errorCode"] = errorCode
            }


Says AnyObject is not convertible to  NSDictionary. Needs as! (with !) according to Swift 1.2.


    func append(json:String?) {
        if countElements(sb) > 0 {
            sb += ","
        }
        sb += json != nil ? "\(json!)" : "null"
    }

Says: countElements has been renamed to just count.




public class JOptionalProperty<T : HasReflect, P : StringSerializable> : PropertyType
{
    public var get:(T) -> P?
    public var set:(T,P) -> Void
    
    init(name:String, get:(T) -> P?, set:(T,P?) -> Void)
    {
        self.get = get
        self.set = set
        super.init(name: name)
    }
    
Says: Function signature (T,P?)->Void is not compatible with expected type (T,P)->Void (note the ?).



Warning on:
        let gregorian = NSCalendar(identifier:NSGregorianCalendar)
Says: NSGregorianCalendar is deprecated.

 
        body({ resolver(.Fulfilled($0)) }, { error in
            if let pmkerror = error as? Error {
                pmkerror.consumed = false
                resolver(.Rejected(pmkerror))
            } else {
                resolver(.Rejected(Error(domain: error.domain, code: error.code, userInfo: error.userInfo)))
            }
        })


Says: Cannot invoke Body with an argument list of type ((_)-> (hard to see)



On the DTO there are not many problems.
The only one I can see is that one of the classes “does not conform to protocol IReturn”.
// @Route("/assets/css/{Name}", "GET")
public class CssContent : IReturn
{
    typealias Return = String

    required public init(){}
    public var name:String?
}





Mvh.
Jens Petter Abrahamsen
petter@netup.no

**Comment by mythz** [comment]
@specimen151 Hi,

I've updated the ServiceStackClient so it compiles with the latest Xcode 6.3/Swift 1.2 update. The new ServiceStackXCode plugin @Layoric linked above should download the updated version for your version of Xcode, but if not you can get the latest from [JsonServiceClient.swift](https://github.com/ServiceStack/ServiceStack.Swift/blob/master/dist/XCode/6.3/JsonServiceClient.swift) which you can copy/paste into your project.

The generated Swift DTO's also requires a minor change so you'll need the latest v4.0.39 version that's [avaialble on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Unfortunately it looks like there is a regression in Swift where the compiler is now segfaulting when dealing with generic type Response DTO's, this affects AutoQuery Services since they return `QueryResponse<T>`. I'm trying to register a bug about this issue with Apple but unfortunately their https://bugreport.apple.com is down - will file an issue as soon as I can get through, but unfortunately they've been historically slow to respond to issues in the past.

Please let me know if the update works or if you encounter any other issues.

**Comment by specimen151** [comment]
I don't understand what you mean by that the generated Swift DTO's requires a change so I have do get a new SS version. There is no SS installed on the iOS client. Do I have to update the server-side with new DLL's?

Also there's trouble with some of my DTO's, but this could be because of not updating SS on the server-side?
E.g. 

    // @Route("/assets/css/{Name}", "GET")
    public class CssContent : IReturn
    {
      typealias Return = String
      required public init(){}
      public var name:String?
    }

has error message: Type CssContent does not conform to protocol IReturn.

For reference:

    public protocol IReturn
    {
      typealias Return : JsonSerializable
    }

I have tried to exclude this class by adding:

    //ExcludeTypes: CssContent

but the Update ServiceStack reference just clears the changes and includes everything.

**Comment by mythz** [comment]
> I don't understand what you mean by that the generated Swift DTO's requires a change so I have do get a new SS version. 

I mean that the server generated DTO's requires a newer version of ServiceStack on the remote Server. 

Can you please provide the full DTO class definition for `CssContent`?

**Comment by specimen151** [comment]
That's what I thought you meant. I'll let you know once I've tried that.

About the DTO, the definition is:

    [Route("/assets/css/{Name}", Verbs="GET")]       
    public class CssContent : IReturn<string>
    {
        public string Name { get; set; }       // filename
    }

and the service, which inherits from `Service` is:

    public string Get(CssContent request)
        {
            if (string.IsNullOrEmpty(request.Name))
                throw new HttpError(400, "Name must be provided.");

            try
            {
                string content = File.ReadAllText(Path.Combine(CssDir, request.Name));
                return content;
            }
            catch (Exception)
            {
                throw new HttpError(404, "Not Found",request.Name);
            }
        }

**Comment by mythz** [comment]
Thanks, unfortunately adding a `JsonSerializable` extension to `String` caused a segfault but I found a workaround where it works when the extension was added to `NSString` and emit the extension inline as done in this commit: https://github.com/ServiceStack/ServiceStack/commit/c29e827aad9ce0adbb34781f9ddea35c6b93bbcd

This change just finished deploying to MyGet, if you had a previous MyGet version installed you'll need to clear the NuGet cache and delete the `/packages` folder to download the latest version, see: https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages

You'll also need to delete and re-add the Swift ServiceStack Reference in Xcode so it picks up the latest `JsonServiceClient.swift`.

**Comment by Layoric** [comment]
@specimen151 regarding the comment below: 
>I have tried to exclude this class by adding:

>//ExcludeTypes: CssContent
>but the Update ServiceStack reference just clears the changes and includes everything.

When you want to change the options you want to use to update the DTOs, you have to remove the leading `//`. These are there to show what is possible to update. Options with leader `//` are suppose to indicate they are commented out and ignored.

If you change `//ExcludeTypes: CssContent` to `ExcludeTypes: CssContent` in the options at the top of the file, it should send the correct request to the server to exclude the type.

**Comment by specimen151** [comment]
Thanks, you are of course correct.

**Comment by mythz** [comment]
We've now shipped [support for Swift 2.0 and Xcode 7](https://github.com/ServiceStack/ServiceStack/blob/master/docs/2015/release-notes.md#swift-20-support) in the latest v4.0.46. You'll need to upgrade both the remote ServiceStack Server to v4.0.46 and install the latest Xcode 7 compatible version of the ServiceStackXCode plugin.
