### ISSUE TITLE
LoadSelectAsync doesn't load queries, but SelectAsync does

### ISSUE THREAD

**Issue by rogeroliveira84** [ServiceStack/Issues#275]
I have tried to use LoadSelectAsync passing a join and where queries as parameters and it didn't work, however when using SelectAsync with the same codes, it works.

It may not be an issue depending on the use expected for this method. However you can see a good explanation of my issue in my post in Stackoverflow website:
http://stackoverflow.com/questions/29640141/servicestack-ormlite-sql-server-optional-filter/29643690#29643690

Thanks

**Comment by Layoric** [comment]
Hi @rogeroliveira84,

When you say "didn't work", can you give us any more details? Was there an exception? did it generate an invalid query? did the properties just not populate? Any info on the results you got would help.

An example of the use of [LoadSelectAsync](https://github.com/ServiceStack/ServiceStack.OrmLite#querying-pocos-with-references) can be found in the [ServiceStack.OrmLite tests](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/8b0839863fbbd307b566d3c7f7342237cce5df05/tests/ServiceStack.OrmLiteV45.Tests/SqlExpressionTests.cs#L12).

If you could provide a failing test or snippet containing all related classes and code that fails, it would give us a better idea of the problem your having.

**Comment by rogeroliveira84** [comment]
Hi Layoric, 

By not working I mean the error below only when I use LoadSelectAsync, when I use SelectAsync it works.



Response Status

    Error Code
        SqlException
    Message
        Ambiguous column name 'ProjectId'.
    Stack Trace
        [AllProjectTasks: 17/04/2015 12:23:18 AM]: [REQUEST: {DepartmentId:0,ProjectTaskStatusId:0,AssignedToId:0}] System.Data.SqlClient.SqlException (0x80131904): Ambiguous column name 'ProjectId'. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData() at System.Data.SqlClient.SqlDataReader.get_MetaData() at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString) at System.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader() at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod) at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult) at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult) at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at ServiceStack.OrmLite.Support.LoadListAsync`2.<SetRefFieldAsync>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter.GetResult() at ServiceStack.OrmLite.OrmLiteReadCommandExtensionsAsync.<LoadListWithReferences>d__26`2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Next.Management.Repository.ProjectTaskRepository.<GetAllProjectTasks>d__2.MoveNext() in c:\dev\Next\Logistics\Management\src\Management.Repository\Repository\ProjectTaskRepository.cs:line 28 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at Next.Management.Service.ProjectTaskService.<Get>d__0.MoveNext() in c:\dev\Next\Logistics\Management\src\Management.WebHost\Service\ProjectTaskService.cs:line 27 ClientConnectionId:f6d24c48-c0b7-4ba6-9e51-7b8c16f6abcb Error Number:209,State:1,Class:16
    Errors

I sent attached the .cs files involved (I had to rename the .rar to .rar.png  to be able to attach here.

![codes rar](https://cloud.githubusercontent.com/assets/10275369/7194115/f599f4d2-e4ec-11e4-902c-6eea37026d96.png)

**Comment by mythz** [comment]
This should now be resolved with the latest [v4.0.39 release of ServiceStack on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by rogeroliveira84** [comment]
Thanks! That's great!
