### ISSUE TITLE
Sqlite bool? incorrect behaviour

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#276]
SS: 4.0.40
Db package: ServiceStack.OrmLite.Sqlite.Windows

Model:

    public class Shutdown
    {
        public bool? IsShutdownGraceful { get; set; }
    }

Ormlite code:

    db.Insert(new Shutdown { IsShutdownGraceful = null });
    db.Select<Shutdown>()

The select will return records that are deserialised with IsShutdownGraceful = true

**Comment by mythz** [comment]
Each table needs a primary key and if one is not provided (e.g. has an `Id` field) it will fallback to using the first column and PK's are treated differently by Sqlite. It works when there is a distinct PK as seen in:

https://github.com/ServiceStack/ServiceStack.OrmLite/commit/dc085c9bc4f5561c1b1b23a8b8b3b2c9c9c20660
