### ISSUE TITLE
Running ServiceStack on FIPS enabled machine

### ISSUE THREAD

**Issue by SteveHallNNT** [ServiceStack/Issues#280]
Hi

I just ran our product on a FIPS enabled Windows 8.1 machine and got a couple of problems in the Auth Repository area when using MongoDB as the persistent auth repository.

ServiceStack.Authentication.MongoDb.MongoDbAuthRepository uses the SaltedHash and DigestAuthFunctions classes which both, by default, use an MD5 based hashing algorithm.

I couldn't see any way to change this other than changing the implementation locally so thought that perhaps this was something you should be aware of.  If I've missed something and this behaviour can be changed via configuration / other methods than I'd be happy to hear it.

Thanks
Steve H

**Comment by mythz** [comment]
Unless I'm missing something only the `DigestHa1Hash` uses MD5 which is only used by the `DigestAuthProvider` for HTTP Digest Auth. 

The salted password (used by CredentialsAuth) uses [SaltedHash](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Auth/SaltedHash.cs) class which uses `SHA256Managed` by default.

**Comment by SteveHallNNT** [comment]
Thanks Demis.  

Unfortunately the SHA256Managed used by default in SaltedHash isn't FIPS approved (from MS  - "SHA256Managed, like all the other crypto classes ending with “Managed”, is implemented strictly in .NET managed code and doesn’t use the underlying platform implementations. .. the Managed implementations have never been submitted to NIST for validation.")

Is there something else I should be doing?

Thanks,
Steve

**Comment by mythz** [comment]
Hi Steve,

I've updated all references for `SaltedHash` to access it from a virtual method in your AppHost which you can override to return a custom `IHashProvider` which the AuthProviders will use instead. By default it just returns the default instance of SaltedHash, e.g:

```csharp
public virtual IHashProvider GetHashProvider()
{
    return new SaltedHash();
}
```
 
This change is available from v4.0.41 which is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by SteveHallNNT** [comment]
Thanks Demis - sounds good.

**Comment by mythz** [comment]
Hi Steve, just wanted to let you know that I've removed the `GetHashProvider()` method in favor of using an alternative `IHashProvider` provider by registering it in the IOC, e.g:

```csharp
container.Register<IHashProvider>(c => new SaltedHash());
```

This change is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by SteveHallNNT** [comment]
Great, thanks for the update Demis, appreciated.

Steve
