### ISSUE TITLE
Index was outside the bounds of the array while deseirializing complex structure

### ISSUE THREAD

**Issue by lokijota** [ServiceStack/Issues#281]
Hello,

I'm having this error with this stacktrace:

Index was outside the bounds of the array., stack trace:    
   at System.String.get_Chars(Int32 index)
   at ServiceStack.Text.Json.JsonTypeSerializer.ParseString(String json, Int32& index)
   at ServiceStack.Text.Json.JsonTypeSerializer.EatValue(String value, Int32& i)
   at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(TypeConfig typeConfig, String strType, EmptyCtorDelegate ctorFn, Dictionary\`2 typeAccessorMap)
   at ServiceStack.Text.Common.DeserializeType\`1.\<>c__DisplayClass3.\<GetParseMethod>b__1(String value)
   at ServiceStack.Text.Common.DeserializeDictionary\`1.ParseDictionary\[TKey,TValue](String value, Type createMapType, ParseStringDelegate parseKeyFn, ParseStringDelegate parseValueFn)
   at ServiceStack.Text.Common.DeserializeDictionary\`1.ParseDictionaryType(String value, Type createMapType, Type\[] argTypes, ParseStringDelegate keyParseFn, ParseStringDelegate valueParseFn)
   at ServiceStack.Text.Common.DeserializeDictionary\`1.\<>c__DisplayClass3.\<GetParseMethod>b__1(String value)
   at ServiceStack.Text.Json.JsonReader\`1.Parse(String value)
   at ServiceStack.Text.JsonSerializer.DeserializeFromString\[T](String value)

While deserializing a .Net structure like this:

Dictionary\<CoreGeneral.Brand, List\<MenuNavigation>>

Where Brand is a POCO object with properties of native types (int, string, int?, bool) and MenuNavigation is a simpler POCO object with properties also of native types (int, string, int?).

The object being deserialized was also serialized with ServiceStack's serializer. The code is something like:

// serialize, objectToSerialize is an object of the Dictionary type I described above
JsonSerializer.SerializeToString(objectToSerialize)

...

// deserialize, T is the Dictionary Type
JsonSerializer.DeserializeFromString\<T>(serializedObject);

Any Ideas?
The Json is:

{{"Id":4,"Code":"ALL","Title":"something Group","MenuTitle":"something Group","Url":"http://localhost:60000/en","LogoUrl":"/assets/img/blank.png","SortOrder":1,"IsAggregator":true,"ButtonId":"something_group","Checked":false}:\[{"Id":15,"Title":"Hotel Directory","SortOrder":10,"Url":"http://localhost:60000/en/directory"},{"Id":19,"Title":"Experiences","SortOrder":10,"Url":"http://localhost:60000/en/experience"},{"Id":20,"Title":"Promotions","SortOrder":10,"Url":"http://localhost:60000/en/promotion"},{"Id":25,"Title":"Meetings & Events","SortOrder":10,"Url":"http://localhost:60000/en/meetings"},{"Id":26,"Title":"Restaurants","SortOrder":10,"Url":"http://localhost:60000/en/restaurants"},{"Id":27,"Title":"Weddings","SortOrder":10,"Url":"http://localhost:60000/en/weddings"},{"Id":28,"Title":"Institutional","SortOrder":1,"Url":"http://localhost:60000/en/contents/institutional"}],{"Id":1,"Code":"something","Title":"something Hotels and Resorts","MenuTitle":"Hotels and Resorts","Url":"http://localhost:60001/en","LogoUrl":"/assets/img/blank.png","SortOrder":2,"IsAggregator":false,"ButtonId":"hotels_resorts","Checked":false}:\[{"Id":15,"Title":"Hotel Directory","SortOrder":10,"Url":"http://localhost:60000/en/directory?theme=something"},{"Id":19,"Title":"Experiences","SortOrder":10,"Url":"http://localhost:60000/en/experience?theme=something"},{"Id":20,"Title":"Promotions","SortOrder":10,"Url":"http://localhost:60000/en/promotion?theme=something"},{"Id":25,"Title":"Meetings & Events","SortOrder":10,"Url":"http://localhost:60000/en/meetings?theme=something"},{"Id":26,"Title":"Restaurants","SortOrder":10,"Url":"http://localhost:60000/en/restaurants?theme=something"},{"Id":27,"Title":"Weddings","SortOrder":10,"Url":"http://localhost:60000/en/weddings?theme=something"}],{"Id":2,"Code":"POUSADAS","Title":"Pousadas de Portugal","MenuTitle":"Pousadas","Url":"http://localhost:60001/en","LogoUrl":"/assets/img/blank.png","SortOrder":3,"IsAggregator":false,"ButtonId":"pousadas_de_portugal","Checked":false}:\[{"Id":15,"Title":"Hotel Directory","SortOrder":10,"Url":"http://localhost:60000/en/directory?theme=pousadas"},{"Id":19,"Title":"Experiences","SortOrder":10,"Url":"http://localhost:60000/en/experience?theme=pousadas"},{"Id":20,"Title":"Promotions","SortOrder":10,"Url":"http://localhost:60000/en/promotion?theme=pousadas"},{"Id":25,"Title":"Meetings & Events","SortOrder":10,"Url":"http://localhost:60000/en/meetings?theme=pousadas"},{"Id":26,"Title":"Restaurants","SortOrder":10,"Url":"http://localhost:60000/en/restaurants?theme=pousadas"},{"Id":27,"Title":"Weddings","SortOrder":10,"Url":"http://localhost:60000/en/weddings?theme=pousadas"}],{"Id":3,"Code":"COLLECTION","Title":"something Collection","MenuTitle":"something Collection","Url":"http://localhost:60001/en","LogoUrl":"/assets/img/blank.png","SortOrder":4,"IsAggregator":false,"ButtonId":"luxury","Checked":false}:\[{"Id":15,"Title":"Hotel Directory","SortOrder":10,"Url":"http://localhost:60000/en/directory?theme=collection"},{"Id":19,"Title":"Experiences","SortOrder":10,"Url":"http://localhost:60000/en/experience?theme=collection"},{"Id":20,"Title":"Promotions","SortOrder":10,"Url":"http://localhost:60000/en/promotion?theme=collection"},{"Id":25,"Title":"Meetings & Events","SortOrder":10,"Url":"http://localhost:60000/en/meetings?theme=collection"},{"Id":26,"Title":"Restaurants","SortOrder":10,"Url":"http://localhost:60000/en/restaurants?theme=collection"},{"Id":27,"Title":"Weddings","SortOrder":10,"Url":"http://localhost:60000/en/weddings?theme=collection"}]}

**Comment by Layoric** [comment]
The `CoreGeneral.Brand` type you are using for the key of the dictionary is what is causing these problems. The JSON being produce via serialization isn't valid because the key needs to be able to be serialized into a string to work as a JSON key:object pair. 

Have a look at the [ServiceStack.Text tests](https://github.com/ServiceStack/ServiceStack.Text/blob/master/tests/ServiceStack.Text.Tests/DictionaryTests.cs) to show the different uses of dictionaries for serialization/deserialization.

One suggestion would be to use an ID as the dictionary key value that can be looked up at another point in time. Or if you are building a menu on a web client, come up with a structure in JSON that represents your menu and create response POCO that matches the structure, populating data from CoreGeneral.Brand and MenuNavigation in the service and send it back.

@mythz are int and string the only valid data types for keys in dictionary serialization?
