### ISSUE TITLE
Conflicting issues with body parameters and swagger

### ISSUE THREAD

**Issue by bcffx** [ServiceStack/Issues#282]
Hi,

I have run into several related issues when creating an ASP.NET json REST web service and would appreciate some guidance and/or bug fixes that would let me proceed. Sorry if these should be reported as several issues, but the problem is that individually they could be worked around, but together the workarounds seem to conflict.

The requirements i am trying to achieve are:

A) Have a swagger interface that accurately matches the service contracts (no duplicate properties, displayed model is correct)
B) Have a DELETE operation with only path/query params
C) Have a GET operation that returns a json model that can be fed directly into the below POST body
D) Have a POST operation that accepts both a custom body dto (with multiple params) and a query param

I have put together a minimal repo below. Using latest v4.0.40.0 nuget packages.

**Issue#1)** When DisableAutoDtoInBodyParam is false (default), SS is still generating a body param for DeleteRequestDto, even though all params have ApiMember.ParameterType="path". If values are supplied to this body param they are not used.

Possible fix: when doing AutoDtoInBodyParam, exclude members that have an explicit ApiMember.ParameterType != "body"? If no members, do not add body param.
Workaround: set DisableAutoDtoInBodyParam to true (conflicts with Issue#3)

![](http://i.imgur.com/IZ4dPz6.png)

**Issue#2)** In PostRequestDto1, when the MyBody property ApiMember.DataType is set to the property type "MyBodyDto", the swagger model displays

```javascript
{
  "IntParam1": "int",
  "IntParam2": "int"
}
```

but the IntParamX values are not received. Instead it actually expects the model
```javascript
{
  "MyBody": {
    "IntParam1": "int",
    "IntParam2": "int"
  }
}
```
Possible fix: update the operation behaviour to allow body DataType to be set to property type, so that it matches the swagger model?
Workaround: set ApiMember.DataType to the dto class name (conflicts with Issue#3)

![](http://i.imgur.com/rIeuvX3.png)

**Issue#3)** In PostRequestDto2, when the MyBody property ApiMember.DataType is set to the class name "PostRequestDto2", the swagger model includes other non-body properties, eg:

```javascript
{
  "MyBody": {
    "IntParam1": "int",
    "IntParam2": "int"
  },
  "MyFlag": false  // <---
}
```

Both the body and query params work (query takes precedence), but i would expect to only see MyBody and not MyFlag in the body model. Ideally i want the body model to just be: (requirement C)

```javascript
{
  "IntParam1": "int",
  "IntParam2": "int"
}
```

Possible fix: exclude non ApiMember.ParameterType="body" properties?
Workaround: move body params from MyBodyDto to PostRequestDto3 and go back to using AutoDtoInBodyParam (conflicts with Issue#1)

![](http://i.imgur.com/CZFda6k.png)

**Issue#4)** When using the PostRequestDto3 option and AutoDtoInBodyParam is not disabled, the swagger model for the auto body param includes properties that have ApiMember.ParameterType="query":

```javascript
{
  "IntParam1": "int",
  "IntParam2": "int",
  "MyFlag": false  // <---
}
```

Again, both the body and query params work (query takes precedence), but MyFlag is duplicated.

Possible fix: same as Issue#1?
Workaround: ...?

![](http://i.imgur.com/JXynOie.png)

Of the three PostRequestDto's, only the first is displayed as i would like in swagger (but doesn't work).

Repo:

```csharp
using System;
using Funq;
using ServiceStack;
using ServiceStack.Api.Swagger;

namespace TestServiceStack
{
  public class AppHost : AppHostBase
  {
    public AppHost()
      : base( "TestServiceStack", typeof( TestService ).Assembly )
    {

    }

    public override void Configure( Container container )
    {
      var swaggerFeature = new SwaggerFeature();
      //swaggerFeature.DisableAutoDtoInBodyParam = true;
      this.Plugins.Add(swaggerFeature);
    }
  }


  public class TestService : Service
  {
    public object Delete( DeleteRequestDto request )
    {
      return String.Format( "\"DeleteRequestDto {0} {1}\"", request.IntParam1, request.IntParam2 );
    }

    public object Post( PostRequestDto1 request )
    {
      if( request.MyBody == null )
        return "\"request.MyBody == null\"";
      return String.Format( "\"PostRequestDto1 {0} {1} (MyFlag {2})\"", request.MyBody.IntParam1, request.MyBody.IntParam2, request.MyFlag );
    }

    public object Post( PostRequestDto2 request )
    {
      if( request.MyBody == null )
        return "\"request.MyBody == null\"";
      return String.Format( "\"PostRequestDto2 {0} {1} (MyFlag {2})\"", request.MyBody.IntParam1, request.MyBody.IntParam2, request.MyFlag );
    }

    public object Post( PostRequestDto3 request )
    {
      return String.Format( "\"PostRequestDto3 {0} {1} (MyFlag {2})\"", request.IntParam1, request.IntParam2, request.MyFlag );
    }

    public object Get( GetRequestDto request )
    {
      return new MyBodyDto { IntParam1 = request.IntParam1, IntParam2 = request.IntParam2 };
    }
  }


  [Route( "/test/delete/{IntParam1}/{IntParam2}", "DELETE" )]
  public class DeleteRequestDto : IReturn<string>
  {
    [ApiMember( DataType = SwaggerType.Int, Description = "IntParam1", IsRequired = true, ParameterType = "path" )]
    public int IntParam1 { get; set; }

    [ApiMember( DataType = SwaggerType.Int, Description = "IntParam2", IsRequired = true, ParameterType = "path" )]
    public int IntParam2 { get; set; }
  }

  public class MyBodyDto
  {
    public int IntParam1 { get; set; }
    public int IntParam2 { get; set; }
  }

  [Route( "/test/post1", "POST" )]
  public class PostRequestDto1 : IReturn<string>
  {
    [ApiMember( DataType = "MyBodyDto", Description = "MyBody", IsRequired = true, ParameterType = "body" )]
    public MyBodyDto MyBody { get; set; }

    [ApiMember( DataType = SwaggerType.Boolean, Description = "MyFlag", IsRequired = false, ParameterType = "query" )]
    public bool MyFlag { get; set; }
  }

  [Route( "/test/post2", "POST" )]
  public class PostRequestDto2 : IReturn<string>
  {
    [ApiMember( DataType = "PostRequestDto2", Description = "MyBody", IsRequired = true, ParameterType = "body" )]
    public MyBodyDto MyBody { get; set; }

    [ApiMember( DataType = SwaggerType.Boolean, Description = "MyFlag", IsRequired = false, ParameterType = "query" )]
    public bool MyFlag { get; set; }
  }

  [Route( "/test/post3", "POST" )]
  public class PostRequestDto3 : IReturn<string>  // requires DisableAutoDtoInBodyParam = false
  {
    // AutoDtoInBodyParam, no [ApiMember]
    public int IntParam1 { get; set; }

    // AutoDtoInBodyParam, no [ApiMember]
    public int IntParam2 { get; set; }

    [ApiMember( DataType = SwaggerType.Boolean, Description = "MyFlag", IsRequired = false, ParameterType = "query" )]
    public bool MyFlag { get; set; }
  }

  [Route( "/test/get/{IntParam1}/{IntParam2}", "GET" )]
  public class GetRequestDto : IReturn<MyBodyDto>
  {
    [ApiMember( DataType = SwaggerType.Int, Description = "IntParam1", IsRequired = true, ParameterType = "path" )]
    public int IntParam1 { get; set; }

    [ApiMember( DataType = SwaggerType.Int, Description = "IntParam2", IsRequired = true, ParameterType = "path" )]
    public int IntParam2 { get; set; }
  }
}
```

**Comment by mythz** [comment]
The first issue where **body** params are showed in **DELETE** API's should fixed with this commit: https://github.com/ServiceStack/ServiceStack/commit/a1f08d41b28fde8a27ffbe3a47e1b4d91ae161a2

This change just finished [deploying to MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

The other issues are impacted by customizing the Swagger model with `[ApiMember]` annotations which get passed through to the Swagger API's.

So I want to go back to focus on the default behavior without any attributes which works as expected, i.e:

```csharp
[Route("/test/postdefault", "POST")]
public class PostDefault : IReturn<string>
{
    public MyBodyDto MyBody { get; set; }

    public bool MyFlag { get; set; }
}
```

Has the expected ModelSchema of:

```json
{
  "MyBody": {
    "IntParam1": "int",
    "IntParam2": "int"
  },
  "MyFlag": false
}
```

Now if you want to exclude MyFlag property, you can use `[DataContract]` and `[DataMember]` attributes to mark which are the serializable properties, e.g:

```csharp
[Route("/test/postdefault", "POST")]
[DataContract]
public class PostDefault : IReturn<string>
{
    [DataMember]
    public MyBodyDto MyBody { get; set; }

    public bool MyFlag { get; set; }
}
```

Which generates a ModelSchema of:

```json
{
  "MyBody": {
    "IntParam1": "int",
    "IntParam2": "int"
  }
}
```

Then you can make `MyFlag` a **query** param with:

```csharp
[Route("/test/postdefault", "POST")]
[DataContract]
public class PostDefault : IReturn<string>
{
    [DataMember]
    public MyBodyDto MyBody { get; set; }

    [ApiMember(ParameterType = "query")]
    public bool MyFlag { get; set; }
}
```

Which will show up as a **query** param in Swagger UI.

**Comment by bcffx** [comment]
Hi mythz,

Thanks for the quick response.

Regarding issue#1, yes just blacklisting the `DELETE` verb will solve my particular issue, but i suspect it may return (eg [here](http://stackoverflow.com/questions/17873071/swagger-ui-displaying-extra-parameter-using-servicestack)). A better solution may be to consider excluding if all properties have explicit `ApiMember` attributes set to non-"body". Anyway, i'm happy for now so i'll leave that up to you.

Regarding the body issue, your `PostDefault` suggestion doesn't seem to work (the query `MyFlag` value is not received). Also, i am trying to get the post body model to be just the `MyBodyDto` object

```javascript
{
  "IntParam1": "int",
  "IntParam2": "int"
}
```

In reality this model it has 15+ properties and is used in several places (eg, the GET response), so i'd rather not have to define them all multiple times (as in `PostRequestDto3`). Having an additional single top-level json element may be an okay workaround, but i'd need to convince a third party to change their spec.

Is it possible to make `PostRequestDto1` work as expected? It already displays correctly in swagger, and seems to be the most intuitive way to describe the request dto:

```csharp
  public class PostRequestDto1
  {
    [ApiMember( ParameterType = "body" )]  // only allowed one of these
    public MyBodyDto MyBody { get; set; }

    [ApiMember( ParameterType = "query" )]
    public bool MyFlag { get; set; }
  }
```

It seems this used to work in [older versions of SS](http://stackoverflow.com/questions/15533787/swagger-with-servicestack-does-not-send-elements-to-server-on-post/16228093#16228093), but this functionality has since been lost?

**Comment by mythz** [comment]
I've added a new `[ApiMember(ExcludeInSchema=true)]` attribute that will allow you to exclude properties from being emitted in Swagger's ModelSchema in this commit: https://github.com/ServiceStack/ServiceStack/commit/f8a9caa4b55a977908510f17296256e4e13daed9

So you should now be able to get the desired behavior with:

```csharp
[Route("/test/postdefault", "POST")]
public class PostDefault : IReturn<string>
{
    public MyBodyDto MyBody { get; set; }

    [ApiMember(ParameterType = "query", ExcludeInSchema = true)]
    public bool MyFlag { get; set; }
}
```

This change is currently deploying to MyGet (should be available in ~15 mins). Since you have an existing v4.0.41 from MyGet installed you'll nee to [clear your NuGet package cache and /packages folder](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) to download the latest version.

Note: The `[ApiMember]` attributes don't have any effect on the behavior in ServiceStack, they're just metadata used to describe the Service. ServiceStack assumes the entire Request DTO is POST'ed so the `body` needs to match the shape of the Request DTO (i.e. could be a subset) but they can't be used to change ServiceStack's deserialization behavior - which allows the Request DTO properties to be populated a variety of different ways, e.g. path, query, form, body, (HTTP/JSON/XML/JSV/etc, MQ, SOAP), etc.

**Comment by bcffx** [comment]
Okay, this works fine, thank you.
