### ISSUE TITLE
Potential illegal fragment detected

### ISSUE THREAD

**Issue by vicjohnson1213** [ServiceStack/Issues#283]
Ormlite uses IndexOf to compare an SQL fragment against the array of potentially illegal fragments which causes exceptions on valid SQL.

For example:
```c#
Db.Select<TEntity>(q => q.OrderBy("DateCreated DESC"));
```

Is illegal because the column `DateCreated` contains the illegal fragment `create`, even though it is a perfectly legal column.

[Ormlite Source](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite/OrmLiteUtils.cs#L207)

If this is the intended functionality, could somebody point me in a direction to avoid this issue?  Otherwise, I am more than willing to contribute to a solution to this issue.

**Comment by mythz** [comment]
Yes this is intended when using free text in a SqlExpression. You can modify the list of illegal tokens by modifying the `OrmLiteUtils.IllegalSqlFragmentTokens` array.

Alternatively consider using the typed API, e.g:

    Db.Select<TEntity>(q => q.OrderByDescending(x => x.DateCreated));
