### ISSUE TITLE
Request filters don't always run in consistent or expected order

### ISSUE THREAD

**Issue by rudism** [ServiceStack/Issues#284]
The order in which request filter attributes and global request filters run seems to change depending on whether you define the attribute on your service class or on the methods within that class. I have created a simple test case to illustrate what I'm talking about:

https://gist.github.com/rudism/c11c2ed21452ddddb6d0

In the gist, I'm defining two services that both use the same `TestFilterAttribute` with a priority of -100. Based on the documentation for filter attributes, the expected behavior when setting priority less than zero is that it should always run before the global request filters. The difference between the two services in the gist is that one service defines the filter attribute at the service class level, and the other defines it at the service method level. Running the program results in the following output:

    ServiceStack SelfHost listening on port 9090
    
    Filter execution order with class attribute:
    AttributeFilter
    GlobalFilter
    
    Filter execution order with method attribute:
    GlobalFilter
    AttributeFilter

When the filter attribute is defined on the class, it executes before the global filter as expected. When it's defined on the method, it runs after the global filter. I would expect at the very least that these should be consistent (i.e., I had expected that applying a filter attribute at the service class level would be equivalent to applying that filter to all of the service methods within the class).

**Comment by mythz** [comment]
This is intended behavior, the proximity of the Filter attributes dictates the order, whilst the priority orders the filter within the same proximity.

**Comment by rudism** [comment]
It might be worth updating the documentation here to reflect that:
https://github.com/ServiceStack/ServiceStack/wiki/Filter-attributes

The comments on the interface code says that setting priority <0 will cause it to be run before global filters, but if I understand you correctly that is intentionally only true when the filter is applied at certain scopes and not others.

**Comment by mythz** [comment]
Right, this applies to service-level attribute filters, I'll make a note of method-level attribute filters.
