### ISSUE TITLE
OrmLite Select positioning

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#286]
SS 4.0.40

In the below example, the Select has to be after the LeftJoin and before the Where, which is a very specific and unclear requirement.

If the Select is after the From, then the table name is not prepended to the column name.
If the Select is after the And, then all columns in the Invoice table are selected (loosing any index optimisation opportunity).

Is there any scope for you allowing the Select to appear 
* anywhere after the From 

OR failing that,
* at the end of the statement (I think it would be a common assumption that this position for the Select should not select all columns)

**Code**

                conn
                    .From<Invoice>()
                    .LeftJoin<Invoice, UsagePageInvoice>((i, upi) => i.Id == upi.InvoiceId)
                    .Select(c => new {c.Id, c.WorkflowId, c.DocumentId, c.DocumentStatus, c.PageCount})
                    .Where<Invoice>(i => (i.DocumentStatus == "a" || i.DocumentStatus == "b"))
                    .And<UsagePageInvoice>(upi => upi.Id == null);

**Comment by mythz** [comment]
`Select()` should be at the end of the SqlExpression like it is for LINQ. 

I've added a fix so the Custom Select() should be used instead when specified in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/54b5dca49600a44b8ad238fbeae6fb20a0e5f3fc

This change is available from v4.0.41 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
