### ISSUE TITLE
ServiceClient cannot deserialize null result causing GetAsync to await indefinitly

### ISSUE THREAD

**Issue by kaspur** [ServiceStack/Issues#289]
Hi,

In our scenario we're having a frontendservice making calls to a backendservice. When a backendservicecall returns null, the await GetAsync method never completes and should properly have set a result. This is causing a never ending proces in IIS (and ultimately choking up iis not accepting any new incoming calls). 

I've made a small service calling itself to demonstrate. 

	[Route("/Hello/", Verbs = "GET", Summary = "Test")]
	public class HelloReq : IReturn<object>
	{
		public bool ReturnNull { get; set; }
	}

	public class MyServices : Service
	{

		public static ServiceClientBase ApiClient { get; set; }

		public MyServices()
		{
			ApiClient = ApiClient ?? new JsonServiceClient(HttpContext.Current.Request.Url.ToString().Replace("/Hello", ""));
		}

		public async Task<object> Any(HelloReq request)
		{
			if (!request.ReturnNull)
				request.ReturnNull = true;
			else return null;
			//else return Task.FromResult<object>(null);
			
			var a = await ApiClient.GetAsync(request);
			// never gets here!!
			return a;
		}

	}

**Comment by mythz** [comment]
You should never return `null` in a Task method. To return an empty task you can return:

.NET 4.6:

    return Task.CompletedTask;

.NET 4.5:

    return Task.FromResult(0); //or 
    return Task.FromResult<object>(null);

.NET 4.0 can use ServiceStack's `AsTaskResult()` helper extension method, e.g:

    return ((object)null).AsTaskResult();
