### ISSUE TITLE
swagger-client.js ignores ApiMember.IsRequired

### ISSUE THREAD

**Issue by andreimatusevich** [ServiceStack/Issues#290]
swagger-client.js throws a required path param exception despite parameter can be marked as        
ApiMember.IsRequired = false

    for (i = 0; i < params.length; i++) {
        param = params[i];
        if (param.paramType === 'path') {
          if (typeof args[param.name] !== 'undefined') {
            // apply path params and remove from args
            var reg = new RegExp('\\{\\s*?' + param.name + '[^\\{\\}\\/]*(?:\\{.*?\\}[^\\{\\}\\/]*)*\\}(?=(\\/?|$))', 'gi');
            url = url.replace(reg, this.encodePathParam(args[param.name]));
            delete args[param.name];
          }
          else
            throw '' + param.name + ' is a required path param.';
        }

**Comment by mythz** [comment]
Any issues with Swagger UI or Client needs to be raised with the upstream [Swagger project](https://github.com/swagger-api/swagger-ui) where these files are imported from.

But `path` params would be expected to be required since they're required to construct the url.
