### ISSUE TITLE
ReadAsync in AsyncUtils causes unobserved task exception

### ISSUE THREAD

**Issue by dabide** [ServiceStack/Issues#293]
We sometimes get an UnobservedTaskException event from this method:
```
        public static Task<int> ReadAsync(this Stream stream, byte[] buffer, int offset, int count, CancellationToken token)
        {
            return token.IsCancellationRequested
                ? TaskConstants<int>.Canceled
                : Task<int>.Factory.FromAsync(stream.BeginRead, stream.EndRead, buffer, offset, count, null);
        }
```

The stream is apparently disposed when stream.EndRead() is executed. We are using a JsonClient, which is reused from request to request, and we're using GetAsync() and PostAsync(). This is the exception we get:

```
System.AggregateException A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. 
System.ObjectDisposedException Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.    at System.Net.ConnectStream.EndRead(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

**Comment by mythz** [comment]
Why do you think it's thrown from that method? Do you have a repro?

**Comment by dabide** [comment]
We don't use `Task<T>.Factory.FromAsync(...)` ourselves, and the stack trace does look very much like your code, where you call EndRead() on a stream from the FromAsync() method.

I have looked at the usages in ServiceStack, and there doesn't seem to be any handling of exceptions thrown by this Task. It ends up in `ReadCallBack<T>(Task<int> task, AsyncState<T> requestState)` in `AsyncServiceClient`, where there's a ContinueWith() without checking for exceptions.

We don't know how to reproduce it yet. Would a loss of connection with the server lead to the NetworkStream being disposed?

**Comment by mythz** [comment]
Going to need a repro so I can verify where the Exception is thrown and its proper handling. I believe `ObjectDisposedException` gets thrown on HttpWebRequest.Abort() but it doesn't appear `Stream.EndRead` throws an `ObjectDisposedException`:
https://msdn.microsoft.com/en-us/library/system.io.stream.endread(v=vs.110).aspx

**Comment by dabide** [comment]
`NetworkStream`'s `EndRead()` does indeed throw an `ObjectDisposedException`if the `NetworkStream` is closed: https://msdn.microsoft.com/en-us/library/47y06f66(v=vs.110).aspx

**Comment by mythz** [comment]
Could not repro this, tried making an async request error whilst physically disconnecting the network which threw:

```
System.Net.WebException : The request timed out
  ----> System.Net.WebException : The request was aborted: The request was canceled.
```

When making an async call without a Network connection it ends up throwing:

```
System.Net.WebException : The remote name could not be resolved: 'test.servicestack.net'
```

Going to need a stand-alone repro to investigate any further.
