### ISSUE TITLE
RedisClient.StoreAll() in large batches causes incorrect set items returned when querying by ID while the batch is saving

### ISSUE THREAD

**Issue by jpasichnyk** [ServiceStack/Issues#294]
I'll try to put together an isolated repro on this, but here is my use case:

1. Find a large number of items that need to be persisted into redis
2. store them into redis in batches (in my case 5000 at a time) using .StoreAll()
3. RedisClient stores the values into redis
4. RedisClient does a bunch of SADD calls to a SET to maintain list of keys present

Somewhere in the 3-4 time frame, if I query for items by ID, incorrect values are often returned.  If I retry a few times, so that the retries continue until after that batch of updates has completed, the proper item is returned. 

This issue is currently on redis 2.8.19 and servicestack.redis 4.0.40, though i don't see anything in the redis changelog to indicate that there is a server-side issue that has been identified.  

Like I said, I'll dig further, but wanted to share to get the conversation started.

**Comment by mythz** [comment]
Isn't this just due to the Index Id's not finished saving?

**Comment by jpasichnyk** [comment]
Not sure. Is that that the expected behavior, that it will return the wrong item while its saving?  I should have been more clear - in my case, these items may already exist, and are being re-saved due to updates or what not.  I was under the assumption that if I update some items, that it would cause incorrect items to be returned while its processing...

**Comment by mythz** [comment]
The Index is a separate operation added after the items are added, so if you're making calls relying on it (i.e. by Id) then they wont exist in the index.

**Comment by jpasichnyk** [comment]
Ok, so even if items already exist, and I'm simply updating their values, they won't exist at their expected locations until the index is updated?   If so, i think this should be documented somewhere, because I assumed this usage would still return the old version of the item, until its value was updated, and then you'd get the new value.

**Comment by mythz** [comment]
Please provide a repro, updating an existing item should already have their id in the index.

**Comment by jpasichnyk** [comment]
Ok, will do.  Probably won't happen until sometime next week.  I have a mitigation right now, with some retries on the read of the value (i have the id in the value itself as well, so i can verify I'm getting the correct item back, and retry fetching it otherwise).

**Comment by mythz** [comment]
re-open when you find time to provide a repro.
