### ISSUE TITLE
Redis Messaging - Writing to Read-only node 

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#295]
Hello,

I have created a small application to reproduce this behavior, please see https://github.com/stephenpatten/RedisHA for details.

You may have to modify the conf files to use directories specific to your machine, but you should just run the startAll.cmd to get 3 instances of Redis running along with 3 instances of Sentinel. 

The run the WindowService in debug mode through visual studio. 

HTH

**Comment by mythz** [comment]
Hi Stephen,

Thanks for the projects and scripts. Can you try [clearing the NuGet package cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) and trying again with the latest v4.0.41 MyGet packages.

**Comment by stephenpatten** [comment]
Hi Demis,

The messaging framework is behaving much better in the demo app. I'm going to take our LOB application and upgrade, then provide feedback. I'm truly grateful for you working on your vacation.

Regards,
Stephen

**Comment by mythz** [comment]
ok cool, the read-only slave issue should be resolved, if you find further issues please open a new issue, thx.
