### ISSUE TITLE
Directory deserialization lower-cases Guids.

### ISSUE THREAD

**Issue by joero74** [ServiceStack/Issues#296]
Guids are forced to lower-case when they are deserialized as value in a Dictionary<string, object>. This seems to come from DeserializeType<TSerializer>.ParseQuotedPrimitive(string value).

For us this is a problem, because we use the string representation of GUIDs as case sensitive keys. 

The Guid parsing behavior should be configurable.

**Comment by mythz** [comment]
Please provide a full repro or failing test showing the issue.

**Comment by joero74** [comment]
https://github.com/joero74/ServiceStack.Text/commit/57d653aef09faf0a3204c927f1218386a948112d

**Comment by mythz** [comment]
This is parsed into a typed `Guid`, if you want it left as a string use:

    var deserialized = JsonSerializer.DeserializeFromString<Dictionary<string, string>>(json);

Otherwise just upper case the Guid: 

    deserialized["GuidString"].ToString().ToUpper()

**Comment by joero74** [comment]
No, that doesn't help.

1. We need to use Dictionary<string, object> as we don't have only string values (see the test)
2. Upper casing doesn't help either, as there might be upper and lower case UIDs. We have to preserve the case.

**Comment by joero74** [comment]
Isn't it possible to simply create an option for that? I don't want to fork ServiceStack.Text for this issue.

**Comment by joero74** [comment]
I created a pull request with a possible solution: https://github.com/ServiceStack/ServiceStack.Text/pull/457

**Comment by mythz** [comment]
That's too fine-grained and would pollute the Config API making in unnecessarily verbose esp. for this obscure option that no one else is likely to use. 

I've gone with a more flexible `JsConfig.ParsePrimitiveFn` that can be used instead to return a value to use instead, check the test to see how to skip guids: https://github.com/ServiceStack/ServiceStack.Text/commit/7d51fa1c85f52e02008af02c454cd041a324118b

**Comment by joero74** [comment]
OK, sounds good.

Thanks!
