### ISSUE TITLE
Index out of bounds exception with ServerSentEvents and C# Client when using a 'custom' selector

### ISSUE THREAD

**Issue by RobSchoenaker** [ServiceStack/Issues#297]
The selector parsing code in ServerEventsClient.cs expects a '.' in the name of teh selector. If there is no '.', you will get forementioned exception.

An easy fix for this:

 ```javascript
void ProcessEventMessage(ServerEventMessage e)
    {
      var parts = e.Data.SplitOnFirst(' ');
      e.Selector = parts[0];
      var selParts = e.Selector.SplitOnFirst('@');
      if (selParts.Length > 1)
      {
        e.Channel = selParts[0];
        e.Selector = selParts[1];
      }

      e.Json = parts[1];

      if (!string.IsNullOrEmpty(e.Selector))
      {
        parts = e.Selector.SplitOnFirst('.');
        e.Op = parts[0];
        var target = parts[1].Replace("%20", " "); // Exception
```

This last line should be this or something alike:

 ```javascript
        var target = parts.Length > 1 ? parts[1].Replace("%20", " ") : string.Empty;
```

**Comment by mythz** [comment]
Every selector needs a `.` what selector are you trying to send?

**Comment by RobSchoenaker** [comment]
Hello Demis,

Any arbitrary selector *without* a .

I understand now it requires a ., but this is not in the docs and (as a 
result) I tried to use one I made up, like 'my_selector'. Either raise 
an exception saying "Selector should include a '.'", or do not raise an
exception at all.


/Rob

Demis Bellot schreef op 10-6-2015 om 6:40:

**Comment by mythz** [comment]
The [docs already show the different selectors allowed](https://github.com/ServiceStack/ServiceStack/wiki/C%23-Server-Events-Client) which all contain a `.`. 

The selector is invalid so allowing it would result in undefined behavior, it's only raising an Exception now because it's an un expected argument.

**Comment by mythz** [comment]
Changed to throw an explicit exception in this commit: https://github.com/ServiceStack/ServiceStack/commit/001e77bf4dac18f9ec92b3a7bf6d643b05c5c5a8

**Comment by RobSchoenaker** [comment]
Demis,

Perfect. The docs state some selectors used, but they do not mention the 
requirement (!) of an X.Y format. This was unclear to me and since I got 
an IndexOutOfBouds, this looked 'odd'.
Please update the documentation to state that anyselector should be in 
X.Y format or it will fail.

Thx for the commit. This looks perfect.

/Rob


Demis Bellot schreef op 10-6-2015 om 8:03:
