### ISSUE TITLE
[StringLength(Int32.MaxValue)] on model property with UseUnicode in OrmLite SqlServerDialect should use nvarchar(max) instead of varchar(max)

### ISSUE THREAD

**Issue by ansashkan** [ServiceStack/Issues#299]

**Comment by mythz** [comment]
This should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/50dc4186b6855a89fd10faa2805d69085a6e6960) that's available from v4.0.41+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
