### ISSUE TITLE
Select and Insert problems occur with field names containing '°' symbol (degree)

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#300]
I am using a legacy SQL Server Database.
This database contains some tables where fields have names like _'n° ticket'_.
The degree symbol is authorized in field names (at least on SQL Server) but it is not as a parameter name (used on INSERT command generation for instance).

I investigated a bit and updating _OrmLiteDialectProviderBase.SanitizeFieldNameForParamName_ does the trick for INSERT commands.

However, I still had problems on methods like _SingleById_ (in this case my _'n° ticket'_ field is the identifier).
Thank you for your support.

**Comment by mythz** [comment]
Please provide a failing test or repro.

**Comment by labilbe** [comment]
namespace ServiceStack.OrmLite.SqlServerTests.UseCase
{
    public class TestEntityWithAliases
    {
        #region Properties

        [AutoIncrement]
        [Alias("Id Column")]
        public int Id { get; set; }

        [Alias("Foo Column")]
        public String Foo { get; set; }

        [Alias("Bar Column °")]
        public String Bar { get; set; }

        //[Index]
        [Alias("Baz Column")]
        public Decimal Baz { get; set; }
        
        #endregion
    }
}

**Comment by mythz** [comment]
Should be able to resolve this with this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/6fa58fa0d67b9b1cc94933bfe4b741174245dcfe

Where you can strip illegal param name chars by setting `OrmLiteConfig.SanitizeFieldNameForParamNameFn`, e.g:

```csharp
OrmLiteConfig.SanitizeFieldNameForParamNameFn = s =>
    (s ?? "").Replace(" ", "").Replace("°", "");
```

Please provide failing tests if you identify other issues.

**Comment by labilbe** [comment]
Thank you very much Mythz!
