### ISSUE TITLE
Empty (but not null) DTO array property being deserialized as null if GET request (bug), but as empty array if POST request (correct).

### ISSUE THREAD

**Issue by mayerwin** [ServiceStack/Issues#301]
Reproducible failing test (with ServiceStack 4.0.40) available here:
https://gist.github.com/mayerwin/581b230611ce874be6e7

**Comment by mythz** [comment]
Thanks, should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack/commit/4dde1ce673d46e2871c6fd6b1820c7f2d61a4c36 available from v4.0.41+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
