### ISSUE TITLE
ServiceStack Error 502 on Azure

### ISSUE THREAD

**Issue by Formator** [ServiceStack/Issues#302]
Hi guys,

I'm having an issue with combination of Azure Web Site, ServiceStack, Google+ Auth and Integrated mode. This issue is also reported in #124 

In our situation we need to be running in integrated mode as there are advantages and plus we want to run SignalR! 

I have also built a simple app https://github.com/Formator/ServiceStackGoogleAuthAzure to reproduce this error.

Any help is greater appreciated.

**Comment by Layoric** [comment]
Hi @Formator,

I've dug into this problem quite a lot (must admit the remote debugger for Azure is pretty compelling) and it seems that Azure Websites doesn't like the `HttpResult` returning from `OAuth2Provider` method.

Specifically, it doesn't like the 'Content-Length' header being set when returning a `HttpResult`. I'm not sure exactly why this is the case as It works locally and when deployed to my own IIS host on AWS.

I've [created a repository](https://github.com/Layoric/AzureWebsiteTesting) you can deploy yourself that highlights this issue.

Azure Websites seem to be interpreting this response differently than on a standard IIS setup (eg, installed via Web Installer on a clean VM) which seems to be causing the problem.

One (not very nice) work around would be to use a `GlobalResponseFilter` stripping out "Content-Length" header of the **only** the GoogleOAuth response.

I've tested this out and indeed worked as expected and I was able to login using Google OAuth. Here is an example of using a GlobalResponseFilter to work around this problem.

```
GlobalResponseFilters.Add((req, res, dto) =>
{
    if (!req.PathInfo.EndsWith("/auth/GoogleOAuth", true, CultureInfo.InvariantCulture))
    {
        return;
    }
    HttpResult httpResult = dto as HttpResult;
    if (httpResult != null && httpResult.Headers.ContainsKey("Content-Length"))
    {
        httpResult.Headers.Remove("Content-Length");
    }
});
```

I've done a bunch of reading on Azure Websites, but can't find info explaining this behavior. If you do find out any more info, would be great if you can post more info here for others.

Let me know how you go with the above work around.

Cheers.

**Comment by Formator** [comment]
Hi @Layoric

Thank you very much for your workaround. It's working and that is enough for me now. I have also implemented your solution in Formator/ServiceStackGoogleAuthAzure#2 so this can now be representative solution for all users that will encounter this kind of problem on Azure.

If I find any better solution in the future I will come back with it, but for now thank you very much!

**Comment by Layoric** [comment]
Good to hear :+1:.
