### ISSUE TITLE
 JsConfig.IgnoreAttributesNamed property is not working (ServiceStack.Text v4.0.40.0)

### ISSUE THREAD

**Issue by manojagg** [ServiceStack/Issues#303]
Hi,

Environment:
.Net 4.5
ASP.Net Web API2
ServiceStack.Text v4.0.40.0
Runtime Version: v4.0.30319

Need: 
Writing a custom MediaTypeFormatter to be injected in Web API config for the purposes of Serialization/ Deserialization of C# objects to/From JSON. For this purpose, I used the source code available on 

[Github](https://github.com/WebApiContrib/WebApiContrib.Formatting.ServiceStack/blob/master/src/WebApiContrib.Formatting.ServiceStack/ServiceStackTextFormatter.cs)

I modified the WriteToStreamAsync function as below to emit Camel Case JSON and to ignore properties marked with ScriptIgnoreAttribute:

```
 public override Task WriteToStreamAsync(Type type, object value, System.IO.Stream stream, HttpContent content, TransportContext transportContext)
        {
            return Task.Factory.StartNew(() =>
            {
                using (var scope = JsConfig.BeginScope())
                {
                    scope.DateHandler = _dateHandler;
                    JsConfig.IgnoreAttributesNamed = new[] { typeof(ScriptIgnoreAttribute).Name }; //IgnoreAttributesNamed should be available in scope object too
                    JsConfig.EmitCamelCaseNames = true;
                    JsConfig.IncludeDefaultEnums = true;
                    JsonSerializer.SerializeToStream(value, type, stream);
                }
            });
        }
```
In order to inject the Formatter, I am using following code in WebApiConfig's Register Method.

```
config.Formatters.Clear();
            config.Formatters.Insert(0, new ServiceStackTextFormatter());
```

Am I missing something or there is something wrong with the version of ServiceStack library that I am using.

Thanks,
Manoj Aggarwal.

**Comment by mythz** [comment]
Firstly all static `JsConfig` configuration should be set once on Startup, not inside a Task. See this [StackOverflow Answer on how to ignore properties](http://stackoverflow.com/a/14859968/85785).

But otherwise what's the exact issue? Please be specific as it's not clear from this description.

**Comment by mythz** [comment]
`JsConfig.IgnoreAttributesNamed` is working as expected:

```csharp
JsConfig.IgnoreAttributesNamed = new[] {
    typeof(ScriptIgnoreAttribute).Name,
    typeof(IgnoreDataMemberAttribute).Name, 
};

public class IgnoredModel
{
    public int Id { get; set; }

    [IgnoreDataMember]
    public int DataMemberIgnoreId { get; set; }

    [ScriptIgnore]
    public int ScriptIgnoreId { get; set; }
}

var dto = new IgnoredModel { ScriptIgnoreId = 1 };
Assert.That(dto.ToJson(), Is.EqualTo("{\"Id\":0}"));
```

Please reopen with a reproducible failing test that repro's the issue.

**Comment by manojagg** [comment]
I am sorry for not being clear.

The problem is that I don't want to set the configuration on global level, but rather want to set it on scope level. I am using ServiceStack's Redis Cache library and want to set extra information in the cache while not returning all the information in form of JSON to the client. Having the ability to define what needs to be ignored at scope level will be very handy. Can we call it a valid enhancement request?

**Comment by mythz** [comment]
You can file any [feature requests on UserVoice](http://servicestack.uservoice.com/forums/176786-feature-requests).
