### ISSUE TITLE
PclExportClient Timer v4.0.40 

### ISSUE THREAD

**Issue by Nness** [ServiceStack/Issues#304]
The project I have been working on got an exception recently. Where it crashed client app. Here is exception recorded by windows's event.

```
The process was terminated due to an unhandled exception. Exception Info: System.NullReferenceException Stack:
 at ServiceStack.ServerEventsClient.Heartbeat(System.Object)
 at ServiceStack.Net40PclExportClient+<>cDisplayClass5.<CreateTimer>b4(System.Object)
 at System.Threading.TimerQueueTimer.CallCallbackInContext(System.Object)
 at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
 at System.Threading.TimerQueueTimer.CallCallback()
 at System.Threading.TimerQueueTimer.Fire()
 at System.Threading.TimerQueue.FireNextTimers()
 at System.Threading.TimerQueue.AppDomainTimerCallback()
```

While I'm still trying to figure out what happen and to reproduce that issue. But I thought there might be something could be improve. 

[CreateTimer](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/PclExportClient.cs#L1718)

I have seen report on timer class, where it throw null reference exception under certain condition. I have come up with following change, see if that suit for that method.
```
var timer = new Timer(cb, state, Timeout.Infinite, Timeout.Infinite);
var itimer = new AsyncTimer(timer);
timer.Change((int) timeOut.TotalMilliseconds, Timeout.Infinite);
return itimer;
```

Also for [WaitAsync](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/PclExportClient.cs#L1728).

I was trying to use that method the other day on .Net 4.0 application. But seems that method actually block thread instead of wait async. I have checked source code, it only used by ServerEventClient. 

Possible improvement would be.

```
var tcs = new TaskCompletionSource<object>();
var timer = new Timer(tcs.SetResult, null, Timeout.Infinite, Timeout.Infinite);
var task = tcs.Task.ContinueWith(_ => timer.Dispose());
timer.Change(waitForMs, Timeout.Infinite);
return task;
```

I have implemented that way in my project as `Delay` method, works so far so good.

Just something that I have found, not sure about the intention of those method in current SS.Client project. Hope above helps.

**Comment by mythz** [comment]
Thanks, I've changed the WaitAsync impl in this commit: https://github.com/ServiceStack/ServiceStack/commit/f64c82d5ff75b42e94141a5f0642682a261f6b59 to:

```csharp
var tcs = new TaskCompletionSource<bool>();
var timer = new Timer(self => {
    ((Timer)self).Dispose();
    tcs.TrySetResult(true);
});
timer.Change(waitForMs, Timeout.Infinite);
return tcs.Task;
```

As for the `NullReferenceException` its using the code for `CreateTimer` in [Net40PclExportClient](https://github.com/ServiceStack/ServiceStack/blob/cb4eb92a9029b841e352fbd1c5d97ec75939b488/src/ServiceStack.Client/PclExportClient.Net40.cs#L63), e.g:

```csharp
public override ITimer CreateTimer(TimerCallback cb, TimeSpan timeOut, object state)
{
    return new AsyncTimer(new
        System.Threading.Timer(s => cb(s), state, (int)timeOut.TotalMilliseconds, Timeout.Infinite));
}
```

But I can't see where the NRE could be thrown in CreateTimer? Please provide a repro if you can.

**Comment by Nness** [comment]
CreateTimer got me as well. I haven't found the real reason when that will happen, but with following article and another issue ticket on SignalR. I thought change the approach might help. 

http://www.umbyersw.com/2007/12/nullreferenceexception-when-using.html

https://github.com/SignalR/SignalR/issues/3505

One of common fix for that was to assign timer first, then use change to start timer.

As for heart beat, I didn't change server side config, so in theory it's on 10 sec cycle,where this shouldn't be happening.

**Comment by mythz** [comment]
The only place I can see it throw in the Heartbeat callback is check for `ConnectionInfo` which is now guarded against in this commit: https://github.com/ServiceStack/ServiceStack/commit/4782a64491f8372a6180fb4c3f502c792dca9e73

Will need a repro if the issue is somewhere else.

**Comment by Nness** [comment]
Cool. Thanks for fix.

**Comment by Nness** [comment]
Just let you know, it crash again on 4.0.40. This time I got more meaning for log. 

In NLog. Last exception happen at 13:16:51.6706. It's under Restart method.

```
at System.Net.HttpWebRequest.GetResponse()
at ServiceStack.Net40PclExport.GetResponse(WebRequest webRequest)
at ServiceStack.ServerEventsClient.Start()
at ServiceStack.ServerEventsClient.<Restart>b__2(Task t)
```
While once application crash, inside windows event log. The time was: 1:16:53 p.m

Which is 2 sec after. Cause by heart beat. 

I think your fix should work for that crash. Since during heart beat, server event client is on reconnect cycle and `ConnectionInfo` is null.
