### ISSUE TITLE
ServiceStack CSV serializer putting extra quotes around serialized date

### ISSUE THREAD

**Issue by kustnodi** [ServiceStack/Issues#305]
I've posted this on stackoverflow as well: http://stackoverflow.com/questions/31038268/servicestack-csv-serializer-putting-extra-quotes-around-serialized-date

This happens as recently as v4.0.40 and goes back to the v3 versions as well.
 
I'm using ServiceStack in my site to allow users to download a csv of one of the system's datasets. In the configure method of my AppHost, I'm providing a custom serializer for DateTime. It looks like this

    JsConfig<DateTime>.SerializeFn = time =>
    {
        var result = time;
        if (time.Kind == DateTimeKind.Unspecified)
        {
            result = DateTime.SpecifyKind(result, DateTimeKind.Local);
        }
        return result.ToString(CultureInfo.InvariantCulture);
    };

When using the csv format all dates are being wrapped in extra quotes in the result; e.g. Result is """06/24/2015 16:22:16""" when I'd expect it to be 06/24/2015 16:22:16 or "06/24/2015 16:22:16"

It seems to me like this must be a bug in ServiceStack serialization. Is there a way to prevent this from happening? Below is a complete example that exhibits the problem when making a request to /csv/oneway/Request

    public class AppHost : AppHostBase
    {
        /// <summary>
        /// Default constructor.
        /// Base constructor requires a name and assembly to locate web service classes. 
        /// </summary>
        public AppHost()
            : base("CSVBug", typeof(MyService).Assembly)
        {

        }

        public override void Configure(Container container)
        {
            JsConfig<DateTime>.SerializeFn = time =>
            {
                var result = time;
                if (time.Kind == DateTimeKind.Unspecified)
                {
                    result = DateTime.SpecifyKind(result, DateTimeKind.Local);
                }
                return result.ToString(CultureInfo.InvariantCulture);
            };
        }
    }

    public class Request
    {

    }

    public class Response
    {
        public DateTime DateTime { get; set; }
    }

    public class MyService : Service
    {
        public object Any(Request reuqest)
        {
            return new Response()
            {
                DateTime = DateTime.Now
            };
        }
    }

and Global.asax.cs

    public class Global : System.Web.HttpApplication
    {
        protected void Application_Start(object sender, EventArgs e)
        {
            new AppHost().Init();
        }
    }

**Comment by mythz** [comment]
Please see answer on: http://stackoverflow.com/a/31058502/85785

**Comment by kustnodi** [comment]
This works well for the csv format but then the json format breaks because {"DateTime":06/25/2015 14:45:05} is not parseable

**Comment by mythz** [comment]
ok should be resolved with this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/5e1300a0b841c8b4d03292664c9e4c872c63cbc2

You'll need to switch back to using `JsConfig<DateTime>.SerializeFn`.

This change is now [deploying to MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet), will be available in about 15 minutes.

**Comment by kustnodi** [comment]
Thanks Demis.  You're a star
