### ISSUE TITLE
MiniProfiler Javascript error when ShowControls is true

### ISSUE THREAD

**Issue by cohero** [ServiceStack/Issues#308]
I am experiencing a Javascript error when utilizing the ServiceStack MiniProfiler and setting the showControls parameter to true for the ServiceStack.MiniProfiler.Profiler.RenderIncludes method. There error thrown is “Uncaught TypeError: container.hover is not a function” in the ssh-includes.js generated file. The line is thrown on line 491. It seems that the jQuip doesn’t include the ‘hover’ method.

**Comment by Layoric** [comment]
Hi @cohero, could you provide some more info about when the problem occurs? 

I created a new project and following the [wiki entry about using the MiniProfiler](https://github.com/ServiceStack/ServiceStack/wiki/Built-in-profiling), I can't reproduce it.

Would you be able to create a simple project where you reproduce the error?

**Comment by mythz** [comment]
Can you please provide an example of a page that reproduces the issue. What browser you're using and anything else that's needed to see the error?

**Comment by cohero** [comment]
Here is a link to a test project. I also followed the wiki entry but as mentioned, we tried to use the showControls option, and that triggers the problem. I am using IE 11.
https://www.dropbox.com/s/ukx912qbfaahfvj/ProfilerTest.zip?dl=0

**Comment by mythz** [comment]
Which `showControls` option, do you mean the **show trivial** link? Can you post a screenshot with the error as I'm still not able to reproduce it with IE10?

**Comment by mythz** [comment]
ok I just found that you meant the `test.cshtml` page and not the Hello service, investigating..

**Comment by mythz** [comment]
Nope, still can't reproduce it with either IE10, Chrome or Opera. @Layoric do you have access to IE11 you can test this on?

@cohero is it something to do with the cache or .js not loading properly, i.e. does it work after a refresh?

**Comment by cohero** [comment]
I have done a hard reload and cleared the cache. It also occurs in Chrome. In Chrome, as soon as the test view loads, open Inspector and that is where I see the Uncaught TypeError. From here, if you click the m or c of the mini profiler, it almost entirely disappears into the upper right corner and nothing else happens.

**Comment by cohero** [comment]
Here is the console error in Chrome:

![image](https://cloud.githubusercontent.com/assets/1904190/8490792/fa774710-20e3-11e5-90cf-ddcdf685b408.png)

**Comment by cohero** [comment]
And this what is looks like when it loads.  No timings are ever shown.
![image](https://cloud.githubusercontent.com/assets/1904190/8490802/1e468aca-20e4-11e5-809c-3d5e9bc67c58.png)

If you click the 'c' nothing happens and if you click the 'm' the mini control panel sort of half-hides itself and there is no way to get it back.
![image](https://cloud.githubusercontent.com/assets/1904190/8490819/4c15feea-20e4-11e5-8546-d5beb2b6bf0f.png)

(I'm sure that the broken functionality is because of the uncaught type error.)

**Comment by mythz** [comment]
This is what I'm seeing:

![miniprofiler-chrome](https://cloud.githubusercontent.com/assets/89361/8490864/b011296e-2162-11e5-8c00-85487083043f.png)

Basically working without a javascript error in all 3 browsers.

**Comment by mythz** [comment]
Actually nvm, I had removed the `showControls` argument as well, can see it now when `showControls:true`

**Comment by cohero** [comment]
Hmmm...I'm not sure what's going on here then.

Your test page looks different than mine (the test project I posted didn't have any text on it - I added the "Test page" text, but that doesn't change anything.

Also, I don't see the mini control panel on your page, I only see the 0.9ms.  Do you have this code in your page: @ServiceStack.MiniProfiler.Profiler.RenderIncludes(showControls: true).AsRaw()

I only see this problem if I set showControls: true - without that everything works normally.

**Comment by mythz** [comment]
The js error disappears with this commit: https://github.com/ServiceStack/ServiceStack/commit/ab1dcf534bf39b7dfaea916e18c8305ec8b4093e

But the feature doesn't look like it's doing anything useful, just collapsing the profiler stats into the top-right corner and then re-appearing when you mouse over it again, is it meant to do anything more than this? (never used it before)

**Comment by cohero** [comment]
That pretty much what I expected it to do - though I figured the 'c' would clear the list.

I am tracing many ajax calls on each page.  The list necessarily grows long sometimes and covers things I need to access on the page.  I was trying to use the mini control panel to allow me to hide and or clear the list as I'm working on the page.

Thanks for the quick work!
