### ISSUE TITLE
Broken MetaData Page when using PreRequestFilters 

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#309]
Hello,

If this is set in the configure method, the metadata page is never rendered.

                PreRequestFilters.Add((httpReq, httpRes) =>
                {
                    httpReq.UseBufferedStream = true;
                    httpRes.UseBufferedStream = true;
                });

**Comment by mythz** [comment]
Cool should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack/commit/100df16a7d6d0c699d1ad764a7b9930f4890f6d8

This change is available from v4.0.41+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
