### ISSUE TITLE
SelfHost: Prematurely disposing per-request Funq dependency 

### ISSUE THREAD

**Issue by migajek** [ServiceStack/Issues#311]
This problem has been bothering me for a long time, I've already tried to solve it once (the discussion https://plus.google.com/+Micha%C5%82Gajek/posts/4SetZaydtkP ) 
Unfortunately the tips there do not solve my problem, as the entire application is built around the fact that ISession is injected per-request. Refactoring that would be too problematic.

Recently I've also had the same problem on .NET; not only on Mono.
This occurs only when the client issues more than one request in a very short time, which made me suppose that the problem is related to RequestContext.Items persistence via CallContext

I've been digging all day to figure out what is wrong. I've set up a breakpoint on NHibernate Session being Disposed, and found out that one of the sessions instances is *definitely* being release before it's usage.

Unfortunately it's very hard to reproduce. Changing some factors like adding Thread.Sleep to any of the services, even running on different machine, makes it almost impossible to reproduce the problem (although it happens randomly)

Further digging inside the source of ServiceStack I've found out that what Demis wrote in response to my G+ question ("Funq does rely on RequestContext and will work with ThreadStatic, the issue with ThreadStatic is that it's not pinned to request contexts of async/await services") is not exactly correct. 
Although the Funq itself doesn't rely on ``RequestContext``, it's dependencies with ``ReuseScope.Request`` are being persisted in ``RequestContext.Instance.Items``, which, in turn, are persisted via ``CallContext.LogicalGet/Set``

I've set up some logging to preview order of operations:
https://gist.github.com/migajek/0afdab872ebea874850a

this simply writes information on lifetime & every usage of MyDisposable
what it also does is to persist current request url in CallContext and clear it once the request is done

Now if you have a look at the output (in the comment of the gist), the problem starts with the request to ``/user/current``

When it's called, the CallContext is **not empty**, it already contains the url of previous request ( /data/719784222/channel/2 ).
That is probably why it's also injected with the already used instance of MyDisposable (and ISession) which were used for previous request.

I believe this is a proof of "something being wrong" with the CallContext persistence.

Since I cannot share the entire source code of the project, and making any proofs of the bug doesn't make sense (as mentioned, changing anything in the "timing" of the requests makes the problem to be totally random) I'm willing to help with the problem and dig deeper, try different possible solutions etc - as long as you provide any idea what to try/change/debug.

**Comment by mythz** [comment]
> Although the Funq itself doesn't rely on RequestContext, it's dependencies with ReuseScope.Request are being persisted in RequestContext.Instance.Items, which, in turn, are persisted via CallContext.LogicalGet/Set

Are you saying that if you set `RequestContext.UseThreadStatic = true;` that Request Scoped dependencies are still stored in CallContext? Can you point out where in [RequestContext](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/RequestContext.cs) this is done?

As for non-ASP.NET Hosts `RequestContext.Instance.Items ` calls either [GetItems](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/RequestContext.cs#L50) or [CreateItems](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/RequestContext.cs#L67) both of which will return the `[ThreadStatic] RequestItems ` 

One thing you could try if you're not already, is upgrading to .NET 4.5 to see if the new copy on write behavior helps: http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html

**Comment by migajek** [comment]
I never said I've set ``RequestContext.UseThreadStatic`` to ``true``. 
It's set to false by default when using ``AppSelfHostBase``. 
I haven't changed it, because:
1. I've found no reference pointing out I should
2. I've found one post (https://forums.servicestack.net/t/bruno-lopes-67-aug-28-2014/465) saying I could enable UseThreadStatic if I'm not using async/await services. Unfortunately I'm having some async services. 

I'm already running .NET 4.5 

Are you saying that CallContext.LogicalGet/Set shouldn't be used in self-hosted scenario? This would actually mean I can't use async/await self-hosted services when depending on ``ReuseScope.Request`` dependencies?

**Comment by mythz** [comment]
@migajek ? you've [quoted my original statement](https://plus.google.com/+Micha%C5%82Gajek/posts/4SetZaydtkP)  as "not likely correct", when I've only ever said:

> You can change it to use ThreadStatics with: `RequestContext.UseThreadStatic = true;` which is more reliable in Mono. 

Also meaning that if you don't configure it, it wont use ThreadStatic and just uses the default CallContext. i.e. I've never said it uses ThreadStatic by default.

AFAIK `CallContext.LogicalSetData/CallContext.LogicalGetData` is the only option available to pin objects to async threads, if you've found this to be unreliable unfortunately there's no other solution available  in self-hosts. So the only workaround would be not accessing request scoped dependencies in async services.

**Comment by migajek** [comment]
You also wrote "Funq does rely on RequestContext" (see 2 comments below) - and that is what I've questioned. 

I know you didn't wrote it's configured automagically but you wrote "[it's] more reliable on Mono"
In the mentioned discussion I was very wrong, connecting the problem with Mono - right now I've encountered the same problem on .NET/CLR, that's why I've created this issue.

I'm trying to figure out in what circumstances the error is more likely to happen. 

BTW You've also stated that ServiceStack doesn't use async/await internally unless the Service itself is async. Please correct me if I'm wrong but but the below call stack (in a sync service) suggests it's done async (and the methods are Task-based). Isn't async/await just a syntactic sugar over Task operations? Sorry for this extra question but it confuses me a lot.

**Comment by mythz** [comment]
Here's Funq accessing `RequestContext.Instance.Items` for resolving Request-scoped dependencies:
https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Funq/ServiceEntry.Generic.cs#L30

Having a hard time trying to follow what you're asking. Please link to the source code of what's you're questioning (you can click on a line number to link to it on GitHub as seen above). 

Maybe this helps clarifies?

 - ServiceStack doesn't use async/await since they're not available in .NET 4.0 libraries without pkg deps.
 - ServiceStack doesn't yield the Worker Handler thread in synchronous requests, it might use the Task class for merging sync and async code-paths but for this it's just returning completed tasks and not yielding the Worker Handler thread.

I can investigate further if you can put together a stand-alone repro that shows the issue.

**Comment by migajek** [comment]
I've only questioned the statement in the comment: "Funq does rely on RequestContext".

The problem right now is that I'm not able to find out what specific conditions are required for the problem to occur, thus I'm not able to provide repro project.
I'm working on it, so far I've found out that the problem (i.e. CallContext local data being already filled with custom value ("left" from previous request) when global request filter is being executed) only occurs when two subsequent requests are being handled in the same thread. However this is not the only requirement as reducing size of thread pool size to 1 didn't make the problem "predictable".

I'll post here as soon as I find out how to reproduce the problem

**Comment by migajek** [comment]
One more finding:

it happens when working with:
``AppSelfHostBase``
``AppHostHttpListenerSmartPoolBase``

it doesn't seem to happen (at least, didn't happened yet) when uing
``AppHostHttpListenerBase``
``AppHostHttpListenerPoolBase``

the first two depend on Amib Smart Thread Pool, the latter - do not. 
maybe that's the issue?

again - until I'm not able to reproduce the problem deterministically that's just guessing ...

**Comment by mythz** [comment]
It's possible, I go through the differences between the different [concurrency models of each AppHost](https://github.com/ServiceStack/ServiceStack/wiki/Concurrency-model),  i.e. `HttpListenerBase` uses the IO callback thread and `AppHostHttpListenerPoolBase` uses .NET's `ThreadPool` and potentially .NET's ThreadPool does something extra when it's recycling Threads in the Pool.

There's a public `HttpListener.ReceiveWebRequest` event that you could subscribe to, to check the state of the request context before the Thread executes a new request.

**Comment by migajek** [comment]
I think I haven't made myself clear enough, sorry
I'm not talking about .NET's ``ThreadPool`` (which is used by ``AppHostHttpListenerPoolBase `` - no error here so far) but rather about Amib's SmarThreadtPool which is used by both ``AppSelfHostBase`` and ``AppHostHttpListenerSmartPoolBase`` 

I've added CallContext check to the ``ReceiveWebRequest`` and it's always empty as it should be.

Looking at the source of both error-prone SmartThreadPool-dependant hosts they don't differ much, the ``ReceiveWebRequest`` is raised right before the processing task is enqueued.

I'll try to do some more debugging tomorrow

**Comment by mythz** [comment]
Yes that's what I understood, why it's possible that .NET's built-in pool does something in addition (not sure what, just that it's possible) to Amib's SmartThreadPool when recycling the threads.

**Comment by migajek** [comment]
oh, sorry, my bad!

**Comment by migajek** [comment]
ok this really seems to be related to ``SmartThreadPool`` context switching.

I have GlobalRequestFilter which sets ``mg_url`` CallContext LogicalData and the GlobalResponseFilter which clears it.

I've set up two breakpoints in ``AppSelfHostBase.ListenerCallback``, both in the same line:
``threadPoolManager.QueueWorkItem(() => InitTask(context));`` 
the first one is on the first statement (QueueWorkItem) 
the second one on the inner lambda expression

they're both configured with following "When hit" expression:
``{ System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("mg_url") != null ? "NOT EMPTY!!!": "empty"} Function: $FUNCTION, Thread: $TID $TNAME / {context.Request.RawUrl}``


Here's the output, see the last few lines.
The one time when CallContext Logical Data happens inside the lambda, but not "outside" (when it's queued). So it's probably not about ServiceStack internals but about Smart Thread Pool.
Unfortunately STP seems to be way too complex for me to even try to understand and debug it 

```
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2C28 STP SmartThreadPool Thread #90 / "/"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/css/app.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/lib/bootstrap/css/bootstrap.min.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2C28 STP SmartThreadPool Thread #90 / "/css/app.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/lib/font-awesome-4.1.0/css/font-awesome.min.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2C28 STP SmartThreadPool Thread #90 / "/lib/font-awesome-4.1.0/css/font-awesome.min.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/lib/bootstrap-base-admin/css/base-admin-3.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x10A8 STP SmartThreadPool Thread #91 / "/lib/bootstrap/css/bootstrap.min.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/lib/angular-loading-bar/loading-bar.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2C28 STP SmartThreadPool Thread #90 / "/lib/bootstrap-base-admin/css/base-admin-3.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/lib/angular-growl/angular-growl.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/lib/jquery/jquery-2.1.1.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2680 STP SmartThreadPool Thread #92 / "/lib/angular-loading-bar/loading-bar.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/lib/angular-gantt/gantt.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/lib/bootstrap-base-admin/css/base-admin-3-responsive.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/lib/angular/angular.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/lib/angular/angular-animate.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/lib/bootstrap-base-admin/css/base-admin-3-responsive.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2680 STP SmartThreadPool Thread #92 / "/lib/angular-growl/angular-growl.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2C28 STP SmartThreadPool Thread #90 / "/lib/jquery/jquery-2.1.1.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x10A8 STP SmartThreadPool Thread #91 / "/lib/angular-gantt/gantt.css"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2680 STP SmartThreadPool Thread #92 / "/lib/angular/angular.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/lib/angular/angular-animate.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/lib/angular-ui-bootstrap/ui-bootstrap-tpls-0.11.2.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/lib/angular-ui-router/angular-ui-router.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/lib/angular-ui-bootstrap/ui-bootstrap-tpls-0.11.2.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/lib/lodash/lodash.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/lib/angular-growl/angular-growl.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2720 Worker Thread / "/lib/restangular/restangular.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2680 STP SmartThreadPool Thread #92 / "/lib/angular-ui-router/angular-ui-router.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/lib/angular-gettext/angular-gettext.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x10A8 STP SmartThreadPool Thread #91 / "/lib/lodash/lodash.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/lib/angular-loading-bar/loading-bar.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2680 STP SmartThreadPool Thread #92 / "/lib/restangular/restangular.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x25EC STP SmartThreadPool Thread #94 / "/lib/angular-gettext/angular-gettext.js"
The thread 0x2c28 has exited with code 259 (0x103).
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x3208 STP SmartThreadPool Thread #95 / "/lib/angular-loading-bar/loading-bar.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2720 Worker Thread / "/lib/angular-http-auth/http-auth-interceptor.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/lib/angular-growl/angular-growl.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/lib/angular-dynamic-locale/tmhDynamicLocale.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/lib/highstock/highstock.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/lib/highstock/highcharts-more.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x3208 STP SmartThreadPool Thread #95 / "/lib/angular-dynamic-locale/tmhDynamicLocale.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/lib/angular-http-auth/http-auth-interceptor.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/lib/highcharts-ng/highcharts-ng.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/lib/angular-google-maps/angular-google-maps.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x10A8 STP SmartThreadPool Thread #91 / "/lib/highstock/highcharts-more.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/lib/highstock/highstock.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/lib/angular-gantt/angular-gantt.js"
The thread 0x2680 has exited with code 259 (0x103).
The thread 0x25ec has exited with code 259 (0x103).
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/js/form-validation.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x3208 STP SmartThreadPool Thread #95 / "/lib/angular-google-maps/angular-google-maps.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x10A8 STP SmartThreadPool Thread #91 / "/lib/angular-gantt/angular-gantt.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/lib/highcharts-ng/highcharts-ng.min.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/js/app.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/js/services.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/js/file-upload.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x10A8 STP SmartThreadPool Thread #91 / "/js/form-validation.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/js/controllers.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2720 Worker Thread / "/js/filters.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x3208 STP SmartThreadPool Thread #95 / "/js/controllers.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x10A8 STP SmartThreadPool Thread #91 / "/js/services.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/js/directives.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x3208 STP SmartThreadPool Thread #95 / "/js/filters.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/js/app.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x3208 STP SmartThreadPool Thread #95 / "/js/directives.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/js/admin/adminapp.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/js/admin/adminapp.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/js/file-upload.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/js/admin/controllers.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/js/expo.controllers.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/js/admin/controllers.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/js/translations.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2908 STP SmartThreadPool Thread #98 / "/js/translations.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/js/expo.controllers.js"
The thread 0x10a8 has exited with code 259 (0x103).
The thread 0x3208 has exited with code 259 (0x103).
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/lib/angular/i18n/angular-locale_pl.js"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/lib/angular/i18n/angular-locale_pl.js"
The thread 0x19ec has exited with code 259 (0x103).
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/partials/_templates/default.html"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x34B8 Worker Thread / "/dashboard/logger"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/dashboard/item/11"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x3410 Worker Thread / "/partials/main/subnavbar.html"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2720 Worker Thread / "/partials/main/dashboard.item.html"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/partials/main/subnavbar.html"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2908 STP SmartThreadPool Thread #98 / "/dashboard/item/11"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/partials/_templates/default.html"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/partials/main/data.chart.html"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x2864 STP SmartThreadPool Thread #93 / "/partials/main/dashboard.item.html"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/dashboard/logger"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x37B4 STP SmartThreadPool Thread #99 / "/partials/main/data.chart.html"
The thread 0x3b0 has exited with code 259 (0x103).
The thread 0x2908 has exited with code 259 (0x103).
The thread 0x37b4 has exited with code 259 (0x103).
The thread 0x2864 has exited with code 259 (0x103).
The thread 0x17b4 has exited with code 259 (0x103).
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x2368 Worker Thread / "/data/719784222/channel/2"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/data/719784222/channel/2"
"empty" Function: ServiceStack.AppSelfHostBase.ListenerCallback(System.IAsyncResult), Thread: 0x304C Worker Thread / "/user/current"
"NOT EMPTY!!!" Function: ServiceStack.AppSelfHostBase.ListenerCallback.AnonymousMethod__1(), Thread: 0x1CD0 STP SmartThreadPool Thread #96 / "/user/current"
A first chance exception of type 'System.ObjectDisposedException' occurred in NHibernate.dll
The thread 0x1cd0 has exited with code 259 (0x103).
The thread 0x2720 has exited with code 259 (0x103).
The thread 0x304c has exited with code 259 (0x103).
The thread 0x32b0 has exited with code 259 (0x103).
The thread 0x34b8 has exited with code 259 (0x103).
```

**Comment by mythz** [comment]
Maybe you can try changing the `SmartThreadPool.DefaultUseCallerCallContext` constant to true at:
https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/SmartThreadPool/SmartThreadPool.cs#L137

Are you using a custom build from src or do you want me to make the change and push to MyGet?

**Comment by mythz** [comment]
FYI, I've [made the change](https://github.com/ServiceStack/ServiceStack/commit/caa993f99a4bca4b11c43a302164c5bdb8406a1d) which is now on MyGet. Let me know if it helps.

**Comment by migajek** [comment]
Hi, my license is expired right now, covering only <=4.0.38 so I've compiled it from source.
Changing the flag to true, causes the following ``Debug.Asert`` to fail: ``CallerThreadContext.cs`` line 85 (``public static CallerThreadContext Capture``)  - both arguments are false.

**Comment by mythz** [comment]
I've reverted `DefaultUseCallerCallContext` back to `false`. 

It doesn't appear there's a fix for this. The workaround would be to not use the combination of using async/await on Request Scoped dependencies in a SmartThreadPool-based HttpListener. 

It's not available in .NET 4.0 but this could potentially be resolved in a future version by using AsyncLocal for maintaining Thread Local state when using async/await.

**Comment by marcinbudny** [comment]
Hi. I've just encountered the problem mentioned in this issue. Basically, when accessing `RequestContext.Items` after awaiting an async operation, the items seem to be modified by another request. 

I created a repro here: https://github.com/marcinbudny/ServiceStackRequestContextItemsRepro
It has 100% repeatability on two of my machines. Project targets .NET 4.5.2, but I have .NET 4.6 installed. 

I tried 4 concurrency models mentioned above and it seems that this scenario only works on `AppHostHttpListenerPoolBase` while it fails on the others.
Also: I thought this may be related to a test runner (because of what is mentioned [here](https://github.com/ServiceStack/ServiceStack/blob/master/release-notes.md#request-scopes-can-be-configured-to-use-threadstatic)), so I tried a plain console app, but the bahavior is identical.

So what would be the recommended way to handle this problem?

**Comment by mythz** [comment]
This is a known issue of using SmartThreadPool-based HttpListener hosts. The recommendation is not to use RequestContext in async services, use the `IRequest.Items` Dictionary instead if you can, otherwise if you must use RequestContext, inherit from `AppHostHttpListenerPoolBase`.

**Comment by alexeyzimarev** [comment]
We use RequestContext to store Autofac scope. We are unable to use IRequest.Items for this, I'm afraid.
