### ISSUE TITLE
PooledRedisClientManager pooling problem when server is down

### ISSUE THREAD

**Issue by ismetozturk** [ServiceStack/Issues#312]
Hello,
 
We are experiencing some problems with "PooledRedisClientManager". It doesn't pool effectively.
If master is down it doesn't continue with the new master. (sentinel turns slave to new master)
If my both Redis Servers are online there is no problem.
But if master(or slave) is offline then raises an exception and doesn't continue. 
{ "pass@server1:6379", "pass@server2:6379" } - (server1 is down) -> ERROR
{ "pass@server2:6379", "pass@server1:6379" } - (server1 is down) -> OK (server2 is first in the readWriteHost list)

VS2013, .NET 4.5, Console App
![redis](https://cloud.githubusercontent.com/assets/7912917/8526263/3ee564d6-240e-11e5-99d2-70649b84e32b.jpg)

**Comment by mythz** [comment]
All the Redis Client Managers by themselves only looks at the hosts provided for which masters and slaves to use. It doesn't know about what Sentinel's the masters are configured with or if they've swapped server roles. The master and slave hosts can be manually changed at runtime with the `FailoverTo()` API's.

If you're running redis sentinel you'll want to use the new `RedisSentinel` class to be able to listen to server changes and reconfigure the client managers accordingly. You can see this answer on [how to configure and RedisSentinel](http://stackoverflow.com/a/28133657/85785). Please also upgrade to use the latest v4.0.42+ that was just released.
