### ISSUE TITLE
TypeLoadException 4.0.42.0

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#315]
When executing this in my apphost

                using (var db = dbFactory.Open())
                {
                    var allDbSettings = db.Dictionary<string, string>(db.From<ConfigSetting>().Select(x => new {x.Id, x.Value}));
                    var dictionarySettings = new DictionarySettings(allDbSettings)
                    {
                        Tier = tier
                    };
                    multiSettings = new MultiAppSettings(fileSettings, dictionarySettings)
                    {
                        Tier = tier
                    };
                    container.Register<IAppSettings>(c => multiSettings);
                }

the line db.Dictionary throws this exception.

System.TypeLoadException: Could not load type 'ServiceStack.OrmLite.ParameterizedSqlExpression`1' from assembly 'ServiceStack.OrmLite, Version=4.0.42.0, Culture=neutral, PublicKeyToken=null'.
   at ServiceStack.OrmLite.Oracle.OracleOrmLiteDialectProvider.SqlExpression[T]()
   at LO.Leads.UI.AppHost.Configure(Container container) in e:\repo\GitLab\LMS-P1\src\LO.Leads.UI\LO.Leads.UI\AppHost.cs:line 90

here are my using statements

using System;
using System.IO;
using System.Reflection;
using System.Security.Principal;
using CogilityWebService.Interface;
using Funq;
using LO.Leads.Common;
using LO.Leads.DataAccess;
using LO.Leads.DataAccess.Factory;
using LO.Leads.ServiceModel.Interfaces;
using LO.Leads.UI.ServiceInterface.Auth;
using LO.Leads.UI.ServiceInterface.CampaignServices;
using LO.Leads.UI.ServiceInterface.Emailer;
using LO.Leads.UI.ServiceInterface.Lead;
using NodaTime;
using ServiceStack;
using ServiceStack.Api.Swagger;
using ServiceStack.Auth;
using ServiceStack.Configuration;
using ServiceStack.Host.Handlers;
using ServiceStack.Logging;
using ServiceStack.Messaging;
using ServiceStack.Messaging.Redis;
using ServiceStack.MiniProfiler;
using ServiceStack.MiniProfiler.Data;
using ServiceStack.OrmLite;
using ServiceStack.OrmLite.Oracle;
using ServiceStack.Redis;
using ServiceStack.Text;
using ServiceStack.Validation;

and I have flushed my nuget cache.

**Comment by mythz** [comment]
Is your project .NET 4.5?

**Comment by stephenpatten** [comment]
Yes

**Comment by stephenpatten** [comment]
FYI, the upgrade with nuget was miserable, it typically is real slow and then I have to fix all the ref once it's done. This time it was slow , but finished without me having to re-add the refs... BUT 

It added assembly redirects from a console project INTO EVERY PROJECT! I have 24 projects, and then it failed to update the redirect for nlog to latest

**Comment by mythz** [comment]
Yeah NuGet can suck like that, this should now be fixed from v4.0.43+ that's now available on MyGet: https://github.com/ServiceStack/ServiceStack/wiki/MyGet

**Comment by stephenpatten** [comment]
Verified fix.
