### ISSUE TITLE
ServiceStack NLog integration

### ISSUE THREAD

**Issue by andyk2600** [ServiceStack/Issues#317]
I have upgraded my project to use  ServiceStack 4.042.0 and NLog 4.0. but now the ${callsite} nlog template fails to write the correct method signature, instead outputting the ServiceStack wrapper method as the call site 
e.g.
2015-07-10 07:21:18.3248|8|Info|ServiceStack.Logging.NLogger.NLogLogger.InfoFormat|...
 

Environment : Windows 8.1 Visual Studio 2013.Net 4.5.2  IISExpress

My project references are as follows:

    <Reference Include="Microsoft.CSharp" />
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Newtonsoft.Json.7.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="Ninject, Version=3.2.0.0, Culture=neutral, PublicKeyToken=c7192dc5380945e7, processorArchitecture=MSIL">
      <HintPath>..\..\packages\Ninject.3.2.2.0\lib\net45-full\Ninject.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="NLog, Version=4.0.0.0, Culture=neutral, PublicKeyToken=5120e14c03d0593c, processorArchitecture=MSIL">
      <HintPath>..\..\packages\NLog.4.0.1\lib\net45\NLog.dll</HintPath>
      <Private>True</Private>
    </Reference>
    <Reference Include="ServiceStack">
      <HintPath>..\..\packages\ServiceStack.4.0.42\lib\net40\ServiceStack.dll</HintPath>
    </Reference>
    <Reference Include="ServiceStack.Client">
      <HintPath>..\..\packages\ServiceStack.Client.4.0.42\lib\net40\ServiceStack.Client.dll</HintPath>
    </Reference>
    <Reference Include="ServiceStack.Common">
      <HintPath>..\..\packages\ServiceStack.Common.4.0.42\lib\net40\ServiceStack.Common.dll</HintPath>
    </Reference>
    <Reference Include="ServiceStack.Interfaces">
      <HintPath>..\..\packages\ServiceStack.Interfaces.4.0.42\lib\portable-wp80+sl5+net40+win8+monotouch+monoandroid+xamarin.ios10\ServiceStack.Interfaces.dll</HintPath>
    </Reference>
    <Reference Include="ServiceStack.Logging.NLog">
      <HintPath>..\..\packages\ServiceStack.Logging.NLog.4.0.42\lib\net40\ServiceStack.Logging.NLog.dll</HintPath>
    </Reference>
    <Reference Include="ServiceStack.OrmLite">
      <HintPath>..\..\packages\ServiceStack.OrmLite.4.0.42\lib\net45\ServiceStack.OrmLite.dll</HintPath>
    </Reference>
    <Reference Include="ServiceStack.Razor">
      <HintPath>..\..\packages\ServiceStack.Razor.4.0.42\lib\net45\ServiceStack.Razor.dll</HintPath>
    </Reference>
    <Reference Include="ServiceStack.Text">
      <HintPath>..\..\packages\ServiceStack.Text.4.0.42\lib\net40\ServiceStack.Text.dll</HintPath>
    </Reference>
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.Web.DynamicData" />
    <Reference Include="System.Web.Entity" />
    <Reference Include="System.Web.ApplicationServices" />
    <Reference Include="System.ComponentModel.DataAnnotations" />
    <Reference Include="System" />
    <Reference Include="System.Data" />
    <Reference Include="System.Core" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="System.Web.Extensions" />
    <Reference Include="System.Web.Razor">
      <HintPath>..\..\packages\ServiceStack.Razor.4.0.42\lib\net45\System.Web.Razor.dll</HintPath>
    </Reference>
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Drawing" />
    <Reference Include="System.Web" />
    <Reference Include="System.Xml" />
    <Reference Include="System.Configuration" />
    <Reference Include="System.Web.Services" />
    <Reference Include="System.EnterpriseServices" />

**Comment by mythz** [comment]
hmmm, what version was this working in?

**Comment by andyk2600** [comment]
ServiceStack 4.0.35
NLog 3.2.0

If my memory serves me right it started failing from NLog version 3.2.1




On 10 July 2015 at 14:27, Demis Bellot <notifications@github.com> wrote:

> hmmm, what version was this working in?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ServiceStack/Issues/issues/317#issuecomment-120410998>
> .
>



-- 
*Andy Keech*
Senior Software Engineer
Hermes


*Phone:* +44 (0)118 935 9269
*VPN:* 646-2269
*andrew.keech@rockwellcollins.com <andrew.keech@rockwellcollins.com>*
*www.rockwellcollins.com* <http://www.rockwellcollins.com>

Rockwell Collins (UK) Ltd.
Suttons Business Park
Reading
Berkshire
RG6 1LA. UK.
+44 (0)118 935 9000

-- 


The information contained in, or attached to, this e-mail, may contain 
confidential information and is intended solely for the use of the 
individual or entity to whom it is addressed and may be subject to legal 
privilege.  If you have received this e-mail in error, you should notify 
the sender immediately by reply e-mail, delete the message from your system 
and notify your system manager.  Please do not copy it for any purpose, 
disclose its contents to any other person or take any action in reliance on 
it.  The views or opinions presented in this e-mail may solely be those of 
the sender and may not necessarily represent those of the company.  The 
recipient should check this e-mail and any attachments for the presence of 
viruses.  The company accepts no liability for any damage caused, directly 
or indirectly, by any virus transmitted in this email.


Rockwell Collins UK Limited is a Company registered under the laws of 
England and Wales, with a Registered Address of Unit 68 Suttons Business 
Park, Reading, Berkshire, RG6 1LA, United Kingdom. Registration Number 
543016.

**Comment by mythz** [comment]
Should now be fixed in [this commit](https://github.com/ServiceStack/ServiceStack/commit/180fc5d6d504fc6ac57ed0ae2e4304645f7fd17e) which is available from v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)
