### ISSUE TITLE
Broken Swagger Page when using PreRequestFilters

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#318]
page fails to render with the following code in the Configure method. 

                PreRequestFilters.Add((httpReq, httpRes) =>
                {
                    httpReq.UseBufferedStream = true;
                    httpRes.UseBufferedStream = true;
                });

4.0.43

**Comment by mythz** [comment]
Can't reproduce it. What's your environment?

**Comment by stephenpatten** [comment]
When running on localhost it works, but when I publish to the cloud it dies. This publish is still a debug build but it's under SSL.

**Comment by mythz** [comment]
This doesn't help reproduce the issue. Is this a Windows ASP.NET Web Application, what cloud? Are you using it with any other Web Framework, e.g. MVC?

**Comment by stephenpatten** [comment]
Yeah, sorry about that. Turns out it's broken even on localhost

Windows ASP.NET Web Application, with a route at /api/

Did you get the email?

**Comment by stephenpatten** [comment]
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ServiceStack.Support.Markdown.Evaluator.<FindNamespaceInLoadedAssemblies>b__1(Assembly assembly)
   at System.Linq.Enumerable.<SelectManyIterator>d__31`3.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at ServiceStack.Support.Markdown.Evaluator.FindNamespaceInLoadedAssemblies(String assemblyNamespace)
   at ServiceStack.Support.Markdown.Evaluator.AddAssembly(String assemblyName)

**Comment by mythz** [comment]
I've already responded. But please know that I need to reproduce the issue (which I can't) and these details don't help.

**Comment by mythz** [comment]
If you're not using Markdown you can remove it with:

    Plugins.RemoveAll(x => x is MarkdownFormat);

**Comment by stephenpatten** [comment]
Yes, I was lite on the details as this was a slam dunk in my mind, I comment out the the 

PreRequestFilters.Add((httpReq, httpRes) =>
            {
                httpReq.UseBufferedStream = true;
                httpRes.UseBufferedStream = true;
            });

and it works.. real simple like

**Comment by mythz** [comment]
I've already tested this and it doesn't help me repro. 

I can't tell what's different in your Web App that's causing this and I don't have anything to go on. Please put together a small Web Application that I can run that reproduces the issue.

**Comment by mythz** [comment]
nvm, I was able to repro from a blank project. It seems removing `<urlCompression>` or adding:

    <system.webServer>
        <urlCompression doStaticCompression="true" doDynamicCompression="true" />
    </system.webServer>

Resolves the issue.

**Comment by stephenpatten** [comment]
How did you even think of that?

**Comment by mythz** [comment]
Because it messes with buffering in ASP.NET so was the first Web.config change I could think to try.

**Comment by stephenpatten** [comment]
Heres what I get after publishing, and navigating to the swagger url


/div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
</body>
</html>
HTTP/1.1 200 OK
Cache-Control: private
Content-Length: 0
Content-Type: text/html; charset=utf-8
Vary: Accept
Server: Microsoft-IIS/7.5
X-Powered-By: ServiceStack/4.043 Win32NT/.NET
X-AspNet-Version: 4.0.30319
X-MiniProfiler-Ids: ["04a6c727c51d45a9b3cbea6f1fd21feb","abb2e55e0b774caba1c61305010aee3f","df22590bbe614e19b706d298217a33ef"]
X-Powered-By: ASP.NET
Date: Fri, 10 Jul 2015 16:52:12 GMT

<!DOCTYPE html>
<html>
<head>
  <title>Swagger UI</title>
  <link href='css/typography.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/screen.css' media='screen' rel='stylesheet' type='text/css'/>
  <link href='css/reset.css' media='print' rel='stylesheet' type='text/css'/>
  <link href='css/screen.css' media='print' rel='stylesheet' type='text/css'/>
  <script type="text/javascript" src="lib/shred.bundle.js"></script>
  <script src='lib/jquery-1.8.0.min.js' type='text/javascript'></script>
  <script src='lib/jquery.slideto.min.js' type='text/javascript'></script>
  <script src='lib/jquery.wiggle.min.js' type='text/javascript'></script>
  <script src='lib/jquery.ba-bbq.min.js' type='text/javascript'></script>
  <script src='lib/handlebars-2.0.0.js' type='text/javascript'></script>
  <script src='lib/underscore-min.js' type='text/javascript'></script>
  <script src='lib/backbone-min.js' type='text/javascript'></script>
  <script src='lib/swagger-client.js' type='text/javascript'></script>
  <script src='swagger-ui.js' type='text/javascript'></script>
  <script src='lib/highlight.7.3.pack.js' type='text/javascript'></script>
  <script src='lib/marked.js' type='text/javascript'></script>

  
  <script src='lib/swagger-oauth.js' type='text/javascript'></script>
  <script type="text/javascript">
    $(function () {
      var url = window.location.search.match(/url=([^&]+)/);
      if (url && url.length > 1) {
        url = decodeURIComponent(url[1]);
      } else {
        url = "https://dev-cashcall-processor.lms.objectbrains.com/api/resources";
      }
      window.swaggerUi = new SwaggerUi({
        url: url,
        dom_id: "swagger-ui-container",
        supportedSubmitMethods: ['get', 'post', 'put', 'delete', 'patch'],
        onComplete: function(swaggerApi, swaggerUi){
          if(typeof initOAuth == "function") {
            /*
            initOAuth({
              clientId: "your-client-id",
              realm: "your-realms",
              appName: "your-app-name"
            });
            */
          }
          $('pre code').each(function(i, e) {
            hljs.highlightBlock(e)
          });
        },
        onFailure: function(data) {
          log("Unable to Load SwaggerUI");
        },
        docExpansion: "none",
        sorter : "alpha"
      });

      function addApiKeyAuthorization() {
        var key = $('#input_apiKey')[0].value;
        log("key: " + key);
        if(key && key.trim() != "") {
            log("added key " + key);
            window.authorizations.add("api_key", new ApiKeyAuthorization("api_key", key, "query"));
        }
      }

      $('#input_apiKey').change(function() {
        addApiKeyAuthorization();
      });

      // if you have an apiKey you would like to pre-populate on the page for demonstration purposes...
      /*
        var apiKey = "myApiKeyXXXX123456789";
        $('#input_apiKey').val(apiKey);
        addApiKeyAuthorization();
      */

      window.swaggerUi.load();
  });
  </script>
</head>

<body class="swagger-section">
<div id='header'>
  <div class="swagger-ui-wrap">
    <a id="logo" href="http://swagger.io">swagger</a>
    <form id='api_selector'>
      <div class='input'><input placeholder="http://example.com/api" id="input_baseUrl" name="baseUrl" type="text"/></div>
      <div class='input'><input placeholder="api_key" id="input_apiKey" name="apiKey" type="text"/></div>
      <div class='input'><a id="explore" href="#">Explore</a></div>
    </form>
  </div>
</div>

<div id="message-bar" class="swagger-ui-wrap">&nbsp;</div>
<div id="swagger-ui-container" class="swagger-ui-wrap"></div>
</body>
</html>

**Comment by stephenpatten** [comment]
I don't have the "Dynamic Compression Module" installed. 

Windows 64 2008 R2 (IIS 7.5)

**Comment by mythz** [comment]
Are you trying to say the configuration doesn't resolve the issue?

Anyway I've spent some time testing different configurations and it looks like we can also [disable buffering for this in code](https://github.com/ServiceStack/ServiceStack/commit/35230fb15f32a3116590a9429803a0e8241ac860) where it's not dependent on the Web.config.

This change is now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

In future please take note of the [fundamental goal of submitting an issue](https://github.com/ServiceStack/Issues#you-can-view-existing-issues-or-report-a-new-issue).

**Comment by stephenpatten** [comment]
Verified fix.

**Comment by mythz** [comment]
Sweet :+1:
