### ISSUE TITLE
Broken Swagger Page when using PreRequestFilters - Without dynamic compression module installed

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#319]
Hello,

If I add this to my apphost configure method, then the current swagger plug-in breaks

	PreRequestFilters.Add((httpReq, httpRes) =>
	{
		httpReq.UseBufferedStream = true;
		httpRes.UseBufferedStream = true;
	});

ASP.NET host 
ServiceStack is being hosted off of this path 'api' (ServiceStack.*.4.0.43)
Windows Server 2008 64bit R2 without compression module

If you install the dynamic compression module, then you can fix this issue as described here https://github.com/ServiceStack/Issues/issues/318, but if you can't change the setting on the server then this is still a defect.

**Comment by mythz** [comment]
Have you tried the latest MyGet as [per my last comment](https://github.com/ServiceStack/Issues/issues/318#issuecomment-120479411)?

**Comment by mythz** [comment]
Hmm got notification of this after I [left a comment](https://github.com/ServiceStack/Issues/issues/318#issuecomment-120479411) on the previous thread.

Try the latest MyGet.
