### ISSUE TITLE
Latest version issue with stripe integration

### ISSUE THREAD

**Issue by moh-abed** [ServiceStack/Issues#322]
I updated to recent version of service stack (all nuget packages including stripe). I get the following exception:

Exception while executing subscription status job EXCEPTION OCCURRED:System.MissingMethodException Method not found: 'ServiceStack.Text.JsConfigScope ServiceStack.Text.JsConfig.With(System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<ServiceStack.Text.ParseAsType>, System.Nullable`1<ServiceStack.Text.ParseAsType>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<ServiceStack.Text.DateHandler>, System.Nullable`1<ServiceStack.Text.TimeSpanHandler>, System.Nullable`1<ServiceStack.Text.PropertyConvention>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.String, System.Func`2<System.Type,System.String>, System.Func`2<System.String,System.Type>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Int32>, ServiceStack.EmptyCtorFactoryDelegate, System.String[])'. Void .ctor() - System.MissingMethodException: Method not found: 'ServiceStack.Text.JsConfigScope ServiceStack.Text.JsConfig.With(System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<ServiceStack.Text.ParseAsType>, System.Nullable`1<ServiceStack.Text.ParseAsType>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<ServiceStack.Text.DateHandler>, System.Nullable`1<ServiceStack.Text.TimeSpanHandler>, System.Nullable`1<ServiceStack.Text.PropertyConvention>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.String, System.Func`2<System.Type,System.String>, System.Func`2<System.String,System.Type>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Boolean>, System.Nullable`1<Int32>, ServiceStack.EmptyCtorFactoryDelegate, System.String[])'.
   at ServiceStack.Stripe.StripeGateway.ConfigScope..ctor()
   at ServiceStack.Stripe.StripeGateway.Send[T](IReturn`1 request, String method, Boolean sendRequestBody, String idempotencyKey)
   at ServiceStack.Stripe.StripeGateway.Get[T](IReturn`1 request)

**Comment by Layoric** [comment]
Sounds like there might be an old DLL sitting around from the NuGet update.

First try cleaning out the bin folder and rebuilding. Also might want to try clearing the NuGet packages directory and [NuGet cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#clear-nuget-package-cache) if you are still having the problem.

**Comment by moh-abed** [comment]
Did all that, still not solved

**Comment by mythz** [comment]
Unfortunately it was referencing an old ServiceStack.Text.dll which should be resolved with [this commit](https://github.com/ServiceStack/Stripe/commit/6f0c02c83f384f46aaabdd90e91c80dc0f6996a0) which is available from v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by moh-abed** [comment]
When is the actual release ?

**Comment by mythz** [comment]
We just released last week so not for another few weeks. You can use the interim pre-release builds on MyGet until then.

**Comment by moh-abed** [comment]
You don't have any test coverage for such a payment related integration ?!

Anyway switched to other Stripe.Net library :S

**Comment by mythz** [comment]
Yes the tests are in the repo, but the issue was that it wasn't referencing the right .dll version, it is now.

**Comment by pappavic** [comment]
I'm getting the exception: MissingMethodException - Method 'GetStripePlans.set_Limit' not found.

Stack Trace:
[GetSubscription: 18/08/2016 8:11:00 AM]: [REQUEST: {}] System.MissingMethodException: Method 'GetStripePlans.set_Limit' not found. at (wrapper dynamic-method) System.Object:lambda_method (System.Runtime.CompilerServices.Closure,object,object) at ServiceStack.Host.ServiceRunner`1[TRequest].Execute (IRequest request, System.Object instance, ServiceStack.Host.TRequest requestDto) [0x000de] in <filename unknown>:0

I've been getting the same thing after upgrading to 4.0.60 and still getting it with 4.0.62, is this related to this issue?

**Comment by mythz** [comment]
No it's not related, this issue has been resolved for over a year.

Please make sure all your projects have their dependencies upgraded to the latest v4.0.62 release so you're not mixing/matching dirty .dlls. If it's still an issue please provide the offending Source Code causing the error.
