### ISSUE TITLE
ServiceStack.Logging.NLog 4.0.43 nuget package is looking for NLog version 4.0.43 or greater

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#323]
I think there is a typo in the spec. on MyGet

**Comment by mythz** [comment]
No typo, NLog's 4.01 conflicted with rule for rewriting package versions for ServiceStack libs so needed to add an [explicit workaround for NLog](https://github.com/ServiceStack/ServiceStack/commit/afcc33dc07f30633ca929ec2aace397a6ae1bcaa).

Now available on MyGet.

**Comment by stephenpatten** [comment]
Verified.
