### ISSUE TITLE
MongoDb.Driver v2

### ISSUE THREAD

**Issue by Domantas** [ServiceStack/Issues#325]
Hi, 

I'm using MongoDb as primary application storage. I updated MongoDb driver to version 2 to support async methods. From now I'm not able use MongoDbAuthRepository because it works with old driver. When can I expect update for async support ?

**Comment by mythz** [comment]
Note: the Auth Repository are synchronous API's and requires a synchronous driver.

There are currently no feature requests to support the v2 driver but you [can add one on User Voice](http://servicestack.uservoice.com/forums/176786-feature-requests).
