### ISSUE TITLE
Setting `Content-Type` by implementing `IHasOptions` doesn't work in Mono

### ISSUE THREAD

**Issue by marshall007** [ServiceStack/Issues#330]
Using `IHasOptions` I'm setting both `Content-Type` and `Content-Disposition` headers. The `Content-Disposition` header always comes through just fine, but `Content-Type` reverts to the default (`text/html`) when running in Mono.

```csharp
public class RequisitionPopulator : IStreamWriter, IHasOptions
{
    private readonly Stream _requisition;

    public IDictionary<string, string> Options { get; private set; }

    public RequisitionPopulator(Stream template)
    {
        Options = new Dictionary<string, string>
        {
            {"Content-Type", "application/pdf"},
            {"Content-Disposition", "attachment; filename=\"requisition.pdf\";"}
        };

        _requisition = new MemoryStream();

        // ...
    }

    // ...

    public void WriteTo(Stream response)
    {
        _requisition.WriteTo(response);
        response.Flush();

        _requisition.Dispose();
    }
}
```

I think the issue may be related to [these lines](https://github.com/ServiceStack/ServiceStack/blob/9fed787fbdc4a2d4a117403dfc571ec179f38ae5/src/ServiceStack/HttpResponseExtensionsInternal.cs#L187-L212). Perhaps `response.AddHeader("Content-Type", ...)` doesn't update the value of `response.ContentType`?

**Comment by mythz** [comment]
I've added a workaround for Mono that should now be [fixed with this commit](https://github.com/ServiceStack/ServiceStack/commit/44ddef948a2b7f5487848120cfe8f5fa53e948bb).

This change is available from v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
