### ISSUE TITLE
Problem with session cookies in HTTP Headers and querystring

### ISSUE THREAD

**Issue by alistefano** [ServiceStack/Issues#334]
Hi,
I am trying to authenticate users with session cookies in http headers or querystring, but the webservice sends always a 401 error.

I ran a debug and I think that problem is in this function in SessionExtensions.cs

public static string GetSessionParam(this IRequest httpReq, string sessionKey)
        {
            return httpReq.GetItemOrCookie(sessionKey)
                ?? httpReq.GetHeader("X-" + sessionKey)
                ?? (HostContext.Config.AllowSessionIdsInHttpParams
                    ? (httpReq.QueryString[sessionKey] ?? httpReq.FormData[sessionKey])
                    : null);
        }

because ServiceStack checks this sequence:
1. Session Cookies
2. Headers
3. QueryString

I found that if there are no cookies in the request, ServiceStack creates a new one before calling the function GetSessionParam.
If session cookies are available but invalid the authentication fails (the other two cases are never inspected).

**Comment by mythz** [comment]
Hi, please provide a repro of the issue, i.e. the full client code (or Raw HTTP Headers) that you're using to make the request.

I've just added a test with HTTP Headers that's working as expected: https://github.com/ServiceStack/ServiceStack/commit/d2247cb023b0e1ed45e13ada0dad99883101bdb7

```csharp
var client = new JsonServiceClient(Config.AbsoluteBaseUri);
Assert.That(Log(client.Get(new SessionTypedIncr())).Tag, Is.EqualTo(1));

var cookies = client.GetCookieValues();
var sessionId = cookies["ss-id"];
sessionId.Print();

var altClient = new JsonServiceClient(Config.AbsoluteBaseUri)
{
    Headers = {
        { "X-ss-id", sessionId }
    }
};

Assert.That(Log(altClient.Get(new SessionTypedIncr())).Tag, Is.EqualTo(2));
```

**Comment by alistefano** [comment]
I created a small full example project with this issue:
https://github.com/alistefano/ServiceStackAuthIssue

I don't know if this is a misconfiguration issue or a bug. I tested with a simple api debug tool (RestClient for firefox) and also directly calling the api urls via browser.

To reproduce the issue:
- Create a new user with registration plugin
- Authenticate the user.
- Get the ss-id and ss-pid tokens from cookie
- Send a new request from anonymous browser page or with RestClient at test service via url "/api/test/Hello?ss-id(or pid)=token"
- You get an 401 Error from service
- Same issue if you include the authentication headers X-ss-pid and X-ss-id in request

**Comment by mythz** [comment]
Hi, thanks for the repro - I've added a test and fix for overriding session ids in Cookies in this commit: https://github.com/ServiceStack/ServiceStack/commit/8725ecb1368c50b350dade4ab34b2b69695fad6a

This change is available from v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

A couple notes from your example:

You should only use `SetConfig()` for any configuration, e.g:

```csharp
SetConfig(new HostConfig {
    AllowSessionIdsInHttpParams = true,
});
```

And you can quickly create/register a test user by using the `IUserAuthRepository` directly, e.g:

```csharp
var authRepo = container.Resolve<IUserAuthRepository>();
authRepo.CreateUserAuth(new UserAuth
{
    UserName = "test"
}, "test");
```

**Comment by alistefano** [comment]
Thank you mythz.
Now the authentication with headers works correctly.

The authentication with Querystring has a problem with the ss-pid token.
You can check this issue on unit test that I have added on my repo: last test (auth with pid) fails.

**Comment by mythz** [comment]
This should be solved with this commit: https://github.com/ServiceStack/ServiceStack/commit/8085bf3dba58c50fd5253bff7b5cf569d66a2918

See [Redownloading MyGet Packages](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) for instructions on how to download the latest v4.0.43 NuGet packages.
