### ISSUE TITLE
Ioc Bug with RabbitMqServer 

### ISSUE THREAD

**Issue by kharabasz** [ServiceStack/Issues#335]
I have found a difference in behavior between how ServiceStack processes http requests and queue requests. The difference boils down to how the http and message servers interact with the ioc container. The http server properly creates and disposes of objects scoped per request whereas the message server does not.

I have reproduced this behavior with an example self hosting service - you can find the code in this git repository: https://github.com/kharabasz/ServiceStackRabbitMqServerIocDisposeBug

Since this is using RabbitMqServer in default configuration, it requires a rabbitmq-server installed locally and running on localhost.

Two service implementations are included. MessageConsumingService - which is registered to serve incoming requests from rabbitmq and http; and MessagePublishingService - provided to make it easier to push requests over rabbitmq to the MessageConsumingService.

When the MessageConsumingService processes messages from http (http://localhost:8088/process-http-request) we can see that the http server properly interacts w/ the ioc container, creating and disposing of objects scoped for the request.

example output:
Request 1 Starts: 5621b62e-4ad4-4c8d-bc06-bacf3c90ca35 (guid of object instance)
Request 1 Ends: Disposing: 5621b62e-4ad4-4c8d-bc06-bacf3c90ca35
Request 2 Starts: 2ed53491-75c6-4a99-b725-1aee54e70e00
Request 2 Ends: Disposing: 2ed53491-75c6-4a99-b725-1aee54e70e00
Request 3 Starts: c01d58ae-aa46-4d67-9786-694e2fd7480d
Request 3 Ends: Disposing: c01d58ae-aa46-4d67-9786-694e2fd7480d

When the MessageConsumingService processes messages from a queue  (http://localhost:8088/process-queued-request) we can see that the message server does not properly close the request scope with the ioc container:

example output:
Request 1 Starts: 39f1f97b-9e1d-40b2-95cc-c1234b49b04a
Request 1 Ends:
Request 2 Starts: 39f1f97b-9e1d-40b2-95cc-c1234b49b04a
Request 2 Ends:
Request 3 Starts: 39f1f97b-9e1d-40b2-95cc-c1234b49b04a
Request 3 Ends:
Request 4 Starts: 39f1f97b-9e1d-40b2-95cc-c1234b49b04a
Request 4 Ends:
Request 5 Starts: 39f1f97b-9e1d-40b2-95cc-c1234b49b04a (always uses the same object instance)
Request 5 Ends:

**Comment by mythz** [comment]
Should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack/commit/b76de32e84a2f962a310580338a90c8092c8316b

Available from v4.0.33+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by kharabasz** [comment]
@mythz would it be hard to backport this fix to v3? I could make a pull request if you point me in the general direction.

**Comment by mythz** [comment]
This was done my @piotr-g in this PR: https://github.com/ServiceStack/ServiceStack/pull/1002

**Comment by mythz** [comment]
I'm generally fine with back-porting my V4 fixes back to V3 - but please ask permission to relicense by contributions into BSD first.

Please also note support is [only available for v4 Customers](https://github.com/ServiceStack/Issues#servicestack-issues), i.e. including this issues list, forums, etc.
