### ISSUE TITLE
CompositeIndex behaving differently in PostgreSQL and SQLite

### ISSUE THREAD

**Issue by scpeterson** [ServiceStack/Issues#336]
We have a custom AuthUser, that we are using and it looks like this:

    [Alias("UserAuth")]
    [CompositeIndex(true, "company_id", "user_name")]
    public class MyCustomUserAuth : IMyCustomUserAuth
    {
        public MyCustomUserAuth()
        {
            Roles = new List<string>();
            Permissions = new List<string>();
        }

        [AutoIncrement]
        public int Id { get; set; }

        [References(typeof(Company))]
        public long CompanyId { get; set; }
               
        public string UserName { get; set; }
        
        public string Email { get; set; }
    }

Our PostgreSQL provider is set up in AppHost as follows:

    var dbCompanyConnectionFactory = new OrmLiteConnectionFactory(appConfig.CompanyConnectionString, PostgreSQLDialectProvider.Instance);
    OrmLiteConfig.DialectProvider.NamingStrategy = new PostgreSqlNamingStrategy();
    container.Register<IDbConnectionFactory>(dbCompanyConnectionFactory);

As you can see, we are using the PostgreSQL naming strarategy, so the column names all get changed from MyPropertyName to my_property_name .  When we run our code, the UserAuth table is created in PostgreSQL just fine, and specifying the CompositeIndex  with the expected column names works just fine.  However, when I want to use SQLite to create this table for testing, my tests fail because there are no fields named "company_id" or "user_name," just ones named CompanyId and UserName.  This makes sense because the NamingStrategy is just for PostgreSQL.  What is the best approach to get SQLite to use the same naming strategy?  Is such a thing in ServiceStack or SQLite, or do I need to roll my own?

**Comment by scpeterson** [comment]
Ugh, never mind. If I use the PostgreSQLNamingConvention when I set up the SQLite database in my tests, everything works just fine.  I didn't try this at first because I was using SQLite and didn't think to use a naming strategy for PostgreSQL.

**Comment by mythz** [comment]
Right the behavior is expected as they both use a different naming strategy, so you could register Sqlite to use the same naming strategy as Postgres. (Note: PostgreSql doesn't need it since it uses it uses it by default).

But have you tried just using the property names, i.e?

```csharp
[CompositeIndex(true, "CompanyId", "UserName")]
```

**Comment by scpeterson** [comment]
Yes, I tried just using the property names ash you showed above.  Doing that makes the test work, but causes the application to fail since the column names are now wrong, i.e., the app is expecting company_id and is getting CompanyId.

**Comment by mythz** [comment]
What version are you using?

**Comment by scpeterson** [comment]
ServiceStack 4.0.42

**Comment by mythz** [comment]
ok just checked I can repro this with v4.0.42 that's now on NuGet, but you should now be able to use

```csharp
[CompositeIndex(true, "CompanyId", "UserName")]
```

Which generates this SQL Index for PostgreSQL:

```
CREATE UNIQUE INDEX uidx_userauth_companyid_username ON "user_auth" ("company_id" ASC, "user_name" ASC); 
```

From v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by scpeterson** [comment]
OK, thanks!  We will upgrade to 4.0.43 once it's on NuGet.

I appreciate your help and very fast replies.
