### ISSUE TITLE
SSE RegisterSubscription high CPU usage and long executing time

### ISSUE THREAD

**Issue by Nness** [ServiceStack/Issues#339]
We have a chat server that's build on top of servicestack's SSE. Lately we notice there is an issue with it's performance under certain situation. 

It only happen once or twice a week. When it happen, chat server CPU will go up to close to 100%, number of SSE connection drop, number of requests finish execute drop, request execution time increase. This last for several hours until we restart server.

Average SSE connections I believe is up to 10K ~ 20k, when issue happen it drop to 4k~5k.

We did perf-view during issue come up and while it's stable. One thing came up was  RegisterSubscription method cost a lot of CPU time. While 'TryUpdate' and TryGetValue was on the chart. 

I will post  several images, include perfview and performance monitor. For performance monitor's time, we restart server on 6:07:25PM, then the connection quickly come back and eventually become stable.

From source code, I think it might relate to that while loop when save subscription into array. Will that be logic to have internal collection be concurrent dictionary instead of array, even though resource might use higher but it will be rare to get into this situation. On the other hand, each subscription id should only have one SSE connection anyway. So dictionary can be base on subscription id.

![Request Execution Time](https://cloud.githubusercontent.com/assets/1712143/9511299/4a2bd102-4cc9-11e5-8363-40ac2fd2baa8.png)

![Request Executing](https://cloud.githubusercontent.com/assets/1712143/9511307/5e003d1c-4cc9-11e5-9956-bbb9bd3f6398.png)

![CPU](https://cloud.githubusercontent.com/assets/1712143/9511310/69b312d8-4cc9-11e5-9336-8f34221bd7c7.png)

![Request/Sec](https://cloud.githubusercontent.com/assets/1712143/9511313/7418e6da-4cc9-11e5-857f-9042626f33b7.png)

![PerfView when we had issue](https://cloud.githubusercontent.com/assets/1712143/9511316/7eaba7cc-4cc9-11e5-9bf4-10884f8a885b.png)

![PerfView after restart server](https://cloud.githubusercontent.com/assets/1712143/9511322/98ec13d8-4cc9-11e5-8f0e-830ab5ceedcf.png)

**Comment by mythz** [comment]
Hi thanks for the profiler screenshots, I'd like to get a better idea of what the issue is so I've extracted creating a new array + resizing the array in different methods which will hopefully better highlight where the issue is in this commit: https://github.com/ServiceStack/ServiceStack/commit/b233f9d4218ab352b926fb5434dff067cbaa1c17

I've also added locks around subscription reads in-case it's due to a memory model issue.

This change is available from v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Please send updated screenshots with the change above.

**Comment by Nness** [comment]
Since this only happen once a week. I will use your build and deploy to our server later and monitor it next week. If issue happen again I will give you update.

We do have previous perfview data stored. If you want them just let me know. Thanks for changes you made.

**Comment by Nness** [comment]
Issue happen again right after deploy, took 50+ sec sample from perfview which here is result.

I still left new server there, if issue happen again my colleague will help me take more sample. 

![50 sec sample](https://cloud.githubusercontent.com/assets/1712143/9539925/f54dae5a-4dac-11e5-85f7-be632c9a175b.png)

**Comment by mythz** [comment]
Not seeing any of the new array API's in the list?

**Comment by Nness** [comment]
From that perfview no.

Some of them shows it has child but it's gray out. That's maximum I can expand.

Those threads at top of list that consume similar amount of resource tend to have same stack trace.

I will check again on USA Sunday when I get back to office.

**Comment by Nness** [comment]
Probably I can right click on OTHER<<clr?!>> to load symbols. I will post result here later.

**Comment by Nness** [comment]
I have just loaded clr for last time perfview section. A lot of resource been used on array creation and copy.

I did notice that you added some change to keep timeout connection low after the commit you give to me. When I wrote code, I actually did similar thing to use your logic to detect connection that suppose to expire and expire manually. 

Timer for our cleanup was setup to be every 1 min. 

But I did one critical mistake, when I loop through all of connection, I actually locked whole subscription dictionary.

```
foreach (var entry in events.Subcriptions.Values) {
     foreach (var sub in entry) {
          if (sub == null || sub.SubscriptionId == null)
             continue;

          subs.Add(new SubObj(sub));
     }
}
```

By iterate through ConcurrentDictionary's Values property, that actually locked whole dictionary, but good thing is I didn't perform any heavy operation, other than convert subscription to a separate object. 

```
       private class SubObj
        {
            public SubObj([NotNull]IEventSubscription sub)
            {
                SubscriptionId = sub.SubscriptionId;
                LastPulseAt = sub.LastPulseAt;
            }

            public string SubscriptionId { get; set; }

            public DateTime LastPulseAt { get; set; }
        }
```
As you can see, that loop through should be fast and only grab necessary property that I need. Once I got whole list, I will perform check for last pulse and expire a list of connections by using `IServerEvents.Unregister`.

So that's something I need to fix or even remove according to your latest commit. But how big is the impact to resolve CPU issue, I'm not sure. On the other hand, if issue happen again I will record it, see if there is different compare to what we see last time.


![By Name](https://cloud.githubusercontent.com/assets/1712143/9569284/6b74028c-4fba-11e5-86c5-ae849fa27732.png)
![By Caller for newarr1](https://cloud.githubusercontent.com/assets/1712143/9569286/701b9fac-4fba-11e5-947d-8411e37edb49.png)

**Comment by Nness** [comment]
This morning, our chat server was sitting on 50% CPU, where I notice one interesting behavior, total subscription was 20k at that time, but only 10k count as active. Active as last pulse in specified timeout (default value).

I have removed those lock loop from my code see what's different I can get. I will keep an eye that.

**Comment by Nness** [comment]
Server looks stable in last week. I will close this issue. Thanks for all the help.

**Comment by mythz** [comment]
Awesome glad to hear it.
