### ISSUE TITLE
MemoryCacheClient Increment/Decrement Are Not Atomic

### ISSUE THREAD

**Issue by jasonpepper** [ServiceStack/Issues#340]
The ICacheClient comments state that the Increment and Decrement operations are atomic. However, in MemoryCacheClient they are not.

The following test should output "200000". But it outputs something less than that due to the lack of atomicity.

    using System;
    using System.Threading;
    using ServiceStack.Caching;

    namespace Test
    {
        internal class Test
        {
            public static readonly ICacheClient CacheClient = new MemoryCacheClient();

            private static void Main(string[] args) {
                var numThreads = 20;
                var resetEvent = new ManualResetEvent(false);
                var threadsLeft = numThreads;

                for (var i = 0; i < numThreads; i++) {
                    new Thread(() =>
                    {
                        for (var j = 0; j < 10000; j++) {
                            CacheClient.Increment("test", 1);
                        }
                        if (Interlocked.Decrement(ref threadsLeft) == 0)
                            resetEvent.Set();
                    }).Start();
                }

                resetEvent.WaitOne();
                Console.WriteLine(CacheClient.Increment("test", 0));
                Console.ReadKey();
            }
        }
    }

**Comment by mythz** [comment]
Hi, thanks for the failing test!

This should now fixed from this commit: https://github.com/ServiceStack/ServiceStack/commit/ae27334321c76f30340493db386dc5eaaa229e61

This change is available from v4.0.43+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
