### ISSUE TITLE
How to avoid HTTP 401 when ServiceStack server requires authorization?

### ISSUE THREAD

**Issue by Leonidnei** [ServiceStack/Issues#342]
When server requires Windows authentication, each request sent by client is rejected with HTTP 401 and resent send time with auth headers, then the request succeeds.

How to avoid these double requests?

For WCF or ASMX service we can use:
request.PreAuthenticate = true;
request.UnsafeAuthenticatedConnectionSharing = true;

where request is HttpRequest being sent to the server.

How to implement this with ServiceStack?

**Comment by mythz** [comment]
Hi, ServiceStack .NET Service Clients provides a thin wrapper over .NET's `HttpWebRequest` which you can modify with a global or local request filter, e.g:

```csharp
var client = new JsonServiceClient(BaseUrl) {
    RequestFilter = httpReq => {
        httpReq.PreAuthenticate = true;
        httpReq.UnsafeAuthenticatedConnectionSharing = true;
    }
};
```

Please note this Issue Tracker is for reporting reproducible bugs/issues, please refer to [servicestack.net/account/support](https://servicestack.net/account/support) for your different support options, e.g. you can use [the Customer Forums](https://forums.servicestack.net/) or [StackOverflow](http://stackoverflow.com/questions/ask) for any general support/howto questions.
