### ISSUE TITLE
AddAttributes not working for RestrictAttribute

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#343]
public override void Configure(Container container)
        {
            SetConfig(new HostConfig
            {
                DebugMode = false
            });

            typeof (Hello2).AddAttributes(new RestrictAttribute {AccessTo= RequestAttributes.None});

            this.Plugins.Add(new SwaggerFeature());
        }

The RestrictAttribute works fine when added to a class definition. RestrictAttribute is not working when used as above, I've tested `AccessTo` and `VisibilityTo`.

Additionally, [mentioned here](http://stackoverflow.com/questions/21305393/how-can-i-hide-swagger-ui-endpoints-from-servicestack-metadata), RestrictAttribute has a dependency on DebugMode.

I guess this was added because the RestrictAttribute is usually added to the DTO class. 

If using AddAttributes at runtime, then we have more programmatic control, so it would be useful to configure SS so RestrictAttribute is not dependent upon DebugMode.

**Comment by mythz** [comment]
Not going to change the behavior of [Restrict] attribute, you can propose any feature requests on [ServiceStack's UserVoice](http://servicestack.uservoice.com/forums/176786-feature-requests).

The runtime attribute API doesn't change the behavior of the attribute, it's just provides another way to annotate types. The Services are wired up and cached before `Configure()` is called so some attributes need to be added before the AppHost is initialized, e.g. in the constructor or outside the AppHost before `appHost.Init()`.

**Comment by mjdaly** [comment]
I had a suspicion wiring up happened before `Configure()`, but [this example](https://github.com/ServiceStack/ServiceStack/blob/master/tests/RazorRockstars.Web/AppHost.cs#L28) and [this test](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.WebHost.Endpoints.Tests/RuntimeAttributeTests.cs#L66) using `AddAttributes(RestrictAttribute)` made me think there was a bug. So do you need to update these examples?

Regarding changing the behaviour of Restrict, I've seen you add in simple benign config parameters before (i.e. default behaviour stays the same, but overriding it is possible through configuration) without requiring user voice. On second look, is this still a big feature request?

**Comment by mythz** [comment]
Right it's not a big feature request but its obscure and already has a configured option that adding another one to reverse the behavior adds unnecessary confusion and clutter where the only way it would be considered is if there was demand for it which is what UserVoice measures.

**Comment by mjdaly** [comment]
On the unlikely event you missed (no acknowledgement from you on correctness) some information from the last comment.

> I had a suspicion wiring up happened before `Configure()`, but [this example](https://github.com/ServiceStack/ServiceStack/blob/master/tests/RazorRockstars.Web/AppHost.cs#L28) and [this test](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.WebHost.Endpoints.Tests/RuntimeAttributeTests.cs#L66) using `AddAttributes(RestrictAttribute)` made me think there was a bug. So do you need to update these examples?

**Comment by mythz** [comment]
updated, thx.
