### ISSUE TITLE
ServerEventsFeature.cs -> RemoveExpiredSubscriptions Null Ref

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#345]
Im getting a null ref in RemoveExpiredSubscriptions, Im guessing it's line 728 from looking at the code.
if (now - sub.LastPulseAt > IdleTimeout)

The Housekeeping methods are setting sub = null, so this crashes.

https://github.com/ServiceStack/ServiceStack/blob/0ca8c75b7d91fe3803a41c00f4e40f823c11c239/src/ServiceStack/ServerEventsFeature.cs#L728

**Comment by mythz** [comment]
Crap, that's annoying, fixed NRE in this commit: https://github.com/ServiceStack/ServiceStack/commit/e465f3c3d82527a6ab636bc8e41fd7e416088107

This change is available from v4.0.45 that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Thanks for reporting!
