### ISSUE TITLE
Sentinel client throws RedisResponseException on the first write command after successful failover

### ISSUE THREAD

**Issue by DonHartman** [ServiceStack/Issues#346]
**Issue**
Using version 4.0.44 of ServiceStack.Redis (and common, interfaces, and text), any first write command issued to a client after failover will throw a RedisResponseException with the message "READONLY You can't write against a read only slave., sPort: 55225, LastCommand: " (Previously, we were on 4.0.42, and we would get this exception indefinitely, not just once.)

- Is this expected behavior?
- Would it make sense to wrap all our commands in a single retry to assure they survive failover?
  - If so, why isn't this built into RedisClient?

**To reproduce:**
1) Configure a basic master/slave sentinel configuration capable of a successful failover.
2) Create and start a RedisSentinel as follows:
```C#
var sentinel = new RedisSentinel(new []{"sentinel1:port", "sentinel2:port", "sentinel3:port"},  "master_name")
     {
        RedisManagerFactory = (masters, slaves) => new PooledRedisClientManager(
            masters,
            slaves,
            new RedisClientManagerConfig
            {
                MaxReadPoolSize = 50,
                MaxWritePoolSize = 50
            },
            null,
            1,
            5)
    };
var clientsManager = sentinel.Start();
```

3) Use the clients manager to issue a command:
```C#
using (IRedisClient client = clientsManager.GetClient())
{
    client.SetValue("foo", "bar");
}
```
4) Connect to any sentinel, trigger a failover "SENTINEL failover <master_name>", and wait for it to complete. (i.e. verify there is a new master)
5) Issue another write command via the same manager:
```C#
using (IRedisClient client = clientsManager.GetClient())
{
   client.SetValue("foo", "bar2");
}
```
This throws the exception. If it is caught, and the action retried, all subsequent commands are successful.

**Environmental Details**
I have been able to reproduce this issue both locally:
- Windows 7 (x64)
- VS2013
- IISExpress
- .NET 4.5.1
- ServiceStack.Redis 4.0.44 (ServiceStack.Common 4.0.44, ServiceStack.Text 4.0.44, ServiceStack.Interfaces 4.0.44)

and on our staging environment:
- Windows Server 2008 R2 Enterprise (x64)
- IIS(7.5.7600.16385)
- .NET 4.5.1
- ServiceStack.Redis 4.0.44 (ServiceStack.Common 4.0.44, ServiceStack.Text 4.0.44, ServiceStack.Interfaces 4.0.44)

**Comment by mythz** [comment]
Hi,

It appears the forced failover doesn't follow the normal failover process events and just sends an event that the masters were switched, which we're now catching in this commit: https://github.com/ServiceStack/ServiceStack.Redis/commit/cc930d49d1dc66e8b8b48ce61c44844198bb9875

This change is available from v4.0.45 that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Please try it out and let me know if it resolves the issue, thx.

**Comment by DonHartman** [comment]
I updated to 4.0.45 from your MyGet feed, and ran the integration tests again (even deleted old packages, cleared bins, etc. first. To be safe). Unfortunately, I still get the same exception on the *first* write after failover. Later writes work as expected.

Then, just to be thorough, instead of step 4 mentioned above(forced failover), I took down the master and let sentinels auto-promote the slave. This yielded the same result.

**Comment by mythz** [comment]
If you had v4.0.45 installed previously you'll also need to [clear the NuGet Package Cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#clear-nuget-package-cache).

Please provide the source code for the failing integration test.

I've tested that this works with a manual failover in [ForceFailover](https://github.com/ServiceStack/ServiceStack.Redis/blob/master/tests/Console.Tests/ForceFailover.cs) that's now working without Exception.

**Comment by DonHartman** [comment]
After taking the time to strip down our code (removing internal references so it would be runnable), I realized this bug is far more elusive than I'd thought. Apparently I just got 'lucky' and had perfect timing the first half dozen times I ran it. It only seems to happen if a write command is sent *immediately* after the previous master claims its role is slave. 

If I had to guess, there's a race condition where the set can get through after the old master is demoted to a slave, but before RedisSentinel reacts to the "+failover-end" or "+switch-master".

If you'd still like the source code I could zip it up and send it (somewhere?), but I'd imagine you can get the same result with some more precise timing. 

When I wrapped my second set with Assert.DoesNotThrow(who knew asserts slowed the code down so much???), I had to put it in a for loop 10,000 times and let it roll right after failover just to catch the exception (happened somewhere around the 2,734th try). Otherwise I couldn't get the timing to reproduce it.

In the short term, I can't imagine one lost set putting our site in a bad state, the once a week (month? [year??]) that a natural failover actually occurs. But the potential for it to happen is still intimidating.

**Comment by mythz** [comment]
This is time dependent since the notification from the Sentinels need to occur before the client pools are reset. Accessing it before this happens, can return an already connected client referencing the old master, during this window it is expected using an existing client connected to an invalid host will throw, just as it would for any clients that were already resolved from the pool before the failover happened.

**Comment by DonHartman** [comment]
Fair enough. and thanks a bunch for the timely replies!

One last thought if you have the time. If a single retry always prevents this from occurring, what reason(s) might there to to *not* include that logic in the client (your code or mine).

**Comment by mythz** [comment]
The client encapsulates a single TCP connection, when it's resolved from the pool it's considered to be active since its still within its Idle Timeout. It's only when it's used does it find out that the connection is invalid and all it can do at that point is throw since it's no longer valid. Just as if you tried to use a DB or HTTP connection after the remote server is no longer available.

**Comment by DonHartman** [comment]
That explains it!
Thanks again!
