### ISSUE TITLE
Your web page example fails

### ISSUE THREAD

**Issue by CBrauer** [ServiceStack/Issues#349]
Hello,

I followed the instructions on your web page:
     https://github.com/ServiceStack/ServiceStack/wiki/Creating-your-first-project
and the test: 
    http://localhost:49174
works fine, but the test:  
    http://localhost:49174/hello/world
failed with the error: "HTTP Error 500.19 - Internal Server Error"

I am running on a new Windows 8.1 Enterprise, Intel I7 (x64), machine with all updates installed.
I build your sample program with Visual Studio 2015.

I can send you my complete project code to reproduce the error if you desire.
I look forward to hearing from you.

Charles
![image](https://cloud.githubusercontent.com/assets/1317234/9805125/28e72f92-57ea-11e5-9b4f-aa52af1aa26e.png)

**Comment by mythz** [comment]
The error suggests there's a duplicate configuration defined. Please post your entire Web.config file here.

**Comment by CBrauer** [comment]
<?xml version="1.0"?>

<configuration>
  <configSections>
    <sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor">
      <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor" requirePermission="false"/>
      <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor" requirePermission="false"/>
    </sectionGroup>
  </configSections>
  
  <system.web>
    <compilation debug="true" targetFramework="4.5">
      <buildProviders>
        <add extension=".cshtml" type="ServiceStack.Razor.CSharpRazorBuildProvider, ServiceStack.Razor"/>
      </buildProviders>
    </compilation>
    <httpRuntime/>
    <httpHandlers>
      <add path="*" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*"/>
    </httpHandlers>
    <pages controlRenderingCompatibilityVersion="3.5" clientIDMode="AutoID"/>
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true"/>
    <validation validateIntegratedModeConfiguration="false"/>
    <urlCompression doStaticCompression="true" doDynamicCompression="false"/>
    <handlers>
      <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true"/>
    </handlers>
  </system.webServer>
  <appSettings>
    <add key="webPages:Enabled" value="false"/>
  </appSettings>
  <system.web.webPages.razor>
    <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc"/>
    <pages pageBaseType="ServiceStack.Razor.ViewPage">
      <namespaces>
        <add namespace="System"/>
        <add namespace="ServiceStack"/>
        <add namespace="ServiceStack.Html"/>
        <add namespace="ServiceStack.Razor"/>
        <add namespace="ServiceStack.Text"/>
        <add namespace="ServiceStack.OrmLite"/>
        <add namespace="WebApplication1"/>
      </namespaces>
    </pages>
  </system.web.webPages.razor>
</configuration>

**Comment by CBrauer** [comment]
<?xml version="1.0"?>

<configuration>
  <configSections>
    <sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor">
      <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor" requirePermission="false"/>
      <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor" requirePermission="false"/>
    </sectionGroup>
  </configSections>
  
  <system.web>
    <compilation debug="true" targetFramework="4.5">
      <buildProviders>
        <add extension=".cshtml" type="ServiceStack.Razor.CSharpRazorBuildProvider, ServiceStack.Razor"/>
      </buildProviders>
    </compilation>
    <httpRuntime/>
    <httpHandlers>
      <add path="*" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*"/>
    </httpHandlers>
    <pages controlRenderingCompatibilityVersion="3.5" clientIDMode="AutoID"/>
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true"/>
    <validation validateIntegratedModeConfiguration="false"/>
    <urlCompression doStaticCompression="true" doDynamicCompression="false"/>
    <handlers>
      <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true"/>
    </handlers>
  </system.webServer>
  <appSettings>
    <add key="webPages:Enabled" value="false"/>
  </appSettings>
  <system.web.webPages.razor>
    <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc"/>
    <pages pageBaseType="ServiceStack.Razor.ViewPage">
      <namespaces>
        <add namespace="System"/>
        <add namespace="ServiceStack"/>
        <add namespace="ServiceStack.Html"/>
        <add namespace="ServiceStack.Razor"/>
        <add namespace="ServiceStack.Text"/>
        <add namespace="ServiceStack.OrmLite"/>
        <add namespace="WebApplication1"/>
      </namespaces>
    </pages>
  </system.web.webPages.razor>
</configuration>

**Comment by CBrauer** [comment]
<?xml version="1.0"?>

<configuration>
  <configSections>
    <sectionGroup name="system.web.webPages.razor" type="System.Web.WebPages.Razor.Configuration.RazorWebSectionGroup, System.Web.WebPages.Razor">
      <section name="host" type="System.Web.WebPages.Razor.Configuration.HostSection, System.Web.WebPages.Razor" requirePermission="false"/>
      <section name="pages" type="System.Web.WebPages.Razor.Configuration.RazorPagesSection, System.Web.WebPages.Razor" requirePermission="false"/>
    </sectionGroup>
  </configSections>
  
  <system.web>
    <compilation debug="true" targetFramework="4.5">
      <buildProviders>
        <add extension=".cshtml" type="ServiceStack.Razor.CSharpRazorBuildProvider, ServiceStack.Razor"/>
      </buildProviders>
    </compilation>
    <httpRuntime/>
    <httpHandlers>
      <add path="*" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*"/>
    </httpHandlers>
    <pages controlRenderingCompatibilityVersion="3.5" clientIDMode="AutoID"/>
  </system.web>
  <system.webServer>
    <modules runAllManagedModulesForAllRequests="true"/>
    <validation validateIntegratedModeConfiguration="false"/>
    <urlCompression doStaticCompression="true" doDynamicCompression="false"/>
    <handlers>
      <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true"/>
    </handlers>
  </system.webServer>
  <appSettings>
    <add key="webPages:Enabled" value="false"/>
  </appSettings>
  <system.web.webPages.razor>
    <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc"/>
    <pages pageBaseType="ServiceStack.Razor.ViewPage">
      <namespaces>
        <add namespace="System"/>
        <add namespace="ServiceStack"/>
        <add namespace="ServiceStack.Html"/>
        <add namespace="ServiceStack.Razor"/>
        <add namespace="ServiceStack.Text"/>
        <add namespace="ServiceStack.OrmLite"/>
        <add namespace="WebApplication1"/>
      </namespaces>
    </pages>
  </system.web.webPages.razor>
</configuration>

**Comment by CBrauer** [comment]
I tried to "paste" the contents of the Wen.config file into the comment window above.  It does not look right.  Any suggestions?

**Comment by CBrauer** [comment]
I tried to "paste" the contents of the Web.config file into the comment window above. It does not look right. Any suggestions?

**Comment by CBrauer** [comment]
I tried to "paste" the contents of the Web.config file into the comment window above. It does not look right. How 'bout we switch to email: CBrauer@CypressPoint.com?  That way I can send you my project.

**Comment by CBrauer** [comment]
I "pasted" the contents of the Web.config file into the comment window above. Your software generated the Web.config.  If it is wrong, then you have a bug.

How 'bout we switch to email: CBrauer@CypressPoint.com? That way I can send you my project.

**Comment by mythz** [comment]
I've just updated your post. You just need to include any xml in literal quotes, e.g:

    ```xml
    ```

I suspect you have an abnormal .NET environment / Machine.config setting.

I've created new ServiceStackVS templates and added them to the [ServiceStackVS folder in the Templates repository](https://github.com/ServiceStack/Templates/tree/master/src/ServiceStackVS). I've tested every one and they all work as expected. 

Can you try cloning the Templates repo and seeing if you can run one of the pre-made ServiceStackVS templates?

**Comment by CBrauer** [comment]
I tried the first template: AspNetEmpty.sln.
Again, running: 
  http://localhost:57649
worked, but: 
  http://localhost:57649/hello/world
 failed with
   "HTTP Error 500.19 - Internal Server Error".  
Should this work?

**Comment by CBrauer** [comment]
I tried the first template: AspNetEmpty.sln.
Again, running: 
  http://localhost:57649
worked, but: 
  http://localhost:57649/hello/world
failed with
  "HTTP Error 500.19 - Internal Server Error".

When you tested these templates did you use Visual Studio 2015 and Widows 8.1?

**Comment by CBrauer** [comment]
I tried WindowsService.sln and it worked:
![image](https://cloud.githubusercontent.com/assets/1317234/9823280/2f991068-587a-11e5-84f7-99a46e48e427.png)

**Comment by mythz** [comment]
Yes all the templates are working as expected:

![aspnetempty_helloworld](https://cloud.githubusercontent.com/assets/89361/9823066/ed80fb6a-5878-11e5-8ba2-b962a8f4c426.png)

Now tested and working on: VS 2015 / Windows 10, VS 2015 / Windows 8, VS 2013 / Windows 8, VS 2012 / Windows 8.

We've never had this issue reported before with any template so I suspect it's something unique to your environment, which I wont be able to tell help with. I suspect it will work fine if you try on a different pc otherwise you can try [googling for this error](https://www.google.com/search?q=cannot+add+duplicate+collection+entry+of+type+add) to see if any of the reported solutions help you.

The error suggests you have the **ServiceStack.Factory** handler already defined but if you've never used ServiceStack before I don't see how that's possible, but you can try removing it with

```xml
    <system.webServer>

        <handlers>
            <remove name="ServiceStack.Factory" />
            <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true" />
        </handlers>
    </system.webServer>
```

or possibly clearing previous handlers:

```xml
    <system.webServer>

        <handlers>
             <clear/>
            <add path="*" name="ServiceStack.Factory" type="ServiceStack.HttpHandlerFactory, ServiceStack" verb="*" preCondition="integratedMode" resourceType="Unspecified" allowPathInfo="true" />
        </handlers>
    </system.webServer>
```

Sorry I can't help you more.

**Comment by mythz** [comment]
BTW all self-hosting solutions will work because they don't use any previous IIS / ASP.NET Web.config mappings. 

The problem likely lies in custom configuration added in one of:

  - C:\inetpub\wwwroot\Web.config
  - applicationHost.config
  - machine.config

**Comment by CBrauer** [comment]
I tried:

![image](https://cloud.githubusercontent.com/assets/1317234/9823788/5f5d0d6a-587d-11e5-8f1b-13e5dea0ac4f.png)

**Comment by mythz** [comment]
It should be under `<system.webServer><handlers/>` 

You can remove `<system.web><handlers />` it's not needed in IIS7+.

**Comment by CBrauer** [comment]
Well, we are making some progress. Now when I try AspNetEmpty, http://localhost:57649/hello/world, your software changed the URL to: http://localhost:57649/hello/world/metadata, and I get:

![image](https://cloud.githubusercontent.com/assets/1317234/9823988/ba4c2dea-587e-11e5-931f-f5f4089eb68e.png)

**Comment by mythz** [comment]
Can you post the screenshot for: http://localhost:57649/hello/world?debug=requestinfo

**Comment by mythz** [comment]
Actually if you don't have a JSON prettify plugin just post the raw JSON response.

**Comment by CBrauer** [comment]
When I debug with:
![image](https://cloud.githubusercontent.com/assets/1317234/9824426/9bb9b93a-5881-11e5-8a9b-ffb99df44905.png)

I still get:

![image](https://cloud.githubusercontent.com/assets/1317234/9824457/c76c64b0-5881-11e5-94dd-69ce64e72290.png)

**Comment by mythz** [comment]
Don't change the Project url, put it back to `http://localhost:57649/`

Just put `http://localhost:57649/hello/world?debug=requestinfo` in a browser, if it still redirects, add the `?debug=requestinfo` to the final url it redirected to.

**Comment by CBrauer** [comment]
I got:

{"Usage":"append '?debug=requestinfo' to any querystring","Host":"WebServer20_v4.044_AspNetEmpty","Date":"\/Date(1442000588274)\/","ServiceName":"AspNetEmpty","UserHostAddress":"::1","HttpMethod":"GET","PathInfo":"/","ResolvedPathInfo":"/","StripApplicationVirtualPath":false,"GetLeftPath":"http://localhost:57649","Path":"/hello/world","GetPathUrl":"http://localhost:57649/hello/world","AbsoluteUri":"http://localhost:57649/hello/world?debug=requestinfo","ApplicationBaseUrl":"http://lo","ResolveAbsoluteUrl":"http://lo/resolve","ApplicationPath":"/hello/world","ApplicationVirtualPath":"/hello/world","VirtualAbsolutePathRoot":"/","VirtualAppRelativePathRoot":"/","RawUrl":"/hello/world?debug=requestinfo","ContentType":"","Status":0,"ContentLength":0,"Headers":{"Connection":"keep-alive","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8","Accept-Encoding":"gzip, deflate, sdch","Accept-Language":"en-US,en;q=0.8","Host":"localhost:57649","User-Agent":"Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36","Upgrade-Insecure-Requests":"1","DNT":"1"},"QueryString":{"debug":"requestinfo"},"FormData":{},"AcceptTypes":["text/html","application/xhtml+xml","application/xml;q=0.9","image/webp","*/*;q=0.8"],"OperationName":"/hello/world","ResponseContentType":"text/html","LogonUserInfo":{"Name":"BIGSUR\\CBrauer","AuthenticationType":"","IsAuthenticated":"False","IsAnonymous":"False","IsGuest":"False","IsSystem":"False","Groups":"S-1-1-0, S-1-5-32-559, S-1-5-32-545, S-1-5-4, S-1-2-1, S-1-5-11, S-1-5-15, S-1-11-96-3623454863-58364-18864-2661722203-1597581903-2678686197-428210959-1466644497-1605774124-1900611786, S-1-5-113, S-1-2-0, S-1-5-64-32","User":"S-1-5-21-3704706833-110272719-4242021717-1001","User.AccountDomainSid":"S-1-5-21-3704706833-110272719-4242021717","User.IsAccountSid":"True"},"DebugString":"System.Web.HttpRequest|System.Web.HttpResponse","PluginsLoaded":["HtmlFormat","CsvFormat","MarkdownFormat","PredefinedRoutesFeature","MetadataFeature","NativeTypesFeature","RequestInfoFeature"],"StartUpErrors":[],"Stats":{"RawHttpHandlers":"2","PreRequestFilters":"0","RequestBinders":"0","GlobalRequestFilters":"0","GlobalResponseFilters":"1","CatchAllHandlers":"4","Plugins":"7","ViewEngines":"1","RequestTypes":"8","ResponseTypes":"2","ServiceTypes":"2","RestPaths":"8","ContentTypes":"5","EnableFeatures":"All","VirtualPathProvider":"[FileSystemVirtualPathProvider: C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty], [ResourceVirtualPathProvider: AspNetEmpty], [ResourceVirtualPathProvider: ServiceStack]"},"VirtualPathProviderFiles":["C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\AppHost.cs","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\AspNetEmpty.csproj","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\AspNetEmpty.csproj.user","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\Global.asax","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\Global.asax.cs","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\packages.config","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\Web.config","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\Web.Debug.config","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\Web.Release.config","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\AspNetEmpty.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\AspNetEmpty.dll.config","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\AspNetEmpty.pdb","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\AspNetEmpty.ServiceInterface.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\AspNetEmpty.ServiceInterface.pdb","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\AspNetEmpty.ServiceModel.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\AspNetEmpty.ServiceModel.pdb","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Client.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Client.xml","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Common.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Common.xml","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Interfaces.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.OrmLite.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Razor.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Razor.xml","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Redis.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Redis.xml","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Server.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Text.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.Text.xml","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\ServiceStack.xml","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\System.Web.Razor.dll","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\bin\\System.Web.Razor.xml","C:\\Temp\\Templates-master\\src\\ServiceStackVS\\AspNetEmpty\\AspNetEmpty\\Properties\\AssemblyInfo.cs","ServiceStack.FluentValidation.Resources.Messages.resources","ServiceStack.js.ss-utils.js","ServiceStack.js.ss-utils.d.ts","ServiceStack.MiniProfiler.UI.includes.css","ServiceStack.MiniProfiler.UI.includes.js","ServiceStack.MiniProfiler.UI.includes.tmpl","ServiceStack.MiniProfiler.UI.jquip.all.js","ServiceStack.Properties.Resources.resources","ServiceStack.Templates.HtmlFormat.html","ServiceStack.Templates.IndexOperations.html","ServiceStack.Templates.OperationControl.html"]}

**Comment by CBrauer** [comment]
What browser are you using?

**Comment by CBrauer** [comment]
Hi Demis,

 

My machine is new.  I have not installed IIS 8.5 so I don’t have a C:\inetpub directory.

 

Charles

**Comment by CBrauer** [comment]
Hi Demis,

My machine is new.  I have not installed IIS 8.5 so I don’t have a C:\inetpub directory.

Charles

**Comment by mythz** [comment]
Primarily Chrome, but use and have all FF, IE, Safari, Opera installed.

There seems to be an issue with the `ApplicationBaseUrl` being passed in by IIS/ASP.NET (again suggesting an abnormal/corrupt environment). This affects what PathInfo is calculated which for `http://localhost:57649/hello/world` should be `/hello/world`

This is what it should be:

```
PathInfo: "/hello/world",
ResolvedPathInfo: "/hello/world",
StripApplicationVirtualPath: false,
GetLeftPath: "http://localhost:57649",
Path: "/hello/world",
GetPathUrl: "http://localhost:57649/hello/world",
AbsoluteUri: "http://localhost:57649/hello/world?debug=requestinfo",
ApplicationBaseUrl: "http://localhost:57649",
ResolveAbsoluteUrl: "http://localhost:57649/resolve",
ApplicationPath: "/",
ApplicationVirtualPath: "/",
VirtualAbsolutePathRoot: "/",
VirtualAppRelativePathRoot: "~/",
```

Compared to what your ASP.NET is returning:

```
"PathInfo": "/",
"ResolvedPathInfo": "/",
"StripApplicationVirtualPath": false,
"GetLeftPath": "http://localhost:57649",
"Path": "/hello/world",
"GetPathUrl": "http://localhost:57649/hello/world",
"AbsoluteUri": "http://localhost:57649/hello/world?debug=requestinfo",
"ApplicationBaseUrl": "http://lo",
"ResolveAbsoluteUrl": "http://lo/resolve",
"ApplicationPath": "/hello/world",
"ApplicationVirtualPath": "/hello/world",
"VirtualAbsolutePathRoot": "/",
"VirtualAppRelativePathRoot": "/",
```

You can try specify the WebHostUrl in `AppHost.Configure()`:

```csharp
SetConfig(new HostConfig {
    WebHostUrl = "http://localhost:57649/hello/world"
});
```

You can also change the absolute url resolve at runtime by overriding ResolveAbsoluteUrl in AppHost, e.g:

```csharp
public override string ResolveAbsoluteUrl(string virtualPath, IRequest httpReq)
{
    return base.ResolveAbsoluteUrl(virtualPath, httpReq);
}
```

But this is patching over the underlying issue, which I'm not sure what the solution is - maybe you should try installing latest IIS/ASP.NET from Web Platform Installer to see if that helps.

**Comment by mythz** [comment]
I think I may have tracked this issue down, can you try with the latest v4.0.45 of ServiceStack that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
