### ISSUE TITLE
Change in redirect behaviour

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#350]
[This problem has resurfaced again.](https://github.com/ServiceStack/Issues/issues/249)

Moving from 4.0.40 to 4.0.44, authentication redirect behaviour has changed.

1) Our default login page is `/login`
2) After updating to v4.0.44, accessing `/`, redirects to `lo/login?redirect=http%3a%2f%2flo`
3) You can download the `/?debug=requestinfo` output [here](https://drive.google.com/file/d/0B5cglv2mrbC7NXhJamhhaWpjOHc/view?usp=sharing)

**Comment by mythz** [comment]
It was a path resolution issue but wasn't the same one. Should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack/commit/12070eb80922a644b8e1cdba6638aa27ae82f2a8

This change is available from v4.0.45+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
