### ISSUE TITLE
Mvc integration. ReuseScope.Request not disposing

### ISSUE THREAD

**Issue by suhrab** [ServiceStack/Issues#351]
Tried to use SS with Mvc. Wanted to share dependecies with Mvc controllers. https://github.com/ServiceStack/ServiceStack/wiki/Mvc-integration#sharing-dependencies-with-mvc-controllers

Dependencies are wired, but not disposed in **ServiceStackController** if using **ReuseScope.Request**. 
Look at **MyDisposable** class; overrided **Release** method of AppHostBase.
Services are not affected.

I've found this q/a http://stackoverflow.com/a/29829667/1243426 but I'am using ServiceStackController and in there is no word in docs https://github.com/ServiceStack/ServiceStack/wiki/Mvc-integration#sharing-dependencies-with-mvc-controllers about manually disposing

Demo app https://mega.nz/#!LIUjDD6a!mEJp13gscOyVbopqQFFd19r-LwE3cGG5yH40GqHK1f8

ServiceStack 4.0.44
Windows 8.1
VisualStudio 2013

**Comment by mythz** [comment]
Should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack/commit/dddbe35b6b8db440ecfd6782b40a54efa439affe

This change is available from v4.0.45+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
