### ISSUE TITLE
Possibility of moving HttpResult into ServiceStack.Interfaces

### ISSUE THREAD

**Issue by kharabasz** [ServiceStack/Issues#352]
Hello @mythz,

We are currently migrating from v3 to v4 and have noticed that the HttpResult class has moved out of the Common package into the ServiceStack package. Would you consider moving HttpResult into ServiceStack.Interfaces? We have separated our service logic from the service host around the Common package and do not feel comfortable bringing the core ServiceStack package in as a dependency into out service logic projects.

I appreciate any thoughts/suggestions on the matter.

**Comment by mythz** [comment]
Sorry No, ServiceStack.Interfaces should be an impl-free library, e.g. it defines [IHttpResult](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Interfaces/Web/IHttpResult.cs) which HttpResult implements.

The concrete `HttpResult` is a server-side Framework feature, which makes the most sense to be in ServiceStack project. If you want to decouple it you could encapsulate it behind your own abstraction, similar to how [LogManager](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Interfaces/Logging/LogManager.cs) decouples the `ILog` interface from its implementations.
