### ISSUE TITLE
OrmLite fails to select Scalar<Guid> (SQLite database)

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#353]
Following test throws exception with this message: System.InvalidCastException : Specified cast is not valid.

```c#
    [TestFixture]
    public class SelectScalarTests : OrmLiteTestBase
    {
        public class TestPerson
        {
            public Guid Id { get; set; }
        }

        [Test]
        public void Should_Return_Scalar_Value()
        {
            using (var db = OpenDbConnection())
            {
                db.DropAndCreateTable<TestPerson>();
                var id = Guid.NewGuid();
                db.Insert(new TestPerson { Id = id });
                var pid = db.Scalar<Guid>(db.From<TestPerson>().Where(x => x.Id == id).Select(x => x.Id));
                Assert.AreEqual(pid, id);
            }
        }
    }
```

**Comment by mythz** [comment]
I've switched over to use Type Converters for converting Scalar values in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/e1bf81ebbc910b2426df573bad874f90a80b0ecc

This change is available from v4.0.47 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

thx for the failing test!
