### ISSUE TITLE
Error on first execution (v4.0.46)

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#354]
This error occurs after compilation, on the first page access. If you hit F5 to refresh the page, the error disappears. Error occurs on each mode (dev, test, production).

Note: My .NET Framework is in french.

Here the details:

Erreur du serveur dans l'application '/'.

La collection a été modifiée ; l'opération d'énumération peut ne pas s'exécuter.

Description : Une exception non gérée s'est produite au moment de l'exécution de la requête Web actuelle. Contrôlez la trace de la pile pour plus d'informations sur l'erreur et son origine dans le code. 

Détails de l'exception: System.InvalidOperationException: La collection a été modifiée ; l'opération d'énumération peut ne pas s'exécuter.

Erreur source: 

Ligne 19 :     </head>
Ligne 20 :     <body class="ksm">
Ligne 21 :         @Html.Action("NavBar", "Common")
Ligne 22 :         <div class="container">
Ligne 23 :             <div class="row">

Fichier source : d:\Projets\gecko\src\gui\Ksm.Gecko.Gui.WebMvc\Views\Shared\_Layout.cshtml    Ligne : 21 

Trace de la pile: 

[InvalidOperationException: La collection a été modifiée ; l'opération d'énumération peut ne pas s'exécuter.]
   System.Collections.HashtableEnumerator.MoveNext() +12102703
   ServiceStack.ServiceStackHost.OnEndRequest(IRequest request) +108
   ServiceStack.Mvc.ServiceStackController.Dispose(Boolean disposing) +65
   System.Web.Mvc.Controller.Dispose() +20
   System.Web.Mvc.DefaultControllerFactory.ReleaseController(IController controller) +24
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +54
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.Mvc.<>c__DisplayClassa.<EndProcessRequest>b__9() +22
   System.Web.Mvc.<>c__DisplayClass4.<Wrap>b__3() +10
   System.Web.Mvc.ServerExecuteHttpHandlerWrapper.Wrap(Func`1 func) +27
   System.Web.Mvc.ServerExecuteHttpHandlerWrapper.Wrap(Action action) +64
   System.Web.Mvc.ServerExecuteHttpHandlerAsyncWrapper.EndProcessRequest(IAsyncResult result) +71
   System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride) +1194

[HttpException (0x80004005): Erreur d'exécution de la demande enfant pour le gestionnaire 'System.Web.Mvc.HttpHandlerUtil+ServerExecuteHttpHandlerAsyncWrapper'.]
   System.Web.HttpServerUtility.ExecuteInternal(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage, VirtualPath path, VirtualPath filePath, String physPath, Exception error, String queryStringOverride) +3423122
   System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm, Boolean setPreviousPage) +77
   System.Web.HttpServerUtility.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm) +29
   System.Web.HttpServerUtilityWrapper.Execute(IHttpHandler handler, TextWriter writer, Boolean preserveForm) +24
   System.Web.Mvc.Html.ChildActionExtensions.ActionHelper(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues, TextWriter textWriter) +463
   System.Web.Mvc.Html.ChildActionExtensions.Action(HtmlHelper htmlHelper, String actionName, String controllerName, RouteValueDictionary routeValues) +83
   System.Web.Mvc.Html.ChildActionExtensions.Action(HtmlHelper htmlHelper, String actionName, String controllerName) +11
   ASP._Page_Views_Shared__Layout_cshtml.Execute() in d:\Projets\gecko\src\gui\Ksm.Gecko.Gui.WebMvc\Views\Shared\_Layout.cshtml:21
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy() +197
   System.Web.Mvc.WebViewPage.ExecutePageHierarchy() +105
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +90
   System.Web.WebPages.<>c__DisplayClass3.<RenderPageCore>b__2(TextWriter writer) +232
   System.Web.WebPages.HelperResult.WriteTo(TextWriter writer) +10
   System.Web.WebPages.WebPageBase.Write(HelperResult result) +80
   System.Web.WebPages.WebPageBase.RenderSurrounding(String partialViewName, Action`1 body) +63
   System.Web.WebPages.WebPageBase.PopContext() +237
   System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage) +98
   System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance) +235
   System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer) +107
   System.Web.Mvc.ViewResultBase.ExecuteResult(ControllerContext context) +291
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResult(ControllerContext controllerContext, ActionResult actionResult) +13
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +56
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultFilterRecursive(IList`1 filters, Int32 filterIndex, ResultExecutingContext preContext, ControllerContext controllerContext, ActionResult actionResult) +420
   System.Web.Mvc.ControllerActionInvoker.InvokeActionResultWithFilters(ControllerContext controllerContext, IList`1 filters, ActionResult actionResult) +52
   System.Web.Mvc.Async.<>c__DisplayClass2b.<BeginInvokeAction>b__1c() +173
   System.Web.Mvc.Async.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult) +100
   System.Web.Mvc.Async.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult) +10
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeAction(IAsyncResult asyncResult) +27
   System.Web.Mvc.Controller.<BeginExecuteCore>b__1d(IAsyncResult asyncResult, ExecuteCoreState innerState) +13
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecuteCore(IAsyncResult asyncResult) +36
   System.Web.Mvc.Controller.<BeginExecute>b__15(IAsyncResult asyncResult, Controller controller) +12
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +22
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.Controller.EndExecute(IAsyncResult asyncResult) +26
   System.Web.Mvc.Controller.System.Web.Mvc.Async.IAsyncController.EndExecute(IAsyncResult asyncResult) +10
   System.Web.Mvc.MvcHandler.<BeginProcessRequest>b__5(IAsyncResult asyncResult, ProcessRequestState innerState) +21
   System.Web.Mvc.Async.WrappedAsyncVoid`1.CallEndDelegate(IAsyncResult asyncResult) +29
   System.Web.Mvc.Async.WrappedAsyncResultBase`1.End() +49
   System.Web.Mvc.MvcHandler.EndProcessRequest(IAsyncResult asyncResult) +28
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.EndProcessRequest(IAsyncResult result) +9
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +9723757
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155

**Comment by labilbe** [comment]
The error didn't occur on v4.0.44

**Comment by mythz** [comment]
hmm that's strange, the only thing that really changed in Razor was the [Debuggable Razor Views](https://github.com/ServiceStack/ServiceStack/blob/master/docs/2015/release-notes.md#debuggable-razor-views).

Can you let me know if disabling it makes a difference?

```csharp
Plugins.Add(new RazorFeature {
    IncludeDebugInformation = false,
});
```

**Comment by labilbe** [comment]
Do you mean RazorFormat instead of RazorFeature?

**Comment by labilbe** [comment]
By the way, I'm not using the ServiceStack Razor format (I use the ASP.NET MVC 5 one).

Here is a list of plugins used during execution.

![image](https://cloud.githubusercontent.com/assets/54315/10041862/de738e4e-61e7-11e5-85e3-48d3aef03db6.png)

**Comment by mythz** [comment]
Yeah I meant `RazorFormat` ok in that case I'm guessing that you're using `ServiceStackController` then? In which case can you wrap the Controllers Dispose method behind a try/catch to see if it resolves the issue?

```csharp
        protected override void Dispose(bool disposing)
        {
            try {
                return base.Dispose(disposing);
            } catch(Exception ex) {
                ex.Message.Print();
            }
        }
```

and let me know what it prints out?

**Comment by labilbe** [comment]
Yes I'm using <code>public abstract class ControllerBase : ServiceStackController<CustomUserSession></code>.

The try catch resolves the issue.
Printed message is:
<code>La collection a été modifiée ; l'opération d'énumération peut ne pas s'exécuter.</code>
so
<code>Collection has been modified ; enumeration operation can not execute.</code>

**Comment by labilbe** [comment]
If I comment <code>@Html.Action("NavBar", "Common")</code> the next call to another <code>Html.Action</code> throws the same exception.

**Comment by labilbe** [comment]
When Controller is disposed, there is call done to

<pre>
using System.Data;
using ServiceStack.Data;

namespace Ksm.Gecko.Services.ServiceInterface.Services.Common
{
    public abstract class DbServiceBase<T> : AppServiceBase where T : IDbConnectionFactory
    {
        private IDbConnection _db;

        public override IDbConnection Db
        {
            get
            {
                return _db ?? (_db = TryResolve<T>().OpenDbConnection());
            }
        }

        public override void Dispose()
        {
            if (_db != null)
            {
                _db.Dispose();
            }
            base.Dispose(); // <-- This line is throwing the exception
        }
    }
}
</pre>

Am I doing something wrong?

**Comment by mythz** [comment]
It's the same issue right? i.e. this eventually calls a Dispose() method on a controller?

**Comment by mythz** [comment]
I'm having trouble reproducing this issue, what type of dependencies do you have registered in AppHost? are you sharing the ServiceStack Func IOC in MVC, e.g:

```csharp
ControllerBuilder.Current.SetControllerFactory(new FunqControllerFactory(container));
```

Are you using any Request scoped dependencies? which ones?

**Comment by labilbe** [comment]
It's the same issue yes.

My Global.asax <code>Application_Start()</code>

<pre><code>        protected void Application_Start()
        {
            //AreaRegistration.RegisterAllAreas();
            //FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            //RouteConfig.RegisterRoutes(RouteTable.Routes);
            //BundleConfig.RegisterBundles(BundleTable.Bundles);

            Profiler.Settings.PopupRenderPosition = RenderPosition.Left;
            Profiler.Settings.SqlFormatter = new SqlServerFormatter();

            var ignoredPaths = Profiler.Settings.IgnoredPaths.ToHashSet();
            ignoredPaths.Add("/fonts/");
            ignoredPaths.Add("/flags/");
            ignoredPaths.Add("/api/js/");
            ignoredPaths.Add("/api/event-");
            ignoredPaths.Add("/api/ssr-");
            Profiler.Settings.IgnoredPaths = ignoredPaths.ToArray();

            RegisterGlobalFilters(GlobalFilters.Filters);
            RegisterRoutes(RouteTable.Routes);

            AppHost = new WebAppHost(this);
            AppHost.Init();

            // Init ControllerBuilder ControllerFactory after, otherwise, it does not work
            //Set MVC to use the same Funq IOC as ServiceStack
            ControllerBuilder.Current.SetControllerFactory(new FunqControllerFactory(AppHost.Container));
            //ServiceStackController.CatchAllController = reqCtx => container.TryResolve&lt;HomeController&gt;();

            RegisterModelBinders(ModelBinders.Binders);
        }</code></pre>

All the controller iherit from my custom <code>ControllerBase</code>

<pre><code>
    public abstract class ControllerBase : ServiceStackController&lt;CustomUserSession&gt;
    {
        public IAccountingService AccountingService { get; set; }
        public IAccountingWriteService AccountingWriteService { get; set; }
        public IActionTypeService ActionTypeService { get; set; }
        public IArticleFamilyService ArticleFamilyService { get; set; }
        public IArticleInventoryService ArticleInventoryService { get; set; }
        public IArticlePriceService ArticlePriceService { get; set; }
        public IArticleService ArticleService { get; set; }
        ...

        // Keep it like this because easier to mock
        protected override TUserSession SessionAs&lt;TUserSession&gt;()
        {
            return HttpContext == null ? default(TUserSession) : base.SessionAs&lt;TUserSession&gt;();
        }

        /// <summary>
        /// Returns default page list size to display elements (list or table).
        /// </summary>
        public const int PageListSize = 30;

        protected override void Dispose(bool disposing)
        {
            try
            {
                base.Dispose(disposing);
            }
            catch (Exception ex)
            {
                ex.Message.Print();
            }
        }

        ...
</code></pre>

**Comment by mythz** [comment]
ok tho still not seeing something I can use here to help repro. Are the dependencies registered on `AppHost.Container`? Do you have anything unusual on them, e.g Request Scoped dependencies?

BTW the error is now logged instead of being bubbled in v4.0.47 that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

But I'd still like to know which Hashtable is causing the issue and why so anything you could do to provide a repro will be appreciated.

**Comment by mythz** [comment]
Going to close this issue, this exception is now being handled / logged. Although I haven't been able to repro this issue, you can re-open with a stand-alone repro if you want me to investigate further.

**Comment by labilbe** [comment]
Thank you mythz for the fix. I will test to investigate further too and give you a repro of this issue.
