### ISSUE TITLE
JsonServiceClient Digest Auth not working with Async method

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#355]
I've run into an issue with `JsonServiceClient` and it's ability to authorise itself after it receives an unauthorized server response.

Given the client

            var client = new JsonServiceClient(url)
            {
                UserName = userName,
                Password = password,
            };

when it is contacting a server that is using digest auth

            //this call will correctly send the digest auth header when 401 response is received
            ServiceClient.Get(new CompaniesReport());

            //but  
 
            //this async call will send the basic auth header when 401 response is received
            await ServiceClient.GetAsync(new CompaniesReport());

[Looks like only basic auth is catered for, any reason?](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/AsyncServiceClient.cs#L334).

**Comment by mythz** [comment]
Yeah it adds a lot of duplicated code so left it out until it was needed as I didn't like strategy of having this baked into the client, I prefer a more decoupled/extensible strategy. Anyway async Digest Support should now be supported from this commit: https://github.com/ServiceStack/ServiceStack/commit/5cb8aecc1f3dc6ad9d9a493d2874df159d71228c

Which is available from v4.0.47 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
