### ISSUE TITLE
SqliteOrmLiteDialectProvider.Instance throws exception in 4.0.46

### ISSUE THREAD

**Issue by devedse** [ServiceStack/Issues#357]
As of the latest update to 4.0.46 all my unit tests fail that use Sqlite for an in memory database because of this exception:

![image](https://cloud.githubusercontent.com/assets/2350015/10260310/71b8f7aa-6974-11e5-86ff-f13f94933189.png)

Opening the inner exception shows this:

![image](https://cloud.githubusercontent.com/assets/2350015/10260352/8e93763e-6974-11e5-8adf-e2f919e44bd3.png)
 
When looking through the last checkins it might have something to do with the StringColumnDefinition being removed in this checkin:

https://github.com/ServiceStack/ServiceStack.OrmLite/commit/70ef432587db54eee78c3424867ac7648cf3798b#diff-7962d39137e4adf239ad99f78809aee7

Besides this it also seems the nuget package for OrmLite.Sqlite32 was not updated beyond version 4.0.42 yet.

Kind regards,

Devedse

**Comment by mythz** [comment]
The [ServiceStack.OrmLite.Sqlite32](https://www.nuget.org/packages/ServiceStack.OrmLite.Sqlite32) and [ServiceStack.OrmLite.Sqlite64](https://www.nuget.org/packages/ServiceStack.OrmLite.Sqlite64) packages have been deprecated as mentioned on the NuGet packages. They have been replaced with [ServiceStack.OrmLite.Sqlite.Windows](https://www.nuget.org/packages/ServiceStack.OrmLite.Sqlite.Windows). If you're trying to use different v4.0.42 version with a different v4.0.46 that is likely the reason.

**Comment by devedse** [comment]
Ah yes that seemed to be the issue :). Might it be an idea to still provide an update to the Sqlite32/64 packages will which open a readme file showing that it's deprecated?

**Comment by mythz** [comment]
You need to make sure you're only using the same versions of packages together, if you have a dependency issue this is the reason. If newer versions of that package doesn't exist it's very likely it's because it has been deprecated at which point check the NuGet package description or refer back to the project page on what the correct package to install is.
