### ISSUE TITLE
COALESCE and MOD creates bad SQL

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#358]
OrderByDescendingInternal and ThenByDescendingInternal both splits the fields on a ','
this will break if you have a COALESCE, MOD or a string that contains ','.

https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite/Expressions/SqlExpression.cs#L521

The commit that changes this https://github.com/ServiceStack/ServiceStack.OrmLite/commit/d6c160d42f4f5ad4c2a276a071dcdff5ebe723c6 

As far as i can see, there are no checks for this as the test only checks Asc.

    public class Program
    {
        class Record
        {
            public int Id { get; set; }
            public double Value { get; set; }
            public DateTime? Time { get; set; }       

        }

        static void Main(string[] args)
        {
            var factory = new OrmLiteConnectionFactory(":memory:",  SqliteDialect.Provider);

            using (var connection = factory.Open())
            {
                // Create table
                connection.DropAndCreateTable(typeof(Record));

                // Insert test records
                connection.InsertAll(new Record[] {
                    new Record()
                    {
                        Id = 1,
                        Value = 50,
                        Time = DateTime.Now,
                    },
                });

                // Expression that works.
                var exp = connection.From<Record>();
                exp.OrderByDescending(x => x.Time ??  DateTime.UtcNow);

                // This fails because DESC is place wrong.
                // SELECT "Id", "Value", "Time" FROM "Record" ORDER BY "Id", COALESCE("Time" DESC, '2015-10-02 11:01:11.2418195') DESC
                //                                                                            / \
                //                                                                             |
                var output = connection.Select(exp);
            
            }
        }
    }

**Comment by mythz** [comment]
ok this should now be resolved using a smarter tokenizer with this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/e5a247afe46dbc2b8ad6a1568c7c7eeeac9412c9

This change is available from v4.0.47 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
