### ISSUE TITLE
{ breaks Ormlite Select

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#360]
Using MySQL.

A query was breaking when using Ormlite because I was concatenating strings with the `{` character.

Ormlite is throwing System.FormatException just because the SQL statement contains `{` not followed by `0}` for example.

The simple query below where `{` is commented, throws an exception, therefore this must be a SS issue.

            var sql2 = @"
            SELECT
                ua.Email
                -- {
            FROM UserAuth ua
            GROUP BY
                ua.Email";

            var people = Db.Select<Person2>(sql2);

Whatever magic is supposed to be happening in the background, can it be turned off?

**Comment by mythz** [comment]
You can use `Sql*` API's for executing custom SQL as-is:

    var people = Db.SqlList<Person2>(sql2);
