### ISSUE TITLE
When setting HtmlRedirect to null on AuthFeature, [Authorize] is returning a 302 instead of a 401 when unauthorized

### ISSUE THREAD

**Issue by bumblebeeman** [ServiceStack/Issues#363]
So, for example, when I create a new AuthFeature like so:

    Plugins.Add(new AuthFeature(ObjectFactory.GetInstance<IAuthSession>, new IAuthProvider[] { })
    {
        HtmlRedirect = null
    });

Using the [Authorize] attribute should return a 401 when unauthorized, instead it returns a 302.

Playing about with the source code, in **ServiceStack.AspNet.ServiceStackPage.cs**, if I replace:

    public virtual string UnauthorizedRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect() + "?redirect={0}#f=Unauthorized"; }
    }
    
    public virtual string ForbiddenRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect() + "?redirect={0}#f=Forbidden"; }
    }

With:

    public virtual string UnauthorizedRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect(); }
    }
    
    public virtual string ForbiddenRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect(); }
    }

And then in **ServiceStack.Mvc.ServiceStackController.cs** replace:

    public virtual string UnauthorizedRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect() + "?redirect={0}#f=Unauthorized"; }
    }
    
    public virtual ActionResult AuthenticationErrorResult
    {
        get
        {
            var returnUrl = HttpContext.Request.GetPathAndQuery();
            return new RedirectResult(UnauthorizedRedirectUrl.Fmt(returnUrl.UrlEncode()));
        }
    }
    
    public virtual string ForbiddenRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect() + "?redirect={0}#f=Forbidden"; }
    }

With:

    public virtual string UnauthorizedRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect(); }
    }
    
    public virtual ActionResult AuthenticationErrorResult
    {
        get
        {
            var returnUrl = HttpContext.Request.GetPathAndQuery();
    
            var encoded = returnUrl.UrlEncode();
            var unauthorizedRedirectUrl = UnauthorizedRedirectUrl;
    
            if (string.IsNullOrEmpty(unauthorizedRedirectUrl))
            {
                return new HttpUnauthorizedResult();
            }
    
            var formatted = unauthorizedRedirectUrl.Fmt(encoded);
            return new RedirectResult(formatted);
        }
    }
    
    public virtual string ForbiddenRedirectUrl
    {
        get { return HostContext.GetPlugin<AuthFeature>().GetHtmlRedirect(); }
    }

That seemed to resolve the issue. When setting HtmlRedirect to null, I get a 401 when not authenticated, and a 302 when it is not null and I am not authenticated. When I am authenticated, I get a 200 response.

I can put together a pull request if you like, but I was unsure about other, knock-on, effects so thought I would just raise an issue instead.

Thanks

**Comment by mythz** [comment]
Hi, yeah this looks like a good change, a PR for this would be very welcomed, thx.

Just a cautionary note, (in-case it isn't) that the `IAuthSession` instance needs to be a new instance everytime:

```csharp
Plugins.Add(new AuthFeature(ObjectFactory.GetInstance<IAuthSession>, ..);
```

I've seen a few people using IOC's for creating `AuthUserSession` instances get bitten by this.

**Comment by bumblebeeman** [comment]
No worries, will sort that in the morning

**Comment by bumblebeeman** [comment]
And thanks for the hint regarding *IAuthSession*, will keep that in mind!

**Comment by bumblebeeman** [comment]
Pull request has been added

**Comment by bumblebeeman** [comment]
I see this has been merged, cool, ok if I close?

**Comment by mythz** [comment]
yep, thx.
