### ISSUE TITLE
Xamarin.Mac needs its own PCL export provider

### ISSUE THREAD

**Issue by colbylwilliams** [ServiceStack/Issues#367]
Related discussion [here](http://stackoverflow.com/questions/28725867/servicestack-client-on-xamarin-mac-not-ios)

To recap the comment there a bit:

The suggestion in the answer there to use the the IosPclExportClient appears to work in 'debug' mode.  However, when you build for release or enable SDK linking directly in the build settings, the compiler will link away (remove) the Xamarin.iOS assembly that the IosPclExportClient depends on, resulting in the following compile error:

>Error MM2002: Failed to resolve assembly: 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065' (MM2002)

So it would seem that Xamarin.Mac requires its own PCL export client with a reference to Xamarin.Mac rather than Xamarin.iOS.

I see there is a ServiceStack.Pcl.Mac20 project in the SS repo & Xamarin solution - is this something that's already being rectified for a future release?

**Comment by mythz** [comment]
I've not had success with enabling SDK Linking in ServiceStack.Text, I just imagined it couldn't handle assemblies that use reflection where it can't statically determine which code is referenced. So is this issue really 'Debug' mode or just SDK linking? i.e. does it work in 'Release' mode with SDK Linking disabled?

I can add an explicit PclExport for Mac referencing Xamarin.Mac but I don't expect this will fix SDK linking  issues.

**Comment by mythz** [comment]
> I see there is a ServiceStack.Pcl.Mac20 project in the SS repo & Xamarin solution - is this something that's already being rectified for a future release?

This hasn't changed in a few releases which is already in the ServiceStack.Client NuGet package - you can download and unzip the [ServiceStack.Client NuGet package](https://www.nuget.org/api/v2/package/ServiceStack.Client/4.0.46) to see the existing dlls. It uses Xamarin.iOS Unified API which I thought could be used for both iOS and Mac - I can make it explicitly reference Xamarin.Mac to see if it helps.

**Comment by colbylwilliams** [comment]
> I've not had success with enabling SDK Linking in ServiceStack.Text, I just imagined it couldn't handle assemblies that use reflection where it can't statically determine which code is referenced. So is this issue really 'Debug' mode or just SDK linking? i.e. does it work in 'Release' mode with SDK Linking disabled?

Xamarin has three different linking options; `Don't Link`, `Link SDK Assemblies Only`, and `Link All Assemblies.`  `Link SDK Assemblies` only links Xamarin's stuff (actually changing it to `Link Framework Assemblies Only` now), and that's where I'm running into trouble.  `Link All` is likely where you ran into issues with ServiceStack.Text.  I've used ServiceStack.Text in several Xamarin.iOS apps using the `Link SDK Assemblies Only` option, and it worked great.

> It uses Xamarin.iOS Unified API which I thought could be used for both iOS and Mac - I can make it explicitly reference Xamarin.Mac to see if it helps.

Yes, that should do the trick.  If it'd help, you can send me a version with the update and I'll test.

**Comment by mythz** [comment]
Hi, I've modified the Mac20 project to have an explicit reference to Xamarin.Mac and have created an explicit PCL Export for the Mac client which can be registered with:

```csharp
static class MainClass
{
	static void Main(string[] args)
	{
		ServiceStack.MacPclExportClient.Configure();

		NSApplication.Init();
		NSApplication.Main(args);
	}
}
```

I've tested this with the new [PclTest.Mac](https://github.com/ServiceStack/ServiceStack/tree/master/tests/PclTest.Mac) project which references the .dlls directly. This project is in the **ServiceStack.Pcl.Xamarin.sln** in [ServiceStack/src](https://github.com/ServiceStack/ServiceStack/tree/master/src) if you want an example project to run.

This change is available from the v4.047 pre-release NuGet builds which are [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

It would be great if you can confirm if the issue is resolved on your end as well.

**Comment by colbylwilliams** [comment]
Confirmed!  v4.0.47 pre-release NuGet build from your MyGet works perfectly.  I really appreciate the quick turnaround.

**Comment by mythz** [comment]
Sweet glad to hear it! thx for your guidance with this :+1:
