### ISSUE TITLE
Calls to Redis BlockingPopFromList are raising a socket exception and invoking the retry

### ISSUE THREAD

**Issue by fuzzycactus** [ServiceStack/Issues#368]
When issuing a call to a blocking pop it does not appear to respect the timeout value passed and instead raises a socket send/receive exception that in turn invokes the retry mechanism - when the list is empty.  I created a small test app that should repro the steps - when using timeout = null the socket exception is raised immediately.

I suspect it might be related to Redis clearing the list's key when empty.  The exception that is displayed is logged, but handled in the RedisClient SendReceive method.

[repro test app](https://github.com/fuzzycactus/redistestapp)

Sample code block:
```
// add items to list
for (int i = 1; i <= 10; i++)
{
	redis.PushItemToList("mylist", "item {0}".Fmt(i));
}

do
{
	var item = redis.BlockingPopItemFromList("mylist", null);

	// log the popped item.  if BRPOP timeout is null and list empty, 
        // I do not expect to print anything
	LogManager.LogFactory.GetLogger("redistest").InfoFormat("{0}", item.IsNullOrEmpty() ? " list empty " : item);

	System.Threading.Thread.Sleep(1000);

} while (DateTime.Now - startedAt < TimeSpan.FromSeconds(30));
```

**Comment by mythz** [comment]
Did you know that you're [specifying a Receive Timeout](https://github.com/fuzzycactus/redistestapp/blob/master/Program.cs#L28)? 

Which will throw a Socket Exception if the client doesn't receive anything from the elapsed time.

Did you add this to force an exception? If so what issue did you want it to highlight?

**Comment by fuzzycactus** [comment]
Couple things happening here ...
a) I wrongly assumed that a blocking call, designed to block, would supersede the receive timeout, since the value is explicitly passed as a parameter.

b) I blew past the fact that the default was -1, indefinite, rather than a fixed duration.

You are correct that by moving to -1 the issue is not present.  This implies however, that if the application uses a blocking call with timeout 0, a receive timeout could not be used as the base config.  Unless there is a way to scope it à la JsConfig with a using block?

**Comment by mythz** [comment]
No the ReceiveTimeout is tied to the underlying TCP socket connection and not something that can be replaced adhoc at runtime. You would need to create a new RedisClient connection with the settings you want for that connection.

**Comment by fuzzycactus** [comment]
Answers my issue, thank you.
