### ISSUE TITLE
Swagger integration behind a load balancer (custom private port) is problematic

### ISSUE THREAD

**Issue by jpasichnyk** [ServiceStack/Issues#369]
We run our ServiceStack processes on a custom private port (not 80/443) behind a public IP:443 hosted by a load-balancer, as quite a few people do.  When a request comes into a given host in this setup, the host thinks its running on the private port, instead of the public port.

For some things, we're able to override (based on previous suggestion) ResolveAbsoluteUrl() to get the behavior of dropping any non-standard ports when we want to, however the Swagger integration seems to resolve the hosted path based on HostConfig.WebHostUrl which is obviously set on startup (not per request).  This sort of works for us, as we can still set the expected hosted url in our publish profile and load that as WebHostUrl on startup.  This lets swagger load fine for us, however it makes it hard to test calls to individual backend machines via their private ports if needed.

Would it make sense to use ResolveAbsoluteUrl() @ https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Api.Swagger/SwaggerResourcesService.cs#L73 instead, so the path can more easily be overridden at request time?  I believe this would also remove the need for any publish time settings and make for more simple xcopy deploys.

**Comment by mythz** [comment]
hmm strange that this path resolution code lasted this long :) it existed before `ResolveBaseUrl()` which I've now updated in this commit: https://github.com/ServiceStack/ServiceStack/commit/c646209ea270bd4fd18bd20df9f39ddbe69555a8

Just tested this with a hosting at a / root path and /custom path so should be a safe change. Let me know if you have issues with it.

This change is available from v4.0.47 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by jpasichnyk** [comment]
@mythz thanks man.  we aren't hosting on a custom path, but port, but should probably have the same effect.  Let me test and i'll let you know.
