### ISSUE TITLE
Tasks should not be started without specifying the TaskScheduler

### ISSUE THREAD

**Issue by mayerwin** [ServiceStack/Issues#370]
I am encountering a lot of freezing/hanging bugs ([see for example question on StackOverflow here](http://stackoverflow.com/questions/33376945/hanging-on-thread-startinternal-when-handling-a-servicestack-request), but also right now requests are queued to the `TaskScheduler` as `WaitingToRun` but never processed for an unknown reason) that seem to be related to threading.

I have not yet figured it out, but I noticed while checking ServiceStack's source code that you are sometimes starting tasks without specifying an explicit TaskScheduler (for by creating a `Task` and then calling `Start()`, or by calling `StartNew()` to create and run it). For example in `HttpAsyncTaskHandler.cs`:

    public virtual Task ProcessRequestAsync(IRequest httpReq, IResponse httpRes, string operationName)
    {
      Task processRequestTask = this.CreateProcessRequestTask(httpReq, httpRes, operationName);
      processRequestTask.Start();
      return processRequestTask;
    }

As you may know, this will cause the task to be started using the current `TaskScheduler`, which may or may not be `TaskScheduler.Default`.
Some reading here:
http://blog.stephencleary.com/2013/08/startnew-is-dangerous.html
http://stackoverflow.com/questions/6800705/why-is-taskscheduler-current-the-default-taskscheduler

To avoid any hard to debug issues, it seems relevant to either call `Task.Run`, or always specify `TaskScheduler.Default` (which will use the default threadpool).

**Comment by mythz** [comment]
np, now specifying to use explicit TaskScheduler.Default in this commit: https://github.com/ServiceStack/ServiceStack/commit/280198a83cbf2efb27cd2620ddfbc02c1cca19cd

This change is available from v4.0.47 that's [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by mayerwin** [comment]
Thanks for the fast turnaround. Maybe all usages of `Start()` and `Task.Factory.StartNew` across the projects should be checked to ensure explicit TaskScheduler.Default is used? For example in AsyncUtils.cs.

**Comment by mythz** [comment]
Yeah I did a find all references before but it didn't find anything, searching on StartNew returned a couple of places which is now updated: 
https://github.com/ServiceStack/ServiceStack/commit/862e2fae07a74298665e4ba804738bbf2337e2ae
