### ISSUE TITLE
StaticFileHandler should return Status Code 304 Not Modified

### ISSUE THREAD

**Issue by jklemmack** [ServiceStack/Issues#371]
Minor issue, but the StaticFileHandler returns `304 OK`, not `304 Not Modified`.  While the code seems to be honored by browsers, it'd be nice to line up the status text with the status code.

https://github.com/ServiceStack/ServiceStack/blob/862e2fae07a74298665e4ba804738bbf2337e2ae/src/ServiceStack/Host/Handlers/StaticFileHandler.cs#L148

![image](https://cloud.githubusercontent.com/assets/1782307/11045329/c6f1d4ec-86db-11e5-91ef-2de175a11120.png)

**Comment by mythz** [comment]
Good catch, updated in this commit: https://github.com/ServiceStack/ServiceStack/commit/50ca9e1cf0c647ff524d0abe65ede50dec97bff1
