### ISSUE TITLE
Java types incorrectly skipping a reused class when related class exlcuded

### ISSUE THREAD

**Issue by Layoric** [ServiceStack/Issues#373]
Reproduction steps.

Create SomeClass class
Create Class1 class (request) that implements IReturn<SomeClass>
Create Class2 class (request) that has a property of type SomeClass
Implement the service as usual
Exclude the Class1 using the option ExcludeTypes
The generated code will only include Class2 with a property of type SomeClass but the SomeClass will not be present in the file. I was able to reproduce this problem with the Swift generator as well.

``` csharp
public class Class1 : IReturn<SomeClass>
{
}

public class Class2 : IReturn<string>
{
    public SomeClass Classy { get; set; }
}

public class SomeClass
{
    public string SomeValue { get; set; }
}

public class MyServices : Service
{
    public object Any(Hello request)
    {
        return new HelloResponse { Result = "Hello, {0}!".Fmt(request.Name) };
    }

    public SomeClass Any(Class1 request)
    {
        return new SomeClass();
    }
    public String Any(Class2 request)
    {
        return "Hello!";
    }
}
```
Request types from `baseurl/types/java?ExcludeTypes=Class1`.

``` java
public class dto
{

    @Route("/hello/{Name}")
    public static class Hello implements IReturn<HelloResponse>
    {
        public String Name = null;
        
        public String getName() { return Name; }
        public Hello setName(String value) { this.Name = value; return this; }
        private static Object responseType = HelloResponse.class;
        public Object getResponseType() { return responseType; }
    }

    public static class Class2 implements IReturn<String>
    {
        public SomeClass Classy = null;
        
        public SomeClass getClassy() { return Classy; }
        public Class2 setClassy(SomeClass value) { this.Classy = value; return this; }
        private static Object responseType = String.class;
        public Object getResponseType() { return responseType; }
    }

    public static class HelloResponse
    {
        public String Result = null;
        
        public String getResult() { return Result; }
        public HelloResponse setResult(String value) { this.Result = value; return this; }
    }

}
```

SomeClass is referenced by Class2 but result does not have a definition for `SomeClass`.

**Comment by mythz** [comment]
This issue is because `SomeClass` is defined as a Response Type due to `IReturn<SomeClass>` marker which supersedes its re-declaration as a normal Type. So once the `Class1` Operation is excluded it also removes its Response Type definition and because there are no other Response Types left containing `SomeClass`, it's no longer emitted. This corner case is a limitation of the current implementation so wont be fixed.
