### ISSUE TITLE
exception when using ormlite Insert within a transaction

### ISSUE THREAD

**Issue by mdissel** [ServiceStack/Issues#374]
Servicestack v 4.0.46.0, SQL Server 2012

runnnig this code will raise an exception that the transaction for the executescalar command is not valid.

```
factory = new OrmLiteConnectionFactory(System.Configuration.ConfigurationManager.ConnectionStrings["Test"].ConnectionString, SqlServer2012Dialect.Provider);
using (IDbConnection connection = factory.OpenDbConnection())
{
                using (IDbTransaction transaction = connection.BeginTransaction())
                {
                    long id = connection.Insert(new LookupItem { Code = "Code" }, true);
                    transaction.Commit();
                }
 }
```

will raise an exception:
Result Message:	System.InvalidOperationException : Voor ExecuteScalar is vereist dat de opdracht een transactie bevat als de verbinding die is toegewezen aan de opdracht bezig is met een wachtende lokale transactie.  De eigenschap Transaction van de opdracht is niet geïnitialiseerd.

bij System.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
   bij System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   bij System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   bij System.Data.SqlClient.SqlCommand.ExecuteScalar()
   bij ServiceStack.OrmLite.OrmLiteCommand.ExecuteScalar()
   bij ServiceStack.OrmLite.OrmLiteDialectProviderBase`1.InsertAndGetLastInsertId[T](IDbCommand dbCmd)
   bij ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Insert[T](IDbCommand dbCmd, T obj, Boolean selectIdentity)
   bij ServiceStack.OrmLite.OrmLiteWriteApi.<>c__DisplayClass4`1.<Insert>b__3(IDbCommand dbCmd)
   bij ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
   bij ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Exec[T](IDbConnection dbConn, Func`2 filter)
   bij ServiceStack.OrmLite.OrmLiteWriteApi.Insert[T](IDbConnection dbConn, T obj, Boolean selectIdentity)
   bij Test.Db.TLookupItem.TestMethod() in

**Comment by mythz** [comment]
You need to use [OpenTransaction](https://github.com/ServiceStack/ServiceStack.OrmLite#transaction-support) to have the transaction attached to the executed command.
