### ISSUE TITLE
ServiceStack Mvc unsigned assembly forces Signed assemblies to download (v4.0.48)

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#376]
When launching "install-package ServiceStack.Mvc" to update on latest version (4.0.48)

I have the following nuget package manager console output

<pre>
PM> install-Package ServiceStack.Mvc
Attempting to gather dependencies information for package 'ServiceStack.Mvc.4.0.48' with respect to project 'Presentation\Ksm.Gecko.Gui.WebMvc', targeting '.NETFramework,Version=v4.5'
Attempting to resolve dependencies for package 'ServiceStack.Mvc.4.0.48' with DependencyBehavior 'Lowest'
Resolving actions to install package 'ServiceStack.Mvc.4.0.48'
Resolved actions to install package 'ServiceStack.Mvc.4.0.48'
Adding package 'ServiceStack.Text.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Text.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Text.Signed.4.0.48' to 'packages.config'
Successfully installed 'ServiceStack.Text.Signed 4.0.48' to Ksm.Gecko.Gui.WebMvc
Adding package 'ServiceStack.Client.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Client.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Client.Signed.4.0.48' to 'packages.config'
Successfully installed 'ServiceStack.Client.Signed 4.0.48' to Ksm.Gecko.Gui.WebMvc
Adding package 'ServiceStack.Common.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Common.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Common.Signed.4.0.48' to 'packages.config'
Successfully installed 'ServiceStack.Common.Signed 4.0.48' to Ksm.Gecko.Gui.WebMvc
Adding package 'ServiceStack.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Signed.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Signed.4.0.48' to 'packages.config'
Successfully installed 'ServiceStack.Signed 4.0.48' to Ksm.Gecko.Gui.WebMvc
Adding package 'ServiceStack.Mvc.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Mvc.4.0.48' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Mvc.4.0.48' to 'packages.config'
Successfully installed 'ServiceStack.Mvc 4.0.48' to Ksm.Gecko.Gui.WebMvc
</pre>

I don't want to use signed assemblies.
Is it the expected behavior?

**Comment by mythz** [comment]
Unfortunately this is an issue that was only discovered [after v4.0.48 was released](https://github.com/ServiceStack/ServiceStack/blob/master/docs/2015/release-notes.md#v4048-issues), it's fixed from v4.0.49 on [MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by labilbe** [comment]
Ok thank you.
