### ISSUE TITLE
ServiceStackController typed Execute fails to handle errors

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStack/Issues#378]
The typed ServiceStackController.Execute method (https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Mvc/ServiceStackController.cs#L226) doesn't seem to be handling service errors correctly. Everything is fine when the service returns the correct type, but when the service throws an exception the cast to the service response type fails. It ends with a InvalidCastException, in my case "Unable to cast object of type 'ServiceStack.HttpError' to type 'Orca.ServiceModel.AddNoteResponse."

I'm not sure if the intended behaviour should be to bubble up the original exception or to return the response DTO with the ResponseStatus set.

**Comment by mythz** [comment]
I've updated it to throw if it returns an Exception [in this commit](https://github.com/ServiceStack/ServiceStack/commit/4bc440626e7ee15d9749b97574f8e586f1df3510).

I didn't want it to have different behavior so now all Execute() methods throw returned exceptions.

This change is available from v4.0.49 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)

**Comment by georgehemmings** [comment]
Thanks again
