### ISSUE TITLE
CSV and JSV shown when disabled

### ISSUE THREAD

**Issue by DanielMunch** [ServiceStack/Issues#380]
I made sure Feature.JSV and Feature.CSV are not enabled in EnabledFeatures - AppHost.cs

Despite this, servicestack service default page: "Snapshot of *** generated by ServiceStack" still lists csv and jsv as available formats. ( view json datasource from original url: http:/*** in other formats: json xml csv jsv

Is this intended?

**Comment by mythz** [comment]
Yeah they're hard coded links in the static [HtmlFormat.html](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Templates/HtmlFormat.html#L244-L245) page.

You can use your [own local modified copy of HtmlFormat.html](https://github.com/ServiceStack/ServiceStack/wiki/Metadata-page#updating-html-and-metadata-page-templates) instead by keeping a local copy at `/Templates/HtmlFormat.html`
