### ISSUE TITLE
DTO generato leaves of @ on multi line strings

### ISSUE THREAD

**Issue by jcp-xx** [ServiceStack/Issues#395]
We are having issues updating our reference to a vendors ServiceStack services because multi line strings do not include the @ sign on the string

I see it was issue #364 and the vendor say they cant fix it

Is this an issue that needs to be fixed on the client side or service side(by the vendor)

can you provide details on how to correct this.

**Comment by mythz** [comment]
Hi, I thought this issue should already be resolved.

Can you make sure your vendor is using the latest version, if so please provide the C# DTO causing the issue as well as the generated DTO that has the issue.

**Comment by jcp-xx** [comment]
Vendor is refusing to upgrade.  That why I wanted to know if it was a client side or service side issue.
How difficult is it for the vendor to upgrade?

**Comment by mythz** [comment]
It's a server-side issue as the DTO's are generated on the server at these urls: https://github.com/ServiceStack/ServiceStack/wiki/Add-ServiceStack-Reference#how-it-works

They will need to either upgrade or not use multi-line strings.
