### ISSUE TITLE
Redis Transaction has return method for Sets (HashSet<string>) interface unimplemented

### ISSUE THREAD

**Issue by Stephen3443** [ServiceStack/Issues#396]
The problem is the ServiceStack.Redis.Pipeline.IRedisQueueableOperation (transaction) does not currently have a method to return a HashSet<string> even though there is a method on the ServiceStack.Redis.IRedisClient to return all items in a set.

For example, the following does not work because GetAllItemsFromSet returns a HashSet<string> and the interface does not currently allow for that very common return type used by sets.

HashSet<string> values = null;
using (var transaction = redis.CreateTransaction())
{
     transaction.QueueCommand(command => command.GetAllItemsFromSet("example"), result => values = result);
}

Please update the interface soon or provide a work around we can use now inside a transaction. Our system urgently needs this feature.

**Comment by mythz** [comment]
The missing HashSet Transaction API's should now be added in this commit: https://github.com/ServiceStack/ServiceStack.Redis/commit/d6ed687a1f25cec0f43fb04e3c906905b5c99085

This change is available from v4.0.53 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)
