### ISSUE TITLE
Breaking change IgnoreAttribute

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#400]
Upon switching from SS 4.0.40 to 4.0.52, IgnoreAttribute behaves differently.

```
public class Test
{
    [Ignore]
    public string A { get; set; }
}

...

using (var conn = dbFactory.OpenDbConnection())
{
    var result = conn.Select<Test>("select 'a' A");
}
```

In 4.0.40, Test.A would be populated, but it's not populated in 4.0.52.

I can see `ServiceStack.Text.JsConfig.IgnoreAttributesNamed`, but it doesn't contain `IgnoreAttribute` as a value.

I don't see this change documented in the release notes.

**Comment by mythz** [comment]
`[Ignore]` is only for ignoring columns in OrmLite, use `[IgnoreDataMember]` for ignoring properties in text serializers.

**Comment by mjdaly** [comment]
The problem is that text serialisers now have some dependency on `[Ignore]` where previously they did not.

I've tested the above code with 4.0.40 and 4.0.52, when the ServiceStack.Text dll changes version, so does behavior.

We have POCO's with `[Ignore]` attributes on properties so they don't create columns in the db when we use Ormlite to create tables.

We also have SQL queries like the above, which work correctly on 4.0.40 i.e. data is deserialised into properties, even if they had the `[Ignore]' attribute. Your reply states that 4.0.40 behaviour should happen because text serialisers are not supposed to use the `[Ignore]' attribute.

**Comment by mythz** [comment]
> The problem is that text serialisers now have some dependency on [Ignore] where previously they did not.

Where do text serialisers have a dependency on [Ignore]?

**Comment by mythz** [comment]
Can you provide a failing test that shows this?

**Comment by mjdaly** [comment]
Solution attached with two projects referencing different SS versions.

I've removed the connection string I was using to test with MySQL.

[TestSS.zip](https://github.com/ServiceStack/Issues/files/117909/TestSS.zip)

**Comment by mythz** [comment]
This doesn't have anything to do with the text serializer, this is OrmLite respecting the `[Ignore]` attribute which you can see by viewing the dto returned:

```csharp
var dto = conn.Select<Test>("select 'a' A");
dto.PrintDump();
```

**Comment by mjdaly** [comment]
Can you see the change in behavior between Ormlite respecting `[Ignore]` by not creating columns in the db vs not creating columns in the db **_and additionally_** not deserialising those columns?

By the sound of this, there is no flag for the behavior change, we will just have to re-code?

**Comment by mythz** [comment]
`[Ignore]` tells OrmLite to ignore the property, `[IgnoreDataMember]` tells the text serializers to. There's no flag to change this behavior.

**Comment by mjdaly** [comment]
Now I'm unsure if you actually verified and understand the problem, as you have not acknowledged that there is a change in behavior.

In the example, it's the difference between getting `[{"A":"a"}]` (4.0.40) and `[{}]` (4.0.52).

Can you acknowledge that there is a change and I'll move on to searching for code that needs to be refactored?

**Comment by mythz** [comment]
This is a feature added to OrmLite to ignore properties with `[Ignore]` attribute.

**Comment by mjdaly** [comment]
I know mythz, but it's odd how the behavior changed between versions without a mention in the release notes and there is no acknowledgement from you that it actually happened, even when I ask you directly. 

This thread could go on forever, but I'm loving it :-)

**Comment by mythz** [comment]
This is the documented and expected behavior for both attributes, I don't know what undocumented behavior you were using this for before, but this is now working as intended.

**Comment by mjdaly** [comment]
Example of the _undocumented behavior_ is above. 

Complaining that what we were doing was _undocumented_, is disingenuous, expectations are set by behavior and documentation, additionally, the documentation that exists is good, concise, it is not complete.

It's all good.

**Comment by mythz** [comment]
Sorry, what exactly are you labeling disingenuous? You were using the `[Ignore]` attribute for something other than ignoring properties in OrmLite - which is its intended purpose, I don't ever recall documenting/recommending it doing something other than this. The behavior now is working as intended, if it was different before the functionality hadn't been implemented or a bug was resolved.

**Comment by mjdaly** [comment]
There is a very terse description of the `[Ignore]` attribute, the entire scope of the intended purpose is not clear. It previously behaved in a way that could be seen as correct. Now it behaves in a different way that is apparently _more_ correct.

Saying our usage was undocumented comes across as arbitrary.
