### ISSUE TITLE
AsyncServiceClient does not close response stream correctly on UWP

### ISSUE THREAD

**Issue by GuillaumeSalles** [ServiceStack/Issues#401]
Hello,

AsyncServiceClient try to flush the response stream on UWP, but this operation is not supported on System.Net.Http.StreamContent.ReadOnlyStream.

https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/AsyncServiceClient.cs#L451

Tell me if you want more info about this issue.

Thanks a lot for your support.

**Comment by mythz** [comment]
I've moved the impl-specific behavior for this from ServiceStack.Client out into to the platform-specific projects in this commit: https://github.com/ServiceStack/ServiceStack/commit/c86ca7f2780438c47d829e4dff13300669b52929

This change should use the right behavior for WinStore / UWP apps which is available from v4.0.53 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Let me know if this resolves the issue?

**Comment by GuillaumeSalles** [comment]
Everything seems fine ! Thanks a lot for your efficiency.
