### ISSUE TITLE
Redis Timeout expired

### ISSUE THREAD

**Issue by sdevvathi** [ServiceStack/Issues#402]
Hi,

We are getting the  below error after moving to "AZURE REDIS CACHE".
Error:Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use

1. Below is the class we are using for connection pooling. 
    We've a limit  of  2000  connections but we can see max of 40 connected clients.

2. What are the ideal values for 'ConnectTimeout, PoolTimeOut'.

public class CustomRedisPooledClient
    {
        private static CustomRedisPooledClient _instance = null;
        public PooledRedisClientManager poolredisClient = null;

        string redisConn = ConfigurationManager.AppSettings["RedisClient"].ToString();

        // Objeto sincronización para hacer el Lock 
        private static object syncLock = new object();

        private CustomRedisPooledClient()
        {
            poolredisClient = new PooledRedisClientManager(redisConn);
        }

        public static CustomRedisPooledClient GetPooledClient()
        {
            if (_instance == null)
            {
                lock (syncLock)
                {
                    if (_instance == null)
                    {
                        _instance = new CustomRedisPooledClient();
                        //_instance.poolredisClient.ConnectTimeout = 6000;
                        //_instance.poolredisClient.PoolTimeout = 6000;
                    }
                }
            }
            return _instance;
        }
    }

Regards,
Suresh

**Comment by mythz** [comment]
Please see the documentation on [Redis Client Managers](https://github.com/ServiceStack/ServiceStack.Redis#redis-client-managers) which is thread-safe and should only be used as a **singleton** so you don't need to add any locks to resolve a client, so you could just have:

```csharp
static PooledRedisManager = new PooledRedisClientManager(redisConn);
```

But the most important part is that wherever you resolve the client it **must be disposed after use**, returning it to the pool, as-is typically with a using statement, e.g:

```csharp
using (var redis = PooledRedisManager.GetClient())
{
   //.. use Redis Client
}
```

There's no optimal configuration for all environments, I'd start with the defaults first, then if needed tweak settings to see what's optimal for your environment. For better insight have a look at the Redis Manager Stats:

```csharp
PooledRedisManager.GetStats().PrintDump();
```

Or the global [Redis Stats](https://github.com/ServiceStack/ServiceStack.Redis/wiki/Redis-Stats):

```csharp
RedisStats.ToDictionary().PrintDump();
```

**Comment by Appjunkie** [comment]
Hello Mythz

Could you please post a code sample which shows how to dispose the client?
The above code was provided by service stack when we contacted them a few months earlier.

Thanks,
Kalyan

**Comment by mythz** [comment]
I just did, you can use a using statement:

```csharp
using (var redis = PooledRedisManager.GetClient())
{
   //.. use Redis Client
}
```

**Comment by mythz** [comment]
I've had a look at the support history, and I've actually repeated exactly what I've told you here, emphasizing PooledRedisClientManager is thread-safe, should be a singleton and the Redis Client should be disposed after use, the entire email response:

```
The RedisClient manager (i.e. PooledRedisClientManager) is thread-safe so you don't need any locks when resolving a client from it.
But the resolved RedisClient instance is not thread-safe (as per .NET instance conventions), so it should be resolved and released within the same method. 

_instance = new PooledRedisClientManager(...); //singleton

As the Redis Pool is thread-safe you don't need locks to resolve a Redis Client instance so you can just do:

//release and resolve a RedisClient instance after usage
using (var client = _instance.GetClient())
{
   //….
}
```

The source code you posted above was entirely your own.

**Comment by sdevvathi** [comment]
Mythz,

Thanks for the update. Removed the lock as per the suggestion. 
In the code already implemented the  using() but still we are getting the error.
Note: The error coming in 'Azure Redis cache' only and not in on Premise storage.

Please see the snippet of code as below and suggest where we need to correct the code to fix the issue.
----------------------------------------------------------------------------------------------------
using (var client = customRedisPooledClient.poolredisClient.GetClient())
 {
      string cntSetId = "hitcount." + mobilenumber;
      hitCount = client.Get<byte[]>(cntSetId);
      if (hitCount != null)
      {
             hitcnt = Convert.ToInt32(System.Text.Encoding.UTF8.GetString(hitCount));
       }
 }
      ----------------------------------------------------------------------------------
public class CustomRedisPooledClient
    {
        private static CustomRedisPooledClient _instance = null;
        public PooledRedisClientManager poolredisClient = null;
        string redisConn = ConfigurationManager.AppSettings["RedisClient"].ToString();

        private CustomRedisPooledClient()
        {
            poolredisClient = new PooledRedisClientManager(redisConn);
        }

        public static CustomRedisPooledClient GetPooledClient()
        {
            if (_instance == null)
            {
                _instance = new CustomRedisPooledClient();
             }
            return _instance;
        }
    }

**Comment by mythz** [comment]
This code should work but I've no idea why you're not just exposing the static PooledRedisClientManager  instance, instead of hiding it behind a wrapper. Note `CustomRedisPooledClient` seems inappropriately named, it's not a custom client, it's just a wrapper.

Although my preference is to use an IOC, you could do the same thing with a lot less code with just:

```csharp
public class GlobalManagers
{
    public static readonly PooledRedisClientManager RedisManager
        = new PooledRedisClientManager(ConfigUtils.GetAppSetting("RedisClient"));
}
```

Then your code is just:

```csharp
using (var client = GlobalManagers.RedisManager.GetClient())
{
    string cntSetId = "hitcount." + mobilenumber;
    hitCount = client.Get<byte[]>(cntSetId);
    if (hitCount != null)
    {
        hitcnt = Convert.ToInt32(System.Text.Encoding.UTF8.GetString(hitCount));
    }
}
```

Whilst this shows the correct usage, you need to make sure that **all code that uses redis** is used within a using statement like this or is otherwise properly disposed. You can check the Redis Stats provided above to see if there are any connection leaks.

Also note any connectivity issues with Hosting Redis on Azure is an issue with hosting on Azure, i.e. if the Redis Client can't make a tcp connection the only thing it can do is throw (after retrying until `RedisConfig.DefaultRetryTimeout`).
