### ISSUE TITLE
Running Servicestack inside a Docker Container

### ISSUE THREAD

**Issue by smlsrtencara** [ServiceStack/Issues#403]
I am having issues running Servicestack inside a Docker Container, no it may be something simple, but I can not seem to get it tracked down.  This is compiled on a MAC running 4.0.2 MONO, copy the bin/Debug over to CentOS with MONO 4.0.2 on it.

Flags are set for x86 compile on all modules of application.

Unhandled Exception: System.TypeInitializationException: An exception was thrown by the type initializer for ServiceStack.LicenseUtils ---> System.TypeInitializationException: An exception was thrown by the type initializer for ServiceStack.PclExport ---> System.TypeLoadException: Could not load type 'ServiceStack.Net40PclExport' from assembly 'ServiceStack.Text, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43'.
  --- End of inner exception stack trace ---
  at ServiceStack.LicenseUtils..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at ServiceStack.Licensing.RegisterLicense (System.String licenseKeyText) [0x00000] in <filename unknown>:0 
  at TencaraControlServer.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for ServiceStack.LicenseUtils ---> System.TypeInitializationException: An exception was thrown by the type initializer for ServiceStack.PclExport ---> System.TypeLoadException: Could not load type 'ServiceStack.Net40PclExport' from assembly 'ServiceStack.Text, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43'.
  --- End of inner exception stack trace ---
  at ServiceStack.LicenseUtils..cctor () [0x00000] in <filename unknown>:0 
  --- End of inner exception stack trace ---
  at ServiceStack.Licensing.RegisterLicense (System.String licenseKeyText) [0x00000] in <filename unknown>:0 
  at TencaraControlServer.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by mythz** [comment]
Can you please provide the steps to repro? basically starting from scratch.

**Comment by smlsrtencara** [comment]
This happens on a generic Linux Install as well (NO DOCKER)

Install a a CentOS 7.2 System (latest and greatest)

yum -y install epel-release

cd /etc/yum.repos.d
wget -q "https://copr.fedoraproject.org/coprs/tpokorra/mono-opt/repo/epel-7/tpokorra-mono-opt-epel-7.repo" 

yum update

sudo yum install -y mono-addins mono-basic-opt mono-opt mono-data-sqlite mod_mono-opt 

#if you want IDE too, monodevelop-opt 

nano/vi or a /etc/ld.so.conf.d/mono.conf
--- containing:  /usr/lib/mono

sudo chown root:root /etc/ld.so.conf.d/mono.conf
sudo ldconfig

At this point you have a functioning CENTOS 7.2 with MONO system

No create any Servicestack solution with:

References:
Servicestack, .common, .interfaces, .client, ormlite, ormlite.sqlite, ormlite mysql, .redis and .text

in main add 1 line to REGISTER your code:

"Servicestack.Register.License....."

Compile

Open a shell window

goto the bin/Debug:

mono Programname.exe

You will get the error.

I just did these exact steps on a virgin system, and reproduced immediately

Servicestack Version 4.0.52.0

Only thing odd I see - is all my DLL are 4.0.52.0 EXCEPT Interface dll, that is 4.0.0.0

NuGet doesnt update it nor can I see where there is a 4.0.52.0 Interface version.

Let me know if you need more info

**Comment by smlsrtencara** [comment]
Initial bug reported running 4.0.0.0, then I tried updating to see if that fixed it, is now why I am at 4.0.52.0

**Comment by smlsrtencara** [comment]
I think I may have found the issue.... mono 2.x is in /usr/ where as mono 4.x is in /opt/mono/bin

let me do some testing before you go crazy...

**Comment by smlsrtencara** [comment]
That was completely it, working late hours will get you sometimes !!! Apologize for that, will mark closed - user error

**Comment by mythz** [comment]
Ok great glad it's sorted
