### ISSUE TITLE
ResponseFilter not called for some requests

### ISSUE THREAD

**Issue by Leonidnei** [ServiceStack/Issues#404]
We defined request and response filters for some service class. Request filter is always called while response filter is called for some methods but not for others. The difference is that "good" method returns defined response class while "bad" method returns object got from ToOptimizedResult.

Is this planned behavior?

I added global response filter as a temporary bypass, but I prefer to use normal response filter attribute for invoking the filter.

**Comment by mythz** [comment]
`ToOptimizedResult()` doesn't just return the response DTO, on subsequent requests when retrieved from the Cache it returns a `CompressedResult` which encapsulates serialized compressed bytes.

If you're referring to different behavior you'll need to provide a complete example of the Service and Response Filter implementation that we can use to repro and identify the issue.
