### ISSUE TITLE
SqliteDateTimeConverter - not preserving UTC dates correctly

### ISSUE THREAD

**Issue by brentby** [ServiceStack/Issues#405]
The SqliteDateTimeConverter doesn't appear to preserve dates correctly when DateStyle is set to Utc (both Local and Unspecified work, however). Hopefully the following illustrates the problem:

```c#
[TestFixtureSetUp]
public void TestFixtureSetUp()
{
    OrmLiteConfig.DialectProvider = new SqliteOrmLiteDialectProvider();
    DateTimeConverter dates = OrmLiteConfig.DialectProvider.GetDateTimeConverter();
    dates.DateStyle = DateTimeKind.Utc;
}

public class User
{
    public int Id { get; set; }

    public DateTime Date { get; set; }
}

[Test]
public void insert_and_select_utc_DateTime()
{
    using (IDbConnection db = ":memory:".OpenDbConnection())
    {
        db.CreateTable<User>(true);

        var utcDate = DateTime.UtcNow;

        db.Insert(new User { Id = 1, Date = utcDate });

        var actual = db.SingleById<User>(1);

        Assert.AreEqual(actual.Date.Kind, DateTimeKind.Utc); // passes
        Assert.AreEqual(actual.Date, utcDate);  // fails, the date is off by the UTC offset
    }
}
```

I've attached the full unit tests (there may be a few other things that are helpful) and have reproduced this problem in both 4.0.50 and 4.0.52, using ServiceStack.Ormlite.Sqlite.Windows.

Thanks!

Brent
[_DateTimeTests.zip](https://github.com/ServiceStack/Issues/files/121990/_DateTimeTests.zip)

**Comment by mythz** [comment]
This test passes when using the default [ServiceStack.OrmLite.Sqlite.Mono](https://www.nuget.org/packages/ServiceStack.OrmLite.Sqlite.Mono) package but fails when using the SQLite ADO.NET Provider in [System.Data.SQLite.Core](https://www.nuget.org/packages/System.Data.SQLite.Core/).

Not sure best way to resolve this, OrmLite assumes the SQLite providers have the same behavior.

**Comment by mythz** [comment]
Ok I've added a new SqliteWindowsDateTimeConverter to handle difference in behavior for System.Data.SQLite.Core in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/9babf36bfb52a833f3343e6dfebacbdc53a6b80e

This change is available from v4.0.53 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by brentby** [comment]
Many thanks, Demis.

An interesting side note from the Mono team, as they seem to recommend storing dates as integers (e.g. Unix epoch time)- http://www.mono-project.com/docs/database-access/providers/sqlite/#storing-datetimes. An integer-based converter might be a bit simpler and more performant - don't know what it would break though.

**Comment by mythz** [comment]
Yeah I like serializing epoch's across the wire, esp. when dealing with different languages/platforms, but they lack readability in a database and would break existing OrmLite sqlite db's making it a non-starter.
