### ISSUE TITLE
Drop Table when using Naming Strategy fails to work 

### ISSUE THREAD

**Issue by smlsrtencara** [ServiceStack/Issues#406]
I have a class:  Inventory

When using ORM I use a default naming strategy (all lowercase)

		public bool CreateFactory()
		{
			bool result = false;
			try {
				factory = new OrmLiteConnectionFactory (connectionString, dbProvider);
				_logger.Debug("Setting Specialized Lowercasing for DB Factory");
				OrmLiteConfig.DialectProvider.NamingStrategy = new Tencara.Common.LowercaseNamingStrategy();
			} catch (Exception ex) {
				_logger.Error (ex);
				result = true;
			}
			return result;
		}

When attempting to drop or drop and create a table, the drop is failing:

SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name = 'Inventory'

As you can see its check does not honor the naming strategy when looking for the table.

I have not checked exists, and such.  I do know CREATE works fine.

Shawn

**Comment by mythz** [comment]
Doesn't seem right, it [does use NamingStrategy](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite.Sqlite/SqliteOrmLiteDialectProviderBase.cs#L134) which is called by [DoesTableExist()](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite.Sqlite/SqliteOrmLiteDialectProviderBase.cs#L155)

```csharp
var sql = "SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name = {0}"
    .SqlFmt(GetTableName(tableName, schema));
```

Why are you not setting the NamingStrategy on the `dbProvider`?

```csharp
factory = new OrmLiteConnectionFactory (connectionString, dbProvider);
dbProvider.NamingStrategy = new Tencara.Common.LowercaseNamingStrategy();
```

Are you using multiple dbProviders?

**Comment by smlsrtencara** [comment]
Yup multiple providers - changing how I opened and set the naming strategy as you suggested fixed it.

Thanks
