### ISSUE TITLE
RestrictAttribute behaving incorrectly on Self Host

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#407]
On a self hosted app, RestrictAttribute has no effect when visibility set as `[Restrict(VisibleInternalOnly = true)]`.

Screenshots below of the same code running on IIS vs Self Host, service accessed via the internet.

**IIS**
![ss_restrict_iis_2016-02-16_2057](https://cloud.githubusercontent.com/assets/2940965/13091091/5b8c1834-d4f1-11e5-8f06-977bf7094b00.png)

**Self Host**
![ss_restrict_selfhost_2016-02-16_2057](https://cloud.githubusercontent.com/assets/2940965/13091092/5b9e319a-d4f1-11e5-9a7a-4166f20e0d37.png)

**Comment by mjdaly** [comment]
**Note**
The services shown are different branches of the same code base, there are some minor differences in routes available i.e. you will see discrepancies in the authentication key images and soap hyperlinks displayed when putting the two images side by side.

Just pointing this out in case you see it and think they are not the same service.

**Comment by mythz** [comment]
I'm assuming you're accessing the self-hosted instance directly and not going through any proxy right? If you are, can you post the `?debug=requestinfo` versions of both IIS and Self Host.

**Comment by mjdaly** [comment]
Access direct, there is no proxy. Both IIS and Self Host are on the same machine, accessed in the same way, the only configuration difference would be that they are bound to different host names so they can run on the same ports.

**Comment by mythz** [comment]
Note: I'm still waiting for the [?debug=requestinfo](https://github.com/ServiceStack/ServiceStack/wiki/Debugging#request-info) responses in order to investigate this. I've also just added some extra debug info that will help identify the issue in the latest [v4.0.53 NuGet packages on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet). 

Can you upgrade to v4.0.53 packages on MyGet and provide the `?debug=requestinfo` JSON responses for both IIS and Self-Hosts.

**Comment by mjdaly** [comment]
Read `?debug=requestinfo` as only relevant if running through a proxy.

Will get that over to you tomorrow.

**Comment by mjdaly** [comment]
Please see debug info linked below (Note: I have not had a chance to update the MyGet packages and deploy onto server). 

Looks like `UserHostAddress` returns the machine network adapter local IP when running under Self Host.

https://drive.google.com/folderview?id=0B5cglv2mrbC7RUxXSENLRHNBQ1U&usp=sharing

Let me know if you still need debug info from the latest MyGet packages.

**Comment by mythz** [comment]
ok thanks for the info, can you try the latest [v4.0.53 on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet) to see if that resolves the issue?

**Comment by mjdaly** [comment]
Issue fixed, thanks for quick turn around, as usual.

**Comment by mythz** [comment]
great happy to hear it!
