### ISSUE TITLE
Add SS Reference Code Generation DefaultAttribute

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#408]
Thought you might want to know about this.

Given the POCO
```
    public class DbTable
    {
        [AutoIncrement]
        public long Id { get; set; }

        [Default(1)]
        public bool SomeBool { get; set; }
    }
```

Add SS Reference will generate this code
```
    public partial class Company
    {
        public virtual long Id { get; set; }

        [Default(DefaultType=typeof(System.Int32), DefaultValue="1")]
        public virtual bool SomeBool { get; set; }
    }
```

This will not compile because DefaultAttribute does not have a parameterless constructor.

**Comment by mythz** [comment]
ok thanks, I've decided to drop the `[Default]` attribute from being emitted [from this commit](https://github.com/ServiceStack/ServiceStack/commit/71a895334724223e5b84a368bd3ef5a58ba3e59d) as it's not an external service concern.

This change is available from v4.0.53 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)
