### ISSUE TITLE
RedisSentinel GetValidSentinelWorker Error

### ISSUE THREAD

**Issue by wworker** [ServiceStack/Issues#410]
A valid sentinel isn't being returned when the sentinel in the list of servers is completely offline.  For example if you have the following list of Sentinel configured for your application in this order:

xxx.xxx.xxx.1
xxx.xxx.xxx.2
xxx.xxx.xxx.3
xxx.xxx.xxx.4

If xxx.xxx.xxx.1 server crashes and cannot be reached via the network there is a bug in the function RedisSentinel::GetValidSentinel.  In the code below when a connection to the first server in the list is made, it throws an exception but when the while look checks to see if it should continue to search for a valid connection it fails, as this.worker is no longer set to null.

```csharp
while (this.worker == null && ShouldRetry())
{
	try
	{
		this.worker = GetNextSentinel();
		GetRedisManager();
		this.worker.BeginListeningForConfigurationChanges();
		this.failures = 0; //reset
		return this.worker;
	}
	catch (RedisException ex)
	{
		if (OnWorkerError != null)
			OnWorkerError(ex);

		lastEx = ex;
		this.failures++;
		Interlocked.Increment(ref RedisState.TotalFailedSentinelWorkers);
	}
}
```

When an exception is thrown this.worker should be reset to null so it will allow the ShouldRetry logic to kick in and the next server in the Sentinel list can be checked and returned when the first sentinel server in the list is offline.

**Comment by mythz** [comment]
Thanks for catching this, worker is now being reset to null from this commit: https://github.com/ServiceStack/ServiceStack.Redis/commit/0042922fb765a46a97fe77a45caa4e406ec65322

This change is available from v4.0.55 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by wworker** [comment]
Thank you for the quick turnaround, what is your release cycle usually on when this will be published to NuGet?

**Comment by mythz** [comment]
We don't have specific dates but release cycles are usually every 4-6 weeks, next one's likely a couple of weeks out at least.
