### ISSUE TITLE
Current sentinel worker dies, the active worker isn't reset

### ISSUE THREAD

**Issue by wworker** [ServiceStack/Issues#411]
This is a continuation of the previous bug #410.  The fix there resolves the issue with the startup of the app, and this now has to do with the app already running and a sentinel dies when it is currently set as the active worker.  Scenario is you have four nodes each with redis and sentinel configured on each.

xxx.xxx.xxx.1
xxx.xxx.xxx.2
xxx.xxx.xxx.3
xxx.xxx.xxx.4

When the app starts it is connected to sentinel and redis xxx.xxx.xxx.1.  When you take the box down exception errors are thrown and a new sentinel worker is never set.  A message is published that the host went down but the only thing that the RedisSentinelWorker::SentinellMessageReceived does is ResetClients, but that is going to fail as well, because the sentinel worker is also down.

Because the current worker is always cached it is never checked to see if it is valid.  So thinking there could be a couple of options here:

1.    Within GetValidSentinelWorker if this.worker isn't null then let's perform a check here and see if it is still valid, If so then let's return the worker, otherwise fall through and find a new sentinel worker.

2.   Within the RedisSentinelWorker class let's wrap a try/catch block statement around the code within GetMasterHost.  If an exception is thrown here let's catch it and make a call to OnSentinelError if it isn't null.
```
internal string GetMasterHost(string masterName)
{
    try
    {
            var masterInfo = sentinelClient.SentinelGetMasterAddrByName(masterName);
            return masterInfo.Count > 0
                ? SanitizeMasterConfig(masterInfo)
                : null;
    }
    catch (Exception ex)
    {
    if (OnSentinelError != null)
             OnSentinelError(ex);
    }
        return null;
}
```

**Comment by mythz** [comment]
thx, I've gone with your 2nd try/catch solution in this commit: https://github.com/ServiceStack/ServiceStack.Redis/commit/81c8a4fa6199207b508043e24ab85a16ae4656d5

This change is available from v4.0.55 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Please let me know on this thread if the issue still persists.
