### ISSUE TITLE
Xcode 7.3 plugin not working

### ISSUE THREAD

**Issue by neobeppe** [ServiceStack/Issues#412]
ServiceStack plugin is not working on Xcode 7.3

**Comment by mythz** [comment]
@Layoric can you investigate.

**Comment by Layoric** [comment]
Updated to support 7.3.

@neobeppe update with the new `dmg` you can [download here](https://github.com/ServiceStack/ServiceStack.Swift/raw/master/dist/ServiceStackXcode.dmg) and let us know if you have any issues :+1:
