### ISSUE TITLE
Update ServiceStack Reference not working on Xcode 7.3

### ISSUE THREAD

**Issue by neobeppe** [ServiceStack/Issues#413]
With new version of the plugin for Xcode 7.3 "add reference" works well but "update reference" doesn't make any change at all, even at the update time.

**Comment by Layoric** [comment]
I've tested this with the TechStacks site, Xcode 7.3 and seems to be working. Steps I follow are:

- Open DTO file by selecting it in the project exlorer

![image](https://cloud.githubusercontent.com/assets/234642/14174723/04b6db0c-f792-11e5-8f68-86de42d38b7f.png)
- File -> `Update ServiceStack Reference`.

Could you make sure the endpoint is accessible, eg `BaseUrl + `/types/swift`. Anything to help me reproduce the issue would be appreciated!

**Comment by neobeppe** [comment]
It worked well since 7.3, now I follow those steps, as before, and nothing happens
I've tried to start from scratch with Add Reference and it works, but not the update, i need to fill the ExcludeTypes and BaseClass after the Add
The url is accessible

**Comment by Layoric** [comment]
I'll assume the issue is resolved by you closing it? Open a new issue if find out what might be causing the problem :+1:
