### ISSUE TITLE
HostConfig NewInstance() and FallbackRestPath

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#414]
I have a test fixture that needs to instantiate and dispose a ServiceStack app host multiple times. 

On the second instantiation, an error message is thrown: 

> Config.FallbackRestPath is already defined. Only 1 [FallbackRoute] is allowed

Should `HostConfig NewInstance()` be resetting `FallbackRestPath`?

**Comment by mythz** [comment]
Doesn't hurt so I've just added it in: https://github.com/ServiceStack/ServiceStack/commit/269bf19ad6097d63e39dcce48551a5a215e7ea84
