### ISSUE TITLE
TryToParsePrimitiveTypeValues does not work for object properties.

### ISSUE THREAD

**Issue by dmytro-gokun** [ServiceStack/Issues#415]
Hi,

I have this code:

```
private class MyType
        {
            public object Value { get; set; }
        }

        private static void Main()
        {
            JsConfig.TryToParsePrimitiveTypeValues = true;

            var json = new MyType {Value = 10}.ToJson();
            var value = JsonSerializer.DeserializeFromString<MyType>(json);
            Console.WriteLine(json);
            Console.WriteLine(value.ToJson());
            Console.WriteLine(value.Value.GetType());
        }
```

It outputs:

```
{"Value":10}
{"Value":"10"}
System.String
```

I would expect it to output

```
{"Value":10}
{"Value":10}
System.Int32
```

instead, because of JsConfig.TryToParsePrimitiveTypeValues = true.
It looks like a bug in the JSON deserializer. Is it?

Best regards,
Dmitry

**Comment by mythz** [comment]
Should be resolved from this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/c667dfce939ff6762df5dca25367e8661df3c59a

This change is available in v4.0.55 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet)

I'd recommend against using `object` values in the typed serializer, if you don't know of the types you can [parse unstructured JSON with JsonObject instead](https://github.com/ServiceStack/ServiceStack.Text#supports-dynamic-json). 

```csharp
var o = JsonObject.Parse("{\"Value\":1}");
o["Value"].Print(); //= 1
```
