### ISSUE TITLE
TryToParsePrimitiveTypeValues (presumably) wrongly parses strings to integers.

### ISSUE THREAD

**Issue by dmytro-gokun** [ServiceStack/Issues#417]
According to release notes (https://github.com/ServiceStack/ServiceStack.Text/wiki/Release-Notes):

JsConfig.TryToParsePrimitiveTypeValues - Enables deserialization into object to attempt to figure out the type of the object (ie bool, int, date, etc) rather than always using a string.

after the latest fixes this seems to work fine. But, it also does it to much.

For example:

```
        [Test]
        public void Deserialize_NumericStringToObject_ShouldWork()
        {
            const string json = @"{""Value"":""100000""}";

            var actual = JsonSerializer.DeserializeFromString<TestType1>(json);
            actual.Value.Should().BeOfType(typeof(string)).And.Be("100000");
        }
```

here, the string value "100000" gets parsed to an integer value 100000, which in my opinion is not correct. That would be correct if JSON were {"Value":100000} where the value is an intger.
The same happens with "boolean" strings, e.g. {"Value":"False"}.

Am I correct here? Is it a bug? If it is not, would not make sense to have a glaf to disable this behavior?

**Comment by mythz** [comment]
This is the current behavior, it tries to pick the most suitable data type based on the string value. Like I said earlier I recommend not using `object` types in typed serializers, either specify the type you want it deserialized into or use `JsonObject` to parse unstructured JSON dynamically.

**Comment by dmytro-gokun** [comment]
Hi Demis,

first for all, thanks for the great library and quick responses!

While I agree with you that JsonObject might be a better choice for this case, please let me make my point here.

I have to interact with some existing API. I've made strongly typed object definitions for requests/responses to use in my application. That all works fine and well. But, in a couple of places they return a field which might be of type int/boolean or string.

Naturally, I made that field an "object" in my response definition. Later though I was surprised by the fact that the field always gets serialized to a string (despite of the fact that original JSON contains the type information for the field implicitly). I dug for a bit and found the TryToParsePrimitiveTypeValues flag. It made things better for a while. Until I found that this flag is "too smart" - not only it uses JSON type info, but it also tries to parse the string values.

What i think would make sense is to have a way to grab JSON type info without trying to parse into the strings. E.g. {"value":10000} becomes an int, {"value":true} - a boolean, {"value":"1000"} - a string. Do you think that would be totally useless/illogical behavior for the deserializer?

Thanks in advance,
Dmytro.

**Comment by mythz** [comment]
It doesn't do this by design, it treats every value as text and looks at the target type to work out what it should deserialize into, this is not a use-case the serializer is optimized for and is too disruptive to change.

**Comment by dmytro-gokun** [comment]
Okay, i get it. I will try to use JsonObject.
In any case, thanks a lot for your help and time!

**Comment by dmytro-gokun** [comment]
Demis, i'm sorry to disturb you again. I'm just trying to understand ServiceStack's way to handle JSON properly and there are not that much documentation about all this.

So, my question is this: suppose, i'm asked to write a web service. The request should contain a list of parameters, each of which might be an integer, a boolean, a string or an array of any of those types.
How should i define the DTO object for such a request using ServiceStack?

You see, if I define that field as an "object", it will always convert the value to a string and the type info is lost. If I use TryToParsePrimitiveTypeValues - it will sometime convert strings to integers and so one, thereby swallowing the type information from the original request.

Another option would be to use JsonValue and/or JsonObject for such a field/DTO. But then I still do not see a way to find the type info using that as well.

May be I'm missing something here? Is it possible to do what I need here at all, without adding an additional "Type" field?

Thanks in advance,
Dmytro.

**Comment by georgehemmings** [comment]
Dmytro, 

This discussion in the forum might be of interest to you. https://forums.servicestack.net/t/avoiding-interfaces-in-dtos/1927/2

I think you'll need a string and "Type" field. Or a list for each Type you are expecting, e.g. `List<int> IntValues; List<decimal> DecimalValues;

I went with the list for each Type method, as I was expecting a limited number of types and it made validation and persistence (to an existing db schema) easier in my case.

**Comment by dmytro-gokun** [comment]
I see. Thanks, George (Y).
To be honest, i was hoping to avoid having this "Type" field, coz all required info is in JSON already. But it looks there is no way around :(
