### ISSUE TITLE
CacheResponse attribute appears to have issues with Get request and compression, results in null return

### ISSUE THREAD

**Issue by rsafier** [ServiceStack/Issues#419]
The new `CacheResponse` attribute looks nice, but I think I found a bug. 
By adding the attribute to standard Hello request sample:
      
     [CacheResponse(Duration = 500)]
     public object Any(Hello request) { ... }

If consuming with a Get request that uses compression it will return null. 
A basic unit test like will fail unless `c.DisableAutoCompression = true;` then it gives expected result:
    
     using (var c = new JsvServiceClient("http://localhost:9999/"))
     {
         var result = c.Get(new Hello { Name = "World" });
         Assert.That(result.Result, Is.EqualTo("Hello, World!"));
     }

**Comment by mythz** [comment]
Hi Richard,

Thanks for beta testing this already :) but I'm not able to reproduce this issue, I've added an integration test for this at: https://github.com/ServiceStack/ServiceStack/commit/fb402d4c6de334fc5d0fcb4dffc5a80970c111d0

But it's passing without issue. Can provide more details so I can repro this locally?

P.S. [Disposing Service Clients are unnecessary](https://github.com/ServiceStack/ServiceStack/blob/fb402d4c6de334fc5d0fcb4dffc5a80970c111d0/src/ServiceStack.Client/ServiceClientBase.cs#L1751) :)

**Comment by rsafier** [comment]
Actually I would expect it to work in the example unit test, because it always was working when `DisableAutoCompression = true`, this issue is arising only with compression enabled. 
I'll try get an example written (and make sure I don't have some other version conflicts going on), but effectively its the same as your test but `DisableAutoCompression` should be left as its default `false`.

**Comment by mythz** [comment]
Ok but DisableAutoCompression=false is the default and that's not showing any issues either, will wait for your example, thx.

**Comment by rsafier** [comment]
It seems I must have had some sort of crossed packages causing an issue. After killing out my NuGet cache and packages folder my failing test started operating. I'll try to be more diligent about clearing these things when working against the beta version.
