### ISSUE TITLE
HTTP Status Description overwritten with default when HTTP Status Code set

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStack/Issues#421]
Hi

When `WriteErrorToResponse` sets the HTTP Status Code it overwrites the HTTP Status Description. I suspect this may be happening in the underlying `HttpResponseBase` in `AspNetResponse`.

This is where the StatusCode is set:
https://github.com/ServiceStack/ServiceStack/blob/cf6c6772ded0c037a21da7b5026770f6003ec6f8/src/ServiceStack/HttpResponseExtensionsInternal.cs#L387

Could you maybe capture the `StatusDescription` before setting the `StatusCode` then set it again?

**Comment by mythz** [comment]
Do you mean just set the StatusCode first? https://github.com/ServiceStack/ServiceStack/commit/f797634fb6df800706d2d3016c007cac6882b700

**Comment by georgehemmings** [comment]
That helps a bit :)

But if I set the `StatusDescription` on the response before calling `WriteErrorToResponse` it will still get overwritten when the `StatusCode` is set.

I was just thinking something like this:

     var capturedStatusDescription  = httpRes.StatusDescription;
     httpRes.StatusCode = statusCode;
     httpRes.StatusDescription = capturedStatusDescription;

Thanks

**Comment by mythz** [comment]
ok yeah I see what you mean, should be resolved in this commit: https://github.com/ServiceStack/ServiceStack/commit/a882f84c90985f79f9141d7cffe575cf24812a00

Are you building from source or do you want this change deployed on MyGet?

**Comment by georgehemmings** [comment]
Thanks. I'll work around it for now. I can wait until the next NuGet release.

**Comment by mythz** [comment]
Actually this broke a lot of tests, if the existing StatusDescription was OK and the StatusCode was an error, the StatusDescription goes back to OK which is wrong, going to have to revert.

**Comment by mythz** [comment]
I've changed it to [only override if it's not the default StatusDescription](https://github.com/ServiceStack/ServiceStack/blob/bdaa07192b80f433ed4c172b6177b4a01e51cea8/src/ServiceStack/HttpResponseExtensionsInternal.cs#L384-L397), so the code is now:

```csharp
var hold = httpRes.StatusDescription;
var hasDefaultStatusDescription = hold == null || hold == "OK";

httpRes.StatusCode = statusCode;

if (hasDefaultStatusDescription)
{
    if (errorMessage != null)
        httpRes.StatusDescription = errorMessage;
}
else
{
    httpRes.StatusDescription = hold;
}
```

**Comment by georgehemmings** [comment]
Ok, cheers
