### ISSUE TITLE
Razor partial not found when page is accessed as default for directory

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStack/Issues#426]
I'm trying to use `@Html.Partial("RazorContent")` to render a cshtml partial. When accessing the page as the default for the directory (e.g. /stars/alive/vedder/) the partial doesn't render. Accessing the page directly (e.g. /stars/alive/vedder/default) does render the partial. However Markdown pages are rendered in both scenarios.

My fork of RazorRockstars showing this issue: https://github.com/georgehemmings/RazorRockstars/commit/4353986879f7fcd58a4269b9a02ed82b00f27619

**Comment by mythz** [comment]
Should now be resolved from this commit: https://github.com/ServiceStack/ServiceStack/commit/1bf2383377477f02734c43e44a619eed2a02b33f

Available from v4.0.57+ which is [now on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
