### ISSUE TITLE
do you support angular2?

### ISSUE THREAD

**Issue by dongeast** [ServiceStack/Issues#427]
/**
 * @license AngularJS v1.2.20
 * (c) 2010-2014 Google, Inc. http://angularjs.org
 * License: MIT
 */

The version of AngularJS is too slow~ 
do you support angular2 beta?

**Comment by mythz** [comment]
Not yet, we're waiting for it to be released, please submit [feature requests on UserVoice](https://servicestack.uservoice.com/forums/176786-feature-requests)

**Comment by jklemmack** [comment]
What support does ServiceStack have for AngularJS 1.x now anyway?  The closest I'm aware of is the ss-utils.js, but that's all built on jquip / jQuery.  I've made my own shim to enable things like SS's JS-client EventSource to play well in my AngularJS services, but I'd be interested if there are any first-party AngularJS-SS libraries.

**Comment by mythz** [comment]
ss-utils.js depends on jQuery, there's no library specific for Angular, you can just use jQuery's `$.ajax` or Angular's `$http` like we do in TechStacks (an AngularJS App): https://github.com/ServiceStackApps/TechStacks/blob/master/src/TechStacks/TechStacks/js/tech/services.js

There's no plan or feature requests on UserVoice for any AngularJS-specific libraries, but creating a separate TypeScript Service Client + SSE Client without a dependency on jQuery would make sense.
