### ISSUE TITLE
InProcessServiceGateway access restriction applied

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStack/Issues#429]
Hi

Loving the new Service Gateway, it's simplified a number of my services.

The only issue I'm having is that access restrictions are applied when using the InProcessServiceGateway. I'm not sure if this was by design, but I think it would make sense to skip them.

In my case, I've applied JSON only restriction to all my internal service. I have a services that a 3rd party post to in `text/plain`, this calls one of my internal services via `Gateway`, this fails with an `UnauthorizedAccessException`.

**Comment by mythz** [comment]
ok access restrictions should be skipped for in-process requests from this commit: https://github.com/ServiceStack/ServiceStack/commit/33c676fed129f3164ac849f0df2de9652e2e8cfe
