### ISSUE TITLE
LicenseException when using running AppHosts in different AppDomains

### ISSUE THREAD

**Issue by Martaver** [ServiceStack/Issues#430]
We're experimenting with running multiple AppHosts during testing by placing them in different AppDomains. It looks promising, but the AppHosts in other AppDomains don't register their license correctly.

I've attached a file with a stand-alone test demonstrating the issue.

Note lines 112-113:
`var license = ConfigurationManager.AppSettings["servicestack:license"];
				Licensing.RegisterLicense(license);		`

When running the test, you can comment out lines 112-113, and you can see the expected license exception since we're loading more than 20 types.

When lines 112-113 are active, to apply the license to their AppDomain with Licensing.RegisterLicense, I get a LicensingException with the message: "This license is invalid. Please see servicestack.net or contact team@servicestack.net for more details." .

With a single developer license, my understanding is that this is within the bounds of the licensing agreement?

[LicensingInAnotherAppDomain.txt](https://github.com/ServiceStack/Issues/files/236587/LicensingInAnotherAppDomain.txt)

**Comment by mythz** [comment]
The license needs to be registered **once on Application Startup** and only applies to that AppDomain. If you have multiple AppDomains it needs to be registered once in each App Domain.

Consider using one of the alternative license registration methods: https://servicestack.net/download#register

E.g. adding it to **App.config** `<appSettings/>` or in the `SERVICESTACK_LICENSE` Environment Variable.

**Comment by Martaver** [comment]
Yup, tried all of that - still have the same problem.

For the main AppDomain, we use `<appSettings/>` in the App.config file... works fine.

In the second AppDomain, the same license is being registered IN that AppDomain, before the AppHost is Initialised - and we get a LicenseException.

Try it and see!

**Comment by mythz** [comment]
Are you sure you've tried using an environment variable? I've got one set and the test is passing, you don't need to set the License Key in code. 

Also you should be using `OrmLiteConnectionFactory` to use OrmLite, e.g:

```csharp
dbFactory = new OrmLiteConnectionFactory(":memory:", SqliteDialect.Provider);
_conn = dbFactory.OpenDbConnection();
```

**Comment by Martaver** [comment]
I've just set the license in AppDomainInitializer as a literal, and that works... Actually, now that I think of it, it must have been a combination of me setting the license too late, or the config file not being loaded yet. I'll try the ENV variable too.

Thanks and sorry to waste your time Demis!
