### ISSUE TITLE
ServiceStack.Text.HttpUtils.cs → UploadFile 's Bug

### ISSUE THREAD

**Issue by hgp7369** [ServiceStack/Issues#431]
@mythz 

original code:
**var boundarybytes = ("\r\n--" + boundary + "\r\n").ToAsciiBytes();**

fixed code:
**var boundarybytes = ("\r\n--" + boundary + "--\r\n").ToAsciiBytes();**

original code can't upload a file
add "--" can fix this bug

**Comment by mythz** [comment]
We have tests [showing UploadFile works as it is](https://github.com/ServiceStack/ServiceStack/blob/75847c737f9c0cd9f5dd4ea3ae1113dace56cbf2/tests/ServiceStack.WebHost.Endpoints.Tests/FileUploadTests.cs#L92).

When reporting an Issue please [include a repro](https://github.com/ServiceStack/Issues#you-can-view-existing-issues-or-report-a-new-issue) that we can use to verify the issue.
