### ISSUE TITLE
Pubsub - Client does not reconnect after longer outage.

### ISSUE THREAD

**Issue by DawidDuniec** [ServiceStack/Issues#432]
Hi,

I'm having the issue when Redis have a longer outage. To reproduce it:

Set timeout to small value like 1 second (it also happen with default values, but you have to wait longer):
HeartbeatInterval = TimeSpan.FromSeconds(1),
HeartbeatTimeout = TimeSpan.FromSeconds(1),
WaitBeforeNextRestart = TimeSpan.FromSeconds(1)

Drop network connection

Wait untill some heartbeats will fail

After a while restore the connection

It will stuck in the RedisPubSubServer.SendHeartbeat with current status "stopping" and won't reconnect.

Can someone provide workaround for that until is patched? Or am i doing something wrong?

...
Only solution that i can think off is setting my own Timer, send heartbeat and recreate whole RedisPubSubServer object, because i can't even change a state, and while "stopping" i can't restart/stop/start it.

**Comment by xplicit** [comment]
Could you send a reproducible case which shows the issue? Also, please note which ServiceStack version you use.

I ran the following snippet with 4.0.56 version then switched off the network cable from the machine, where server ran and after several seconds plug it back. Connection was restored and  heartbeats were started to send again.

           PooledRedisClientManager manager = new PooledRedisClientManager(new string[]{ "host:port" }, new string[]{ "host:port" }, 5);

            RedisPubSubServer server = new RedisPubSubServer(manager, "test");
            server.HeartbeatInterval = TimeSpan.FromSeconds(1);
            server.HeartbeatTimeout = TimeSpan.FromSeconds(1);
            server.WaitBeforeNextRestart = TimeSpan.FromSeconds(1);
            server.OnHeartbeatSent +=  () => Console.WriteLine("Heartbeat sent");
            server.OnHeartbeatReceived +=  () => Console.WriteLine("Heartbeat received");
            server.OnInit += () => Console.WriteLine("Init");
            server.OnStart += () => Console.WriteLine("Start");
            server.OnError += ex => Console.WriteLine(ex);

            server.Start();

            while (true)
            {
                Thread.Sleep(1000);
            }


Also, I think you should increase `HeartbeatTimeout` and `WaitBeforeNextRestart` values otherwise you can get situation where server is continuously restarted due to network lags, even when it receives heartbeats.

For example, I used these values to prevent restarting server all the time:

            server.HeartbeatInterval = TimeSpan.FromSeconds(1);
            server.HeartbeatTimeout = TimeSpan.FromSeconds(3);
            server.WaitBeforeNextRestart = TimeSpan.FromSeconds(5);

**Comment by DawidDuniec** [comment]
xplicit thank you for the quick answer.

It's a subscriber which is trying to reconnect with the server, it's not just a couple seconds, give him a few minutes, and put the breakpoint on "OnHeartbeatSent" at some point you will see that it stopped hitting it.

I know that the heartbeat with default values need bigger timeout, these ones are just to faster reproduce the issue.

**Comment by mythz** [comment]
Please provide the exact source code you're using so we can all run the same code and can repro the same issue.

**Comment by DawidDuniec** [comment]
[PubsubTest.zip](https://github.com/ServiceStack/Issues/files/257134/PubsubTest.zip)

![result](https://cloud.githubusercontent.com/assets/19264483/15146238/88f21c5a-16ba-11e6-8c9b-97e5818739b4.png)

**Comment by xplicit** [comment]
How long did you wait after enabling network back? After sequential errors timeout between trying to restart is increased.  

Here is my output 

Heartbeat sent
Thread started: <Thread Pool> #8
Heartbeat sent
Thread started: <Thread Pool> #9
Heartbeat sent
Error
Error
5/10/2016 7:01:22 PM
5/10/2016 7:01:27 PM
5/10/2016 7:01:32 PM
5/10/2016 7:01:37 PM
5/10/2016 7:01:42 PM
5/10/2016 7:01:47 PM
5/10/2016 7:01:52 PM
5/10/2016 7:01:57 PM
5/10/2016 7:02:02 PM
5/10/2016 7:02:07 PM
5/10/2016 7:02:12 PM
5/10/2016 7:02:17 PM
Error
Error
Error
5/10/2016 7:02:22 PM
5/10/2016 7:02:27 PM
5/10/2016 7:02:32 PM
Thread finished: <Thread Pool> #3
Thread started: <Thread Pool> #10
5/10/2016 7:02:37 PM
5/10/2016 7:02:42 PM
5/10/2016 7:02:47 PM
5/10/2016 7:02:52 PM
5/10/2016 7:02:57 PM
5/10/2016 7:03:02 PM
5/10/2016 7:03:07 PM
5/10/2016 7:03:12 PM
5/10/2016 7:03:17 PM
5/10/2016 7:03:22 PM
5/10/2016 7:03:27 PM   --- >> at this place I plugged back network cable
5/10/2016 7:03:32 PM
Thread finished: <Thread Pool> #10
Thread started: <Thread Pool> #11
5/10/2016 7:03:37 PM
5/10/2016 7:03:42 PM
5/10/2016 7:03:47 PM
5/10/2016 7:03:52 PM
5/10/2016 7:03:57 PM
5/10/2016 7:04:02 PM
5/10/2016 7:04:07 PM
Heartbeat sent
5/10/2016 7:04:12 PM
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
5/10/2016 7:04:17 PM
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
5/10/2016 7:04:22 PM
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
5/10/2016 7:04:27 PM
Heartbeat sent
Heartbeat received

**Comment by DawidDuniec** [comment]
@xplicit i think i don't understand something ... in the case that you've pasted, there is no heartbeat within 3 minutes (but there is couple second timeout set), after those 3 minutes from what i understand, there is some kind of heartbeat sent from the server, which change the state of the client?

**Comment by xplicit** [comment]
@DawidDuniec The log starts at the time when I plugged out the network cable. After this no heartbeats received from the server. Then I wait couple of minutes and plugged the network cable back at 5/10/2016 7:03:27 PM. After this operation I wait roughly a minute for restart of `RedisPubSubServer` and heartbeats become working again.

**Comment by DawidDuniec** [comment]
@xplicit thank you for clarifying the test case, but i'm wondering, how does the client know that server is coming back up if he didn't send the heartbeat?

**Comment by xplicit** [comment]
@DawidDuniec Is there issue resolved for you?

**Comment by DawidDuniec** [comment]
@xplicit no it's not. I'm really supprised that it works for you, here is my log: redis 3.0.6 on virtual machine (virtualbox), i'm unplugging cable via options in virtual box, and plug it again around 1:58:40, here is the log:

5/16/2016 1:47:13 PM
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
5/16/2016 1:47:18 PM
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
5/16/2016 1:47:23 PM
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
5/16/2016 1:47:28 PM
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
5/16/2016 1:47:33 PM
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
5/16/2016 1:47:39 PM
Heartbeat sent
Error
Error
Error
5/16/2016 1:47:44 PM
Error
5/16/2016 1:47:49 PM
Error
Error
Error
Error
Error
5/16/2016 1:47:54 PM
Error
Error
Error
Error
5/16/2016 1:47:59 PM
5/16/2016 1:48:04 PM
5/16/2016 1:48:09 PM
5/16/2016 1:48:14 PM
5/16/2016 1:48:19 PM
5/16/2016 1:48:24 PM
5/16/2016 1:48:29 PM
5/16/2016 1:48:34 PM
5/16/2016 1:48:39 PM
5/16/2016 1:48:44 PM
5/16/2016 1:48:49 PM
5/16/2016 1:48:54 PM
5/16/2016 1:48:59 PM
5/16/2016 1:49:04 PM
5/16/2016 1:49:09 PM
5/16/2016 1:49:14 PM
5/16/2016 1:49:19 PM
5/16/2016 1:49:24 PM
5/16/2016 1:49:29 PM
5/16/2016 1:49:34 PM
5/16/2016 1:49:39 PM
5/16/2016 1:49:44 PM
5/16/2016 1:49:49 PM
5/16/2016 1:49:54 PM
5/16/2016 1:49:59 PM
5/16/2016 1:50:04 PM
5/16/2016 1:50:09 PM
5/16/2016 1:50:14 PM
5/16/2016 1:50:19 PM
5/16/2016 1:50:24 PM
5/16/2016 1:50:29 PM
5/16/2016 1:50:34 PM
5/16/2016 1:50:39 PM
5/16/2016 1:50:44 PM
5/16/2016 1:50:49 PM
5/16/2016 1:50:54 PM
5/16/2016 1:50:59 PM
5/16/2016 1:51:04 PM
5/16/2016 1:51:09 PM
5/16/2016 1:51:14 PM
5/16/2016 1:51:19 PM
5/16/2016 1:51:24 PM
5/16/2016 1:51:29 PM
5/16/2016 1:51:34 PM
5/16/2016 1:51:39 PM
5/16/2016 1:51:44 PM
5/16/2016 1:51:49 PM
5/16/2016 1:51:54 PM
5/16/2016 1:51:59 PM
5/16/2016 1:52:04 PM
5/16/2016 1:52:09 PM
5/16/2016 1:52:14 PM
5/16/2016 1:52:19 PM
5/16/2016 1:52:24 PM
5/16/2016 1:52:29 PM
5/16/2016 1:52:34 PM
5/16/2016 1:52:39 PM
5/16/2016 1:52:44 PM
5/16/2016 1:52:49 PM
5/16/2016 1:52:54 PM
5/16/2016 1:52:59 PM
5/16/2016 1:53:04 PM
5/16/2016 1:53:09 PM
5/16/2016 1:53:14 PM
5/16/2016 1:53:19 PM
5/16/2016 1:53:24 PM
5/16/2016 1:53:29 PM
5/16/2016 1:53:34 PM
5/16/2016 1:53:39 PM
5/16/2016 1:53:44 PM
5/16/2016 1:53:49 PM
5/16/2016 1:53:54 PM
5/16/2016 1:53:59 PM
5/16/2016 1:54:05 PM
5/16/2016 1:54:10 PM
5/16/2016 1:54:15 PM
5/16/2016 1:54:20 PM
5/16/2016 1:54:25 PM
5/16/2016 1:54:30 PM
5/16/2016 1:54:35 PM
5/16/2016 1:54:40 PM
5/16/2016 1:54:45 PM
5/16/2016 1:54:50 PM
5/16/2016 1:54:55 PM
5/16/2016 1:55:00 PM
5/16/2016 1:55:05 PM
5/16/2016 1:55:10 PM
5/16/2016 1:55:15 PM
5/16/2016 1:55:20 PM
5/16/2016 1:55:25 PM
5/16/2016 1:55:30 PM
5/16/2016 1:55:35 PM
5/16/2016 1:55:40 PM
5/16/2016 1:55:45 PM
5/16/2016 1:55:50 PM
5/16/2016 1:55:55 PM
5/16/2016 1:56:00 PM
5/16/2016 1:56:05 PM
5/16/2016 1:56:10 PM
5/16/2016 1:56:15 PM
5/16/2016 1:56:20 PM
5/16/2016 1:56:25 PM
5/16/2016 1:56:30 PM
5/16/2016 1:56:35 PM
5/16/2016 1:56:40 PM
5/16/2016 1:56:45 PM
5/16/2016 1:56:50 PM
5/16/2016 1:56:55 PM
5/16/2016 1:57:00 PM
5/16/2016 1:57:05 PM
5/16/2016 1:57:10 PM
5/16/2016 1:57:15 PM
5/16/2016 1:57:20 PM
5/16/2016 1:57:25 PM
5/16/2016 1:57:30 PM
5/16/2016 1:57:35 PM
5/16/2016 1:57:40 PM
5/16/2016 1:57:45 PM
5/16/2016 1:57:50 PM
5/16/2016 1:57:55 PM
5/16/2016 1:58:00 PM
5/16/2016 1:58:05 PM
5/16/2016 1:58:10 PM
5/16/2016 1:58:15 PM
5/16/2016 1:58:20 PM
5/16/2016 1:58:25 PM
5/16/2016 1:58:30 PM
5/16/2016 1:58:35 PM
5/16/2016 1:58:40 PM
5/16/2016 1:58:45 PM
5/16/2016 1:58:50 PM
5/16/2016 1:58:55 PM
5/16/2016 1:59:00 PM
5/16/2016 1:59:05 PM
5/16/2016 1:59:10 PM
5/16/2016 1:59:15 PM
5/16/2016 1:59:20 PM
5/16/2016 1:59:25 PM
5/16/2016 1:59:30 PM
5/16/2016 1:59:35 PM
5/16/2016 1:59:40 PM
5/16/2016 1:59:45 PM
5/16/2016 1:59:50 PM
5/16/2016 1:59:55 PM
5/16/2016 2:00:00 PM
5/16/2016 2:00:05 PM
5/16/2016 2:00:10 PM
5/16/2016 2:00:15 PM
5/16/2016 2:00:20 PM
5/16/2016 2:00:25 PM
5/16/2016 2:00:30 PM
5/16/2016 2:00:35 PM
5/16/2016 2:00:40 PM
5/16/2016 2:00:45 PM
5/16/2016 2:00:50 PM
5/16/2016 2:00:55 PM
5/16/2016 2:01:00 PM
5/16/2016 2:01:05 PM
5/16/2016 2:01:10 PM
5/16/2016 2:01:15 PM
5/16/2016 2:01:20 PM
5/16/2016 2:01:25 PM
5/16/2016 2:01:30 PM
5/16/2016 2:01:35 PM
5/16/2016 2:01:40 PM
5/16/2016 2:01:45 PM
5/16/2016 2:01:50 PM
5/16/2016 2:01:55 PM
5/16/2016 2:02:00 PM
5/16/2016 2:02:05 PM
5/16/2016 2:02:10 PM
5/16/2016 2:02:15 PM
5/16/2016 2:02:20 PM
5/16/2016 2:02:25 PM
5/16/2016 2:02:30 PM
5/16/2016 2:02:35 PM

**Comment by xplicit** [comment]
Can you add in file `PubSubWorker.cs` at line 28 following code:

                OnStart = () => Console.WriteLine("Start"),

then run test again, wait 5-7 minutes after enabling network back and attach output here?

**Comment by DawidDuniec** [comment]
Network disabled: 2:58:12
Network enabled: 3:03:09

5/16/2016 2:57:57 PM
Start
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
5/16/2016 2:58:02 PM
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
5/16/2016 2:58:07 PM
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat received
5/16/2016 2:58:12 PM
Heartbeat sent
Heartbeat received
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
5/16/2016 2:58:17 PM
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
Heartbeat sent
5/16/2016 2:58:24 PM
Heartbeat sent
Error
5/16/2016 2:58:28 PM
Error
Error
5/16/2016 2:58:33 PM
Error
Error
Error
5/16/2016 2:58:38 PM
Error
Error
Error
Error
Error
5/16/2016 2:58:43 PM
Error
5/16/2016 2:58:48 PM
5/16/2016 2:58:53 PM
5/16/2016 2:58:58 PM
5/16/2016 2:59:03 PM
5/16/2016 2:59:08 PM
5/16/2016 2:59:13 PM
5/16/2016 2:59:18 PM
5/16/2016 2:59:23 PM
5/16/2016 2:59:28 PM
5/16/2016 2:59:33 PM
5/16/2016 2:59:38 PM
5/16/2016 2:59:43 PM
5/16/2016 2:59:48 PM
5/16/2016 2:59:53 PM
5/16/2016 2:59:58 PM
5/16/2016 3:00:03 PM
5/16/2016 3:00:08 PM
5/16/2016 3:00:14 PM
5/16/2016 3:00:19 PM
5/16/2016 3:00:24 PM
5/16/2016 3:00:29 PM
5/16/2016 3:00:34 PM
5/16/2016 3:00:39 PM
5/16/2016 3:00:44 PM
5/16/2016 3:00:49 PM
5/16/2016 3:00:54 PM
5/16/2016 3:00:59 PM
5/16/2016 3:01:04 PM
5/16/2016 3:01:09 PM
5/16/2016 3:01:14 PM
5/16/2016 3:01:19 PM
5/16/2016 3:01:24 PM
5/16/2016 3:01:29 PM
5/16/2016 3:01:34 PM
5/16/2016 3:01:39 PM
5/16/2016 3:01:44 PM
5/16/2016 3:01:49 PM
5/16/2016 3:01:54 PM
5/16/2016 3:01:59 PM
5/16/2016 3:02:04 PM
5/16/2016 3:02:09 PM
5/16/2016 3:02:14 PM
5/16/2016 3:02:19 PM
5/16/2016 3:02:24 PM
5/16/2016 3:02:29 PM
5/16/2016 3:02:34 PM
5/16/2016 3:02:39 PM
5/16/2016 3:02:44 PM
5/16/2016 3:02:49 PM
5/16/2016 3:02:54 PM
5/16/2016 3:02:59 PM
5/16/2016 3:03:04 PM
5/16/2016 3:03:09 PM
5/16/2016 3:03:14 PM
5/16/2016 3:03:19 PM
5/16/2016 3:03:24 PM
5/16/2016 3:03:29 PM
5/16/2016 3:03:34 PM
5/16/2016 3:03:39 PM
5/16/2016 3:03:44 PM
5/16/2016 3:03:49 PM
5/16/2016 3:03:54 PM
5/16/2016 3:03:59 PM
5/16/2016 3:04:04 PM
5/16/2016 3:04:09 PM
5/16/2016 3:04:14 PM
5/16/2016 3:04:19 PM
5/16/2016 3:04:24 PM
5/16/2016 3:04:29 PM
5/16/2016 3:04:34 PM
5/16/2016 3:04:39 PM
5/16/2016 3:04:44 PM
5/16/2016 3:04:49 PM
5/16/2016 3:04:54 PM
5/16/2016 3:04:59 PM
5/16/2016 3:05:04 PM
5/16/2016 3:05:09 PM
5/16/2016 3:05:14 PM
5/16/2016 3:05:19 PM
5/16/2016 3:05:24 PM
5/16/2016 3:05:29 PM
5/16/2016 3:05:34 PM
5/16/2016 3:05:39 PM
5/16/2016 3:05:44 PM
5/16/2016 3:05:49 PM
5/16/2016 3:05:54 PM
5/16/2016 3:05:59 PM
5/16/2016 3:06:04 PM
5/16/2016 3:06:09 PM
5/16/2016 3:06:14 PM
5/16/2016 3:06:19 PM
5/16/2016 3:06:24 PM
5/16/2016 3:06:29 PM
5/16/2016 3:06:34 PM
5/16/2016 3:06:39 PM
5/16/2016 3:06:44 PM
5/16/2016 3:06:49 PM
5/16/2016 3:06:54 PM
5/16/2016 3:06:59 PM
5/16/2016 3:07:04 PM
5/16/2016 3:07:09 PM
5/16/2016 3:07:14 PM
5/16/2016 3:07:19 PM
5/16/2016 3:07:24 PM
5/16/2016 3:07:29 PM
5/16/2016 3:07:34 PM

**Comment by xplicit** [comment]
@DawidDuniec OK, I think I was able to reproduce such behaviour at least one time I get into similar situation.

**Comment by xplicit** [comment]
@DawidDuniec thank you for the output, I'll look into this.

**Comment by DawidDuniec** [comment]
@xplicit I've also try to check the source of RedisPubSubServer, and it occurs when this is happen, that it stuck with status "Stopping", and that's the reason why it doesn't send the heartbeat, hope it will help.

**Comment by xplicit** [comment]
@DawidDuniec  At the machine where I was able to reproduce the issue following workaround helps to restore Heartbeats after long disconnects. In `PubSubWorker` constructor add the line:

    _redisClientFactory.SocketReceiveTimeout = 10 * 1000;

Please let me know if this working for your configuration too.

**Comment by DawidDuniec** [comment]
@xplicit thank you for sorting that out, but would this help for longer outages? Our systems could be down even thru the whole weekend, and we count that heartbeat would reconnect after that time again.

**Comment by xplicit** [comment]
@DawidDuniec The issue when `SocketReceiveTimeout` is not set that `RedisPubSubServer` is not restarted after network disconnect. It does not receive a message about connection loss and tries to read data from socket with indefinite timeout. When timeout occures it restarted normally, but as I mentioned timeout is not set and `RedisPubSubServer` waits infinitely. After restart `RedisPubSubServer` starts to send heartbeats again and if redis server is available it receives the heartbeat responses. 

So the answer to your question: yes it will send heartbeats even after longer disconnects.  If you see message "Start" occurs periodically in console output that means all works fine and heartbeats will be restored after long disconnects.

**Comment by DawidDuniec** [comment]
@xplicit so it works fine, thank you for the solution!

**Comment by DawidDuniec** [comment]
@xplicit How i can fix it if i'm using IRedisClientsManager?

**Comment by xplicit** [comment]
@DawidDuniec What exact code do you use? Setting static config variable `RedisConfig.DefaultReceiveTimeout` before redis pool initialization should help

      RedisConfig.DefaultReceiveTimeout = 10 * 1000;
      //then create pool manager
