### ISSUE TITLE
OrmLite GroupBy(string groupBy) produces invalid sql

### ISSUE THREAD

**Issue by RodrigoAxel** [ServiceStack/Issues#433]
Hi,

Using `GroupBy(string groupBy)` produces invalid sql as shown in the following SqlExpression:

```
var sql = DB
   .From<User>()
   .GroupBy("VersionId")
   .Select(u => new { u.VersionId, Count = Sql.Count("*") });
```

**Produces:**

```
SELECT "VersionId",Count(*) 
FROM "User"
VersionId

```

**The 'GROUP BY' clause is missing in the generated sql, is this the expected behavior?**

Note that if I use the `GroupBy<TKey>(Expression<Func<T, TKey>> keySelector)` overload it works as expected and is the preferred way in the previous example, however I have a use-case where I am generating the GroupBy fields dynamically and the string overload is easier to use.

Thanks!!!
(btw, awesome library)

**Comment by mythz** [comment]
Hi, thanks for the repro - this should now be fixed from this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/09276a11c46cd232b7b71d9584dc5bf321f73826

This fix is available from v4.0.57 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Thanks for reporting!
