### ISSUE TITLE
IAuthSession which save into redis do not support NamespacePrefix.

### ISSUE THREAD

**Issue by dongeast** [ServiceStack/Issues#434]
NamespacePrefix = this.AppSettings.GetString("redis.NamespacePrefix")

I set NamespacePrefix for redis, but I find: 
urn:iauthsession:0mgb4CAENdbaiyBkCT4q
session do not use NamespacePrefix.

so I review the source code of 
ServiceStack\ServiceStack\SessionFeature.cs

`
        public static string GetSessionKey(string sessionId)
        {
            return sessionId == null ? null : IdUtils.CreateUrn<IAuthSession>(sessionId);
        }

        // urn:iauthsession:0mgb4CAENdbaiyBkCT4q
`

The session key donot have NamespacePrefix .

And urn:UserAuth>UserOAuthProvider do not support NamespacePrefix  too.
If we have two or more web application run at one redis, we use NamespacePrefix to mark one web application, the session data and userAuth data have been mixed up.

**Comment by mythz** [comment]
The NamespacePrefix is only for internal data-structures maintained by the RedisClients and doesn't affect user-specified keys. You would need to use a different Redis DB or Instance if you want them isolated, although as the Session Id is just Base64 encoded random bytes, multiple apps have as much chance as clashing as generating session ids in the same app.
