### ISSUE TITLE
/auth/{Provider Name} have not any example for Android and IOS

### ISSUE THREAD

**Issue by dongeast** [ServiceStack/Issues#435]
I write web api by ServiceStack.
I use /auth/vkcom for login.

Android and IOS how to use token?
Android and IOS can authenticate the web api by cookie which sent by /auth/vkcom, it work well.
If I use cookies to login, it is safe?
But how can I use token? vkcom return token string, it was all but forgotten.

**Comment by mythz** [comment]
Please only use this issues list to submit [reproducible issues](https://github.com/ServiceStack/Issues) that includes code we can run locally to identify and repro the issue. 

You can ask any support questions in the [Customer Forums](https://forums.servicestack.net/) or [StackOverflow](http://stackoverflow.com/questions/ask).

You can check out our Live Demos for examples using Xamarin.Auth:

  - [TechStacks Auth](https://github.com/ServiceStackApps/TechStacksAuth)
  - [Android Xamarin Chat](https://github.com/ServiceStackApps/AndroidXamarinChat)
