### ISSUE TITLE
JsonHttpClient is not thread-safe when AlwaysSendBasicAuthHeader = true

### ISSUE THREAD

**Issue by dmytro-gokun** [ServiceStack/Issues#438]
There is a race condition on DefaultRequestHeaders.
Why not assign that field within GetHttpClient()?

We've just bumped into this problem in a highly concurrent app. The result is that some requests are sent w/o any auth headers at all.

**Comment by mythz** [comment]
Yeah looks like anything modifying `HttpClient.DefaultRequestHeaders` should only happen once when the instance is created. Changed in this commit: https://github.com/ServiceStack/ServiceStack/commit/25b97f6a89cf730f2bf035822f1b34de0bd0c55d

This change is available from v4.0.57 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by dmytro-gokun** [comment]
Thanks a lot!
