### ISSUE TITLE
JsonHttpClient does not implement IDisposable

### ISSUE THREAD

**Issue by dmytro-gokun** [ServiceStack/Issues#439]
Since it is a wrapper for a disposable resource (HttpClient), i think it should implement IDisposable as well, should not it?

**Comment by mythz** [comment]
This is a constant design issue promoting incorrect usage of [HttpClient which shouldn't be disposed](http://stackoverflow.com/a/15708633/85785).  As no other Service Client implements IDisposable, this shouldn't either as it would encourage different usage of what should be substitutable dependencies. If for some reason you need to dispose it you can access the wrapped HttpClient instance with:

```csharp
client.HttpClient.Dispose();
```
