### ISSUE TITLE
Redis info doesn't update after client was previously disposed

### ISSUE THREAD

**Issue by gentisaliu** [ServiceStack/Issues#442]
I am using `ServiceStack.Redis` version `4.0.56` to read and display Redis server information as shown in the class below:

    using ServiceStack.Redis

    class Test
    {
        private IRedisClientManager clientManager;
    
        public Test()
        {
            clientManager = new PooledRedisClientManager(10, 10, connectionString);
        }
    
        public IDictionary<string, string> GetInfo()
        {
             var redisClient = redisClientManager.GetClient();
             var info = redisClient.Info;
     
             // If commented out, all info values are updated (i.e. uptime, keys etc)
             redisClient.Dispose();
    
             return info;
        }
    }

The problem is, as soon as the client is disposed (per best-practice), the `Info` property of `redisClient` always returns the old values, even though I obtain a new client instance as shown in the `GetInfo` method above.

When I leave out the `redisClient.Dispose` call, the `Info` values are all updated.

What am I doing wrong?

I also have posted this as a question on [SO](http://stackoverflow.com/questions/37723288/redis-info-doesnt-update-after-client-was-previously-disposed).

**Comment by xplicit** [comment]
Looks like RedisClient caches INFO and does not update data on the next calls or after Dispose when using with ClientManager. This commit should fix the issue https://github.com/xplicit/ServiceStack.Redis/commit/426f4b2e56f19c59d894774220455bf63a28981a

**Comment by mythz** [comment]
Should now be fixed in this commit:  https://github.com/ServiceStack/ServiceStack.Redis/commit/8b980d6636c5d767c4acfca2cfbe898f43efafd3

Available from v4.0.59 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by gentisaliu** [comment]
Thanks @xplicit and @mythz .

Any idea when this will be available on nuget, since that's what we are using for package management and it would be too painful for us to switch?

**Comment by mythz** [comment]
You don't have to switch, you can just add a NuGet package source as shown in the docs.

We released on NuGet yesterday, so the next release wont be for another 4-6 weeks.

**Comment by gentisaliu** [comment]
Latest version on NuGet is v4.0.58 though: https://www.nuget.org/packages/ServiceStack.Redis/

**Comment by mythz** [comment]
Yes that was yesterdays release, v4.0.59 is for pre-release packages on MyGet. NuGet version numbers are always even.

**Comment by mythz** [comment]
FYI we've just published v4.0.60 release to NuGet with this fix.

**Comment by gentisaliu** [comment]
Thank you for the heads up!
