### ISSUE TITLE
JsConfig.Reset locks config of property deserialization

### ISSUE THREAD

**Issue by BlakeRaymond-AI** [ServiceStack/Issues#443]
I have custom serialization rules for a type B, and a DTO type A with a property of B that doesn't itself have its own custom serialization rules. If I call JsConfig.Reset after deserializing A at least once, the config for A gets stuck with default deserialization for its B property.

From what I can gather, calling JsConfig.Reset will loop over all of the types it knows about and reset them, so if it resets type B before type A, and type A has a property of type B, then the config for A will be reset to use the empty/default config for its B property, and subsequent re-configs of B won't affect A's config for its property.

The context is that I'm trying to use an HTTP listener AppHost in tests along with some custom serialization, where the AppHost is disposed on tear down after each test. ServiceStackHost.Dispose calls JsConfig.Reset.

```c#
using System;
using System.Globalization;
using NUnit.Framework;
using ServiceStack;
using ServiceStack.Text;

namespace JsConfigTests
{
    [TestFixture]
    public class JsConfigTests
    {
        struct CustomFormatType
        {
            private int _value;

            public int Value
            {
                get { return _value; }
            }

            public CustomFormatType(int value)
            {
                _value = value;
            }
        }

        class Dto
        {
            public CustomFormatType CustomFormatTypeProperty { get; set; }
        }

        [Test]
        public void CallReset_AfterSerializingOnce_WithCustomSerializationForProperty_DoesNotPickUpFurtherConfigChangesForPropertyType()
        {
            var dto = new Dto {CustomFormatTypeProperty = new CustomFormatType(12345)};

            ConfigureCustomFormatType();
            TestRoundTripValue(dto);

            JsConfig.Reset();

            ConfigureCustomFormatType();
            TestRoundTripValue(dto);
        }

        private static void ConfigureCustomFormatType()
        {
            JsConfig<CustomFormatType>.RawSerializeFn = value => value.Value.ToString("x");
            JsConfig<CustomFormatType>.DeSerializeFn = str => new CustomFormatType(Int32.Parse(str, NumberStyles.HexNumber));
        }

        private static void TestRoundTripValue(Dto dto)
        {
            Assert.AreEqual(dto.CustomFormatTypeProperty.Value, dto.ToJson().FromJson<Dto>().CustomFormatTypeProperty.Value);
        }
    }
}
```

**Comment by mythz** [comment]
Should now be fixed in this commit: https://github.com/ServiceStack/ServiceStack.Text/commit/99358b2826abcf7b832bcaf9a6f46236dabbfa76

thx for reporting :+1:

**Comment by BlakeRaymond-AI** [comment]
Thanks!
