### ISSUE TITLE
OrmLite: second bug in Sql.In

### ISSUE THREAD

**Issue by OlegNadymov** [ServiceStack/Issues#446]
Null parameter in Sql.In works very well now! (fixed there: https://github.com/ServiceStack/Issues/issues/444)

But if I create in my business object a property like that "CustomProperty":
```C#
public class AnyObjectClass
{
    public Guid? Identity { get; set; }

    public string Name { get; set; }

	[Ignore]
	public decimal CustomProperty
	{
		get
		{
			return db.Select<AnyObjectClassItem>(s => Sql.In(s.Identity,
					   db.From<AnyObjectClassItem>()
						   .Where(b => b.AnyObjectClassId == this.Identity)
						   .Select(b => b.Identity))).Sum(r => r.PurchasePrice);
		}
	}
}


public class AnyObjectClassItem
{
    public Guid? Identity { get; set; }

    public string Name { get; set; }

    public decimal PurchasePrice { get; set; }

	[ForeignKey(typeof (AnyObjectClass))]
	public Guid AnyObjectClassId { get; set; }

    public AnyObjectClass AnyObjectClass { get; set; }
}
```

OrmLite produces incorrect SQL for ```this.Identity```  (in SQL writes ```Object.Identity``` instead of Guid value of property "Identity"):
```SQL
Select Identity, Name, PurchasePrice, AnyObjectClassId 
From AnyObjectClassItem
Where Identity in (
   Select Identity
   From AnyObjectClassItem
   Where AnyObjectClassId = Object.Identity)
```

P.S. It's simplified example.

**Comment by mythz** [comment]
FYI I've added this example to the test suite: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/5b7d6c4de78abd902cf78df6d6bf441d8c25b9fe

but it executes without issue:

```sql
SELECT "Identity", "Name", "PurchasePrice", "AnyObjectClassId", "AnyObjectClass" 
FROM "AnyObjectClassItem"
WHERE "Identity" IN (SELECT "Identity" 
FROM "AnyObjectClassItem"
WHERE ("AnyObjectClassId" = "Identity"))
```

Do you have a stand-alone example that repro's the issue?

> BTW I think it's a [bad idea for data models to contain db connections](https://forums.servicestack.net/t/best-way-to-share-db-all-over-poco-classes/2524/3?u=mythz) and having an unintended db access behind a property like this is even worse.

**Comment by mythz** [comment]
please reopen with a stand-alone failing test that repro's the issue.

**Comment by OlegNadymov** [comment]
I don't understand how reopen issue.

**Comment by OlegNadymov** [comment]
I found one more bug in Sql.In. New issue here: https://github.com/ServiceStack/Issues/issues/455
