### ISSUE TITLE
Removing HTML Feature Breaks Swagger

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#448]
FYI

Version 4.0.60

            this.Plugins.Add(new ValidationFeature());
            this.Plugins.Add(new SwaggerFeature());
            this.Plugins.Add(new PostmanFeature());

            SetConfig(new HostConfig
            {
                DebugMode = true,
                DefaultContentType = MimeTypes.Json,
                EnableFeatures = Feature.All.Remove(Feature.Html),
            });

Breaks the Swagger page. I think it makes some sense though since you're removing the HTML MetaData Formatter

-Stephen

**Comment by mythz** [comment]
Not sure why you're filing this as an issue, removing HTML support will break plugins generating HTML.

**Comment by stephenpatten** [comment]
As a courtesy to you, since I was unaware of the behaviour.
