### ISSUE TITLE
Exception getting response from lua script in transaction

### ISSUE THREAD

**Issue by gertgoeman** [ServiceStack/Issues#450]
Hello,

We're running in to some issues while migrating our code from StackExchange.Redis to ServiceStack.Redis.

The following code returns an array from a lua script. The StackExchange.Redis client supports this. Running it using the ServiceStack.Redis client throws an exception: Unable to Connect: sPort: 62445 (the port number looks random).

```Cs
using (var clientManager = new PooledRedisClientManager(1, "my-host:6379"))
{
        using (var client = clientManager.GetClient())
        {
                using (var tx = client.CreateTransaction())
                {
                        tx.QueueCommand(c => c.ExecLua("return {'myval', 'myotherval'}"));
                        tx.Commit();
                }
         }
}
```

Using ExecLuaAsString() instead, gives the following exception: Unexpected reply: *2.

The same happens when returning an error-reply from the lua script (with redis.error_reply("")).

**Comment by mythz** [comment]
Hi, support for executing ExecLua inside a transaction has been added [in this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/ea6235ed84924be2e463f93d99a94a33b25159aa).

This change is available from v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
