### ISSUE TITLE
AddParm precision and scale

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#452]
I don't know if this is a bug or intended, but AddParm uses the value as precision and scale when running Stored Procedures.

So if you have a SP that returns a decimal with a precision of (5,3) and the value for AddParm being 1M, the value will be clipped to precision 1,0.

I got around this by adding the Parms directly to the Parameters collection. Is this the way to do it or should AddParm be extended with Precision and Scale ?
(I have a couple of failing tests if this is a bug)

**Comment by mythz** [comment]
Additional overloads for scale, precision and size were added in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/pull/519/commits/e6fb419ec21872289eb44d8d72e227c323cc4816

This change is available from v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
