### ISSUE TITLE
HostContext.TestMode and Service.SessionAs

### ISSUE THREAD

**Issue by AVee** [ServiceStack/Issues#457]
After upgrading to 4.0.60 some of our tests started to fail because the custom AuthSession we use wouldn't be returned by Service.SessionAs(). This seems to be caused by this commit: https://github.com/ServiceStack/ServiceStack/commit/c3f8107fcc047a1ff74f375e53d84294335a6f35
I think the `!` on line 148 shouldn't be there.

We currently register our session like this: `container.Register<MySession>((o) => sess);`. I can work around this by changing that to `container.Register<IAuthSession>((o) => sess);`. I'm perfectly fine with that, but the commit suggests registering the custom session type is supposed to work as well.

**Comment by mythz** [comment]
Ahh crap, yeah fixed in this commit: https://github.com/ServiceStack/ServiceStack/commit/137aa4927372ab84adae548c941b070ecd2ff651

This change is available in v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
