### ISSUE TITLE
Inconsistent increment behavior between MemoryCacheClient and RedisCacheClient

### ISSUE THREAD

**Issue by jklemmack** [ServiceStack/Issues#458]
`Cache.Increment` uses a special collection in the `MemoryCachecClient`, I assume for performance reasons. However, calling `Cache.Set<uint>(0)` on the key will NOT wipe the counter.  It will set a separate hash key to 0.

In Redis, it appears to use a common pool of keys and IncBy and Set.

This popped up as a failing test in my testing suite.  In test land I am using MemoryCacheClient, and in production Redis.  Ideally they should have identical (or more similar) behavior.

**Comment by mythz** [comment]
Can you provide an example of the failing code?

**Comment by mythz** [comment]
I just figured out what you meant by this, should now be fixed in this commit: https://github.com/ServiceStack/ServiceStack/commit/da42d21bb516d3745b33a9b79f63b5a9db2333ea

**Comment by jklemmack** [comment]
Gah - thanks.  Real life interfered with making a reproducible demo.  Thanks Demis.
