### ISSUE TITLE
Problem in my custom class inherited from SqlExpression.

### ISSUE THREAD

**Issue by OlegNadymov** [ServiceStack/Issues#460]
I'm trying to make CustomSqlExpression (class inherited from SqlExpression). In this class I've implemented support for complex filter like that:
```C#
var complexFilter = db.From<AnyObjectClass>().Where(xx => xx.SomeProperty1.SomeProperty2.SomePropertyN.AnyField == "anyValue");
```
But after update to OrmLite v.4.0.60 I had a problem in my class for filter for boolean property e.g.:
```C#
var complexBoolFilter1 = db.From<AnyObjectClass>().Where(xx => xx.SomeProperty1.SomeProperty2.SomePropertyN.AnyBoolField == true);
```
At once this filter works correctly:
```C#
var complexBoolFilter2 = db.From<AnyObjectClass>().Where(xx => xx.SomeProperty1.SomeProperty2.SomePropertyN.AnyBoolField);
```

I checked source code of origin SqlExpression and I came to below conclusion.
 To solving my problem could you make method ``protected bool IsFieldName(object quotedExp)`` to ``protected virtual`` instead of only ``protected``? 
Or second way: could you make for field ``List<ModelDefinition> tableDefs = new List<ModelDefinition>();`` protected property (in SqlExpression class) for access to this field from my CustomSqlExpression (this way is less preferred).

I hope for your understanding.

**Comment by mythz** [comment]
I've made `IsFieldName()`, `modelDef` and `tableDefs` protected in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/795bc73b033c62c5aca5c84ed1cc89385e6b8bce

This change is available from v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

> Note: it's easier and faster to just send a PR to change accessibility modifiers.

**Comment by OlegNadymov** [comment]
It is cool! Thank you very much!

**Comment by OlegNadymov** [comment]
@mythz I don't understand about "to just send a PR to change accessibility modifiers.". 
What do you mean? And how can I do this?

**Comment by mythz** [comment]
All our repositories are on Github, e.g. OrmLite is located at: https://github.com/ServiceStack/ServiceStack.OrmLite

You can contribute minor changes like this via a pull request: https://help.github.com/articles/creating-a-pull-request/

**Comment by OlegNadymov** [comment]
Ok! In the future I will try it.
