### ISSUE TITLE
Setting [ApiMember] on one property hides all others in swagger

### ISSUE THREAD

**Issue by dylanvdmerwe** [ServiceStack/Issues#462]
I have marked one property with an ApiMember description:

```
    public class ServiceRequest: IServiceRequest, IHasApiKey
    {
        [ApiMember(Description = "The API Key required for authentication", DataType = "string", IsRequired = true)]
        public string ApiKey { get; set; }
    }
```

All my requests inherit from the above class:
![image](https://cloud.githubusercontent.com/assets/2852839/16866356/b8d4beb6-4a6b-11e6-82f6-1c85503f1b11.png)

In Swagger only the ApiKey property is displayed.

![image](https://cloud.githubusercontent.com/assets/2852839/16866383/dc1f7014-4a6b-11e6-9aba-04c392728f7b.png)

If the ApiMember attribute is remove, all request parameters are displayed.

**Comment by mythz** [comment]
That's by design which follows the same behavior as `[DataMember]` where by default all properties are exported but if you annotate your DTO with `[ApiMember]` it becomes opt-in and you need to annotate each property you want exported.
