### ISSUE TITLE
Show allowed enum values in metadata

### ISSUE THREAD

**Issue by dylanvdmerwe** [ServiceStack/Issues#463]
I have the following request:

```
    public enum HeadlineType
    {
        FrontPage, 
    }

    [Route("/headline/{HeadlineType}", "GET", Summary = @"Get a list of all headlines from Time Media RSS feeds")]
    public class GetHeadline : PagedServiceRequest, IReturn<GetHeadlineResponse>
    {
        [ApiMember(IsRequired = true, DataType = "HeadlineType", Description = "Headline type will default to Frontpage. Options are are only Frontpage for the moment.")]
        public HeadlineType HeadlineType { get; set; }
    }
```

Should the metadata page not show a list of all enums used in the request and responses so consumers of the API know which values are allowed? ServiceStack should have this information available.

It would also be good for Swagger to show a dropdown for this field?

Example of meta data:
![image](https://cloud.githubusercontent.com/assets/2852839/16867388/dd5cbc42-4a71-11e6-8ac9-c3958559c3cb.png)

**Comment by mythz** [comment]
Hey Dylan, Can you ask technical support questions in the Customer Forums or StackOverflow, the priority issues list is only for reproducible bugs.

You need to add `[ApiAllowableValues]` attribute to display Enum values, e.g:

```csharp

[ApiMember(IsRequired = true, DataType = "HeadlineType")]
[ApiAllowableValues("HeadlineType ", typeof(HeadlineType))]
public HeadlineType HeadlineType { get; set; }
```

**Comment by dylanvdmerwe** [comment]
Sorry I did think it was a bug. No worries and thanks for the information!
