### ISSUE TITLE
Mapping problem when setting PropertyName

### ISSUE THREAD

**Issue by krillehbg** [ServiceStack/Issues#464]
Hi,

i'm using ORMLite with servicestack.
I have problems that my properties are not mapped for some columns when setting another PropertyName.

For example in my T4 template i have this

`tables["EventPrice"]["EventPriceVAT"].PropertyName="PriceVAT";`

But i get null in the field when running this query
`
            var prices = Db.Select(
                Db.From<ServiceModel.Db.ServicePrice>()
                    .Where(p => p.ServiceId == service.Id)
                );

            service.Prices = prices.ToList();`

If i leave the template with the same name it works

`tables["EventPrice"]["EventPriceVAT"].PropertyName="EventPriceVAT";`

What am i doing wrong?

Thanks

**Comment by Layoric** [comment]
Hi @krillehbg ,

This question is probably better suited to the customer forums or a StackOverflow question as the [issues list is used to track reproducible issues/bugs](https://github.com/ServiceStack/Issues).

Best place to start looking what why you might be having issues mapping responses from OrmLite is to look at code the T4 template is generating. If the property name changes, the property will need to have a column `[Alias]`. Best if you can provide all the code related to the query so others can work out what the problem might be. The code provided above doesn't look complete as the `Db.Select` or `Db.From` should be specifying the type that is used in the query somewhere.

Could you provided a stand alone example of the problem and post a StackOverflow question? We monitor SO regularly to help out with problems just like this :+1:
