### ISSUE TITLE
dotnet core clr support

### ISSUE THREAD

**Issue by joelharkes** [ServiceStack/Issues#466]
Hey Demis,

I was (and probably more people are) wondering if and when servicestack is going to work on dotnet core. Judging based on latest nuget package there is no core support yet.

Is there any roadmap you are working on? can  we expect to see partial core support any time soon?

**Comment by mythz** [comment]
Hi,

Please [vote for this feature request](https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/10286952-support-dnx) to get notified of progress updates to .NET CoreCLR support, which also contains info for CoreCLR support in the comments.

> Please use the [Customer Forums](https://forums.servicestack.net/) for support questions, this issues list is only for [reporting reproducible bugs/issues](https://github.com/ServiceStack/Issues#servicestack-issues).
