### ISSUE TITLE
Typo error in property name

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#468]
On `ServiceStack.Text.CsvConfig`

```
public static string ItemSeperatorString
    {
      get
      {
        return CsvConfig.tsItemSeperatorString ?? CsvConfig.sItemSeperatorString ?? ",";
      }
      set
      {
        CsvConfig.tsItemSeperatorString = value;
        if (CsvConfig.sItemSeperatorString == null)
          CsvConfig.sItemSeperatorString = value;
        CsvConfig.ResetEscapeStrings();
      }
    }
```

`Seperator` should be spelled `Separator`.
Are concerned:

- tsItemSeperatorString
- sItemSeperatorString
- ItemSeperatorString

**Comment by mythz** [comment]
It's unfortunate, but it's misspelt in a lot of different places that have been part of the public API for years which would cause a lot of breaking changes and/or duplication to change it now, so we're stuck with it.

**Comment by labilbe** [comment]
Private members could be changed and public members properties could be marked as `Deprecated` until a major version.

**Comment by mythz** [comment]
that would mean duplicate properties uglifying the API surface area, that's gone years without being noticed so I don't intend to change it now. If it was a newer API I could deprecate it and remove the old API name very soon later, but it's baked into the libraries for too long to consider removing.

**Comment by labilbe** [comment]
Ok thank you.
