### ISSUE TITLE
Java JsonServiceClient Utils.createResponseStatus exception

### ISSUE THREAD

**Issue by jamesXUI** [ServiceStack/Issues#470]
Hey,

I was trying out the Android Studio Add ServiceStack Reference feature, the JsonServiceClient is throwing an exception when the service is authenticated and returns an unauthorized code:
```
java.lang.UnsupportedOperationException: JsonNull

	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
	at net.servicestack.client.Utils.createResponseStatus(Utils.java:555)
	at net.servicestack.client.Utils.createResponseStatus(Utils.java:537)
	at net.servicestack.client.JsonServiceClient.createException(JsonServiceClient.java:216)
	at net.servicestack.client.JsonServiceClient.send(JsonServiceClient.java:339)
```

The problem appears to be in net.servicestack.client.Utils.createResponseStatus, if errorcode, message or stacktrace (in the response) are null, the code does not handle this, it tries to invoke getAsString() on a JsonNull (JsonElement):
```
JsonElement e = obj.get(key);
if(varName.toLowerCase().equals("errorcode")) {
    status.setErrorCode(((JsonElement)jsonElementEntry.getValue()).getAsString());
} else if(varName.toLowerCase().equals("message")) {
    status.setMessage(((JsonElement)jsonElementEntry.getValue()).getAsString());
} else if(varName.toLowerCase().equals("stacktrace")) {
    status.setStackTrace(((JsonElement)jsonElementEntry.getValue()).getAsString());
```

Seems like this is something that needs to be handled better in createResponseStatus or am I way off?

**Comment by mythz** [comment]
I've added a test to check for handling an empty 401 Unauthorized response in this commit: https://github.com/ServiceStack/ServiceStack.Java/commit/db4267cf6cfd7d78e249cd5993bd370395253411

Which works in both Java and the Android Emulator. 

Can you include the Java client code and the HTTP Request/HTTP Response Headers of the request that's causing the issue, you should be able to get it using [Fiddler](http://www.telerik.com/fiddler) or Wireshark.
