### ISSUE TITLE
ServiceStack.OrmLite license expiration issue

### ISSUE THREAD

**Issue by mattburton** [ServiceStack/Issues#471]
I'm not sure where else to post this, so please contact me directly with any questions related to billing, etc... but we renewed our ServiceStack.OrmLite license on 1/21/2016 (Order #2947) for 3 seats and when we went to update our packages recently we are being presented with an error message that our license expired on 5/27/2016 - I can't imagine that the license would only have a lifetime of 4 months, so I'm wondering if there is an issue with the license key we were issued at that point in time when we upgraded? Any help would be appreciated.

**Comment by mythz** [comment]
Hi Matt, Can you please email this licensing issue to team@servicestack.net.
