### ISSUE TITLE
ConnectTimeout query parameter ignored

### ISSUE THREAD

**Issue by Savvkin** [ServiceStack/Issues#475]
Hello,
Seems like that `RedisManagerPool` and `PooledRedisClientManager` ignores `ConnectTimeout` query parameter, specified via connection string.

This:
```c#
var redis = new PooledRedisClientManager("redis://127.0.0.1:6379?ConnectTimeout=1000");
var dt = DateTime.UtcNow;
try { redis.GetClient(); }
catch { Debug.WriteLine($"Got timeout in {DateTime.UtcNow - dt}"); }
```
Outputs:
```
Got timeout in 00:00:10.6117882
```
So it's 10 seconds instead of 1 second!

However, `RedisEndpoint` is parsed correctly using `.ToRedisEndpoint()`
```
"redis://127.0.0.1:6379?ConnectTimeout=100".ToRedisEndpoint()
```
but `RedisManagerPool` and `PooledRedisClientManager` don't accept it.

Thanks.

**Comment by mythz** [comment]
This is expected behavior as the [DefaultRetryTimeout is 10 seconds](https://github.com/ServiceStack/ServiceStack.Redis/blob/master/src/ServiceStack.Redis/RedisConfig.cs#L110) so the Redis Client should [continue to retry failed connections](https://github.com/ServiceStack/ServiceStack.Redis#automatic-retries) for up to 10 seconds.

**Comment by Savvkin** [comment]
But in [Redis Connection Strings](https://github.com/ServiceStack/ServiceStack.Redis/blob/master/README.md#redis-connection-strings) section says that

> Any additional configuration can be specified as QueryString parameters. The full list of options that can be specified include:
> ConnectTimeout | int | Timeout in ms for making a TCP Socket connection

So, I expect that the following connection string should override `DefaultRetryTimeout` and set `ConnectTimeout` to one second :
> redis://clientid:password@localhost:6380?ConnectTimeout=1000

**Comment by mythz** [comment]
Theres nothing to override: ConnectTimeout specifies how long it should wait to make a single connection, Retry Timeout specifies how long it should keep retrying to make a successful connection or operation, etc.

**Comment by Savvkin** [comment]
How do I get my code working, as I expect, then?
What do I need to specify in **connection string** to make `redis.GetClient();` throw timeout exception after 1 second instead of 10 seconds when Redis in not available or gone down?

> redis://clientid:password@localhost:6380?ConnectTimeout=1000&RetryTimeout=1000

**Comment by mythz** [comment]
Disable Automatic retries? 

    redis://clientid:password@localhost:6380?ConnectTimeout=1000&RetryTimeout=0

Which you can do globally with:

    RedisConfig.DefaultRetryTimeout = 0;
