### ISSUE TITLE
Could not load file or assembly 'System.Core, Version=2.0.5.0' exception while running Redis application

### ISSUE THREAD

**Issue by Akshitha26** [ServiceStack/Issues#476]
While executing the Redis application, I am getting the following exception 

System.IO.FileLoadException: Could not load file or assembly 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
File name: 'System.Core, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'
   at ServiceStack.Redis.PooledRedisClientManager..ctor(IEnumerable`1 readWriteHosts, IEnumerable`1 readOnlyHosts, RedisClientManagerConfig config, Nullable`1 initalDb, Nullable`1 poolSizeMultiplier, Nullable`1 poolTimeOutSeconds)
   at ServiceStack.Redis.PooledRedisClientManager..ctor(String[] readWriteHosts)
   at RedisCache.RedisCacheDataManager..cctor()

I have .NET framework 4.0 installed in my system. Please help us resolve this issue.

**Comment by xplicit** [comment]
Do you use portable class libraries in your project? If yes, please check  that you have installed patch for .NET4 on your machine https://www.microsoft.com/en-us/download/details.aspx?id=3556

If it's not your case please describe what is the target platform of your project and how did you add ServiceStack.Redis to your project. If you create empty project with code `var manager = PooledRedisClientManeger(...)` and add ServiceStack.Redis from nuget package do you get this exception?

**Comment by mythz** [comment]
Also note from v4.5.0 we've upgraded all packages to .NET 4.5, details at: https://github.com/ServiceStack/ServiceStack/blob/master/docs/2016/v4.5.0.md

You'll need to upgrade to .NET 4.5 in order to use the current v4.5.0 release or future versions of ServiceStack.

**Comment by xplicit** [comment]
Closed due to no response. @Akshitha26 If you still have the issue, feel free to post the details here.
