### ISSUE TITLE
ServiceStack.MsgPack.Signed missing

### ISSUE THREAD

**Issue by Savvkin** [ServiceStack/Issues#477]
Hello.
I use Signed versions of ServiceStack libs in my project.
Unfortunately, there is no signed version of ServiceStack.MsgPack available in NuGet.

Thanks.

**Comment by mythz** [comment]
We only maintain .Signed packages for popular packages, you can submit a feature request at https://servicestack.uservoice.com

Otherwise you can just copy the source files into your project from https://github.com/ServiceStack/ServiceStack/tree/master/src/ServiceStack.MsgPack
