### ISSUE TITLE
ServiceStack.OrmLite: Bug SqliteGuidConverter

### ISSUE THREAD

**Issue by Krnlsoft** [ServiceStack/Issues#478]
File: ServiceStack.OrmLite.Sqlite/Converters/SqliteGuidConverter.cs

ColumnDefinition should be BLOB(16)

method GetValue
    GetGuid throw exception:

System.FormatException: Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).

Since Mono.Data.Sqlite_2.0/SQLiteDataReader.cs

```
    public override Guid GetGuid(int i)
    {
      if (i >= VisibleFieldCount && _keyInfo != null)
        return _keyInfo.GetGuid(i - VisibleFieldCount);

      TypeAffinity affinity = VerifyType(i, DbType.Guid);
      if (affinity == TypeAffinity.Blob)
      {
        byte[] buffer = new byte[16];
        _activeStatement._sql.GetBytes(_activeStatement, i, 0, buffer, 0, 16);
        return new Guid(buffer);
      }
      else
        return new Guid(_activeStatement._sql.GetText(_activeStatement, i));
    }

```
check for type affinity 

Thank you have a nice day.

**Comment by mythz** [comment]
Can you please provide a reproducible failing test that demonstrates an issue?

**Comment by Krnlsoft** [comment]
I'll see what I can do

**Comment by Krnlsoft** [comment]
Here a small program with evidence

```
   class TestTable
   {
      public int Id { get; set; }
      public Guid Data { get; set; }
   }

   class MainClass
   {
      public static void Main (string [] args)
      {
         var dbFactory = new OrmLiteConnectionFactory ("test.db", SqliteDialect.Provider);

         using (IDbConnection db = dbFactory.OpenDbConnection ()) {

            db.CreateTableIfNotExists<TestTable> ();

            db.Delete<TestTable> (x => x.Id == 1);
            Guid guid = Guid.NewGuid ();

            db.Insert (new TestTable {
               Id = 1,
               Data = guid
            });

            var record = db.Single<TestTable> (x => x.Id == 1);
            Debug.Assert (record.Data == guid);
         }

         Console.ReadLine ();
      }
   }
```

**Comment by mythz** [comment]
This test is passing for me as-is using both in memory of file-based sqlite:

```csharp
public class TestTable
{
    public int Id { get; set; }
    public Guid Data { get; set; }
}

[TestFixture]
public class SqliteGuidIssue
{
    [Test]
    public void Can_select_Guid_in_Sqlite()
    {
        var dbFactory = new OrmLiteConnectionFactory(
            "~/App_Data/test.db".MapProjectPath(), SqliteDialect.Provider);

        using (IDbConnection db = dbFactory.OpenDbConnection())
        {
            db.CreateTableIfNotExists<TestTable>();

            db.Delete<TestTable>(x => x.Id == 1);
            Guid guid = Guid.NewGuid();

            db.Insert(new TestTable {
                Id = 1,
                Data = guid
            });

            var record = db.Single<TestTable>(x => x.Id == 1);
            Assert.That(record.Data, Is.EqualTo(guid));
        }
    }
}
```

What package and version of Sqlite are you using?

**Comment by Krnlsoft** [comment]
Mono.Data.Sqlite
[assembly: AssemblyVersion ("2.0.0.0")]
[assembly: AssemblyFileVersion ("1.0.61.0")]

**Comment by Krnlsoft** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="ServiceStack" version="4.5.0" targetFramework="net45" />
  <package id="ServiceStack.Client" version="4.5.0" targetFramework="net45" />
  <package id="ServiceStack.Common" version="4.5.0" targetFramework="net45" />
  <package id="ServiceStack.Interfaces" version="4.5.0" targetFramework="net45" />
  <package id="ServiceStack.OrmLite" version="4.5.0" targetFramework="net45" />
  <package id="ServiceStack.OrmLite.Sqlite.Mono" version="4.5.0" targetFramework="net45" />
  <package id="ServiceStack.Text" version="4.5.0" targetFramework="net45" />
</packages>
```

**Comment by mythz** [comment]
ok but this is working in both Windows and Mono: 

 - http://gistlyn.com/?gist=2d0d85b8857725fd456bd0a50bb6fda2
 - http://mono.gistlyn.com/?gist=2d0d85b8857725fd456bd0a50bb6fda2

Can you save a modified copy of the above script that demonstrates an issue?

**Comment by Krnlsoft** [comment]
Still digging I can't reproduce the error on the gist online,
but i found out that by setting OrmLiteConfig.DeoptimizeReader = false
db.Single... > PopulateWithSqlReader > reader.GetValues gets called 
and then reader.GetGuid throws the casting exception.
(maybe some wrong type mapping cache by sqlite GetValues)

Instead by setting OrmLiteConfig.DeoptimizeReader = true
reader.GetGuid works because reader.GetValues is not called.

Looks like it's some strange issue on sqlite side (only on my workstations).
I've tried updating my sqlite on linux up to sqlite-3.14.1, but still not working.

Here the results of my testings:
Windows 10 x64 (Xamarin.Android): Fail
Gentoo Linux x64 (MonoDevelop): Fail
Linux Wine x64: Success

**Comment by mythz** [comment]
Ok this is a known issue and why we've [disabled Optimized Reader](https://github.com/ServiceStack/ServiceStack.OrmLite/blob/68a6322eea905691d6653e01f99a80bfbb504ef7/src/ServiceStack.OrmLite.Sqlite.Windows/SqliteOrmLiteDialectProvider.cs#L14) in Windows version of Sqlite since the behavior is different to the Mono version of Sqlite which we mention in a comment in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/36624b4f71168e99041655c91941ed1cb002cb7b

The bug is in the underlying System.Data.SQLite.Core ADO.NET Provider where calling `reader.GetValues()` changes the behavior of `reader.GetGuid()` and why we deoptimize the reader.
