### ISSUE TITLE
JwtAuthProviderReader throwing unhandled exception when token is invalid

### ISSUE THREAD

**Issue by StephenMIdeagen** [ServiceStack/Issues#479]
Hi there,

When passing an expired token to the JwtAuthProviderReader a TokenException is thrown, this abruptly ends the PreAuthenticate request resulting in the HandleFailedAuth never being hit. The knock on effect is that the JsonServiceClient receives a cors issue due to processing terminating at this point. I've got around this with the following;

`    internal sealed class CustomJwtAuthProviderReader : JwtAuthProviderReader, IAuthWithRequest
    {
        public CustomJwtAuthProviderReader(IAppSettings appSettings) : base(appSettings)
        {
        }

        public new void PreAuthenticate(IRequest req, IResponse res)
        {
            try
            {
                base.PreAuthenticate(req, res);
            }
            catch (TokenException e)
            {
                res.OutputStream.Write(e.Message);
            }
        }
    }`

**Comment by mythz** [comment]
We've got an integration test showing trying to call a Service with an expired token [returns a Unauthorized Error Response](https://github.com/ServiceStack/ServiceStack/blob/e01398b32fe04df0fe353fdd1bb42c79cb5d0cf9/tests/RazorRockstars.Console.Files/StatelessAuthTests.cs#L1411-L1412) and I can't work out what steps are required to go about reproducing this error from just this description. 

Can you provide the raw HTTP Request/Response Headers showing that shows the issue as well as a stub of the Service (impl not required) and Request/Response DTOs you're calling including any attributes,.

Can you also provide the `JsonServiceClient` client code you're using.

**Comment by mythz** [comment]
I need more info requested above to be able to investigate and repro this issue further.
