### ISSUE TITLE
OrmLite InsertOnly not accounting for attributes

### ISSUE THREAD

**Issue by CormacBrennan-AI** [ServiceStack/Issues#481]
I think that there is a problem with the OrmLite InsertOnly method. It does not seem to be accounting for attributes on entity fields.

The commit below contains two tests that fail on SQL Server and Sqlite.

[https://github.com/CormacBrennan-AI/ServiceStack.OrmLite/commit/c9a7eeb014db08c83fe54e5f65cd8f0280217dba](https://github.com/CormacBrennan-AI/ServiceStack.OrmLite/commit/c9a7eeb014db08c83fe54e5f65cd8f0280217dba)

**Comment by mythz** [comment]
Hi Cormac,

Can you submit this as a PR so I can check it out?

**Comment by CormacBrennan-AI** [comment]
Hi Demis,

Just raised it: https://github.com/ServiceStack/ServiceStack.OrmLite/pull/532

**Comment by mythz** [comment]
Thanks for the repro! Should now be resolved with this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/543e568e9d38826924a4a6b1c97f889df769ec29

This change is available from v4.5.1 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
