### ISSUE TITLE
run time failure on sqlite database lookup command

### ISSUE THREAD

**Issue by chris-hawley** [ServiceStack/Issues#482]
background info needed for reproducing: 
i'm using the mono-release of service stack. 
i'm using the latest version
i'm using .net 4.6.1

Code used(note: these are just the pieces for needed for reproducing. the code is not necessarily runable as is ):
```
public class questionword
  {
    public long Id { get; set; }

    [Index]
    public string word { get; set; }
    public string type { get; set; } //yn or open
  }
public static ServiceStack.OrmLite.OrmLiteConnectionFactory dbFactory = new ServiceStack.OrmLite.OrmLiteConnectionFactory("NLP", ServiceStack.OrmLite.SqliteDialect.Provider);
public System.Data.IDbConnection db = dbFactory.Open();
str = "what is life?"
List<questionword> p = db.Select<questionword>(x => str.StartsWith(x.word));
```

**Comment by chris-hawley** [comment]
problem also occurs on .net 4.5.2

**Comment by mythz** [comment]
This isn't supported, StartsWith method gets converted into SQL with the pattern on the right, something similar to:

    Field LIKE 'pattern%'

You can't reverse the match with:

    'what is life?%' LIKE Field

So you can only perform queries like:

```csharp
var p = db.Select<questionword>(x => x.word.StartsWith(str));
```

Or you can perform the query on the client with LINQ on the returned resultset, e.g:

```csharp
var str = "what is life?";
var p = db.Select<questionword>().Where(x => str.StartsWith(x.word)).ToList();
```
