### ISSUE TITLE
override ConfigUtils.GetNullableAppSetting

### ISSUE THREAD

**Issue by hgp7369** [ServiceStack/Issues#485]
PlatformNet.cs  needs override GetNullableAppSetting 
`public override string GetNullableAppSetting(string key)
        {
            return ConfigurationManager.AppSettings[key];
        }`

**Comment by mythz** [comment]
Thanks, Added in this commit: https://github.com/ServiceStack/ServiceStack/commit/ea862fe51a2cd1d3d4c1dbc45b8ab2de7620874b
