### ISSUE TITLE
Redis List Query missing data

### ISSUE THREAD

**Issue by emreyalcincom** [ServiceStack/Issues#486]
I query a list with items count 1200. After the 1001. item I cannot query the items between 1001 and 1200. For example I query the count in the list and it gives my always 1001 value but there are more than 1001.

**Comment by xplicit** [comment]
Can you provide stand-alone example which will reproduce the issue?

**Comment by emreyalcincom** [comment]
I just ınsert more than 1001 ıtem to a lıst. forexample the poco entıty has 2 property name surname. After the ınsert from 1001 st ıtem, I cannot query the data ıt returns null

Emre Yalçın +90 531 680 24 58
Send from my iPhone

Sergey Zhukov <notifications@github.com> şunları yazdı (19 Eyl 2016 16:57):

**Comment by xplicit** [comment]
Can you please provide a example of code how exactly you are doing this (inserting and quering)? In this case we can reproduce it on our side and understand the cause of the issue.

**Comment by emreyalcincom** [comment]
I wıll send the code now ok

Emre Yalçın +90 531 680 24 58
Send from my iPhone

Sergey Zhukov <notifications@github.com> şunları yazdı (19 Eyl 2016 17:09):

**Comment by emreyalcincom** [comment]
public class MyUser

    {

        public string Id { get; set; }

 

 

        public string Name { get; set; }

    }

 

static void Main(string[] args)

        {

 

   var connectionStringx = "cacheServerAddress";

 

            var pooledRedisClientManagerx = new PooledRedisClientManager(connectionStringx);

 

            using (var azureRedisManager = pooledRedisClientManagerx.GetClient())

            {

                var myuserList = azureRedisManager.As<MyUser>().Lists["MyUsers"];

 

                for (int i = 1; i < 1201; i++)

                {

                    MyUser user = new MyUser();

                    user.Id = Guid.NewGuid().ToString();

                    user.Number = i;

                    user.Name = i.ToString() + " User";

                    myuserList.Add(user);

                }

 

                var itemOf1150 = myuserList.FirstOrDefault(x => x.Number == 1150);

 

                //The variable itemOf1150 is null   

}

}

**Comment by xplicit** [comment]
That's because System.Linq.FirstOfDefault looks in the cached buffer of the redis list, not in the redis itself. 

To get access to the 1150 element in the list you can use such constructions:

    //gets the element by index from the list
    var item = myuserList[1149];  

    or if you want to use LINQ:

    //gets the list from redis to memory and allows to use LINQ methods on it.
    var item = myuserList.ToList().FirstOrDefault(x => x.Number == 1150);

**Comment by emreyalcincom** [comment]
what wıll I do ıf the record ıs ın the 111111111th record

Emre Yalçın +90 531 680 24 58
Send from my iPhone

Sergey Zhukov <notifications@github.com> şunları yazdı (20 Eyl 2016 14:03):

**Comment by xplicit** [comment]
In that case you can use:

    var item = myuserList[111111110];

This will return only the 111111111th record from redis without downloading the whole list.

If you need to work with large amount of data in redis then you should reorganize your data. For example, if you are going to access your users only by Number field, then you'd better to use 
`Add<MyUser>(key, value)` method, where `key` is the value of `Number` field and `value` - the user object. 

     var user =  new MyUser(){ Number=11111111, Name="11111111th user"};

     //add user to redis
     azureRedisManager.Add<MyUser>(user.Number.ToString(), user);
     
     //get user by number
     user = azureRedisManager.Get<MyUser>("11111111");

if you need to find users by crtiteria on several fields then you'd better to use Relational Database instead of NoSQL Redis, because the main purpose  of Redis is effective server implementation of the dictionary structure, but not the searching data by user-defined criterias.

**Comment by emreyalcincom** [comment]
thanks a lot

Emre Yalçın +90 531 680 24 58
Send from my iPhone

Sergey Zhukov <notifications@github.com> şunları yazdı (20 Eyl 2016 15:48):
