### ISSUE TITLE
Update Servicestack Typescript Reference generates concrete method on interface

### ISSUE THREAD

**Issue by riesvriend** [ServiceStack/Issues#487]
In the example below, the createResponse() and getTypeName() methods have an implementation, which is not allowed on an interface. This happens in v4.50, was not there in v4.0.54 used before.

/* Options:
Date: 2016-09-28 17:21:28
Version: 4.50
Tip: To override a DTO option, remove "//" prefix before updating
BaseUrl: http://localhost:81/api

//GlobalNamespace: 
ExportAsTypes: False
//MakePropertiesOptional: True
//AddServiceStackTypes: True
AddResponseStatus: True
//AddImplicitVersion: 
//AddDescriptionAsComments: True
//IncludeTypes: 
//ExcludeTypes: 
//DefaultImports: 
*/

// @Route("/HandlingStatusFromFboImport/")
interface StatusFromHandlerImportRequest extends IReturn<StatusFromHandlerImportResponse>
{
    handlingStatusFromFbo?: FboHandlingStatus[];
    createResponse() { return new StatusFromHandlerImportResponse(); }
    getTypeName() { return "StatusFromHandlerImportRequest"; }
}

**Comment by mythz** [comment]
Apologies, this should be resolved from this commit: https://github.com/ServiceStack/ServiceStack/commit/97f7a21ac2d0ecbfbac543da80114caa1351ca2a

Which is available from v4.5.1 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
