### ISSUE TITLE
Custom auth provider not working with firebase

### ISSUE THREAD

**Issue by vince-nyanga** [ServiceStack/Issues#488]
I'm trying to create a custom credentials auth provider that signs in using firebase. The service hangs after calling an async task to request firebase authentication in the TryAuthenticate() method

**Comment by mythz** [comment]
I've already provided [an answer to your StackOverflow question](http://stackoverflow.com/a/39743267/85785). 

This issue tracker is for reporting reproducible issues with ServiceStack libraries. Your Custom implementation uses a 3rd Party libraries and it's likely your async implementation is dead-locking from using async/await in a sync method.

**Comment by vince-nyanga** [comment]
Thanks @mythz . However, the solution you suggested did not work. I tested the third part library in a normal service call returning `async Task<object>` and it worked. Once I removed the async task the browser hanged again like it does in the custom auth provider. I also tried using HttpClient and stilll got same result.

**Comment by mythz** [comment]
You can't use async/await from a sync method, having a `async Task<object>` response type in your Service uses an async method.

You can try using `ConfigureAwait(false)`, e.g:

```csharp
private Task<bool> Authenticate(string userName,string password)
{
    provider = new FirebaseAuthProvider(new FirebaseConfig(firebaseApiKey));
    return provider.SignInWithEmailAndPasswordAsync(userName, password).ConfigureAwait(false)
        .Success(r => r.User != null)
        .Error(ex => false);
}
```
