### ISSUE TITLE
Automigrations

### ISSUE THREAD

**Issue by Ma3yTa** [ServiceStack/Issues#489]
I saw in your API already there is methods to do this like: 
db.AlterColumn 
db.AlterTable 
db.AddColumn

Just need to implement diff between Domain Modes and schema DB. 

I think need to have db.GetColumns<T>():List<FieldDefinition> which populate fields description from DB to move forward with automigrations.

**Comment by mythz** [comment]
This is a [Feature Request](https://servicestack.uservoice.com/) not a [reproducible issue with our current libraries](https://github.com/ServiceStack/Issues#you-can-view-existing-issues-or-report-a-new-issue).

You can already access the current Schema info with supported RDBMS's with [GetSchema / GetSchemaTable APIs](https://msdn.microsoft.com/en-us/library/kcax58fh(v=vs.110).aspx), but it's not feasible to properly populate the `FieldDefinition` from an RDBMS which is meant from mapping code-first POCOs to an RDBMS not the other way round.
