### ISSUE TITLE
Make SqlExpression<T>.Update(IEnumerable<string> fields) case-insensitive like Select(string[] fields)

### ISSUE THREAD

**Issue by sharakouze** [ServiceStack/Issues#491]
In this sample, the Get() method works perfectly regardless of string case. On the other hand, the Patch() method fails, and I must give the correct case for fields in the Update methods or these fields won't be updated.

```
public class MyPoco1
{
    public string Name { get; set; }
    public int Foo { get; set; }
    public int Bar { get; set; }
}

public class MyService : ServiceStack.Service
{
    public MyPoco1 Get(MyRequest request)
    {
        var q1 = Db.From<MyPoco1>().Select(new[] { "NAME" });

        // Ok
        return Db.Single(q1);
    }

    public void Patch(MyRequest request)
    {
        var model = new MyPoco1() { Name = "new name" };
        var q2 = Db.From<MyPoco1>().Update(new[] { "NAME" });

        // Fails because NAME != Name
        Db.UpdateOnly(model, q2);
    }
}
```
It would be cool if Select() and Update() methods had the same behavior.
Thank you !

**Comment by mythz** [comment]
Historically we've only been relaxed in mapping fields from resultsets in SELECT to POCOs and prefer the Write APIs to have explicit matches but I can see the argument for consistency so I've made Update/Insert only fields case insensitive from [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/253acdd2b63b9e758fae9311b49a47b2d1d55793).

This change is available from v4.5.1 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
