### ISSUE TITLE
System.Reflection.Emit issues when using HttpUtils on a fresh Xamarin.Mac app

### ISSUE THREAD

**Issue by robertmiles3** [ServiceStack/Issues#492]
As an example, I created a fresh Xamarin.Mac app and simply added ServiceStack.HttpClient.Core from NuGet. At that point, the app will compile and run just fine. However, when I added just 1 line such as...

    var test = "https://google.com".GetStringFromUrl ();

...it will compile fine but bomb at runtime with an error about missing System.Reflection.Emit (sometimes it cries about System.Reflection.Emit.Lightweight).

[TestXamMac.zip](https://github.com/ServiceStack/Issues/files/515980/TestXamMac.zip)

This is using all the latest Xamarin stuffs, running on macOS Sierra.

**Comment by mythz** [comment]
You need to switch to use the **Xamarin.Mac .NET 4.5 Framework** in `Project -> Options -> Build -> General`. You'll likely need to do this in a new solution before adding the NuGet packages.

Also why would you use the .NET Core package instead of the normal `ServiceStack.HttpClient` package?
