### ISSUE TITLE
HttpUtils.SendStringToUrl Return Chinese with Garbled

### ISSUE THREAD

**Issue by hgp7369** [ServiceStack/Issues#494]
add Encoding.Default or Encoding.GetEncoding("GB2312") can resolve it
`using (var reader = new StreamReader(stream,Encoding.Default)))
            {
                responseFilter?.Invoke((HttpWebResponse)webRes);
                return reader.ReadToEnd();
            }`

**Comment by mythz** [comment]
The Encoding for HttpUtils is now overridable with:

```csharp
HttpUtils.UseEncoding = Encoding.Default;
```

This change is available from v4.5.1 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).
