### ISSUE TITLE
OrmLite ternary operator creates invalid SQL query.

### ISSUE THREAD

**Issue by eocron** [ServiceStack/Issues#495]
In my code operator (?:) creates invalid query on usage. It uses it's original code name instead of alias:

            var flightsQuery = _odc.From<period>()
                                   .Join<period, route>((nfp, nfr) => nfp.id_route == nfr.Id)
                                   .Join<route, flight>((nfr, nf) => nfr.id_flight1 == nf.Id || nfr.id_flight2 == nf.Id)
                                   .Where<period>(nfp => nfp.calc_quote == 1 && nfp.Id == tarifId)
                                   .Select<period, flight>((nfp, nf) =>
                                                                          new
                                                                          {
                                                                                      ServiceTypeID = ServiceTypeId,
                                                                                      ContractorID = nfp.id_partner > 0 ? Const1 + nfp.id_partner : Const2 + nf.id_airline,
                                                                                      Name = nf.name.Trim(),
                                                                                      Alias = nf.name.Trim(),
                                                                                      FieldID = nf.Id,
                                                                                      Field = nfp.Id.ToString(),
                                                                          });

this query generates this code:

    SELECT 2, IIF((nfp.id_partner > 0), (4000000 + nfp.id_partner), (3000000 + nf.id_airline)), ltrim(rtrim("flight"."name")), ltrim(rtrim("flight"."name")), "flight"."id" AS "FieldID", cast("period"."id" as varchar(1000))

As you see, IIF SQL opearation contains invalid expression.

**Comment by mythz** [comment]
The Select Expression is only for selecting which fields to return. Other than a simple field mapping, the only complex expressions that are currnetly supported are defined on the `Sql.*` static class.
