### ISSUE TITLE
Server Sent Events blocking threads

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#496]
I am having a small problem when using SSE.
Many of my threads are never returning and stuck in HandledUnsubscription after calling NotifySession.

It seem to happen if NotifySession and Create is called at the same time. 

If you need more information, just say so.

![image](https://cloud.githubusercontent.com/assets/391714/19563239/975460e6-96df-11e6-99f4-1c9f29fa294c.png)

**Comment by mythz** [comment]
Can you provide your `ServerEventsFeature` registration inc. if you're using `RedisServerEvents` or not.

**Comment by dlj** [comment]
Sure
NotifyChannelOfSubscriptions = false,
LimitToAuthenticatedUsers = true,
HouseKeepingInterval = new TimeSpan(long.MaxValue),

Nothing else, not using redis.
NotifySession is called from a static class that has an internal concurrency safe dictionary.
I can reproduce it if the server is started and a client connects to it before it has started 100%

**Comment by mythz** [comment]
You can reproduce it? Great, can you send me a small stand-alone repro please?

**Comment by dlj** [comment]
It took me a couple of days to figure this out.
Here is a video and a short description.

https://www.youtube.com/watch?v=_ESbyjjYyeA

Steps to Reproduce.

1. Start Project
2. Start Web Page
3. Wait for project to start up and the SSE to connect
4. Stop Web Page.
5. Change timeout.
6. Start Project again.
7. Wait for project to start up and the SSE to connect

In my production code, it happens when i change the code and it needs to recompile, eg, the startup is slower.

Test project used.
[Blocking Test Project.zip](https://github.com/ServiceStack/Issues/files/550034/Blocking.Test.Project.zip)

The only thing "special" here is my web worker. But i can't see this having any effect on the outcome, other than the connection is made the moment it can be made.
This could still happen if a client is connected fast enough the normal way.

**Comment by mythz** [comment]
Thanks for the steps + solution, I've been able to repro it which appears to be caused from Subscription Exceptions which ends up calling Unsubscribe multiple times which is now being prevented in [this commit](https://github.com/ServiceStack/ServiceStack/commit/c0c2aaa0b1ac83cde371b9b69a59ad0623bfb2a9).

This should resolve it as I haven't been able to repro it since. This change is available from v4.5.5 that's now [available on MyGet](http://docs.servicestack.net/myget).

Please let me know if it resolves it for you as well?

**Comment by dlj** [comment]
As of now, the MyGet feed seems to be empty.

**Comment by mythz** [comment]
ok MyGet had some delay issues, I cleared the packages before publishing the latest version but it looks MyGet they cleared the packages after deploying. The latest version should be up on MyGet now.

**Comment by dlj** [comment]
After upgrading to v4.5.5 i can't reproduce this anymore.
Cheers !

**Comment by mythz** [comment]
Great, glad to hear it :)
