### ISSUE TITLE
Impossible to insert a simple POCO with one property

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#497]
_Tested with ServiceStack 4.5.2
.NET Framework 4.6.2
SQL Server 2016 Developer Edition_

Here is the following piece of code to reproduce the behavior (you must create mydb database before)

```
    public class Withdrawal : IHasIntId
    {
        [PrimaryKey]
        [AutoIncrement]
        public int Id { get; }
    }
    public class AppHost : AppHostBase
    {
        public AppHost()
            : base("MyApp", typeof(Withdrawal).Assembly) { }
        public override void Configure(Container container)
        {
            container.Register<IDbConnectionFactory>(
                c => new OrmLiteConnectionFactory("Server=.\SQLEXPRESS;Database=mydb;Trusted_Connection=True;", SqlServerDialect.Provider));

            using (var db = container.Resolve<IDbConnectionFactory>().Open())
            {
                db.DropAndCreateTable<Withdrawal>();
                db.Insert(new Withdrawal()); // <--- Problem occurs HERE !!!
            }
        }
```

Error thrown is

> An exception of type 'System.Data.SqlClient.SqlException' occurred in ServiceStack.OrmLite.dll but was not handled in user code
Additional information: Incorrect syntax near ')'.

**Comment by mythz** [comment]
It's because you can't INSERT an empty table with just an AutoIncrement Id as OrmLite just generates a:

```
INSERT INTO "Withdrawal" () VALUES ()
```

You'll need to add at least one field to insert or remove `Id` from being an `[AutoIncrement]` field so it gets inserted.

**Comment by labilbe** [comment]
Right.
