### ISSUE TITLE
use sqlserver with NoLock

### ISSUE THREAD

**Issue by hgp7369** [ServiceStack/Issues#499]
how to use ormlite Select method with "with(nolock)" or "with(HOLDLOCK)" and so on

**Comment by mythz** [comment]
OrmLite doesn't include RDBMS-specific features like this in its Typed APIs, so you would need to use the [Custom SQL APIs](https://github.com/ServiceStack/ServiceStack.OrmLite#typed-sqlexpressions-with-custom-sql-apis) to access RDBMS-specific features.

Also please note this Issue Tracker is for submitting [reproducible issues](https://github.com/ServiceStack/Issues#servicestack-issues) of existing features only. Please use the [Customer Forums](https://forums.servicestack.net/) or StackOverflow for any other support questions.

**Comment by hgp7369** [comment]
thanks
