### ISSUE TITLE
Regression when using child containers

### ISSUE THREAD

**Issue by AVee** [ServiceStack/Issues#500]
We have some code which uses child containers in Func (a child per tenant for tenant specific services). With the upgrade to 4.5.4 (from 4.5.0) a specific scenario started failing. Somehow the auto-wiring injects dependencies from the wrong container. I suspect this commit https://github.com/ServiceStack/ServiceStack/commit/7239a23c28eaccb4a4c774293b4b3e0c52c4f0a0 since that introduces a static which breaks isolation between containers. But it could be something else as well, I haven't debugged it deep enough to be sure.

This program reproduces the issue:

	using Funq;
	using System;
	using ServiceStack;

	namespace ConsoleApplication5
	{
		public class Program
		{
			static void Main(string[] args)
			{
				Container parent = new Container();

				// Create two childs, each with a specific instance Dependancy
				Container child1 = parent.CreateChildContainer();
				Container child2 = parent.CreateChildContainer();

				child1.Register(new Dependency("First"));
				child2.Register(new Dependency("Second"));

				// Now register two factories for ISomeService.
				child1.Register<ISomeService>(x => Factory(x));
				child2.Register<ISomeService>(x => Factory(x));

				ISomeService resolved1 = child1.Resolve<ISomeService>();
				ISomeService resolved2 = child2.Resolve<ISomeService>();

				Console.WriteLine("From container 1: " + ((SomeService)resolved1).dependancy.label);
				Console.WriteLine("From container 2: " + ((SomeService)resolved2).dependancy.label);

				Console.ReadKey();
			}

			public static ISomeService Factory(Container c)
			{
				// Register the service by type...
				c.RegisterAutoWiredType(typeof(SomeService), ReuseScope.Hierarchy);
				// ... and force auto-wiring to happen.
				ISomeService result = (ISomeService)c.TryResolve(typeof(SomeService));
				return result;
			}
		}

		public interface ISomeService
		{ }

		public class SomeService : ISomeService
		{
			public readonly Dependency dependancy;

			public SomeService(Dependency dependancy)
			{ 
				this.dependancy = dependancy;
			}
		}

		public class Dependency
		{
			public readonly string label;

			public Dependency(string label)
			{ 
				this.label = label;
			}
		}
	}

The expected output is (which 4.5.0 does produces):
`From container 1: First`
`From container 2: Second`

With 4.5.4 the result is:
`From container 1: First`
`From container 2: First`

It's a very specific use of Func, which is mainly caused by the fact that the actual code does some dynamic loading of assemblies as well. So the factory method is 'abusing' Func to do the initialization of services from the loaded library. 

I can probably find a way to work around it, I haven't looked into that yet. But it is a regression so there may be other unwanted side effects as well.

**Comment by mythz** [comment]
Should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack/commit/39a4cbe67e0ec15b9324ea09b8e702dbde39ffdf).

This fix is available from v4.5.5. that's now [available on MyGet](http://docs.servicestack.net/myget).

Thanks for reporting!
