### ISSUE TITLE
OrmLite not respecting unicode settings for parameters

### ISSUE THREAD

**Issue by bryancrosby** [ServiceStack/Issues#501]
For the given DbParam, the value never gets assigned to SqlDbType.VarChar -- it (rightly so) defaults to NVarChar by the ADO.NET provider, however, this behavior is not always wanted if certain databases are not using Unicode.

GetStringConverter().UseUnicode does not seem to have an effect (and is also false by default)

Given a simple POCO that I got from UpdateTests.cs

```C#
    public class SimpleType
    {
        [AutoIncrement]
        public int Id { get; set; }
        [Alias("name")]
        public string Name { get; set; }
    }
```
However, taking a look at the output on the server, 
```sql
exec sp_executesql N'UPDATE "SimpleType" SET "name"=@name WHERE (("Id" = @0) AND ("name" = @1))',N'@0 int,@1 nvarchar(max) ,@name nvarchar(19)',@0=1,@1=N'Somename',@name=N'a new updated value'
```

The following converter seems to correct the behavior
```C#
    public class NVarcharToVarcharStringConverter : StringConverter
    {
        public override void InitDbParam(IDbDataParameter p, Type fieldType)
        {
            base.InitDbParam(p, fieldType);

            var sqlParam = p as SqlParameter;
            if (sqlParam != null)
            {
                if (!UseUnicode)
                {
                    sqlParam.SqlDbType = SqlDbType.VarChar;
                }
            }
        }
    }

    cf.DialectProvider.RegisterConverter<string>(new NVarcharToVarcharStringConverter());

```

**Comment by mythz** [comment]
No worries, changed the default behavior of SQL Server strings with [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/fd8cc1da0fe4d6dfc20aca84a60c329ee780751b)

This change is available from v4.5.5 that's now [available on MyGet](http://docs.servicestack.net/myget).

Thanks for submitting!
