### ISSUE TITLE
Client PostFile(s)WithRequest encodes filename, fieldname with system default encoding

### ISSUE THREAD

**Issue by robpvn** [ServiceStack/Issues#502]
It seems that when you use the PostFileWithRequest or PostFilesWithRequest methods on a service client, the filename gets serialised with the system's default encoding even though it states in the header that it is UTF-8. When the file is received by the service implementation, the filename gets garbled if it includes any characters where the default encoding does not match UTF-8. 

In my case, on Windows 10 with system locale set to Norwegian Bokmål (Norway), the default encoding is ISO-8859-1 (Western European) and that means that Norwegian letters like æ,ø,å are not received correctly. The same thing also happens if you specify fieldname. 

Here is a single-file selfhosted demonstration, made with ServiceStack 4.5.4:

```
using System;
using System.Diagnostics;
using System.Text;
using ServiceStack;
using System.IO;
using Funq;

namespace SelfHost1
{
    class Program
    {
        static void Main(string[] args)
        {
            new AppHost().Init().Start("http://*:8088/");
            Process.Start("http://127.0.0.1:8088/");
            
            Console.WriteLine("System default encoding is " + Encoding.Default.EncodingName + " - " + Encoding.Default.BodyName);
            //On my system this is ISO 8859-1
            
            var client = new JsonServiceClient("http://127.0.0.1:8088/");
            Stream dummyStream = new MemoryStream();

            string fileName = "afilenamewith_æ_ø_å.dummy";
            string fieldName = "æøå";
            Console.WriteLine("Sending request with filename: " + fileName);
            Console.WriteLine("------------------- fieldname: " + fieldName);
            HelloResponse result = client.PostFileWithRequest<HelloResponse>(dummyStream, fileName, new Hello(), fieldName);
            //Same problem in PostFilesWithRequest

            Console.WriteLine("Received response with filename: " + result.ReceivedFileName);
            Console.WriteLine("--------------------- fieldname: " + result.ReceivedFieldName);
            //On my system, prints text which is ISO 8859-1 read as UTF-8
            Console.ReadLine();
        }
    }

    public class MyServices : Service
    {
        public object Any(Hello request)
        {
            var file = base.Request.Files[0];
            return new HelloResponse { ReceivedFileName = file.FileName, ReceivedFieldName = file.Name };
        }
    }

    [Route("/hello")]
    public class Hello : IReturn<HelloResponse>
    {
    }

    public class HelloResponse
    {
        public string ReceivedFileName { get; set; }
        public string ReceivedFieldName { get; set; }
    }

    public class AppHost : AppSelfHostBase
    {
        public AppHost()
            : base("SelfHost1", typeof(MyServices).Assembly) { }
        
        public override void Configure(Container container)
        {
        }
    }
}


```
Here is a screenshot of the output:
![servicestack_encoding_error](https://cloud.githubusercontent.com/assets/1035195/20348728/46eac108-ac07-11e6-8127-812aba8f309c.PNG)

**Comment by mythz** [comment]
> the filename gets serialised with the system's default encoding even though it states in the header that it is UTF-8. 

The file name and field name [are not specified as UTF-8](https://github.com/ServiceStack/ServiceStack/blob/5c132791e94190db606700971b9070545e295c3a/src/ServiceStack.Client/ServiceClientBase.cs#L1621), i.e:

```csharp
outputStream.Write($"Content-Disposition: form-data;name=\"{fieldName}\";filename=\"{fileName}\"{newLine}{newLine}");
```

In order to specify the name and filename values as UTF-8 it requires sending in a special format to include the encoding as part of the value prefix (https://tools.ietf.org/html/rfc6266#section-4.5), e.g:

```csharp
outputStream.Write($"Content-Disposition: form-data;name*=utf-8''{fieldName};filename*=utf-8''\"{fileName}\"{newLine}{newLine}");
```

However changing to support this special format isn't supported in .NET's HTTP parsing implementations, e.g. HttpListener or .NET Core HTTP parsers so we're not going to be able to make this change.

If you need UTF-8 filenames you'll need to send them as additional parameters, e.g. as part of your Request DTO.
