### ISSUE TITLE
Generated DTO properties for native structs are generated as strings by mistake

### ISSUE THREAD

**Issue by schmidt4brains** [ServiceStack/Issues#503]
Our codebase uses [NodaTime](http://nodatime.org/) types in many request and response DTO properties. Many NodaTime types like [Instant](http://nodatime.org/1.3.x/api/html/T_NodaTime_Instant.htm) and [Interval](http://nodatime.org/1.3.x/api/html/T_NodaTime_Interval.htm) are native .NET structs.

Starting with v4.5.0, these properties are now generated as strings instead of the native type. If the property is nullable, then the generated DTO is still correct (since the underlying type is now a generic `Nullable<T>`). But if the property is simply a native struct, its generated DTO property is munged into a `string` and we lose type-safety. :(

Since upgrading to ServiceStack v4.5.0, we have to manually edit the output of the `<root>/types/csharp` built-in type generator to retain type-safety for our generated client libraries.

Here are some added tests to [NativeTypesTest.cs](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.Common.Tests/NativeTypesTests.cs#L240) which reproduce the bug:
```C#
[Test]
public void IncludeTypes_ReturnsStructTypes_If_IncludeTypes_NoWildcard_Csharp()
{
    var result = appHost.ExecuteService(new TypesCSharp
    {
        IncludeTypes = new List<string> { "DtoRequestWithStructProperty" }
    });

    var stringResult = result.ToString();

    StringAssert.Contains("class DtoRequestWithStructProperty", stringResult);
    StringAssert.Contains("public virtual StructType StructType { get; set; }", stringResult); // KABOOM!
}

[Test]
public void IncludeTypes_ReturnsNullableStructTypes_If_IncludeTypes_NoWildcard_Csharp()
{
    var result = appHost.ExecuteService(new TypesCSharp
    {
        IncludeTypes = new List<string> { "DtoRequestWithNullableStructProperty" }
    });

    var stringResult = result.ToString();

    StringAssert.Contains("class DtoRequestWithNullableStructProperty", stringResult);
    StringAssert.Contains("public virtual StructType? NullableStructType { get; set; }", stringResult);
}

...


public class NativeTypesTestService : Service
{
    public object Any(Dto request)
    {
        return "just a test";
    }

    public object Any(DtoRequestWithStructProperty request) // Added this fake service method
    {
        return "just a test";
    }

    public object Any(DtoRequestWithNullableStructProperty request) // And this one too
    {
        return "just a test";
    }
}

public class DtoRequestWithStructProperty : IReturn<DtoResponse>
{
    public StructType StructType { get; set; }
}

public class DtoRequestWithNullableStructProperty : IReturn<DtoResponse>
{
    public StructType? NullableStructType { get; set; }
}

public struct StructType
{
    // Nothing special here   
}
```

**Comment by schmidt4brains** [comment]
I'm in release-crunch mode right now, so I'm just manually working around this. Once I come up for air, I might be able to debug into this and figure out why it stopped working. But I thought I should post the issue with the failing test example, in case someone from the core team quickly recognizes the issue.

**Comment by mythz** [comment]
The problem with ValueTypes is that we're not able to generate a Struct DTO as they're not a normal DTO Reference Type we can emit a DTO with properties for as they marshal down to a single scalar string as controlled by a custom serialization impl that we can't embed in a DTO Type definition.

The previous behavior would emit the Struct's Type Name without their struct definition (since it's not possible) so if this was a custom Struct Type the client would have a broken reference which would require them to reference a Server .dll (and all its transitive references) which defeats the purpose of a clean DTO. If the struct was defined an external library like NodaTime clients could no longer just reference the DTOs and generic Service Client, they'd need to reference the external libraries the server use as well which adds additional knowledge clients need to know. 

So the safest most interoperable approach is to just serialize them as opaque strings so it would still be at least usable which is also what we need to do in all non-.NET languages where they wouldn't even have the opportunity to reference a Server library.

So there's no good solution for structs but serializing them as strings is the safest choice. But I can look at making this behavior configurable.

**Comment by schmidt4brains** [comment]
I see what you mean (I was guessing this was a thread I shouldn't pull on).

And for non-.NET languages, having our DTOs populated with NodaTime types definitely makes integration harder. It's a tough trade-off, for sure.

NodaTime eliminates a whole bunch of date/time ambiguity problems for our usage, but I guess at the cost of truer portability.

Like I said, I'm able to work around it for now, so it isn't urgent.

Would an aliasing pattern be a useful configuration for all the different generators?

A property like `public Dictionary<string,string> AliasedTypes { get; set; }` in `NativeTypesBase` might provide some nice flexibility to all the native type generators. (I could map NodaTime types to JodaTime types for Java 7 or java.time types for Java 8.

**Comment by mythz** [comment]
Ok I've made this configurable for all Native Type providers with the new `?ExportValueTypes=true` option in [this commit](https://github.com/ServiceStack/ServiceStack/commit/fc3c99b256f4c42a4b55d9edf2159fab67ddc62e) but I'm only showing this as an option in C#, F# + VB.NET as it's not a feature other languages would want to change.

We already have a `TypeAliases` Dictionary on all Type providers, I've added a test showing how you can customize how structs are generated in Java by using `ExportValueTypes` and `TypeAliases` options in [this test](https://github.com/ServiceStack/ServiceStack/blob/3f6adc903e6d6a06d9d097f4dfe5817356b71f7b/tests/ServiceStack.Common.Tests/NativeTypesTests.cs#L274):

```csharp
[Test]
public void Custom_ValueTypes_can_be_exported_as_different_Type_in_java()
{
    JavaGenerator.TypeAliases["StructType"] = "JavaStruct";

    var result = appHost.ExecuteService(new TypesJava
    {
        IncludeTypes = new List<string> { "DtoRequestWithStructProperty" },
        ExportValueTypes = true,
    });

    var stringResult = result.ToString();

    StringAssert.Contains("class DtoRequestWithStructProperty", stringResult);
    StringAssert.Contains("public JavaStruct StructType = null;", stringResult);
    StringAssert.Contains("public JavaStruct NullableStructType = null;", stringResult);

    string value;
    JavaGenerator.TypeAliases.TryRemove("StructType", out value);
}
```

This change is available from v4.5.5 that's now [available on MyGet](http://docs.servicestack.net/myget).

**Comment by schmidt4brains** [comment]
BTW @mythz, the `TypeAliases` property is not exposed on either the `/types/csharp` endpoint nor by the `ssutil` utility. It would be really handy to be able to specify that property on any of the `/types/{platform}` requests.

**Comment by mythz** [comment]
It's not an end-user configurable property, it's local to each concrete Native Types provider.
