### ISSUE TITLE
.NET 4.0 WPF Compatiblity?

### ISSUE THREAD

**Issue by asamsid** [ServiceStack/Issues#504]
Hi, 

I was trying to add ServiceStack to a new project (VS2010 .NET 4.0)  through nuget. But it is giving error due to dependency on .NET 4.5.

How can I use this in .NET 4.0 application?

Thanks,
Sami

**Comment by mythz** [comment]
[ServiceStack v4.0.62 was the last release supporting .NET 4.0](http://docs.servicestack.net/releases/v4.0.54#warning-net-40-builds-will-cease-after-august-1-2016) all v4.5.x ServiceStack packages released after have been upgraded to .NET 4.5.
