### ISSUE TITLE
Incorrect deserialization of ReadOnlyCollection when value is empty list

### ISSUE THREAD

**Issue by Fresa** [ServiceStack/Issues#505]
When deserializing an empty list, the collection is set to null.

```
public class Foo
{
   public ReadOnlyCollection<string> Bar { get; set; }
}
var foo = JsonSerializer.DeserializeFromString<Foo>("{\"Bar\":[]}");
```
Result: foo.Bar is null.
Expectation: foo.Bar should be an empty collection.

When deserializing a list with items, the collection is set as expected.

`var foo = JsonSerializer.DeserializeFromString<Foo>("{\"Bar\":[\"value\"]}");`

Result: foo.Bar is a collection containing the item "value".
Expectation: foo.Bar should be a collection containing the item "value".

Tested with 4.5.4.

**Comment by mythz** [comment]
Should be fixed with [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/c0046adeec04d17f5da4fca616d4a5066d46a954).

This fix is available from v4.5.5 that's now [available on MyGet](http://docs.servicestack.net/myget).
