### ISSUE TITLE
Unable to Connect: sPort: ???

### ISSUE THREAD

**Issue by spmarco** [ServiceStack/Issues#507]
I have the same problem the last issue #465 but in my case this code it works in production, it's only on my machine. I did everthing is suggested and I thought like. 
- Disabled the firewall
- change timeout of connection
- Disabled the antivirus
- cleam everthing and rebuild

In my case  the error happens in the `redisManager.GetClient()`

```
using (var redisManager = new PooledRedisClientManager(ConfigurationManager.ConnectionStrings["Redis"].ConnectionString))
using (var redis = redisManager.GetClient())
{
}
```

   em ServiceStack.Redis.RedisNativeClient.CreateConnectionError()
   em ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   em ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs)
   em ServiceStack.Redis.RedisNativeClient.SendExpectString(Byte[][] cmdWithBinaryArgs)
   em ServiceStack.Redis.RedisNativeClient.get_Info()
   em ServiceStack.Redis.RedisClient.GetServerRole()
   em ServiceStack.Redis.RedisResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
   em ServiceStack.Redis.RedisResolver.CreateMasterClient(Int32 desiredIndex)
   em ServiceStack.Redis.PooledRedisClientManager.GetClient()
   em Jz.Nasa.App.CommandHandler.Model.SolicitacaoVo.Obter() na d:\workspace\Jz.Nasa\2 - Application\Jz.Nasa.App.CommandHandler\Model\SolicitacaoVo.cs:linha 53

Someone have a ideia it's happening

Thanks.

**Comment by mythz** [comment]
Firstly are you using a single instance of `PooledRedisClientManager`? As you should only be using a singleton instance of any Redis Manager.

Are you connecting to the same instance in your local machine as your production server, e.g. same redis-server version running on Linux? 

Does this exception occur everytime or randomly? and can you successfully use redis-cli from your local machine to connect to the redis-server instance? If you're running Windows [you can download redis binaries from](https://github.com/ServiceStack/redis-windows#current-version-30503-june-28-2016)

This exception means the client couldn't establish a TCP connection with the server, there isn't much the client can do when it can't connect other than throw.

**Comment by spmarco** [comment]
Ok,

1) Yes, I using a single instance of `PooledRedisClientManager`.

2) My test and production redis are in Azure and the same version.

3) This exception occur every time. And yes, I'm installed the client of redis in my machine and connect successfully.

And more weird I install the redis in my machine, without password and without nothing, test the connection in my client and ok, but if I try the connection from project the same error happens.

I'm really sad, I tryed everthing and nothing happing.

**Comment by mythz** [comment]
If you can connect from redis-cli then I'm guessing you're likely using the wrong connection string in your project. When you use redis-cli were you able to [SET and GET a key/value](https://github.com/ServiceStack/redis-windows#5-start-playing-with-redis-)? Did you set a password when you use `redis-cli`? (i.e using the [AUTH](https://redis.io/commands/auth) command?) What port did you use when connecting with redis-cli? 

What connection string are you using in your project? (please comment out the hostname and password with `xxx`)

**Comment by mythz** [comment]
More info is needed for us to continue to help investigate the issue.
