### ISSUE TITLE
"The type initializer for 'ServiceStack.Text.JsConfig' threw an exception."

### ISSUE THREAD

**Issue by doucol** [ServiceStack/Issues#508]
Hello - 

I am trying to use ServiceStack.Text on a dotnet core project running on OSX 10.11.6. I have added the "ServiceStack.Text": "4.5.4" to my project.json.

When I try to use ".ToJson()", I get this exception thrown.

Inner exception: {System.TypeInitializationException: The type initializer for 'ServiceStack.LicenseUtils' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.LicenseUtils..cctor()
   --- End of inner exception stack trace ---
   at ServiceStack.LicenseUtils.Init()
   at ServiceStack.Text.JsConfig..cctor()}

Any ideas?

Thank you
-doug

**Comment by mythz** [comment]
Can you please post a small stand-alone repro?

**Comment by doucol** [comment]
attached
[jsontest.zip](https://github.com/ServiceStack/Issues/files/629189/jsontest.zip)

**Comment by mythz** [comment]
You're referencing the wrong NuGet package, [all .NET Core packages have a .Core suffix](http://docs.servicestack.net/netcore#net-core-servicestack-packages). You need to update your project.json to instead reference:

```
      "ServiceStack.Text.Core": "1.0.30"
```

**Comment by doucol** [comment]
ahhhhh - apologies - many thanks!
