### ISSUE TITLE
Servicestack oauth2 google authentication not working for selfhosted sites

### ISSUE THREAD

**Issue by sschoeb** [ServiceStack/Issues#509]
We are facing exactly the issue described in this SO-Post:
http://stackoverflow.com/questions/20133378/servicestack-oauth2-google-authentication-not-working-for-selfhosted-sites

Your statement there:
Yeah I've found that DotNetOpenAuth doesn't work properly when it's hosted in a self-hosted HttpListener, so anything requiring DNOA to work, e.g. OAuth2 supported is limited to ASP.NET hosts at this time. Add a feature request if you would like to see this researched further.

Does this limitation still exist or do we just miss any configuration to get OAuth working in a selfhostet setup?

**Comment by mythz** [comment]
Yeah DotNetOpenAuth has [effectively been abandoned](https://www.nuget.org/packages/DotNetOpenAuth.Core/) with the existing version still coupled to ASP.NET. 

The only potential future I see for a self-hosted OAuth2 solution is a .NET Core implementation since it's self-hosted by default.
