### ISSUE TITLE
Deadlock when blocking on async service client within ASP.NET synchronization context.

### ISSUE THREAD

**Issue by SteveGuidi** [ServiceStack/Issues#511]
This issue arises from the async/await synchronization rules imposed on ASP.NET.  As you're likely aware, ASP.NET only allows one thread to operate in its own synchronization context (in this case, one request thread in an HttpContext).  So if you create and `await` a `Task<T>` within this context, then block on it by calling `.Result` or `.Wait()`, the task will create a deadlock when resuming as it will try to re-enter the original ASP.NET context (the task is waiting for the lock on the context to be released, while the request thread is waiting for the task to complete).  Stephen Cleary [describes this in detail here](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).

I was able to create such a deadlock using the following code, running within an ASP.NET-hosted ServiceStack service.  In this case, we create a `Task<T>` by calling `JsonServiceClient.GetAsync()` and immediately block on it.  Presumably, somewhere in the call stack of `GetAsync()` is an `await` operation, which will attempt to be resumed in the ASP.NET synchronization context, causing deadlock.

```
// Contrived example to demonstrate deadlock; don't write this code!
public string Get(BonjourMessage m)
{
    using (JsonServiceClient client = new JsonServiceClient("http://localhost:51086"))
    {
        // ConfigureAwait(false) likely missing in the call stack of client.GetAsync().
        return client.GetAsync(new HelloMessage()).Result;
    }
}
```

The usual way to fix this is to call `.ConfigureAwait(false)` in all await operations within libraries (since we don't know where the library will be consumed).  This causes the task to be resumed on the .NET thread pool, which is less restrictive, but I'm not sure if this is applicable to the client implementation.

I've attached a full sample with different endpoints that you can call to see the different behavior.  This occurs in ServiceStack 4.5.4, .NET 4.5.2; the licence key has been omitted from the code.

[ServiceStackAsync.zip](https://github.com/ServiceStack/Issues/files/644107/ServiceStackAsync.zip)

**Comment by mythz** [comment]
You [should never block an async method in ASP.NET](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) and you don't need to dispose the ServiceClient so the method should be rewritten so the method just returns the task, either directly, e.g:

```csharp
public Task<string> Get(BonjourMessage m)
{
    var client = new JsonServiceClient("http://localhost:51086"))
    return client.GetAsync(new HelloMessage());
}
```

Or awaiting the Task as in your `HolaMessage` example.

**Comment by SteveGuidi** [comment]
I apologize for not responding sooner but I did want to follow up on this thread.  I appreciate the examples of the work-around to the issue you have provided, but unfortunately the example using a threadpool thread to call and block on an async API also deadlocks, presumably for the exact same reasons noted above and in the [article](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html) that we are both quoting.

```cs
// Will deadlock when attempting to synchronize Task created from
// within GetAsync() back into this ASP.NET request context.
public string Get(BonjourMessage m)
{
    var client = new JsonServiceClient("http://localhost:51086");
    return Task.Run(() => client.GetAsync(new HelloMessage())).GetAwaiter().GetResult();
}

```

I understand that blocking must be avoided when writing new code that leverages async/await.  However, this may not be feasible when migrating a synchronous code base to a more efficient async counterpart, which is the motivation for reporting this issue.  For instance, some teams may choose to migrate more complicated layers in a call stack to the async counterpart a different times, and temporarily introduce blocking to keep things working.

In this case, using `ConfigureAwait(false)` is the correct solution, as Mr. Cleary suggests in his [article](http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html):

> There are two best practices (both covered in my intro post) that avoid this situation:
> 
> 1. In your “library” async methods, use ConfigureAwait(false) wherever possible.
> 2. Don’t block on Tasks; use async all the way down.

We don't know how ServiceStack.Client will be used in end-user code, or in what synchronization context.  It would be nice if the code just worked -- just like `System.Net.Http.HttpClient`, for example.  If I rewrite my example function above as follows, no deadlock occurs even though I violate the suggestion of not blocking in ASP.NET async methods. 

```cs
// Will deadlock when attempting to synchronize Task created from
// within GetAsync() back into this ASP.NET request context.
public string Get(BonjourMessage m)
{
    using (var c = new System.Net.Http.HttpClient())
    {
        HttpResponseMessage r = c.GetAsync(new Uri("http://localhost:51086/hello")).Result;
        return r.Content.ReadAsStringAsync().Result;
    }
}

```

Although I haven't tested this, I'm confident that many other async methods in the .NET Framework behave the same way.  Please consider reopening this issue or at least documenting that it is an unsupported use-case.

**Comment by mythz** [comment]
The solution is to:

    Don’t block on Tasks; use async all the way down.

As [blocking on an async task causes deadlocks](https://twitter.com/bradwilson/status/828782913277661184).

If you can't do that and want to use synchronous code just use `JsonServiceClient` which is [more efficient than async](https://twitter.com/davidfowl/status/828776023135129600) and doesn't cause deadlocks.
