### ISSUE TITLE
PooledRedisClientManager.GetStats throws NullReferenceException inside RedisNativeClient.IsSocketConnected

### ISSUE THREAD

**Issue by UriHendler** [ServiceStack/Issues#513]
I am calling PooledRedisClientManager.GetStats() fairly often to help me investigate some redis connection issues.

It sometimes throws a NRE from inside the `RedisNativeClient.IsSocketConnected` method.

``
Exception Info: System.NullReferenceException
   at ServiceStack.Redis.RedisNativeClient.IsSocketConnected()
   at ServiceStack.Redis.PooledRedisClientManager.GetStats()
``

Looking at my logs, this seems to happen after a redis client experiences a `SocketException`.

I'm guessing that at the point when `GetStats` is called, the redis client is still in the pool, but it's socket has already been disposed and set to null.

I can catch and swallow the error myself, but I think it should be caught inside `GetStats`.

**Comment by mythz** [comment]
Agreed, this NRE should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/dc84959344460010e3f398ad2ede983857493720).

Thx for reporting!
