### ISSUE TITLE
Bug in ExecLuaShaAsInt

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#516]
args.Length should probably be 0 

        public long ExecLuaShaAsInt(string sha1, params string[] args)
        {
            return base.EvalShaInt(sha1, args.Length, args.ToMultiByteArray());
        }

Regards

**Comment by mythz** [comment]
updated in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/c5ac91656c13f20efbd4ac79a758d7c67e903ae1).

Thx for reporting!
