### ISSUE TITLE
Spurious intellisense errors in VS2015 when editing .cshtml files

### ISSUE THREAD

**Issue by adzy84** [ServiceStack/Issues#517]
After trying many things to rid my project of these errors, including the undocumented (but absolutely necessary step) of copying all the project dependencies including un-obvious things like "system.core" into the /bin directory, there are still a number of spurious errors displayed when editing .cshtml files. The project compiles and runs fine, however these are a major distraction. 

One example is 
> Error	CS0103	The name 'Context' does not exist in the current context

which occurs every time you create a view derived from `ServiceStack.Razor.ViewPage` or it's generic equivalent. 
There are many others, for things such as missing extension methods which are defined in the assemblies in the /bin directory.

I've included a copy of my web.config file in case there are errors there, however after reading all the available documentation, I can't see anything wrong with it. 
[Web.config.zip](https://github.com/ServiceStack/Issues/files/792535/Web.config.zip)

**Comment by mythz** [comment]
The [Razor templates in ServiceStackVS](https://github.com/ServiceStack/ServiceStackVS) contain the optimal configuration for Razor. A copy of the [optimal Web.config is maintained in the docs](http://docs.servicestack.net/razor-notes#web-configuration-for-razor). Replacing your config section and `<host factoryType />` may help as the version numbers are different. Also if you haven't already you should reference the **Microsoft.AspNet.WebPages** NuGet packages as mentioned in the docs. Which isn't needed by ServiceStack or has any effect at runtime, it's only used to minimize design-time errors in VS.NET. After making the changes do a project clean and restart the project to clear any previous dirty state.

But that's as much as we're able to do to help VS.NET design-time intelli-sense, unfortunately it's a black box which should respect the configuration in Web.config, but it's behavior shows it's coupled to MVC as seen by needing **Microsoft.AspNet.WebPages** NuGet packages which aren't referenced or used but they're presence removes some design-time errors.

We don't have the same designer issues with our [Razor impl in .NET Core](http://docs.servicestack.net/netcore-razor) which is built on top of .NET Core MVC constructs and doesn't suffer from the same dark coupling.
