### ISSUE TITLE
Missing "export" from outer TypeScript module when using GlobalNamespace

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#519]
When fetching a TypeScript DTO from /types/typescript with a GlobalNamespace X, the resulting file looks like
```
module X
{
    export interface IReturnVoid
...
```
However that is not a valid TypeScript module usable for import. It should rather be
```
export module X
{
    export interface IReturnVoid
...
```
And that would allow other scripts to import with
`    import { X } from "../../X.dtos";`
By fixing this it is possible with a default GlobalNamespace on the server, that we wish to use for our CSharp clients.
We are working around this by making our CSharp clients provide the GlobalNamespace parameter.

**Comment by mythz** [comment]
This should be resolved from [this commit](https://github.com/ServiceStack/ServiceStack/commit/d35b2b4b84b221a5678bdf5a5e892243c3d817a1) which is available from v4.5.7+ that's now [available on MyGet](http://docs.servicestack.net/myget).
