### ISSUE TITLE
Missing SQL debug log for OrmLite Extension method Save()

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#521]
When using ServiceStack with OrmLite and a configured logger
`LogManager.LogFactory = new ConsoleLogFactory(debugEnabled: true);`
and then in any service with the regular Db connection the following code runs
`Db.Insert<X>(x);`
then logging to console works correctly.
However when running:
`Db.Save<X>(x);`
then nothing is logged.

I would expect INSERT to be logged for both cases.

**Comment by mythz** [comment]
This should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/102f0e983b167caf88084c70897a7dd0e4567905).

This change is available from v4.5.7+ that's now [available on MyGet](http://docs.servicestack.net/myget).

Thx for reporting!
