### ISSUE TITLE
OrmLite: GetLastSql() doesn't capture async command text when used in OrmLiteExecFilter.

### ISSUE THREAD

**Issue by SteveGuidi** [ServiceStack/Issues#522]
I am following the example [given here](https://github.com/ServiceStack/ServiceStack.OrmLite#exec-result-and-string-filters) to mock and test the invocation of a stored procedure.  However, if I call the stored procedure using `SqlScalarAsync()`, then `IDbConnection.GetLastSql()` will not capture the command text.

Modification of DB code:

```csharp
OrmLiteConfig.ExecFilter = new MockStoredProcExecFilter();

using (var db = OpenDbConnection())
{
    string result = await db.SqlScalarAsync<string>("exec sp_name @firstName, @age",
        new { firstName = "aName", age = 1 });
}

```

Modification of the exec filter:

```cs
public class MockStoredProcedureExecFilter : OrmLiteExecFilter
{
    public override Task<T> Exec<T>(IDbConnection dbConn, Func<IDbCommand, Task<T>> filter)
    {
        try
        {
            return base.Exec<T>(dbConn, filter);
        }
        catch (Exception)
        {
            // GetLastSql() always returns null, even if base.Exec<T> is explicitly await-ed above.
            if (dbConn.GetLastSql() == "exec sp_name @firstName, @age")
                return (Task<T>)(object)Task.FromResult("abc");
            throw;
        }
    }
}

```

Is this a supported feature, and if so, what am I doing incorrectly?  For the time being, I can ignore comparing the command text in the filter, though that may not be feasible for different types of tests.

_Tested in ServiceStack.OrmLite 4.5.4._

**Comment by mythz** [comment]
This should be fixed from [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/215b929c05bcea9f59abe58714b7f7004fdf9989) which is available from v4.5.7+ that's now [available on MyGet](http://docs.servicestack.net/myget).
