### ISSUE TITLE
Redis client licensing

### ISSUE THREAD

**Issue by amirbrb** [ServiceStack/Issues#523]
Greetings.
We are working on a project where Storage speed and capacity is highly important.
ServiceStack.Redis client came up as one of the options and i have been testing the client for few days now.
Version 4 and above have interface methods (wrapping and using Lua scripts for example) which are very useful but are included in the payed version.

Testing out application using the payed version with a quota of 6000 calls per hour/session, will not give us the possibility to decide if ServiceStack,Redis is the product we need.

My question - is there a way to provide a single user license of the 4.x version for a trial period or increasing the quota?

Thanks.
Amir.

Regards,
Amir Mishori– Developer, Market Data.
Intercontinental Exchange | SuperDerivatives
Derech Menachem Begin 132 | Tel Aviv-Yafo | IL
Cel: +972.54.777.2344
Tel: +972.3.610.6126
Amir.Mishori@Theice.com
intercontinentalexchange.com

**Comment by mythz** [comment]
Hi, you request a trial license by emailing team@servicestack.net ([published on pricing page](https://servicestack.net/pricing#faq))
