### ISSUE TITLE
Null Reference when calling a request that requires a stream.

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#524]
When you call a request that has an IRequiresRequestStream by using the request name, the server will throw a null reference exception.
eg /api/json/reply/MyUploadRequest

https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Host/ServiceController.cs#L171

Looking at the code, Is this intended behavior ? If it is, could there be a better error message ?
Thanks.

**Comment by mythz** [comment]
This should now be fixed from [this commit](https://github.com/ServiceStack/ServiceStack/commit/1af3d97c12e09893ccce20c43c3e74d325f730de) available from v4.5.7 that's now [available on MyGet](http://docs.servicestack.net/myget).

Thx for reporting!
