### ISSUE TITLE
OpenAPI submit to Azure API Management error

### ISSUE THREAD

**Issue by hoaihuongbk** [ServiceStack/Issues#526]
When i submit our openapi to Azure API Management, i get below errors. Please help me?
OpenAPI: https://cloudpmsmng.azurewebsites.net/api/openapi
![capture](https://cloud.githubusercontent.com/assets/8325827/24579969/17ff2d1e-172a-11e7-87f4-24dc7683ca0f.PNG)

**Comment by xplicit** [comment]
Can you show how is your `Version` property annotated with `[ApiMember]` attribute? I assume it's something like this:

```csharp
[ApiMember(ParameterType="form", IsRequired=false....)]
public string Version { get; set; }
```

If I make right assumption then you should change `ParameterType="form"` to `ParameterType="formData"`, because in OpenAPI specification parameter type "form" was renamed to "formData" and Azure API Management import complains on the "form" type.

**Comment by hoaihuongbk** [comment]
I have an abstract BaseRequest
`public abstract class BaseRequest : IHasVersion
    {
        [ApiMember(DataType = "int", Description = "Version. Ex: 1,2,3,...", IsRequired = false, ParameterType = "formData")]
        public int Version { get; set; }
        protected BaseRequest()
        {
            Version = ConfigUtils.GetAppSetting("AppVersion", 1);
        }
    }`

And DTO inherited from this class
`[Route("/client/create", "POST")]
    public class CreateClient : BaseRequest, IReturn<CustomResponse<Types.Client>>
    {
        public int CompanyId { get; set; }
        public int Type { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
    }`
![capture-3](https://cloud.githubusercontent.com/assets/8325827/24583487/d234d24c-1775-11e7-8fe9-ee54b1a4192d.PNG)

**Comment by mythz** [comment]
Please note that your DTOs shouldn't rely on any implementation as it's not going to be ignored in all [Add ServiceStack Reference Languages](http://docs.servicestack.net/add-servicestack-reference#supported-languages).

The preferred way to specify a version is to either configure [AddImplicitVersion in your generated DTO's Config](http://docs.servicestack.net/csharp-add-servicestack-reference#addimplicitversion) or you can configure it globally in your AppHost with:

```csharp
var nativeTypes = this.GetPlugin<NativeTypesFeature>();
nativeTypes.MetadataTypesConfig.AddImplicitVersion = 1;
```

**Comment by xplicit** [comment]
@hoaihuongbk that's other issue. You put `[ApiMember(DataType="int") ...]` while it should be `[ApiMember(DataType="integer", Format="int32",....)]`. Please see `DataType` [migration table](http://docs.servicestack.net/openapi#open-api-attributes) from Swagger 1.2 to OpenAPI.

**Comment by hoaihuongbk** [comment]
Many thanks :) I have added to Azure Api Management successfully.
