### ISSUE TITLE
ServiceStack Redis Geo wrong latitude, longitude

### ISSUE THREAD

**Issue by hoaihuongbk** [ServiceStack/Issues#529]
Hi ServiceStack,  i have project with redis geo
When i call GeoRadius then i get wrong latitude, longitude
Ex: 10.745718, 106.663884 -> 10745718, 106663884
I set global culture in webconfig is
`` 
<globalization fileEncoding="utf-8" requestEncoding="utf-8" responseEncoding="utf-8" culture="vi-VN" uiCulture="vi-VN" />
``
Please help !
![issue](https://cloud.githubusercontent.com/assets/8325827/24785779/bd172b0c-1b86-11e7-883a-de663491c953.PNG)

**Comment by mythz** [comment]
Please provide a stand-alone repro that we can run locally that shows the issue.

**Comment by hoaihuongbk** [comment]
I can not provide this, but i can send code with this issue
```
 var nativeClient = (RedisNativeClient)client;
                    var drivers = nativeClient.GeoRadius(RedisCacheHelper.GetDriverGeoSpartialCacheKey(), 
                        request.Lng, request.Lat, request.Radius, RedisGeoUnit.Kilometers, withCoords: true, asc: true
                        );
```
Also, i have added before
`System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;
`
then i get right value
I think maybe issue by Culture request, default: "vi-VN"
![issue2](https://cloud.githubusercontent.com/assets/8325827/24786590/ef46a46c-1b8c-11e7-8c6a-d0891393476b.PNG)

**Comment by xplicit** [comment]
What are the values of `drivers[0].Latitude` and `drivers[0].Longitude` immediately after you get result from `GeoRadius`? 

I run following code:

```csharp
Thread.CurrentThread.CurrentCulture = new CultureInfo("vi-VN");
Thread.CurrentThread.CurrentUICulture = new CultureInfo("vi-VN");
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("vi-VN");

redis.GeoAdd("Sicily",
       new RedisGeo(13.361389, 38.115556, "Palermo"),
       new RedisGeo(15.087269, 37.502669, "Catania"));

var results = redis.GeoRadius("Sicily", 15, 37, 200, RedisGeoUnit.Kilometers, withCoords: true, asc: true);

Console.WriteLine(results[0].Longitude);
Console.WriteLine(results[0].Latitude);
```
and the code produces correct values for this culture:
```
15,0872674584389
37,5026684233316
```

can you show small sample of the the code which produces the behaviour you've described?

**Comment by hoaihuongbk** [comment]
In webconfig, i set global culture
`<globalization fileEncoding="utf-8" requestEncoding="utf-8" responseEncoding="utf-8" culture="vi-VN" uiCulture="vi-VN" />`

This code for add geo

```
using (var client = TryResolve<IRedisClientsManager>().GetClient())
                {
                    using (var pipeline = client.CreateTransaction())
                    {
                        pipeline.QueueCommand(r => r.AddGeoMember(RedisCacheHelper.GetDriverGeoSpartialCacheKey(), request.Lng, request.Lat, UserSession.UserAuthId));
                        var commited = pipeline.Commit();
                        result.Status = commited ? 1 : 0;
                    }
```

And this code for get radius
```
using (var client = TryResolve<IRedisClientsManager>().GetClient())
 {
                    //Fix get lat, lng
                    System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;

                    var nativeClient = (RedisNativeClient)client;
                    var drivers = nativeClient.GeoRadius(RedisCacheHelper.GetDriverGeoSpartialCacheKey(), 
                        request.Lng, request.Lat, request.Radius, RedisGeoUnit.Kilometers, withCoords: true, asc: true
                        );
```

You can see I add this line for get right result.
  `System.Threading.Thread.CurrentThread.CurrentCulture = System.Globalization.CultureInfo.InvariantCulture;`

Any idea for set IRedisClient use InvariantCulture always?

**Comment by xplicit** [comment]
RedisClient uses `InvarianCulture` when deals with RedisGeo features.

I made sample demo which shows that this use case works with `vi-VN` culture. You can get it here: https://github.com/xplicit/RedisGeo

Run the demo and open following urls in browser:

```
http://localhost:7303/AddGeo?Lat=13.31&Lng=14.41
http://localhost:7303/GetGeo?Lat=13.31&Lng=14.41&Radius=10&format=json
```
The last one will show output:
```
{"Longitude":14.4099989533424,"Latitude":13.3099995055306}
```
So it's what we expected to get.

If you log `dirvers[0].Latitude` and `drivers[0].Longitude` in your app immediately after `GeoRadius` returns them, you should get correct results. I suppose you change some longitude/latitude data (possible converting to string and back) before returning from the service and this produces wrong behavior.

**Comment by mythz** [comment]
This doesn't look like an issue with our library which is working as expected which isn't able to repro the issue in our Sample project provided. If you can put together a [small, stand-alone repro of the issue](https://github.com/ServiceStack/Issues#you-can-view-existing-issues-or-report-a-new-issue) that clearly identifies that the issue is in the library (i.e. and not your code outside of library usage) we can investigate further. 

You can either [fork RedisGeo repo](https://github.com/xplicit/RedisGeo) and modify it to show the issue, or include a stand-alone console app either in a Gist or a [Live example on Gistlyn](http://gistlyn.com/?gist=54e452bb1e86e132068a595d7e72d1a6)

**Comment by hoaihuongbk** [comment]
OK thanks
