### ISSUE TITLE
Serialization of Empty String not working

### ISSUE THREAD

**Issue by kgoderis** [ServiceStack/Issues#530]
[I am not a commercial user, but I see no other place where to report this issue]

Consider the following DTO:

```
	[Route("/message")]
	public class Message : IReturn<MessageResponse>
	{
		public string name { get; set; }
		public List<Property> Properties { get; set; }
	}

	public class Property
	{
		public string id { get; set; }
		public int index { get; set; }
		public object value { get; set; }
	}

	public class MessageResponse
	{
		public string name { get; set; }
		public List<Property> Properties { get; set; }
	}
```

At the server side, when receiving a Message (via POST), processing it and then creating a MessageResponse instance to send back to the client, and putting in that MessageResponse a Property instance with an empty String (e.g "") is assigned to Poperty.value, then ServiceStack writers beyond the Content-Lenght of the HttpResonse stream. The Gson parser at the client fails with an MalformedExpressionException (unterminated string)

More specifically, analysing the wire using WireShark one can observe a lot of "Continuation" frames starting exactly at the JSON payload where the empty string is supposed to be encoded.

**Comment by mythz** [comment]
Don't use [late-bound object data types](http://stackoverflow.com/a/10759250/85785) which causes runtime interoperabilities like this which relies on emitting type info that's only emitted for DTO reference types, not value types or strings. Use `string` Type instead.
