### ISSUE TITLE
How to i get correct RemoteIP and UserAgent when call Gateway send?

### ISSUE THREAD

**Issue by hoaihuongbk** [ServiceStack/Issues#532]
Hi ServiceStack,
I have a question: "How to i get correct RemoteIP and UserAgent when call Gateway send?"
When i call Gateway.Send then in server side i get
IP: IP of app server called, NOT client IP address.
UserAgent: ServiceStack .Net Client 4,50

Please help?

**Comment by mythz** [comment]
This is an [issue tracker for reproducible issues only](https://github.com/ServiceStack/Issues#servicestack-issues). Please ask any support questions in the [Customer Forums](https://forums.servicestack.net/) or on [StackOverflow](http://stackoverflow.com/).
