### ISSUE TITLE
Redis - GetServerTime inside a transaction fails

### ISSUE THREAD

**Issue by volak** [ServiceStack/Issues#535]
I'm seeing this weird issue with the latest redis client v4.5.8 - I'm using it for SSE and its failing due to
```
    [NullReferenceException: Object reference not set to an instance of an object.]
    ServiceStack.Redis.RedisPubSubServer.get_CurrentServerTime() +36
    ServiceStack.&lt;&gt;c__DisplayClass48_0.&lt;StoreSubscriptionInfo&gt;b__0(IRedisClient r)
```
I tracked it down to something to do with the transaction RedisServerEvents creates.  Example code:
```
    var connectionString =
                $"redis://localhost:6379";
            var pool = new RedisManagerPool(connectionString);


            using (var redis = pool.GetClient())
            {
                    var serverTimeAtStart = redis.GetServerTime();
                    Console.WriteLine(serverTimeAtStart);
                
            }

            using (var redis = pool.GetClient())
            {
                using (var trans = redis.CreateTransaction())
                {
                    var serverTimeAtStart = redis.GetServerTime();
                    Console.WriteLine(serverTimeAtStart);
                    trans.Commit();
                }
            }
```

Output is:
```
4/21/2017 12:36:04 PM

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ServiceStack.Redis.RedisClient.GetServerTime()
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\charl\Projects\ConsoleApplication1\ConsoleApplication1
\Program.cs:line 31
```

First one works, second doesn't

**Comment by volak** [comment]
Oh I think I see the problem - CreateTransaction sends MULTI meaning the next TIME call just gets queued, not executed, and RedisClient_Admin is expecting immediate results. 
👍

**Comment by volak** [comment]
I may have figured out the SSE issue - after digging through this I didn't know I had to call IServerEvents.Start() as I've only used MemoryServerEvents before.  Guess its more important for RedisServerEvents!

The transaction time thing is kind of funny though - if you want to address that or not I'll leave this open feel free to close

**Comment by mythz** [comment]
Yeah you can't make Get calls within a transaction and you [need to call QueueCommand](https://github.com/ServiceStack/ServiceStack.Redis/wiki/RedisTransactions) to queue up transactions that you wan't batched together.
