### ISSUE TITLE
OrmLite throws unknown error Insufficient parameters supplied to the command

### ISSUE THREAD

**Issue by dvladimirovich** [ServiceStack/Issues#537]
I find an issue in parsing expressions and generating SQL. I've asked a question on stackoverflow [http://stackoverflow.com/questions/43619796/](url) but decided to post it here also.

**Comment by mythz** [comment]
The issue is likely due to building a predicate instead of using the concrete type in the where expression directly, but can you please provide a small stand-alone example we can run locally to see the issue. 

You can use something like [gistlyn.com]() to create a runnable example.

**Comment by dvladimirovich** [comment]
I have `PersonViewModel` class with properties and nested list of POCOs. I've already had a problem with translating such expression to OrmLite (because OrmLite doesn't have functionality to parse nested lambda expressions which seems strange for me) and I even asked the question: [http://stackoverflow.com/questions/41224057/](url). 
According to my own answer I decided to convert nested lambda in `Sql.In(...)` form. My first Lambda looks like this:

`{pvm => ((((((((((pvm.Pib.Contains("BDV") AndAlso 
                          (pvm.Birthday == 19880427)) AndAlso 
                          pvm.IdentityCode.Contains("454185662")) AndAlso 
                          pvm.BirthPlace.Contains("USA")) AndAlso 
                          pvm.LivePlace.Contains("NEW YORK")) AndAlso 
                          pvm.Document.Contains("QWE17277ASD")) AndAlso 
                          pvm.Nationality.Contains("USA")) AndAlso 
                          pvm.Organization.Contains("INDUSTRIES")) AndAlso 
                          pvm.Pseudonym.Contains("AGAPIT")) AndAlso 
                          pvm.Subjects.Any(svm => (((((((svm.ParentDicType == 10000) AndAlso 
                                                                        ((svm.Value.Contains("063") OrElse 
                                                                          svm.Value.Contains("099")) OrElse 
                                                                          svm.Value.Contains("050"))) AndAlso 
                                                                        ((svm.ParentDicType == 11000) AndAlso 
                                                                          svm.Value.Contains("AA7495CH"))) AndAlso 
                                                                        ((svm.ParentDicType == 12000) AndAlso 
                                                                          svm.Value.Contains("PM-9"))) AndAlso 
                                                                        ((svm.ParentDicType == 13000) AndAlso 
                                                                          svm.Value.Contains("QWERTY@MAIL.RU"))) AndAlso 
                                                                        ((svm.ParentDicType == 14000) AndAlso 
                                                                          svm.Value.Contains("VK.COM"))) AndAlso 
                                                                        ((svm.ParentDicType == 15000) AndAlso 
                                                                          svm.Value.Contains("TEST"))))))}`

After converting instead of `pvm.Subjects.Any()` it will contain 
`In(pvm.Id, value(ServiceStack.OrmLite.Sqlite.SqliteExpression`1[Reestr.DAL.Entities.Subject]))` condition with syntax you've mentioned in developers guide. Here I need to add that it works correctly if: 
     1. There are less than 8 conditons including nested lambda as one of them;
     OR
     2. There are only nested lambda conditions (only `pvm.Subjects.Any()` conditions) without those that directly related to pvm (e.g. pvm.Pib.Contains("BDV"), pvm.BirthPlace.Contains("USA") and so.

If it doesn't help you, write me please and I'll try to reproduce it in http://gistlyn.com/?gist=0cd558e817f28f77b974c44c3e12ff6f&collection=2cc6b5db6afd3ccb0d0149e55fdb3a6a

**Comment by mythz** [comment]
What you're doing is likely unsupported, but please provide a repro we can run locally to investigate the issue.

**Comment by dvladimirovich** [comment]
[http://gistlyn.com/?gist=0cd558e817f28f77b974c44c3e12ff6f&collection=2cc6b5db6afd3ccb0d0149e55fdb3a6a](url)
It shows "Executing script" but doesn't do something and no errors have been shown. It's not obvious. And there is a problem with scrolling and putting cursor on workspace.

**Comment by mythz** [comment]
The first lambda isn't supported, you can't query joined tables through a list like `pvm.Subjects` but the 2nd Lambda works?

You've just got a logic error in:

```csharp
var secondCount = CountByCondition(GetSecondLambda());
if (firstCount != -1)
{
    Console.WriteLine("Success");
}
```

Where it likely should be:

```csharp
if (secondCount != -1)
```

**Comment by dvladimirovich** [comment]
Oh, I see sorry, but all the same, it doesn't work and throws an exception because of strange sql and parameters list generated by OrmLite. I've mentioned this in my first comment see the link to stackoverflow (strange github links doesn't work and we need to copy them as text and paste in browser header) where I described in details.

**Comment by mythz** [comment]
What you've described does not happen with the latest version of OrmLite:

http://gistlyn.com/?gist=d95c3d4fe33c81971e4e1d5262d2c8f2

If you have a repro that does fail with the latest version of OrmLite, please save a gist on Gistlyn and post the link here.

**Comment by dvladimirovich** [comment]
As I mentioned in my first question, I am currently using 4.0.62 version, because my solution works with .NET Framework 4.0. And I can't rise it to newer version. Does it mean that you won't fix this problem for previous versions?

**Comment by mythz** [comment]
We only maintain and support the current version which has already resolved this issue. The only changes we make are on the master branch which is where all releases are created from.

If you can't upgrade then you'd need to avoid the typed API and drop down to use Custom SQL.
