### ISSUE TITLE
Strange sql from ormlite save

### ISSUE THREAD

**Issue by draconculis** [ServiceStack/Issues#538]
Sometimes (not always!) we get strange SQL (as shown by Neor) when doing a simple save on a poco. The error is specific to this code / poco, and we have lots of other pocos. The only thing different with this specific poco is the auto increment.

This happens perhaps 10-25% of the time now, and we have not found a pattern to reproduce it.

C#:
--------------------
[Alias("error_log")]
public class EconomyErrorLog
{
	[Alias("Id")]
	[AutoIncrement]
	public int Id { get; set; }
	[Alias("key")]
	public string Key { get; set; }
	[Alias("eventId")]
	public string eventId { get; set; }
	[Alias("source")]
	public ErrorLogSource Source { get; set; }
	[Alias("topic")]
	public string Topic { get; set; }
	[Alias("message")]
	public string Message { get; set; }
	[Alias("createdDate")]
	public DateTime CreatedDate { get; set; }
}

--------------------
EconomyErrorLog entry = new EconomyErrorLog
	{
		Source = source,
		Topic = topic,
		Message = message,
		CreatedDate = DateTime.UtcNow,
		Key = key,
		eventId = eventId
	};

repository.Db.Save(entry);
----------------------

SQL generated (full version):
INSERT INTO `error_log` (`key`'1403c28a-c525-4442-9395-5c8d257d7555',,`eventId`NULL,,`source`'PSEVENTMANAGER',,`topic`'# PsEventRepository.Any',,`message`'ReadConfiguration response: {\"parameters\":[{\"parameter\":\"melin.tracing.enabled\",\"value\":false},{\"parameter\":\"melin.unsafe_mode\",\"value\":false},{\"parameter\":\"url_base_scheme\",\"value\":\"http\"},{\"parameter\":\"url_base_host\",\"value\":\"http://localhost:58364/api/ps-no\"},{\"parameter\":\"systemevent_handlers\",\"value\":\"customer.acquired.license,practitioner.employed,practitioner.unemployed,employee.accesses.updated,bkm.message.response,bkm.message.signed,bkm.message.sent\"},{\"parameter\":\"systemevent_handler_settings\",\"value\":{\"handlers\":[{\"name\":\"customer.acquired.license\",\"eventTypes\":[\"customer.acquired.license\"]},{\"name\":\"practitioner.employed\",\"eventTypes\":[\"practitioner.employed\"]},{\"name\":\"practitioner.unemployed\",\"eventTypes\":[\"practitioner.unemployed\"]},{\"name\":\"employee.accesses.updated\",\"eventTypes\":[\"employee.accesses.updated\"]},{\"name\":\"bkm.message.response\",\"eventTypes\":[\"bkm.message.response\"]},{\"name\":\"bkm.message.signed\",\"eventTypes\":[\"bkm.message.signed\"]},{\"name\":\"bkm.message.sent\",\"eventTypes\":[\"bkm.message.sent\"]}]}},{\"parameter\":\"system_event.database_url\",\"value\":\"https://development.pasientsky.no\"},{\"parameter\":\"systemevent-worker-port\",\"value\":8090}]}',,`createdDate`'2017-04-28 08:33:24.611781') VALUES (`key`'1403c28a-c525-4442-9395-5c8d257d7555',,`eventId`NULL,,`source`'PSEVENTMANAGER',,`topic`'# PsEventRepository.Any',,`message`'ReadConfiguration response: {\"parameters\":[{\"parameter\":\"melin.tracing.enabled\",\"value\":false},{\"parameter\":\"melin.unsafe_mode\",\"value\":false},{\"parameter\":\"url_base_scheme\",\"value\":\"http\"},{\"parameter\":\"url_base_host\",\"value\":\"http://localhost:58364/api/ps-no\"},{\"parameter\":\"systemevent_handlers\",\"value\":\"customer.acquired.license,practitioner.employed,practitioner.unemployed,employee.accesses.updated,bkm.message.response,bkm.message.signed,bkm.message.sent\"},{\"parameter\":\"systemevent_handler_settings\",\"value\":{\"handlers\":[{\"name\":\"customer.acquired.license\",\"eventTypes\":[\"customer.acquired.license\"]},{\"name\":\"practitioner.employed\",\"eventTypes\":[\"practitioner.employed\"]},{\"name\":\"practitioner.unemployed\",\"eventTypes\":[\"practitioner.unemployed\"]},{\"name\":\"employee.accesses.updated\",\"eventTypes\":[\"employee.accesses.updated\"]},{\"name\":\"bkm.message.response\",\"eventTypes\":[\"bkm.message.response\"]},{\"name\":\"bkm.message.signed\",\"eventTypes\":[\"bkm.message.signed\"]},{\"name\":\"bkm.message.sent\",\"eventTypes\":[\"bkm.message.sent\"]}]}},{\"parameter\":\"system_event.database_url\",\"value\":\"https://development.pasientsky.no\"},{\"parameter\":\"systemevent-worker-port\",\"value\":8090}]}',,`createdDate`'2017-04-28 08:33:24.611781'); SELECT LAST_INSERT_ID()
-------------------------
SQL (message field shortened for readability):
INSERT INTO `error_log`
(`key`'1403c28a-c525-4442-9395-5c8d257d7555',,`eventId`NULL,,`source`'PSEVENTMANAGER',,`topic`'#PsEventRepository.Any',,`message`'xxx',,`createdDate`'2017-04-28 08:33:24.611781') 
VALUES
(`key`'1403c28a-c525-4442-9395-5c8d257d7555',,`eventId`NULL,,`source`'PSEVENTMANAGER',,`topic`'#PsEventRepository.Any',,`message`'xxx',,`createdDate`'2017-04-28 08:33:24.611781'); 
SELECT LAST_INSERT_ID()
----------------------------

Environment: 
Servicestack v. 4.0.60
Windows 10 (as exe or started via mono)
Linux (mono 4.8, but seen on earlier versions).
MySql 6.9.9.0.

**Comment by mythz** [comment]
We really need to be able to reproduce it in order to identify and resolve the issue. 
Please send us a stand-alone repro we can run locally to see the issue.

**Comment by mythz** [comment]
Corrupt queries like this are typically the result of sharing a `IDbConnection` or `IDbCommand` across multiple threads so you'd need to make sure you're not holding static instances and are always resolving/disposing of DB connections within the same thread and are never sharing them across different threads.

We'd need a stand-alone repro in order to be able to investigate this issue any further. Once you have one please add it to this thread.
