### ISSUE TITLE
JoinAlias return type

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#539]
ServiceStack v4.5.8 and below.

When using the Sql.JoinAlias, the type will always be a string.
eg x => Sql.JoinAlias(x.MyIntColumn, 1) == 2 will fail, as the return result should be a string.

Would there be any problem in changening https://github.com/ServiceStack/ServiceStack.OrmLite/blob/master/src/ServiceStack.OrmLite/Expressions/Sql.cs#L63 to something like this ?

```
public static string JoinAlias(string property, string tableAlias) => tableAlias;
public static T JoinAlias<T>(T property, string tableAlias) => property;
```

Link to gist with full example.
https://gist.github.com/dlj/845593777ec4653899232d1b38acfe3a

**Comment by mythz** [comment]
We don't use the return type of `Sql.JoinAlias()` so adding the overload didn't impact existing code.

Your suggestion overload of JoinAlias was added in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/4a321b26c4c538a4f5b78e7fa6b3f7383047a6f3) which is available from v4.5.9 that's now [available on MyGet](http://docs.servicestack.net/myget).
