### ISSUE TITLE
HtmlFormat.cs displays links inconsistent with ServiceStackHost#GetBaseUrl

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#541]
When ServiceStackHost#GetBaseUrl handles http headers such as "x-forward-port", I would expect this to be reflected in the user visible links.
Currently that does not appear to be the case here https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Formats/HtmlFormat.cs#L93
I assume it would be a simple fix to use ServiceStackHost#GetBaseUrl

**Comment by mythz** [comment]
I've changed changed it to resolve using GetBaseUrl() in [this commit](https://github.com/ServiceStack/ServiceStack/commit/9ce056c3b89c4b80827bbcde0904699f81a6f503). If you need to further change how the external URL's are resolved you can override `ResolveAbsoluteUrl()` in your AppHost.

This change is available from v4.5.9 that's now [available on MyGet](http://docs.servicestack.net/myget).
