### ISSUE TITLE
ServiceStack.Interfaces.Core Version

### ISSUE THREAD

**Issue by svantreeck** [ServiceStack/Issues#543]
I'm having an issue where I have a .net core app that references two different services via a nuget package reference (ServiceA.ServiceModel references 1.0.40 ServiceStack.Interfaces.Core and ServiceB.ServiceModel on 1.0.42 ServiceStack.Interfaces.Core), and Visual Studio will start complaining about needing to reference ServiceStack.Interfaces version 1.0.  I think it comes down to the version that it ServiceStack.Interfaces.Core is being published with.  When I synchronize the versions that the nuget packages reference, this error goes away.  When I look at most of the ServiceStack.Core nuget packages, it looks like the Product Version is 1.0.0, whereas with interfaces we are seeing different versions based on what is being used.

1.0.42 shows:
![image](https://user-images.githubusercontent.com/6819011/26944591-c4010138-4c4e-11e7-83ca-9550a1c1ae63.png)

1.0.40 shows:
![image](https://user-images.githubusercontent.com/6819011/26944611-d1f894a4-4c4e-11e7-91fc-b8ba87a16d86.png)

**Comment by mythz** [comment]
I see the version issues but I'm not seeing any errors with the v1.0.42 .NET Core packages on NuGet. I should've resolved the versioning number issues with the latest [v1.0.43 on MyGet](http://docs.servicestack.net/myget),

Can you try [referencing the v1.0.43 .Core packages on MyGet](https://github.com/aspnet/Home/wiki/Configuring-the-feed-used-by-dnu-to-restore-packages#window-machine-without-visual-studio-2015) you just need to add the feed in:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="ServiceStack MyGet feed" value="https://www.myget.org/F/servicestack" />
  </packageSources>
  ...
</configuration>
```

In your **%AppData%\NuGet\NuGet.config** folder. If it resolves the issue I'll deploy the .NET Core packages to NuGet.

**Comment by mythz** [comment]
Let me know if [v1.0.43 on MyGet](http://docs.servicestack.net/myget) doesn't resolve the issue.

**Comment by svantreeck** [comment]
Still running into an issue with 1.0.43 against either 1.0.42/1.0.40 

I pulled some extra info off of the assemblies, and I think the earlier versions were reporting the interfaces dlls as version 1.0.0.0, and in the last two releases, its been 4.0.0.0 and 1.0.43.0.

1.0.39
```
Info Version:1.0.39.0
File Version:1.0.39.0
Version:ServiceStack.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

1.0.40
```
Info Version:1.0.40.0
File Version:1.0.40.0
Version:ServiceStack.Interfaces, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
```

1.0.42
```
Info Version:4.5.9
File Version:1.0.42.0
Version:ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43
```

1.0.43
```
Info Version:
File Version:1.0.43.0
Version:ServiceStack.Interfaces, Version=1.0.43.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43
```

I uploaded a repo that I was using to test this at https://github.com/svantreeck/servicestackcore, but have also attached the error I get below
![image](https://user-images.githubusercontent.com/6819011/27086986-6dd3e5f4-5019-11e7-8b06-9972aec10f5e.png)

**Comment by mythz** [comment]
We only keep a constant version for the PCL **ServiceStack.Interfaces.dll** because it's a signed version, the .NET Core version of **ServiceStack.Interfaces.dll** is not Signed so the Assembly and FileVersion will reflect its true version.

**Comment by svantreeck** [comment]
Just to confirm then, is the error shown above what you'd expect with the versioning scheme? With the 4.x PCL Interfaces dll it was nice to be able to have a common interface (even if every so often a newer version had extra methods) so we could independently update services while being able to distribute our service models with different servicestack versions. 

I'm not sure how we'd do that in .net core with the scheme that you are suggesting...and would probably have to move clients over to using the Cli or VS plugin, but then lose the ability to use nuget to update all of our dependencies.

**Comment by mythz** [comment]
All projects within the same solution should be referencing the same version of ServiceStack libraries in which case you shouldn't be seeing any versioning error messages. Clients with different versions of ServiceModel/SS.Interfaces will still be able to call a Server with a different version since the wire format remains exactly the same, but if the constant version number helps with deployment then I could change it to use a constant version like the PCL version

**Comment by svantreeck** [comment]
I agree about a project utilizing the same version throughout.  The scenario we have is that each service generally will publish a nuget package with it's service models.  The service models will reference ServiceStack.Interfaces to decorate the messages with `IReturn<T>`, `IHasResponseStatus`, `IGet`, `IPost`, etc.  Then, if we have a client that is referencing services on different versions of ServiceStack.Interfaces, having the same version on the assembly means we can always replace the implementations.

**Comment by mythz** [comment]
The latest **ServiceStack.Interfaces.dll** from **ServiceStack.Interfaces.Core** NuGet package should now retain a constant `4.0.0.0` version number whilst you can look at the File Version to see its true version number. Let me know if you run into any further issues.

**Comment by svantreeck** [comment]
Great, thank you!
