### ISSUE TITLE
ServiceStack.Interfaces - System.Runtime.Serialization version conflict

### ISSUE THREAD

**Issue by PanHilary** [ServiceStack/Issues#545]
I have an application that uses ServiceStack.Interfaces package, taken via Nuget (latest version)
In Visual Studio 2015 compilation runs without any warning. But after switching to Visual Studio 2017, during compilation I receive the following warning:

> _No way to resolve conflict between "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.Runtime.Serialization, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes". Choosing "System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrarily._

When I switched the build output verbosity to diagnostic mode, I got a more accurate description:

> _**References which depend on "System.Runtime.Serialization, Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b77a5c561934e089" [C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.6.1\System.Runtime.Serialization.dll]. (TaskId:69)
           C:\Projects\MyApp\packages\ServiceStack.Text.Signed.4.5.10\lib\net45\ **ServiceStack.Text.dll** (TaskId:69)
             Project file item includes which caused reference "C:\Projects\MyApp\packages\ServiceStack.Text.Signed.4.5.10\lib\net45\ServiceStack.Text.dll". (TaskId:69)
               ServiceStack.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL (TaskId:69)
               ServiceStack.Text, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL (TaskId:69)
           C:\Projects\MyApp\packages\ServiceStack.Client.Signed.4.5.10\lib\net45\ **ServiceStack.Client.dll** (TaskId:69)
             Project file item includes which caused reference "C:\Projects\MyApp\packages\ServiceStack.Client.Signed.4.5.10\lib\net45\ServiceStack.Client.dll". (TaskId:69)
               ServiceStack.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL (TaskId:69)
       **References which depend on "System.Runtime.Serialization, Version=2.0.5.0**, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes" []. (TaskId:69)
           C:\Projects\MyApp\packages\ServiceStack.Interfaces.4.5.10\lib\portable-wp80+sl5+net45+win8+wpa81+monotouch+monoandroid+xamarin.ios10\ **ServiceStack.Interfaces.dll** (TaskId:69)
             Project file item includes which caused reference "C:\Projects\MyApp\packages\ServiceStack.Interfaces.4.5.10\lib\portable-wp80+sl5+net45+win8+wpa81+monotouch+monoandroid+xamarin.ios10\ServiceStack.Interfaces.dll". (TaskId:69)
               ServiceStack.Client, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL (TaskId:69)
               ServiceStack.Interfaces, Version=4.0.0.0, Culture=neutral, PublicKeyToken=e06fbc6124f57c43, processorArchitecture=MSIL (TaskId:69)_

It seems that the **ServiceStack.Interfaces.dll** was compiled with old versions of System libraries. Can it be fixed?

**Comment by mythz** [comment]
ServiceStack.Interfaces is a PCL library and its just built with the [System.Runtime.Serialization](https://github.com/ServiceStack/ServiceStack/blob/34acc429ee04053ea766e4fb183e7aad7321ef5e/src/ServiceStack.Interfaces/ServiceStack.Interfaces.csproj#L55) it references using VS2017's new MSBuild format.

Once .NET Standard 2.0 and .NET Core 2.0 is released we'll be merging .NET Standard libraries together into the main ServiceStack NuGet packages in a major v5 release of ServiceStack that will replace the PCL libraries with .NET Standard which will resolve this issue, but we'll need to wait for v5 before we make any structural changes.
