### ISSUE TITLE
Application lock after master fail-over

### ISSUE THREAD

**Issue by ffosselle** [ServiceStack/Issues#546]
## Problem situation description

We are running continuously running worker type service on the Windows platform. The C# code is targeting .NET Framework 4.5 and connecting to Redis 3.0.5 sentinel setup with the use of the Service Stack library of version 4.0.62.

The Redis sentinel setup is composed of the two Redis nodes (one master and one slave on separate machines) and 3 Redis sentinels (2 hosted together with the Redis instances on their machines plus one hosted on the separate machine). The setup is made to resist single node or single machine failure with the use of the Redis sentinel failover.

The observer behaviour, discused further, is a result of single machine failure (i.e. machine hosting Redis master node as well as one Redis sentinel is abruptly shut down).

## System behaviour description

We see that after the system failure (single machine down) the failover on the level of the Redis nodes is resolved in timely fashion with no obvious Redis or infrastructure issues. Remaining two sentinels properly communicate the master down event and elect the remaining slave to the master role.

On the other hand the continuously running worker gives all the signs of the application lock as: no signs of work, no response to propper restart (if running as Windows service). And this is rather puzzling as the application is expected to catch any exceptions originating from the service downtime and no in-application locking is in place which could lead to deadlock

## Analysis of the process memory dump

We have been able to analise the memory dump of the process which had all the signs mentioned before in the WinDbg. List of the running threads can be fount in the attachment. Notable threads are like: 

19   26 1100 000000cfbba00880  3029220 Preemptive  000000CFA37675D8:000000CFA3768AA8 000000cfa14a4e90 2     MTA (Threadpool Worker) ServiceStack.Redis.RedisException 

43   62 1a54 000000cfbf18c270  202b221 Preemptive  000000CFA32C9D10:000000CFA32CA750 000000cfa14a4e90 0     MTA System.Threading.ThreadInterruptedException 

Thread 19: note the killing of the background thread which is not an ideal situation ( https://github.com/ServiceStack/ServiceStack.Redis/blob/0b1a3645b52797069ecf6ebe401696c2e2310add/src/ServiceStack.Redis/RedisPubSubServer.cs#L427 ).

Thread 32: note the last identifiable method (GetMaster from Service Stack library) which appears to be locked.

Thread 43: similar to thread 32 with difference of "GetSentinelInfo" being the last method.

 
## 
[thread_list.txt](https://github.com/ServiceStack/Issues/files/1080927/thread_list.txt)
[thread_43.txt](https://github.com/ServiceStack/Issues/files/1080926/thread_43.txt)
[thread_32.txt](https://github.com/ServiceStack/Issues/files/1080928/thread_32.txt)

Questions and observations

After what we have been able to see and analyse we truly believe that the cause of the application unresponsiveness is of deep non trivial nature, most probably originating from the Service Stack Redis library. In this way we will greatly appreciate any help from your side, helping to solve the true reason behing the apparent application deadlock. We are open for any further assistance if required.

**Comment by xplicit** [comment]
How many memory is used/free when you get deadlock? Dump from thread_32 shows that it hangs when tries to allocate new memory. Which GC mode do you use when run you service? You can try enable [server mode](https://msdn.microsoft.com/en-us/library/cc165011(v=office.11).aspx) if it's not enabled yet. Possible some there are some memory leaks which eats all memory and process hangs, when tries to allocate new memory. You can try to monitor total amount of memory during the process running and Gen0/1/2 collections. (You can use performance counters for it).   

However it's very difficult to say what is the cause of the issue without able to reproduce it locally. It would be very good if you provide an example of sentinnels/redis configurations and the code which produce this deadlock so we can catch the issue and see what is the real cause of it.

**Comment by ffosselle** [comment]
We have created a proof of the concept for the apparent application locking discussed before. The proof consist of the sample Visual Studio solution with a simple continuously running worker–like program.

## Prerequisites
[worker_lock.zip](https://github.com/ServiceStack/Issues/files/1099483/worker_lock.zip)

Please setup 2 redis nodes (one master one replica) and 3 redis sentinel instances, very similar to how it is described at: https://redis.io/topics/sentinel

Please change the App.config file in the solution to properly point to the host hosting the sentinels.

## Issue reproduction

Start the debugging of the program, you should see debugging information filling the screen with the messages. Then Stop Redis master and then one Redis sentinel as well.

You should see at least two exceptions popping up (if in debugging mode), one in the consumer worker base and other in the producer worker. These exception are caught and should not cause application shutdown. The application will ideally then enter the wanted locked state when there is no apparent activity made by the application and it looks like the application is waiting for return of the "GetMaster" function from the Service Stack Redis library.

**Comment by xplicit** [comment]
What I did:
1. I downloaded your code and changed in App.Config to the following value

```xml
<redis host="redis-host" db="0" serviceName="mymaster" type="Sentinel" port="6381"
connectionString="localhost:26380,localhost:26381,localhost:26382">
```

2. I cloned `https://github.com/ServiceStack/redis-config` and changed `sentinel3/windows/start-all.cmd` by commenting out this line

```
REM start %redis_server% server-6382\redis.conf
``` 
3. I started `sentinel3/windows/start-all.cmd`
This bat file starts 2 redis servers (1 master at 6381 and 1 slave at 6380 and 3 sentinels at 23680, 23681, 23682)

3. I started you application with configs I changed at point 1.  I see log messages in console that message that messages are processed and completed on `producer`, `consumer_1`, `consumer_2` 
4. I went to `sentinel3\windows\server-6381` folder and run `stop.cmd`. This command stopped master redis server and one sentinel.
5. I see several exception messages on console.
6. After several seconds I see again messages in console which say that message are processed and completed by `producer`, `consumer_1` and `consumer_2`.  So after shutdown the master the slave redis server processes messages as expected.

Can you try to run your application with redis configs from `https://github.com/ServiceStack/redis-config`? Does this help?

**Comment by xplicit** [comment]
Closed for long inactivity. If you still have the issue feel free to reopen it.

**Comment by egenovwork** [comment]
Hi!
I am experiencing what appears to be the exact same problem. I have written a simple prototype application that can reliably reproduce a problem.
The said prototype works in two modes, let's call them redis-interaction mode and redis-kill mode. redis-interaction mode emulates a relatively intensive interaction with redis (get/set operations and redisClient.Info are continuously executed in separate threads). redis-kill mode searches for current master in a Sentinel setup and shuts it down (both master and its sentinel), then, after a delay restarts it. That part is executed by means of redis-cli and plink to send restart commands, so ServiceStack libraries are not used. While redis-kill is running, redis-interaction hangs due to a lock after some time (after several master restarts).

My sentinel runs on three debian machines, one for master and two for slaves. I can send you all additional information if needed (including a dump file and a prototype). I can also reproduce the problem on a windows sentinel setup using https://github.com/ServiceStack/redis-config.

Redis version: 4.0.8
ServiceStack version: 5.0.2 and 5.1.0


![proc_dump](https://user-images.githubusercontent.com/39552934/40418149-40c6c09c-5e8a-11e8-9a48-33d44339513f.PNG)

**Comment by egenovwork** [comment]
Here is the prototype

I tried to minimize the amount of code in a prototype to make a minimal working example. Here's how it works:
1) redis-interaction mode gets redis client and sends info request once every second
2) redis-kill mode searches for active master, kills it along with the corresponding sentinel, waits a specified amount of time, then starts master and sentinel. It works only on unix setup, and uses plink to restart instances, so you may need to adjust that. redis-kill mode by default runs for 5 minutes, and waits for a minute before sentinel restart
3) It is possible to reproduce the issue by hand (without redis-kill mode) on windows sentinel, albeit I find this process kind-a painful, because sometimes the issue manifests itself only after several restarts

Unfortunately, you will have to make changes to source code and recompile an app in order for it to work, because sentinel addresses are currently hard-coded. redis-kill mode will also work only after compilation.

Here are the steps to prepare and run a prototype:
1) Open the solution in an IDE
2) Restore nuget packages
3) Specify a list of addresses of sentinels in Program.cs
4) Specify a unix password in Program.cs if you are going to run redis-kill mode
5) Compile an application
6) Run an application, you should see results of info command every second
7) Run redis_buster.bat, located in the app root directory
8) After some time, hopefully the application will hang and stop printing messages. A screenshot of what application looks like when it hangs is in the attachment

[RedisPrototype.zip](https://github.com/ServiceStack/Issues/files/2034689/RedisPrototype.zip)
![error](https://user-images.githubusercontent.com/39552934/40477078-3c92e572-5f4e-11e8-90af-349049411d43.PNG)

**Comment by lamnguyen108** [comment]
We're also running into what seems to be the same issue, i.e., failovers resulting in locking behavior that leaves clients spinning and threads queuing up on our web server. Below is part of a memory dump taken during the time our app was hung. The first two stack traces happened first, and then we see many stack traces like the third, where execution seems to be stuck on the RedisSentinel.GetMaster() call.

Redis 3.2.1 on Windows 
ServiceStack.Redis 5.0

OS Thread Id: 0x11cc (16)
        Child SP               IP Call Site
0000008d1c8b8fc8 00007ffad3d60d0a [GCFrame: 0000008d1c8b8fc8] 
0000008d1c8b91e0 00007ffad3d60d0a [GCFrame: 0000008d1c8b91e0] 
0000008d1c8b9218 00007ffad3d60d0a [HelperMethodFrame: 0000008d1c8b9218] System.Threading.Monitor.Enter(System.Object)
0000008d1c8b9310 00007ffa661d0921 ServiceStack.Redis.RedisSentinel.GetSentinelInfo()
0000008d1c8b9370 00007ffa6626e957 ServiceStack.Redis.RedisSentinel.ResetClients()
0000008d1c8b93e0 00007ffa6626e8e1 ServiceStack.Redis.RedisSentinelWorker.SentinelMessageReceived(System.String, System.String)
0000008d1c8b9460 00007ffa6626e61c ServiceStack.Redis.RedisPubSubServer+c__DisplayClass98_0.b__0(System.String, System.String)
0000008d1c8b94c0 00007ffa661db197 ServiceStack.Redis.RedisSubscription.ParseSubscriptionResults(Byte[][])
0000008d1c8b9550 00007ffa670628ef ServiceStack.Redis.RedisSubscription.UnSubscribeFromAllChannelsMatchingAnyPatterns()
0000008d1c8b9590 00007ffa661da8be ServiceStack.Redis.RedisPubSubServer.RunLoop()
0000008d1c8bc938 00007ffac4fedb49 [HelperMethodFrame: 0000008d1c8bc938] 
0000008d1c8bca20 00007ffa661d2bf9 ServiceStack.Redis.RedisNativeClient.SendReceive[[System.__Canon, mscorlib]](Byte[][], System.Func`1, System.Action`1>, Boolean)
0000008d1c8beb58 00007ffac4fedb49 [HelperMethodFrame: 0000008d1c8beb58] 
0000008d1c8bec40 00007ffa661d2aa7 ServiceStack.Redis.RedisNativeClient.SendReceive[[System.__Canon, mscorlib]](Byte[][], System.Func`1, System.Action`1>, Boolean)
0000008d1c8beca0 00007ffa661d28f4 ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][])
0000008d1c8bed10 00007ffa661d27f1 ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(System.String)
0000008d1c8bed50 00007ffa661d0aa3 ServiceStack.Redis.RedisSentinelWorker.GetMasterHostInternal(System.String)
0000008d1c8bed80 00007ffa661d09bd ServiceStack.Redis.RedisSentinelWorker.GetSentinelInfo()
0000008d1c8bedd0 00007ffa661d092b ServiceStack.Redis.RedisSentinel.GetSentinelInfo()
0000008d1c8bee30 00007ffa6626e957 ServiceStack.Redis.RedisSentinel.ResetClients()
0000008d1c8beea0 00007ffa6626e8e1 ServiceStack.Redis.RedisSentinelWorker.SentinelMessageReceived(System.String, System.String)
0000008d1c8bef20 00007ffa6626e61c ServiceStack.Redis.RedisPubSubServer+c__DisplayClass98_0.b__0(System.String, System.String)
0000008d1c8bef80 00007ffa661db197 ServiceStack.Redis.RedisSubscription.ParseSubscriptionResults(Byte[][])
0000008d1c8bf010 00007ffa661dab5b ServiceStack.Redis.RedisSubscription.SubscribeToChannelsMatching(System.String[])
0000008d1c8bf040 00007ffa661da796 ServiceStack.Redis.RedisPubSubServer.RunLoop()
0000008d1c8bf0a0 00007ffac27a4770 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
0000008d1c8bf170 00007ffac27a4604 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
0000008d1c8bf1a0 00007ffac27a45d2 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
0000008d1c8bf1f0 00007ffac282cff2 System.Threading.ThreadHelper.ThreadStart()
0000008d1c8bf448 00007ffac4f95c93 [GCFrame: 0000008d1c8bf448] 
0000008d1c8bf798 00007ffac4f95c93 [DebuggerU2MCatchHandlerFrame: 0000008d1c8bf798] 


OS Thread Id: 0x1a48 (57)
        Child SP               IP Call Site
0000008d210587c8 00007ffad3d60d0a [HelperMethodFrame_1OBJ: 0000008d210587c8] System.Threading.Thread.AbortInternal()
0000008d210588c0 00007ffac2fcf148 System.Threading.Thread.Abort()
0000008d21058900 00007ffa661da59c ServiceStack.Redis.RedisPubSubServer.KillBgThreadIfExists()
0000008d21058940 00007ffa67062e01 ServiceStack.Redis.RedisPubSubServer.Dispose()
0000008d21058990 00007ffa67062c51 ServiceStack.DisposableExtensions.Dispose(System.Collections.Generic.IEnumerable`1, ServiceStack.Logging.ILog)
0000008d210589f0 00007ffa661cf7f5 ServiceStack.Redis.RedisSentinel.GetNextSentinel()
0000008d21058a70 00007ffa67062a11 ServiceStack.Redis.RedisSentinel.OnSentinelError(System.Exception)
0000008d21058ab0 00007ffa66201645 ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(System.String)
0000008d2105abd8 00007ffac4fedb49 [HelperMethodFrame: 0000008d2105abd8] 
0000008d2105acc0 00007ffa661d2bf9 ServiceStack.Redis.RedisNativeClient.SendReceive[[System.__Canon, mscorlib]](Byte[][], System.Func`1, System.Action`1>, Boolean)
0000008d2105cdf8 00007ffac4fedb49 [HelperMethodFrame: 0000008d2105cdf8] 
0000008d2105cee0 00007ffa661d2aa7 ServiceStack.Redis.RedisNativeClient.SendReceive[[System.__Canon, mscorlib]](Byte[][], System.Func`1, System.Action`1>, Boolean)
0000008d2105cf40 00007ffa661d28f4 ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][])
0000008d2105cfb0 00007ffa661d27f1 ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(System.String)
0000008d2105cff0 00007ffa661d0aa3 ServiceStack.Redis.RedisSentinelWorker.GetMasterHostInternal(System.String)
0000008d2105d020 00007ffa6620160b ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(System.String)
0000008d2105d060 00007ffa662014f7 ServiceStack.Redis.RedisSentinel.GetMaster()

OS Thread Id: 0x2e0 (115)
        Child SP               IP Call Site
0000008d2342d4c8 00007ffad3d60d0a [GCFrame: 0000008d2342d4c8] 
0000008d2342d6e0 00007ffad3d60d0a [GCFrame: 0000008d2342d6e0] 
0000008d2342d718 00007ffad3d60d0a [HelperMethodFrame: 0000008d2342d718] System.Threading.Monitor.Enter(System.Object)
0000008d2342d810 00007ffa662014e9 ServiceStack.Redis.RedisSentinel.GetMaster()

**Comment by mythz** [comment]
Please use the latest [v5.1.1 on MyGet](http://docs.servicestack.net/myget), it has all the fixes mentioned in this [Thread](https://forums.servicestack.net/t/application-appears-to-be-deadlocked-after-sentinel-failover/5782/3).
