### ISSUE TITLE
Razor compilation error CS1041: Identifier expected; 'using' is a keyword"}

### ISSUE THREAD

**Issue by VadimUmojo** [ServiceStack/Issues#547]
Hello,

Compiling an razor file there is an error CS1041: Identifier expected; 'using' is a keyword"}. Deeping down inside error's results there is incorrectly generated file with double "usage" using for the last assembly:

`//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP.@__tmp {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using ServiceStack;
    using ServiceStack.Html;
    using ServiceStack.OrmLite;
    using ServiceStack.Razor;
    using ServiceStack.Text;
    using using MYASSEMBLY;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute(\"RazorGenerator\", \"4.5.12.0\")]
    [ServiceStack.Razor.Compilation.CodeTransformers.VirtualPathAttribute(\"~/__tmp/ace39f9f133d4d9c8602e9b3a4bdbd03.cshtml\")]
    public partial class @__ace39f9f133d4d9c8602e9b3a4bdbd03 : ServiceStack.Razor.ViewPage {
	
	public @__ace39f9f133d4d9c8602e9b3a4bdbd03() {
	}
	
	public override void Execute() {`

Thank

**Comment by mythz** [comment]
Note: Microsoft's System.Web.Razor is used to generate the Razor files, you can try clearing our your the `/obj` and `/bin` folders and try re-building to see if that helps. 

Otherwise please provide the Razor Page itself and the complete `<system.web.webPages.razor>` section in the Web.config.

**Comment by VadimUmojo** [comment]
My apologies, an mistake in project's app.config was found:
<system.web.webPages.razor>
    <host factoryType="System.Web.Mvc.MvcWebRazorHostFactory, System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31BF3856AD364E35" />
    <pages pageBaseType="ServiceStack.Razor.ViewPage">
      <namespaces>
        <add namespace="ServiceStack" />
        <add namespace="ServiceStack.Html" />
        <add namespace="ServiceStack.Razor" />
        <add namespace="ServiceStack.Text" />
        <add namespace="ServiceStack.OrmLite" />
        <add namespace="using MYASSEMBLY" />
      </namespaces>
    </pages>
  </system.web.webPages.razor>
