### ISSUE TITLE
OrmLite (SQL Server) generates incorrect SQL, varchar(8000) used instead of varchar(MAX)

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStack/Issues#549]
Strings are truncated to 8000 characters as varchar(MAX) is not generated as the type/size of the parameter.

I've created a sample application which shows the issue:

https://github.com/georgehemmings/SSVarCharMaxBug/blob/master/Program.cs

**Comment by mythz** [comment]
There is no `varchar(Max)` DbType, OrmLite uses the default length in:

```csharp
OrmLiteConfig.DialectProvider.GetStringConverter().StringLength
```

But I've added a fix which will increase the size of the param length if it exceeds the default length in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/23cbc3d87e4d7b5c9ea91cca25f72b00ba3905c7). This change is available from v4.5.13 that's now available on MyGet.

Note the recommended and portable way to declare "maximum string length" is to use:

```csharp
class Person
{
        [AutoIncrement]
        public int Id { get; set; }

        [StringLength(StringLengthAttribute.MaxText)]
        public string Name { get; set; }
}
```

**Comment by georgehemmings** [comment]
Thanks.

With `UseUnicode = true` should the default not be 4000 instead of 8000?

The SQL defaults would then be `varchar(8000)` and `nvarchar(4000)`. The current pairing is `varchar(8000)` and `nvarchar(MAX)`.

**Comment by georgehemmings** [comment]
Actually, if the value is set, could you always set the size to the length of the string?

**Comment by mythz** [comment]
The default length is overridable with StringLength, 8000 is fine for either. I'm ok with only changing from the default size when needed.

**Comment by georgehemmings** [comment]
I think i'll set StringLength to 1 so the param size will always be the value length. I'm not using the schema create/drop APIs. Before I shoot myself in the foot, are there any other areas where the default value is used? Cheers

**Comment by mythz** [comment]
It's used whenever a RDBMS string length is needed, what benefit is there to changing it?

**Comment by georgehemmings** [comment]
Actually, I won't be doing that. It looks like it would [pollute the plan cache](http://www.sqlpassion.at/archive/2015/07/20/how-to-pollute-your-plan-cache-with-parameterized-sql-statements/).

If I was using Unicode strings I'd change it to 4000 as I don't trust the performance would be the same with MAX.

I think the ideal situation would be to set the parameter length to be the same as the column length. [This article ](https://blogs.msdn.microsoft.com/psssql/2010/10/05/query-performance-and-plan-cache-issues-when-parameter-length-not-specified-correctly/) suggests that if they are not the same there is a performance impact with linked server. I don't know if you have the column info (particularly StringLength attribute info) available when you generate the related param.

The change you have already made has resolved my issue though. Thanks.
