### ISSUE TITLE
Why InsertAll() method inserts one row at a time?

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#550]
In ServiceStack.OrmLite, InsertAll() method inserts rows on a foreach.
So, the component is talking to the database at each row.
Why this choice?

A batch insert would be faster.

**Comment by mythz** [comment]
Please submit any [feature requests to UserVoice](https://servicestack.uservoice.com/forums/176786-feature-requests) instead. The current naive implementation supports all databases.

**Comment by KevinHoward** [comment]
https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/6429966-add-bulkinsert-bulk-copy-to-the-ormlite-databases
