### ISSUE TITLE
ToUpdateStatement breaks with $ symbol

### ISSUE THREAD

**Issue by dylanvdmerwe** [ServiceStack/Issues#554]
With the `SqlServer2012Dialect`, I am using the `ToUpdateStatement` extension method on the `IDbConnection`. 

However if one of the strings in the class, for example `FullName`, contains a `$` symbol, the resulting SQL is broken/not valid. 

Seems to happen for any string field I test. 

An example of the SQL I get looks as follows where I gave `FullName` the value of `"Guest$"`:

`UPDATE "AppUser" SET "IsDeleted"=0, "DateCreated"='20170717 21:21:03.3013781', "AccountEnabled"=0, "AppPermission"='', "LoggedInRegionId"=0, "Username"='Guest', "UserId"='58aebc08-41b1-4a53-b07e-d568c81734e0', "FullName"='Guest "Token"='' WHERE "AppUserId"=2025, "Token"='' WHERE "AppUserId"=2025`

**Comment by mythz** [comment]
Please provide a complete example containing the OrmLite code that we can run that repro's the issue.

**Comment by dylanvdmerwe** [comment]
See attached repo

[ConsoleApp1.zip](https://github.com/ServiceStack/Issues/files/1154089/ConsoleApp1.zip)

**Comment by mythz** [comment]
Should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/76af08e09e8292454eaf4e2a33859666ce25ef79) which is now available from v4.5.13 that's now [available on MyGet](http://docs.servicestack.net/myget).
