### ISSUE TITLE
Unable to detect received failure message from remote server

### ISSUE THREAD

**Issue by jsobell** [ServiceStack/Issues#558]
I'm trying to pass in multiple Form variables to a remote server, and the only practical way I can see is to use `PostFilesWithRequest` with a class containing all the properties I need in the text values (is there a better way?)
It works as long as the remote server returns a specific known type, but if the remote server returns an error message (such as `{"error":"There were errors with your request."}`) we get an *"Index was outside the bounds of the array"* no matter what we do with the return data type.

The call looks like this:
```
response = client.PostFilesWithRequest<object>(baseurl, new FormsVarsRequest(), new List<UploadFile>());
```

How do I access the actual returned string or object, and is this the only way to send form data in multipart format?

**Comment by mythz** [comment]
This issues tracker is for submitting reproducible issues only, please use the Customer Forums or StackOverflow for any other support questions.

The ServiceStack Service Clients should only be used to call ServiceStack Services, calling 3rd Party APIs is not supported. ServiceStack Services should return Typed Response DTO. The [docs contains other raw Response Types](http://docs.servicestack.net/csharp-client#support-for-native-built-in-response-types).
