### ISSUE TITLE
Discontinue Silverlight 5

### ISSUE THREAD

**Issue by sundarchi** [ServiceStack/Issues#559]
It's pretty evident that Silverlight is pretty much dead nowadays, with most major browsers not even supporting it anymore. There's a lot of "SL5" code on ServiceStack that should be cut out to reduce bloat.

**Comment by mythz** [comment]
We'd love to, but it's still used internally by Customers and we're not in the habit of dropping support for existing platforms, we're considering marginalising it after v5.
