### ISSUE TITLE
Open Source build - .NET Core - License has expired on 1/1/2013

### ISSUE THREAD

**Issue by ahammedunni** [ServiceStack/Issues#560]
Hi,

We are building an open source aPaaS product (https://github.com/ExpressBaseSystems) on top of .NET  Core. We are using ServiceStack for Web Services/MQ. Thanks for this wonderful product.

Until now we have been using commercial NuGet packages of ServiceStack for convenience. Now the # of operations have started to grow, so we are unable to use the free/starter plan.

We created .NET Core NuGet packages of 4.5.12 Release Service Stack code and consumed in our project, but are getting license exception as below:

**ServiceStack.LicenseException occurred**
  HResult=0x80131500
  Message=**This license has expired on 1/1/2013 and is not valid for use with this release. Please see servicestack.net or contact team@servicestack.net for more details**.

The Test license key used is from:
https://github.com/ServiceStack/ServiceStack.Text/blob/master/tests/ServiceStack.Text.Tests/App.config#L4, which we got from this thread - https://stackoverflow.com/questions/23665009/service-stack-foss-exception.

Is there a new License Key for Opensource / Test projects Or are we doing anything wrong?

**Comment by mythz** [comment]
The official packages on NuGet are only available under the [commercial license](https://servicestack.net/terms). Only the source code in ServiceStack repo's is dual-licensed under the [AGPL/FOSS License](https://github.com/ServiceStack/ServiceStack/blob/master/license.txt).

So you cannot use the NuGet packages under the AGPL/FOSS License. You'll need to build any of the libraries you need from source where you'll be able to use your Test License key.

**Comment by sureba73** [comment]
Thanks for the reply. But we are not using official NuGet packages. We built local NuGet packages from Service Stack Source afresh. And then included the Test License key in Web.config. On running, we get "This license has expired on 1/1/2013 and is not valid for use with this release" message.

Any pointers to solve the issue?

**Comment by mythz** [comment]
You would not get that Exception if you built form source. Build from source and use the resulting .dlls, don't use NuGet packages, you're referencing the wrong ones.
