### ISSUE TITLE
NetCoreLogFactory doesn't log exceptions

### ISSUE THREAD

**Issue by dabide** [ServiceStack/Issues#563]
`NetCoreLogFactory` logs exceptions like this:

```csharp
        public void Error(object message, Exception exception)
        {
            log.LogError(message.ToString(), exception);
        }
```
It should be like this:

```csharp
        public void Error(object message, Exception exception)
        {
            log.LogError(exception, message.ToString());
        }
```

(See https://github.com/aspnet/Logging/blob/9461009174fe3c72081ec5a20786fbfbb725554e/src/Microsoft.Extensions.Logging.Abstractions/LoggerExtensions.cs#L342)

This leads to no exceptions being logged. It is the same for all the methods with an `Exception` parameter.

**Comment by mythz** [comment]
`log.LogError(exception, message.ToString());` is a compile time error but I've updated it to use the appropriate .NET Core Logging APIs in this commit: https://github.com/ServiceStack/ServiceStack/commit/1a0bdd7662a23a2551b0aa013e7112f9c68fbb8b

thx for reporting!

**Comment by dabide** [comment]
OK, the overload w/o EventId is probably from .NET Core 2.0. Thanks for fixing!
