### ISSUE TITLE
Latest version encoding bug

### ISSUE THREAD

**Issue by sundarchi1** [ServiceStack/Issues#564]
I have an issue with the latest version.

I have this service method defined:
```
[AddHeader(ContentType = MimeTypes.PlainText)]
public object Get(InternalCooler request)
```

What it does is basically create a StringBuilder, add a bunch of stuff, and then return its ToString.

The characters that get added can be special, like trademark, copyright symbols, etc.

The browser shows these as corrupted characters.

I think I narrowed down the bug to the response header.
4.5.12:
```
HTTP/1.1 200 OK
Content-Type: text/plain; charset=utf-8
```
4.5.14:
```
HTTP/1.1 200 OK
Content-Type: text/plain
```

Is this intended? If it is, please do tell how to add UTF 8 to response now.

**Comment by mythz** [comment]
I'm still tracking down the commit that caused this change, but you can append `; charset=utf-8` to specific Content Types with:

```csharp
SetConfig(new HostConfig {
    AppendUtf8CharsetOnContentTypes = { MimeTypes.PlainText }
})
```

**Comment by mythz** [comment]
I've tracked it down to our switch to async Response writes where ASP.NET's `HttpResponseBase.Write(string)` implicitly appended the UTF-8 suffix. I've enables this behavior for string responses in [this commit](https://github.com/ServiceStack/ServiceStack/commit/4ff2486d7c54ec81946156e5eccc2dd8b994e1d6).

This change is available from v4.5.15 that's now [available on MyGet](http://docs.servicestack.net/myget), alternatively the explicit config above will append it to plain text responses in v4.5.12.

**Comment by sundarchi1** [comment]
Ok, interesting.. so it was incorrect to assume UTF-8 Content-Types would be returned, and the fact that it worked before this change was undefined/unintended behavior?

Is the proper way to ensure UTF-8 Content-Types to populate that setting? What happens if that setting is set and I try that MyGet fix? It won't append it twice, will it?

**Comment by mythz** [comment]
Text responses are always returned as UTF-8 but it wasn't explicitly specified in the `Content-Type` HTTP Header unless it was added `Config.AppendUtf8CharsetOnContentTypes` except when returning a raw string as it used ASP.NET's `HttpResponseBase.Write(string)` which implicitly appended the UTF-8 suffix. This is now explicitly appended to the Content-Type of all raw string responses in all hosts.

The setting is only appended if it doesn't already exist, i.e. adding it yourself won't duplicate the suffix.
