### ISSUE TITLE
GlobalHtmlErrorHttpHandler doesnt catch exceptions in Razor Views

### ISSUE THREAD

**Issue by rds1983** [ServiceStack/Issues#565]
Hi,
I've attached a small sample made from official ServiceStack.Core RazorRockstars. It differs from the original by 3 lines:
1. Added `GlobalHtmlErrorHttpHandler = new RazorHandler("/");` to Startup.cs.
2. Added throwing of an exception to Views/Shared/MenuDead.cshtml.
3. Added throwing of an exception to RockstarsService.cs to "/reset" request.

The exception in RockstarsService is handled correctly so the user is redirected to the root. But the exception in the view isn't handled.
Unsure if it is a bug as I am a novice ServiceStack.Core user. So if there's an official way to process exceptions in views, please, let me know.

Thanks!

[RazorRockstars2.zip](https://github.com/ServiceStack/Issues/files/1291578/RazorRockstars2.zip)

**Comment by mythz** [comment]
Views should not throw Exceptions, it's a developer error if they do that should be resolved at development time.

**Comment by rds1983** [comment]
Sorry, but I can't agree. Views could throw Exceptions. The most obvious case is throwing of NullReferenceException when Model has null field that View uses.
Also classic ServiceStack seems to catch Exceptions from Views when GlobalHtmlErrorHttpHandler is set.

**Comment by mythz** [comment]
It's too late to be able to handle Exceptions in views that have already started writing to the Response. They can handle Exceptions in Services but they should never throw themselves.

**Comment by rds1983** [comment]
After more digging, I've found workaround:
```public override void OnExceptionTypeFilter(Exception ex, ResponseStatus responseStatus)
{
  throw ex;
}```

It rethrows Exceptions from Views and makes them handle by GlobalHtmlErrorHttpHandler.
