### ISSUE TITLE
AllowRouteContentTypeExtensions not working as intended

### ISSUE THREAD

**Issue by sundarchi1** [ServiceStack/Issues#566]
Here's my endpoint:
`http://localhost:22812/status?format=xml`

Since I have XML disabled, I get this exception:
`'Xml' Features have been disabled by your administrator`

To stop that from happening and to just ignore the `format` as if it wasn't there. I found `AllowRouteContentTypeExtensions` and set it to `false`.

Unfortunately, it did nothing. The exception still occurs, instead of `format` just being ignored entirely, which is what that setting seems to imply.

Seems like a bug!

**Comment by mythz** [comment]
`Config.AllowRouteContentTypeExtensions` refers to using extension to specify the Content-Type, e.g. `/path.xml` not `?format=xml` which says to return the response in XML which as you've disabled returns an exception as expected.

**Comment by sundarchi1** [comment]
How do you disable the `?format=` ?

**Comment by mythz** [comment]
Only the `/path` determines whether a request exists or not, not the `?queryString`. Unmatched routes are what returns 404 responses.

The `?format` is a built in feature in ServiceStack that clients can use to specify the content type they want the response returned in. You can override what client requests by forcing a Content Type by using:

    [AddHeader(ContentType="application/json")]

Or use the more specific `[JsonOnly]`, `[HtmlOnly]`, `[XmlOnly]`, etc which does the same thing.
