### ISSUE TITLE
OrmLite (sqlite): Crashes on Android 7 (API 24)

### ISSUE THREAD

**Issue by retaildata** [ServiceStack/Issues#567]
Xamarin Applications crash on Android 7 (Nougat) when using OrmLite (v1.0.44).
Works fine on earlier versions of android.
This is caused by a permission change for accessing system libraries in android, so apps now need to bundle their own sqlite.so. Maybe changing OrmLite to use v2.0.0 of Microsoft.Data.Sqlite would resolve this?

### Reproduction:
Deploy a Xamarin App which performs sqlite operations to an Android 7.0 device. App will be terminated with the following message once a sqlite operation is performed:

> Detected problems in native app libraries
> (please consult log for detail):
> libmonosgen-32bit-2.0.so: aunauthorized access to "/system/lib/libsqlite.so"

### Environment:
Device                - Samsung Galaxy Tab A (2016)
Model no           - SM-T580
Android Version - 7.0 (Nougat)

**Comment by mythz** [comment]
Honestly we didn't know you could run .NET Core of OrmLite on Android. I've upgraded to use Microsoft.Data.Sqlite v2.0.0 in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/a58ffcc3b23622ac4e92b12ca09b9669beb16abd) which is available from v1.0.45 that's now [available on MyGet](http://docs.servicestack.net/myget).

Hopefully that resolves the issue, if not you'll need to file an issue with Xamarin.
