### ISSUE TITLE
Replace "usefull" with "useful" in ServiceStack.OrmLite

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#568]
Found in comments of following files
src/ServiceStack.OrmLite/OrmLiteWriteExpressionsApi.cs

and

src/ServiceStack.OrmLite/OrmLiteWriteExpressionsApiAsync.cs

**Comment by mythz** [comment]
Fixed in this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/1fc3bffdaaca31481665bd848070acc0276039ec

Ideally typos like this are best resolved with a PR
