### ISSUE TITLE
ServiceStack.LicenseException

### ISSUE THREAD

**Issue by bialguos** [ServiceStack/Issues#569]
Hello,

We have used the redis component without any problems for almost a year. Yesterday, we deployed our mvc web application(Windows server 2008 R2) for the first time in release mode (until yesterday it had been in debug) and now we are getting the "The free-quota limit on '6000 Redis requests per hour' has been reached" error.

We are registering the license file via the web.config, as it follows:

```xml
<appSettings>
    <add key="servicestack:license" value="{licenseKeyText}" />
</appSettings>
```

Could it have something to do with the publish profile (from debug to release)?

**Comment by mythz** [comment]
For some reason ServiceStack isn't able to access the license key, make sure the `Web.config` that's deployed contains the `<appSettings>`. 

You can also try reading from the appSettings and explicitly registering the license key with:

```csharp
var licenseKey = ConfigurationManager.AppSettings["servicestack:license"];
ServiceStack.Licensing.RegisterLicense(licenseKey);
```

**Comment by mythz** [comment]
re-open if you still have issues.
