### ISSUE TITLE
Typescript types for Registration Feature DTOS do not include all required interfaces

### ISSUE THREAD

**Issue by on3al** [ServiceStack/Issues#570]
Issue:  They typscript types generated at types/typescript  do not compile without manual editing because they reference the interface "IPost" when the registration feature plugin is added, but the IPost interface is not included in the generated types.

Should be: Either include required interfaces, or do not put them on generated types
[dtos.txt](https://github.com/ServiceStack/Issues/files/1347542/dtos.txt)

OS: Windwos 10
.Net: dotnetcore-2.0
Sevicestack Version : ServiceStack.Core 1.0.44

These are the generated types (full generated types file attached)
`

// @Route("/assignroles")
// @DataContract
interface AssignRoles extends IReturn<AssignRolesResponse>, IPost
{
    // @DataMember(Order=1)
    userName?: string;

    // @DataMember(Order=2)
    permissions?: string[];

    // @DataMember(Order=3)
    roles?: string[];
}

// @Route("/unassignroles")
// @DataContract
interface UnAssignRoles extends IReturn<UnAssignRolesResponse>, IPost
{
    // @DataMember(Order=1)
    userName?: string;

    // @DataMember(Order=2)
    permissions?: string[];

    // @DataMember(Order=3)
    roles?: string[];
}

// @Route("/session-to-token")
// @DataContract
interface ConvertSessionToToken extends IReturn<ConvertSessionToTokenResponse>, IPost
{
    // @DataMember(Order=1)
    preserveSession?: boolean;
}

// @Route("/access-token")
// @DataContract
interface GetAccessToken extends IReturn<GetAccessTokenResponse>, IPost
{
    // @DataMember(Order=1)
    refreshToken?: string;
}

// @Route("/apikeys")
// @Route("/apikeys/{Environment}")
// @DataContract
interface GetApiKeys extends IReturn<GetApiKeysResponse>, IGet
{
    // @DataMember(Order=1)
    environment?: string;
}

// @Route("/apikeys/regenerate")
// @Route("/apikeys/regenerate/{Environment}")
// @DataContract
interface RegenerateApiKeys extends IReturn<GetApiKeysResponse>, IPost
{
    // @DataMember(Order=1)
    environment?: string;
}
`

**Comment by mythz** [comment]
This issue is [already resolved](https://forums.servicestack.net/t/iput-in-generated-dtos/4642/2?u=mythz) in the latest v4.5.15 that's now [available on MyGet](http://docs.servicestack.net/myget).
