### ISSUE TITLE
Bytes not being compressed

### ISSUE THREAD

**Issue by sundarchi1** [ServiceStack/Issues#572]
I have this DTO:
```
[Route("/a/cjk", "GET")]
public class CJK : IGet
{

}
```
Implemented as so:
```
[AddHeader(ContentType = MimeTypes.Binary)]
public object Get(CJK request)
{
    return new byte[123];
}
```

Unlike my other ServiceStack services, which return json and plain-text, this one doesn't get compressed **even though the browser requests compression**. This seems like a bug.

I did find `CompressResponseAttribute`, but I haven't needed to add that to any other service to get those compressed.

**Comment by mythz** [comment]
It's not a bug, compression is only added if you [enable cached responses](http://docs.servicestack.net/caching) or use the `[CompressResponse]` attribute.

**Comment by sundarchi1** [comment]
But how come if I return plain-text (`return "blah";`) that gets compressed without setting this attribute?
Is there a list of mime types that will get compressed without setting this attribute?

**Comment by mythz** [comment]
Your webserver is likely doing the compression for text responses.

**Comment by sundarchi1** [comment]
Ok, so to clarify, ServiceStack won't compress `anything` (errors, DTO/json responses, text, etc) without the `CompressResponseAttribute` set?

**Comment by mythz** [comment]
ServiceStack does not auto-compresses responses, only when using caching or the `[CacheResponse]` attribute.

**Comment by sundarchi1** [comment]
I think you meant `CompressResponse` there.

I checked web server settings. You're right about .txt, and adding `CompressResponse` to it in ServiceStack appears to double compress it, but interestingly it doesn't corrupt it like I thought.

However, json is not set to compress at the web server level, so will ServiceStack do that when requested, without `CompressResponse` set? It seems like it's getting compressed in there, but it's not marked with `CompressResponse`.

**Comment by mythz** [comment]
Yes I meant `[CompressResponse]` as mentioned my first comment. 

As per my previous 2 comments, ServiceStack does not auto-compress responses.

**Comment by sundarchi1** [comment]
You're right, sorry, my test json was too small.

Thanks for the quick answers.. my last question is if you'd recommend compressing at the IIS level or ServiceStack level? Curious if there's any speed benefits with your implementation, or anything else.

**Comment by mythz** [comment]
If you're caching ServiceStack caches and returns an already compressed response. For uncached responses doing it at the webserver would be faster since it's using unmanaged code. 

If you're using self-hosting without a web server, there is no compression so you'll need to compress it in ServiceStack.
