### ISSUE TITLE
Sentinel not retrieving public master url

### ISSUE THREAD

**Issue by AGAlessio** [ServiceStack/Issues#573]
I m using ServiceStack implementation of redis client. 

My redis configuration is made up on 
    1 Master: 127.0.0.1:6280 
    1 slave: 127.0.0.1:6278

3 Sentinels are monitoring them: 
    127.0.0.1:23679 
    127.0.0.1:23680 
    127.0.0.1:23681 

All the servers are hosted on the same physical server (this is not a production configuration) published with: **mycompany.myserver.redis**

  ```
   List<String> sentinelHosts = new List<string>();
    sentinelHosts.Add("mycompany.myserver.redis:26379");
    sentinelHosts.Add("mycompany.myserver.redis:26380");
    sentinelHosts.Add("mycompany.myserver.redis:26381");
    try {
        var sentinel = new RedisSentinel(sentinelHosts, masterName: "mymaster6280");                
        redisManager = sentinel.Start();
        redisClient = redisManager.GetClient();                
                
     } catch (Exception ex) {               
        String s = ex.Message;
     }
```

In the sentinel.conf i tried to put these configuration lines the way the sentinel can send outside the right master public url:
    
   ```
 bind 127.0.0.1
    port 26379
    sentinel announce-ip mycompany.myserver.redis
    sentinel monitor mymaster6280 mycompany.myserver.redis 6280 2

```

But i m getting this exception:

    No master found in: 127.0.0.1:6280
    at ServiceStack.Redis.RedisSentinelResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
    at ServiceStack.Redis.RedisSentinelResolver.CreateMasterClient(Int32 desiredIndex)
    at ServiceStack.Redis.PooledRedisClientManager.GetClient()

It seems like sentinel is still sending the local master url, so it s impossible to connect to it.

What is wrong?

thank you

**Comment by mythz** [comment]
Can you first look at starting from the Redis Configuration from the [redis-config](https://github.com/ServiceStack/redis-config) project which provides the necessary configuration and scripts of a valid 3-node Sentinel configuration as you've described.

Otherwise we'd need a small stand-alone project with all the redis configuration including C# App to reproduce this issue which we can run locally to identify the issue.

**Comment by AGAlessio** [comment]
[ConsoleApp1.zip](https://github.com/ServiceStack/Issues/files/1400412/ConsoleApp1.zip)


here is the simple code i m using.  Inside the folder configuration you will find the configuration files for sentinel and redis servers master and slave.
In my usecase Redis servers and sentinels are on  the same remote machine in cloud... so they have a public url. The client application is running locally and raise an exception when on this code line

`    redisClient = redisManager.GetClient();`


thank you

**Comment by AGAlessio** [comment]
Solved creating a VPN...
