### ISSUE TITLE
Documentation for API not adequate for function OnMessage in IRedisSubscription

### ISSUE THREAD

**Issue by nathvi** [ServiceStack/Issues#575]
https://github.com/ServiceStack/ServiceStack.Redis/wiki/RedisPubSub gives a good example of how to use pub sub pattern. However, from the documentation that is provided with the API, I don't think there's a way to infer that in the property **Action<string, string> OnMessage { get; set; }** the first param is the channel, 
 and the second one is the msg. Other functions are pretty self explanatory, but for this one, I don't feel like I should have to thumb through a bunch of examples to have to figure out how to use it.

This is for ServiceStack.Redis 4.0.0

**Comment by nathvi** [comment]
A more self explanatory pattern would be to have an actual event **OnMessage**  and then have the args contain the channel and msg data.

**Comment by mythz** [comment]
This issue tracker is only for [submitting reproducible issues](https://github.com/ServiceStack/Issues).

You can submit any feature requests on [ServiceStack UseVoice](https://servicestack.uservoice.com/forums/176786-feature-requests).
