### ISSUE TITLE
Using ServiceStack.Common in .NetStandard project

### ISSUE THREAD

**Issue by OlegNadymov** [ServiceStack/Issues#576]
I can't use ServiceStack.OrmLite in my .NetStandard2.0 project.

I have below warning:
**Package was restored using .NetFramework 4.6.1 instead of target framework .netCore 2.0. The package may not be fully compatible**

![Warning Image](https://i.imgur.com/sJLdRr7.png)

It is a problem that similar to: [.net Core 2.0 - Package was restored using .NetFramework 4.6.1 instead of target framework .netCore 2.0. The package may not be fully compatible](https://stackoverflow.com/questions/46797892/net-core-2-0-package-was-restored-using-netframework-4-6-1-instead-of-target)

You have any plans to add compatibility of your project with .NetStandard2.0  ?

**Comment by mythz** [comment]
You need to reference the [.Core NuGet packages](http://docs.servicestack.net/netcore#net-core-servicestack-packages) to get the .NET Standard 2.0 versions in all v4.x packages on NuGet, i.e. reference `ServiceStack.OrmLite.Core`.

The next v5.0.0 release that’s [now available on MyGet](http://docs.servicestack.net/myget) merges the .NET Standard 2.0 libraries into the main ServiceStack.OrmLite NuGet packages. Please read the [v5 changes](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749) before using v5 packages on MyGet.

**Comment by OlegNadymov** [comment]
@mythz thank you! 👍
