### ISSUE TITLE
ServiceStack RedisSentinel performance ConnectionPool Filled

### ISSUE THREAD

**Issue by AGAlessio** [ServiceStack/Issues#577]
I m trying to managing my use case with ServiceStack.Redis RedisSentinel implementation.

My need is to have high performance cause my processes need to read and write into redis cache with the rate of 50 60 access per second.

Here below the code i use to create client.
After every read/write operation i call the 

     Client.Dispose()

in order to release resources and open connections.

```
      static Cache()
        {
            foreach (String masterGroup in connectionsStrings.Keys)
            {

                List<String> sentinelHosts = new List<string>();
                sentinelHosts.Add(connStr1);
                
                var sentinel = initializeSentinelConn(sentinelHosts, masterGroup);
                sentinel.RedisManagerFactory = CreateCustomPooledRedisClientManager;
                var manager = sentinel.Start();

                lazyConnections.Add(masterGroup, manager);
            }
            connectionHashing = new ConsistentHashing<string>(connectionsStrings.Keys);

        }


    private static RedisSentinel initializeSentinelConn(List<String> sentinelHosts, String masterGroup)
        {
            var sentinel = new RedisSentinel(sentinelHosts, masterName: masterGroup);
            sentinel.OnFailover = manager =>
            {
                sentinel.Dispose();

                sentinel = initializeSentinelConn(sentinelHosts, masterGroup);
                sentinel.RedisManagerFactory = CreateCustomPooledRedisClientManager;
                lazyConnections[masterGroup] = sentinel.Start();
            };
            return sentinel;
        }

    private static IRedisClientsManager CreateCustomPooledRedisClientManager(
                IEnumerable<string> readWriteHosts,
                IEnumerable<string> readOnlyHosts)
        {
            PooledRedisClientManager ma = readOnlyHosts.Any()
           ? new PooledRedisClientManager(readWriteHosts, readOnlyHosts, new RedisClientManagerConfig
           {
               MaxWritePoolSize = 10000,
               MaxReadPoolSize = 10000,
               AutoStart = true
           })
           : new PooledRedisClientManager(readWriteHosts.ToArray());

            //ma.ConnectTimeout = 5;
            ma.IdleTimeOutSecs = 1;
            //ma.PoolTimeout = 10;
            return ma;
        }

```

But the result is that after 10 seconds my processes start to throw this exception:

     Message = "Redis Timeout expired. The timeout period elapsed prior to obtaining a connection from the pool. This may have occurred because all pooled connections were in use."

What is wrong in my code? am i missing anything for a good tuning of the redis client?

**Comment by Layoric** [comment]
This kind of question is not what this issues list is intended for, see readme in this repository.

https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report

>Each issue must be reproducible with either a failing test, sample code, gist, link to a stand-alone project or otherwise clear steps to reproduce the issue. For details please see How to create a Minimal, Complete, and Verifiable example.

You would be better off asking this question on [StackOverflow](https://stackoverflow.com/questions/tagged/servicestack) or the `ServiceStack customer forums](https://forums.servicestack.net/).

**Comment by mythz** [comment]
As @layoric said, also it doesn’t look like you’re using the clients correctly, there should only be one instance of the RedisSentinel which itself uses its own pooled Redis client manager. The RedisSentinel has its own auto retry logic, don’t try to build your solution over the top. If you want you can take a local modified copy of RedisSentinel and modify its internals to suit your needs, but this isn’t a supported usage.
