### ISSUE TITLE
JSONP sanitization

### ISSUE THREAD

**Issue by wshirey** [ServiceStack/Issues#579]
There is a known vulnerability with JSONP that will allow javascript to be injected and executed on the browser. The recommended way to handle is to sanitize the inbound `callback` query parameter and only allow word characters.

Documentation
- https://www.owasp.org/images/3/35/2017-04-20-JSONPXSS.pdf
- https://www.metaltoad.com/blog/using-jsonp-safely

**Comment by mythz** [comment]
Thanks for the references, invalid chars from JSONP callback should be resolved with [this commit](https://github.com/ServiceStack/ServiceStack/commit/11675fd7b10651441c3e2497cd3e1f3063003d51).

This change is available from v5 that's now [available from MyGet](http://docs.servicestack.net/myget). Please review [v5 changes](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749) before upgrading.
