### ISSUE TITLE
Regression in `AddRule ... DelegateValidator` between SS 4.0.x and 4.5.y

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#583]
We rely on FluentValidation in SS to perform our validations.
This worked in SS 4.0.x, but is broken in SS 4.5.y.
A testcase to show the exact problem is available from https://github.com/veridit/ServiceStackValidationRegression

The core of the regression seems to be that DelegateValidator doesn't pick ut the reported failures.
The regression was probably introduced during the async rewrite.

Since SS doesn not yet use Fluent Validation 7.x we are unable to use the new `Custom` feature there, ref. https://github.com/JeremySkinner/FluentValidation/wiki/e.-Custom-Validators#using-a-custom-validator

**Comment by mythz** [comment]
We've upgraded to the latest Fluent Validation 7.2 and included [a test case using your example](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.WebHost.Endpoints.Tests/ValidationCustomTests.cs).

The latest Fluent Validation is available in ServiceStack v5, that's now [available on MyGet](http://docs.servicestack.net/myget).

thx for the repro!
