### ISSUE TITLE
ServiceStackVS Error

### ISSUE THREAD

**Issue by pascalsz** [ServiceStack/Issues#584]
Error: "Unable to connect to NuGet and no cached packages found for ServiceStack.Interface"

Hi Team, we are trying to use the ServiceStackVS Extension for Visual Studio 2015. When we use one of the templates from within this package, we always receive the exception that he is unable to connect to NuGet. 

We are woking in an environment without internet access.
We do have a local version of ProGet Running for our NuGet Packages (currently version 4..5.14) is uploaded to our ProGet Server.

Visual Studio is configured to use the ProGet Server as packages source (options.NuGet Package Manager.Package Sources)

It lookes like the VS Templates do not make use of the configuration in VS and tryes to connect directly to Nuget feed (blocked by our internal firewall team) 

Is there a way to configure the nuget source for the templates or could you fix the templates to use the package sources from visual studio?

When we create a console project and add the packages ourselves, we can add all ServiceStack Project. 

Thanks for your support.
Kind Regards
Pascal

**Comment by mythz** [comment]
No there isn't a way to override it. We're also maintaining our .NET Framework templates in GitHub, which includes a Self Host Console application at: https://github.com/NetFrameworkTemplates/selfhost-netfx

You can either clone the repo or use our new `dotnet-new` tool to create a new project from the above template. Our [v5 changes](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749) includes instructions on how to use the new tool, essentially you need to install `servicestack-cli` npm package:

    $ npm install -g servicestack-cli

Which will install the `dotnet-new` command globally which you can use to list all the available project templates:

    $ dotnet-new

Then create a project from the available templates, e.g. creating a new Self Host Console App:

    $ dotnet-new selfhost-netfx Acme

The templates are currently configured to use the latest v5.0.0 packages on MyGet, but you can configure them to use the current v4.5.12 by doing a global find/replace of `"5.0.0"` to "4.5.12" before doing a NuGet restore.
