### ISSUE TITLE
QueryStringSerializer.SerializeToString uses uppercase bools

### ISSUE THREAD

**Issue by sundarchi1** [ServiceStack/Issues#586]
With this set:
`QueryStringSerializer.ComplexTypeStrategy = QueryStringStrategy.FormUrlEncoded;`

...and then call:
`QueryStringSerializer.SerializeToString`

...on a DTO with a bool property set, the resulting query string contains uppercase boolean values ("True" or "False")

I think they should be lowercase by default ("true" or "false") to be consistent with default JSON serialization, which serializes bools lowercase.

**Comment by mythz** [comment]
The URL QueryString is unrelated to the JSON ContentType, it’s parses case-insensitive but uses the .NET Type ToString output by default.

Please reserve the [IssueTracker for reproducible issues](https://github.com/ServiceStack/Issues). You can submit feature requests on https://servicestack.uservoice.com/

**Comment by sundarchi1** [comment]
@mythz Sorry, this is easily reproducible, and didn't seem like a feature request. More of a quick fix.

Sending uppercase bools in query strings doesn't seem like the standard way to do it. I've never seen it in various web requests I've observed - everything is usually lowercase. Example would be on the Stripe website:
`https://dashboard.stripe.com/invoices?closed=false`
They use lowercase.

It seems like it would be easily fixable by checking for bool in your code when serializing, and then call `.ToString().ToLower()`.

**Comment by mythz** [comment]
No this is not an issue, it’s a feature request of which has never been requested before, you can submit a feature request for it in the link provided.

Source code showing how to lower case strings is absolutely not necessary.

**Comment by sundarchi1** [comment]
Very well, I introduced it here:
https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/32443760-improve-querystringserializer-serializetostring-to

Admittedly, I was a bit wary of posting there since it doesn't seem like most requests get a lot of attention compared to this tracker. Hope you'll consider looking at this one - seems easy!

**Comment by mythz** [comment]
UserVoice is to measure interest in and prioritize feature requests, but this issue tracker is to resolve actual and reproducible issues.

Please note there is no [web standard](https://www.w3.org/standards/) that mandates lower case query strings, if you plan on using terminology with distinct meaning please also include the links to the actual web standard that you're referencing.
