### ISSUE TITLE
Add sensible defaults to MemoryServerEvents

### ISSUE THREAD

**Issue by AVee** [ServiceStack/Issues#587]
I've created a little wrapper around `MemoryServerEvents` to be able to support multiple tenants. While testing that I got bitten by the fact that `new MemoryServerEvents()` creates an unusable instance because `IdleTimeout` is not set, causing all subscriptions to expire instantly. The way to resolve this is easy enough, just set a sensible value for `IdleTimeout` (and `HouseKeepingInterval`). But I think it would still be nice if `MemoryServerEvents` got some sensible defaults so `new MemoryServerEvents()` would create a functioning object.

**Comment by mythz** [comment]
The `IdleTimeout` and `HouseKeepingInterval` properties are public, why can't you just set them?

**Comment by AVee** [comment]
Rereading the above I think may not have been entirely clear. I've already found that I can set those properties. As such there is no immediate issue to resolve.

But I did spend quite some time before I figured this out, so I feel it would be an improvement if MemoryServerEvents had it's own sensible defaults. Currently Server-Sent Events will be broken when you configure your AppHost like this:

        public override void Configure(Container container)
        {
            container.Register<IServerEvents>(new MemoryServerEvents());
            Plugins.Add(new ServerEventsFeature());
        }

To me that is a rather unexpected result. I would have saved quite some time today if a plain `new MemoryServerEvents()` would produce a fully functional object. Right now you get a object where your subscriptions just keep disappearing, and it's not easy to see why. It is in no way essential, but it does seem a useful improvement.

**Comment by mythz** [comment]
MemoryServerEvents is the default, there no need to explicitly register it and you can specify the properties right there on the call-site?

But I've added defaults in [this commit](https://github.com/ServiceStack/ServiceStack/commit/bed1d900de93f889cca05299df4c33a04b7ad7a7).
