### ISSUE TITLE
Exception when deserializing null

### ISSUE THREAD

**Issue by sundarchi1** [ServiceStack/Issues#588]
I've run into a very interesting scenario that looks to have revealed a bug.

In the Cloudflare API, the `result` can contain any DTO object:
https://api.cloudflare.com/#getting-started-responses

So, this makes defining a typed DTO in C# impossible. I came up with a crude workaround:
```
public class CloudflareResponse
{
    public JsonObject result { get; set; }
}
public class PurgeFiles
{
    public List<string> files { get; set; }
}
public class PurgeResponse
{
    public string id { get; set; }
}

Response = JsonSerializer.DeserializeFromString<PurgeResponse>(JsonSerializer.DeserializeFromString<CloudflareResponse>((string)response.ResponseData).result.ToJson());
```

I feel like this is a really ugly hack. Please let me know if there's a better way to do this.

Anyway, the bug:
When the response's result is null (`"result":null`), ServiceStack crashes:
```
Failed to set property 'result' with ''

   at ServiceStack.Text.Common.DeserializeTypeRefJson.StringToType(TypeConfig typeConfig, StringSegment strType, EmptyCtorDelegate ctorFn, Dictionary`2 typeAccessorMap)
   at ServiceStack.Text.Common.DeserializeType`1.<>c__DisplayClass2_0.<GetParseStringSegmentMethod>b__1(StringSegment value)
   at ServiceStack.Text.Json.JsonReader`1.Parse(StringSegment value)
   at ServiceStack.Text.Json.JsonReader`1.Parse(String value)
   at ServiceStack.Text.JsonSerializer.DeserializeFromString[T](String value)
```

Now, if the result is _missing_, (tested via intercepting the HTTP response before ServiceStack catches it), result is properly set to null.

Just looks like you need to add logic to correctly parse actual null values.

**Comment by mythz** [comment]
Please provide an standalone repro we can run (i.e. on gistlyn.com, a complete code sample, or on a GitHub project) to repro the issue as [this works as expected](http://gistlyn.com/?gist=84b21f486091631f2d6b230027ef20e0&collection=2cc6b5db6afd3ccb0d0149e55fdb3a6a):

```csharp
public class CloudflareResponse
{
    public JsonObject result { get; set; }
}

var json = "{\"result\":null}";
var dto = JsonSerializer.DeserializeFromString<CloudflareResponse>(json);
```

**Comment by sundarchi1** [comment]
You need to set this:
`JsConfig.ThrowOnDeserializationError = true;`

So I guess setting that to false fixes the issue, but I think the underlying error should be addressed.

**Comment by mythz** [comment]
Resolved from [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/154cafde88a89c152b7c131b398b4d8bf95e60e8) this change is available from v5 that's now [available on MyGet](http://docs.servicestack.net/myget). 

Please review the [v5 changes](https://forums.servicestack.net/t/myget-pre-release-packages-upgraded-to-v5/4749) before upgrading. Also we should be releasing to publish v5 to NuGet tomorrow so you may want to wait till then.

**Comment by sundarchi1** [comment]
@mythz Thanks - glad I reported this today then!

Tell me though, is this the best way to handle the DTO types that can be anything? The code looks really ugly and was wondering if there's a better way to handle this `result` property to parse it into the correct type more efficiently.

**Comment by mythz** [comment]
We always recommend using a Typed POCO that matches the schema otherwise have a look at our [other dynamic JSON examples](https://github.com/ServiceStack/ServiceStack.Text#supports-dynamic-json). 

There's also our [JavaScript Utils](http://docs.servicestack.net/js-utils) for being able to parse unstructured JSON but this is just for parsing raw JSON string not something you can add to a Typed DTO.

**Comment by sundarchi1** [comment]
Thanks, I looked around and while I couldn't find a 100% clear answer for this scenario, it appears `JsonObject`'s `ConvertTo` does the job. If you have another/better suggestion, let me know.

**Comment by sundarchi1** [comment]
Actually @mythz `ConvertTo` unfortunately won't cut it. Does not handle nested Stripe types well.
Is there a way to avoid this dictionary mapping stuff and have it properly deserialize into the desired DTO only once?

**Comment by mythz** [comment]
My previous answer covers the different ways to deserialize an untyped data structure with ServiceStack libraries.

Please ask any future support questions on StackOverflow or in the Customer Forums.
