### ISSUE TITLE
OrmLite query by anon type regression in 5.0.0 (from 4.5.14)

### ISSUE THREAD

**Issue by georgehemmings** [ServiceStack/Issues#590]
I've found a regression in the latest OrmLite when querying using an anon type. The object I'm using to search with has a byte[] property which I believe is the problem.

When using `SqlServerDialect` an exception is thrown: `System.Data.SqlClient.SqlException: 'Invalid column name 'v0'.'`

With `SqliteDialect` it doesn't error, but just fails to find the record.

I've created a Gist showing it working in 4.5.14. http://gistlyn.com/?gist=ef4cc0390bc78450cb30295bf195c829

I tried to create a Gist showing it failing in 5.0.0 but get this error: `Could not load file or assembly 'System.Data.SQLite, Version=1.0.106.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`.

**Comment by mythz** [comment]
Should be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/3430da6591d13464456756ca42ade257c880468d) which is available from v5.0.1 that's [now on MyGet](http://docs.servicestack.net/myget).

**Comment by georgehemmings** [comment]
👍
