### ISSUE TITLE
Typescript client lost typing

### ISSUE THREAD

**Issue by chrismcv** [ServiceStack/Issues#591]
I've created a dialog to edit an object, and save it back.

I've created a generic typescript store to manage my loading and saving. Basic flow is 
1) `this.data = await client.get(new ProductRequest(), {Id: 1});`
2) do stuff
3) `client.post(this.data);`
4) 3 will error as url is `json/reply/Object`

My issue is that when I get the response back from the client and send it back up in step 3, the type of `this.data` is `Object` rather than `ProductDto`. I think this is because `x` isn't being used at https://github.com/ServiceStack/servicestack-client/blob/master/src/index.js#L679. Could the call back be changed to `{Object.assign(x,o); return x}` or something similar?

Thanks,
Chris

**Comment by mythz** [comment]
Please provide the C# class and generated TypeScript for `ProductRequest`.

**Comment by chrismcv** [comment]
My example wasn't 100%... its actually called `GetProducts` and uses a `Guid`

```
  public class GetProducts : IReturn<ResponseBase<ProductDto>>
    {
        public Guid? Id { get; set; }
    }
```
```
public class ResponseBase<T>
    {
        public ResponseStatus ResponseStatus { get; set; }
        public T Result { get; set; }
        public IEnumerable<T> Results { get; set; }
        public int? Total { get; set; }
    }
```
```
public class ProductDto : IReturn<ResponseBase<ProductDto>>
    {
     
        public Guid Id { get; set; }
        //  more...
    }
```
```
// @Route("/settings/products", "GET")
// @Route("/settings/products/{Id}", "GET")
export class GetProducts implements IReturn<ResponseBase<ProductDto>>
{
    id: string;
    createResponse() { return new ResponseBase<ProductDto>(); }
    getTypeName() { return "GetProducts"; }
}
```

```
export class ResponseBase<T>
{
    responseStatus: ResponseStatus;
    result: T;
    results: T[];
    total: number;
}
```

```
// @Route("/settings/products", "POST")
// @Route("/settings/products/{Id}", "PUT")
export class ProductDto implements IReturn<ResponseBase<ProductDto>>
{
    id: string;
   // more...
}
```

**Comment by mythz** [comment]
So is the issue then calling:

```ts
this.data = await client.get(new GetProducts(), {Id: 1});
```

With this DTO?

```csharp
// @Route("/settings/products", "GET")
// @Route("/settings/products/{Id}", "GET")
export class GetProducts implements IReturn<ResponseBase<ProductDto>>
{
    id: string;
    createResponse() { return new ResponseBase<ProductDto>(); }
    getTypeName() { return "GetProducts"; }
}
```

**Comment by mythz** [comment]
There is no issues with [generating the URL with GetProducts](https://github.com/ServiceStack/servicestack-client/commit/c7bab4f21f607fb1b9c62ebff200c80b49f6fe26). 

Your issue is that you can't resend the Response as a Request DTO because it's only returned as an anonymous JSON object not a Typed Request DTO. You can only send a Typed Request DTO using the `JsonServiceClient`.

**Comment by chrismcv** [comment]
> Your issue is that you can't resend the Response as a Request DTO because it's only returned as an anonymous JSON object not a Typed Request DTO.

Could you explain why? I can see that it doesn't, but that behaviour seems incorrect to me.

There seems to be enough type information to instantiate a Typed ResponseDTO, and it's inconvenient that I now need to introduce an extra step in my code to convert to a Typed object that I can send back up. What's worse is that in VS Code with Intellisense, it looks like it is typed, which is highly confusing...

```
  @bind
  async initialise(args: any): Promise<ProductDto> {
    const res = await this.client.get(new GetProducts(), { id: args.id });
    return Promise.resolve(res.results[0]);
  }
```
This is my code, it I change it to `return Promise.resolve(new OtherDto());` it will fail, which gives the impression I'm dealing with a typed object.

**Comment by mythz** [comment]
There is no "deserialization step" in TypeScript, it returns the JSON object as returned by the server which matches the schema of the generated types. The Types are only for Type Safety to ensure you're binding to the DTO contract in your App logic, which is weird because you're avoiding this benefit when you use an anonymous Type instead of populating the Typed contract, e.g:

```ts
const request = new GetProducts();
request.id = args.id;
const res = await this.client.get(request);
```

There's no "Type information" at runtime required for reflection which you might expect from C# but doesn't exist in JavaScript. All traces are erased when TypeScript compiles to JS, so for instance your `ResponseBase` class looks like this at runtime (unminified):

```js
var ResponseBase = /** @class */ (function () {
    function ResponseBase() {
    }
    return ResponseBase;
}());
```

**Comment by chrismcv** [comment]
The type information was around this line... (in the `createReponse` method)
```
var x = request && typeof request != "string" && typeof request.createResponse == 'function'
            ? request.createResponse()
            : null;
```
which is a couple of lines before it then deserialises to JSON.

> which is weird because you're avoiding this benefit when you use an anonymous Type instead of populating the Typed contract, 

I don't understand what you mean here? `this.data` is defined on my form store, so I thought that would 
```
abstract class FormStore<T extends IReturn<ResponseBase<T>>> {
  isSubmitted: any;
  @observable isSaving: boolean = false;
  @observable data: T = {} as T;
  @observable validationResults: { [key: string]: string[] } = {};
  abstract async initialise(args: any): Promise<T>;
  abstract async onSave(data: T);

  // more
}
```

**Comment by mythz** [comment]
The TypeScript class definition is not available at runtime. The JSON object returned by the server is just that an JSON object and there's no reflection metadata you can query at runtime to discover the type definition of the class you want to deserialize into. 

So you cannot resend a response JSON object you get from the server, you need to use it to populate a new Request DTO instance and send that instead.
