### ISSUE TITLE
Servicemodel with int-members and leading zeroes in request

### ISSUE THREAD

**Issue by haraldv** [ServiceStack/Issues#593]
We have encountered a problem with newer versions of ServiceStack. We upgraded from 4.5.8 to 5.0.0, so I'm not certain when it was introduced.

The example provided is just a small adjustment of a project created the servicestack asp.net empty.

When requesting:
/hello/1 
response yield "Hello, Number 1!"

When requesting:
/hello/01
service "hangs" not yielding any results

We do have a lot of services where we have accepted four digits from request into an servicemodel member with datatype int. Sometimes these numbers have leading zeroes. Using leading zeroes in int-value no longer works in newest version of servicestack. Is there any way we can get the old functionality back, accepting these leading zeroes?

Harald

[LeadingZerosIntParsingRepro.zip](https://github.com/ServiceStack/Issues/files/1579102/LeadingZerosIntParsingRepro.zip)

**Comment by mythz** [comment]
It was removed when we switched to our own StringSegment parsing implementation which adhered to the JSON number format where integers with leading 0's [is not valid JSON](http://www.json.org).

But I've just added support for it back with [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/54d94be112dd253267e7d0e6b67b67e2ff8bc4f9) which is available from v5.0.1 that's now available on MyGet.
