### ISSUE TITLE
ServiceStack.Interfaces.5.0.2 Wrong Version

### ISSUE THREAD

**Issue by sundarchi1** [ServiceStack/Issues#594]
The ServiceStack.Interfaces.5.0.2 NuGet package assembly has the wrong version. The assembly says 5.0.0.0 when it should be 5.0.2.0.

![ssi](https://user-images.githubusercontent.com/31782486/35478657-2a02fae4-03b1-11e8-80ad-a9114d00fb65.png)

The ServiceStack.Text package is correct:

![sst](https://user-images.githubusercontent.com/31782486/35478667-57d939e2-03b1-11e8-899e-dcbff8324698.png)

**Comment by mythz** [comment]
This should now be resolved from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget).

If you had v5.0.3 installed previously you'll need to clear the cache to fetch the latest packages:

    $ nuget locals all -clear

thx for reporting!
