### ISSUE TITLE
RequestLogsFeature Pretty Print

### ISSUE THREAD

**Issue by sundarchi1** [ServiceStack/Issues#598]
When visiting the `RequestLogsFeature`'s `AtRestPath`, the resulting response is not pretty printed when it should be to make it readable in the browser.

Should be an easy fix by using `IndentJson` before returning the response.

**Comment by mythz** [comment]
Any feature requests should be [submitted to UserVoice](http://servicestack.uservoice.com/forums/176786-feature-requests).

Viewing Services in a browser by default returns the [human-friendly HTML5 Report format](http://docs.servicestack.net/html5reportformat), ServiceStack never returns indented JSON.
