### ISSUE TITLE
Custom Validation throwing Argument Exception.

### ISSUE THREAD

**Issue by deipax** [ServiceStack/Issues#601]
We just converted to ServiceStack5 on my team and I am heading up the conversion work from 3.9.71.  During the conversion, our unit tests caught the following exception being thrown by the server due to validation for one of our requests.  

ArgumentException
Cannot create a valid error response with a en empty errorCode and an empty validationError list

To help show the problem, I attached the source for a small service. Restore the nuget packages and then use a browser to attempt to navigate to: http://localhost:53337/Hello?Name=John

[HelloWorld.zip](https://github.com/ServiceStack/Issues/files/1800490/HelloWorld.zip)

**Comment by mythz** [comment]
Custom is a new API that was only recent;y added to FluentValidation. Please see [ValidationCustomTests.cs](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.WebHost.Endpoints.Tests/ValidationCustomTests.cs) for an example of how to use Custom Validation Errors in ServiceStack, e.g:

```csharp
var failure = new ValidationFailure(propertyName, errorMessage) {
    ErrorCode = "NotFound"
};
context.AddFailure(failure);
```
