### ISSUE TITLE
Warning: Stripe version deprecation

### ISSUE THREAD

**Issue by stripe-excelsior** [ServiceStack/Issues#603]
Howdy!

We just wanted to leave a quick note to the maintainers of the ServiceStack Stripe project that we will [soon be turning off access to older versions of the API](https://stripe.com/blog/deprecating-old-api-versions).

This is in line with our [ongoing security infrastructure upgrades](https://stripe.com/blog/completing-tls-upgrade).

It appears you are using API version 2015-10-16. Please see our [upgrade guide](https://stripe.com/docs/upgrades) to upgrade your project.

You should upgrade to a version later than 2017-01-27, but the latest one is recommended.

**Comment by mythz** [comment]
I have updated [ServiceStack.Stripe](https://github.com/ServiceStack/Stripe) to use the latest version of Stripe API which is available from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget).

The link provided is broken: https://stripe.com/blog/deprecating-old-api-versions

Do you have an updated link which shows the timeline of when the existing APIs will stop working?
