### ISSUE TITLE
ServiceStack.Api.Swagger.Core

### ISSUE THREAD

**Issue by seertenedos** [ServiceStack/Issues#604]
At work we are in the process of making all our apps run on both 4.6.1 and dotnet core. The first step in doing this was to upgrade all our shared libraries and their servicestack references. We needed to change all our servicestack to the ".Core" versions as we got errors with servicestack in our 4.6.1 app when they reference on of our netstandard2.0 libs that also reference service stack.

The issue is that ServiceStack.Api.Swagger.Core says it is depricated and to use ServiceStack.Api.Swagger but ServiceStack.Api.Swagger reference dotent 4.5 which will cause our Dll reference issue.  Is there a chance you could update the ServiceStack.Api.Swagger.Core version as well like you do with the other .Core versions for netstandard? I worked this out based on http://docs.servicestack.net/releases/v5.0.0#v502-update  (Run ASP.NET Core Apps on the .NET Framework)

The error i get if everything else is the .Core version and the swagger on is the only one that is not .Core on a 4.6.1 app referencing other netstandard2.0 libs that use servicestack as well.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'Service' exists in both 'ServiceStack, Version=5.0.0.0, Culture=neutral, PublicKeyToken=null' and 'ServiceStack, Version=5.0.0.0, Culture=neutral, PublicKeyToken=02c12cbda47e6587'	UAuthService	D:\Git\uauth---unity-authentication-service\UAuthService\Api\AccessControlService.cs	22	Active
```

**Comment by mythz** [comment]
Hi, please switch to [Open API](http://docs.servicestack.net/openapi) which implements the newer v2.0 of Swagger/Open API. Swagger Feature implements the older v1.2 and is in maintenance mode. Both embeds a version of `/swagger-ui` for its UI.

There is a .NET Standard 2.0 `.Core` version of [ServiceStack.Api.OpenApi.Core](https://www.nuget.org/packages/ServiceStack.Api.OpenApi.Core) available

    PM> Install-Package ServiceStack.Api.OpenApi.Core
