### ISSUE TITLE
Incomplete/errant generated metadata pages - custom batched request implementations

### ISSUE THREAD

**Issue by bzier** [ServiceStack/Issues#605]
When using custom batched request implementations (per the docs [here](http://docs.servicestack.net/auto-batched-requests#custom-batched-requests-implementations)), the metadata page now includes a new separate line item for the array request. However, the metadata pages for this batch request do not include the request/response details (e.g. parameters). Additionally, the JSV page encounters an error due to the lack of a parameterless constructor.

Repro in [this repository](https://github.com/bzier/ServiceStackCustomBatchedRequestsMetadata).

Images showing the issue (also included in the repository):

### New line item for array request:
![toplevelmetadata](https://github.com/bzier/ServiceStackCustomBatchedRequestsMetadata/raw/master/TopLevelMetadata.png "Top-Level Metadata")

### Good metadata on the 'normal' request:
![goodmetadata](https://github.com/bzier/ServiceStackCustomBatchedRequestsMetadata/raw/master/GoodMetadata.png "Good Metadata")

### Missing metadata on the custom batched request:
![missingmetadata](https://github.com/bzier/ServiceStackCustomBatchedRequestsMetadata/raw/master/MissingMetadata.png "Missing Metadata")

### JSV metadata error:
![jsvmetadataerror](https://github.com/bzier/ServiceStackCustomBatchedRequestsMetadata/raw/master/JsvMetadataError.png "JSV Metadata Error")

**Comment by mythz** [comment]
They're not normal Services that should not be displayed in metadata pages so I've ignored them in [this commit](https://github.com/ServiceStack/ServiceStack/commit/619f6825430752995d00407acbc352265a78270f).

This change is available from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget).

**Comment by bzier** [comment]
Thanks @mythz. I can confirm that the latest package from MyGet resolved the issue by hiding those entries. Thanks again for the quick turnaround.
