### ISSUE TITLE
Different behavior between SQL Server 2016 and SQL Server 2008 R2

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#606]
Hi,

# Symptoms
My code runs fine on SQL Server 2016 (dev) but throws `SqlException` with message `'CONCAT' n'est pas une option nom de fonction intégrée reconnue. Syntaxe incorrecte vers 'Clients'. Syntaxe incorrecte vers 'Clients'.` in SQL Server 2008 R2.

# Explanation
I am using ServiceStack.OrmLite on a database hosted on SQL Server 2016 (dev env) and same code is applied to SQL Server 2008 R2 (prod env).
I know `CONCAT` function is not supported on SQL Server 2008 R2, and I would like to know if it is possible to force something like `SqlServer2008Dialect.Provider`, so the generated function will not be using `CONCAT`.
In consequence I am using something like that `var dbFactory = new OrmLiteConnectionFactory(ConfigurationManager.ConnectionStrings["mydatabase"].ConnectionString, SqlServerDialect.Provider)`.
My version of `ServiceStack` is `4.5.14`.

Thank you.

**Comment by mythz** [comment]
Please provide stand-alone repro, either in code fragment or project on GitHub.

**Comment by mythz** [comment]
Which generated function are you referring to? Please provide a stand-alone code example.

**Comment by labilbe** [comment]
The line `Address = Sql.As(q.DocumentSendingModeId == DocumentSendingMode.SnailMail ? (r.ThirdPartyId ?? "") == "" ? p.Address + "\r\n" + p.PostalCode + " " + p.City + "\r\n" + p.CountryId : r.Address + "\r\n" + r.PostalCode + " " + r.City + "\r\n" + r.CountryId : "", nameof(CustomerEskerExport.Address)),` is generating SQL code with CONCAT function, even on SQL Server 2008 R2.

**Comment by labilbe** [comment]
@mythz , is is ok for you or you need something shorter?

**Comment by mythz** [comment]
I've added support for the new `SqlServer2008Dialect.Provider` with a custom `SqlConcat()` in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/169807a81c0eeaf97bffdc95510788354ee0f3cc) and an x-xplat `Sql.Cast(field, Sql.VARCHAR)` in [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/b6ec56b5bceb8203de6b2bd6122d5393d6a29d62).

Note: SQL Server 2008's `+` operator is more fragile than the `CONCAT` operator and will require casting non-char columns you want to concatenate. 

This change is available from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget).

**Comment by labilbe** [comment]
Wow! Thank you very much!
