### ISSUE TITLE
RequestStream and Verbs POST/GET

### ISSUE THREAD

**Issue by sirasmu** [ServiceStack/Issues#614]
This gives an error:
```csharp
[Route("/api/fileupload", Verbs = "POST", Summary = @"Uploads a file.")]
public class FileUploadRequest : IRequiresRequestStream, IReturn<SimpleResponse>
```

While this doesn't:
```csharp
[Route("/api/fileupload", Verbs = "POST, GET", Summary = @"Uploads a file.")]
public class FileUploadRequest : IRequiresRequestStream, IReturn<SimpleResponse>
```
```csharp
[Route("/api/fileupload", Summary = @"Uploads a file.")]
public class FileUploadRequest : IRequiresRequestStream, IReturn<SimpleResponse>
```
The error occurs when using JsonServiceClient with PostBodyAsync, but not when using a HttpWebRequest client.

I am only using POST and GET is not needed and also gives an error if called. IReturn<SimpleResponse> is not needed, but I got another error when trying to POST with PostBodyAsync if it is not included.

**Comment by mythz** [comment]
Please provide the full Exception StackTrace, the server implementation and the client source code which causes the error.

**Comment by sirasmu** [comment]
Sorry, I can't / may not provide you with the code. >Maybe< I can get you the Exception StackTrace by the end of today.

**Comment by mythz** [comment]
The [issue needs to be reproducible](https://github.com/ServiceStack/Issues/blob/master/README.md) with the info provided, if not I won’t be able to identify it’s an actual issue with the library (and not your code) or be able to resolve it.
