### ISSUE TITLE
Bugfix Automatic Enum support with Npgsql 4.0 and newer

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#618]
We have tested running ServiceStack.OrmLite 5.1.0 with Npgsql 4.0.0 and then the automatic Enum support appears broken - failing with a `System.InvalidCastException` and the error message `Can't write CLR type NameOfEnum with handler type TextHandler`.
There are several breaking changes in Npgsql 4 [1] amongst them a change in how enums are handled, allowing both mapping from a C# enum to a Postgresql enum, and another way [2] of handling enums dynamically. While I would love to see a `PgEnum` attribute that supports this, I think it is critical to bugfix the automatic support of storing enum as a `varchar` `text`- hence this support issue.

I'm assuming you'll reproduce this issue quickly by simply upgrading to Npgsql 4.0.0.

[1] http://www.npgsql.org/doc/release-notes/4.0.html#breaking-changes-from-32
[2] http://www.npgsql.org/doc/types/enums_and_composites.html

**Comment by mythz** [comment]
FYI Npgsql v4 is a lot more stricter and broke a lot of tests, not sure how long it will take to resolve.

**Comment by mythz** [comment]
Npgsql v4 should now be supported from [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/ded7d9bfe03ac502938fe2b97482b45fd4263b25). If you find any other issues please include a repro of the source code with the issue.

This change is available from v5.1.1 that's now [available on MyGet](http://docs.servicestack.net/myget).

**Comment by jhf** [comment]
I didn't include a repro in this ticket, as I expected it to be covered by the existing test suite by just upgrading Npgsql, but I'll certainly include a repro if I find anything else!
As always, thank you for the quick fix!
