### ISSUE TITLE
Culture Invariant formatting of DateTimeOffset in OrmLite.

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#619]
In the `PostgreSqlDateTimeOffsetConverter` there is a conversion to an iso timestamp string that is affected by the Culture of the machine it is running on, and that leads to an invalid timestamp synax.

```
        public override string ToQuotedString(Type fieldType, object value)
        {
            var dateValue = (DateTimeOffset) value;
            const string iso8601Format = "yyyy-MM-dd HH:mm:ss.fff zzz";
            return base.DialectProvider.GetQuotedValue(dateValue.ToString(iso8601Format), typeof (string));
        }
```

It turns out that with the Norwegian locale, the `:` is converted to `.`, and the fix is to use `InvariantCulture`. I'm fixing this locally by overriding the `DateTimeOffset` converter, but I really think that shouldn't be required.
```
var now = DateTimeOffset.Now;
// "15.06.2018 19.52.40 +02:00"
now.ToString("yyyy-MM-dd HH:mm:ss.fff zzz")
// "2018-06-15 19.52.40.587 +02:00"
Thread.CurrentThread.CurrentCulture
// "nb-NO"
```
And this is fixed with
```
now.ToString("yyyy-MM-dd HH:mm:ss.fff zzz",System.Globalization.CultureInfo.InvariantCulture)
// "2018-06-15 19:52:40.587 +02:00"
```

**Comment by mythz** [comment]
This should be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/2587a7a9a0a5c4c81b015001d373a17afb3f31f8).

This change is available from v5.1.1 that's now [available on MyGet](http://docs.servicestack.net/myget).
