### ISSUE TITLE
ServiceStack.Api.OpenApi.Core 5.1.1 broken

### ISSUE THREAD

**Issue by seertenedos** [ServiceStack/Issues#620]
Hi,
When we upgraded from 5.0.2 to 5.1.1 we noticed that OpenApi is now broken with the error below.
![image](https://user-images.githubusercontent.com/401009/41520163-a8eb9dd4-730f-11e8-9b10-9eb0f98e1a8e.png)

As you can see all embedded resources are only exactly 59 B which is really no/empty content.
![image](https://user-images.githubusercontent.com/401009/41520177-c57e2700-730f-11e8-8205-e49f67c3fab0.png)

example response
![image](https://user-images.githubusercontent.com/401009/41520250-11cf2cc6-7310-11e8-92ad-a97f372f1458.png)

Dropping everything back to 5.0.2 fixes the issue and we are not overriding any of the swagger files.

**Comment by seertenedos** [comment]
Can you try with dotnet 4.6.1? We can try clearing cache but unlikely as it is on 3 seperate computers including out build server. I may see if I can get the guys to build a dotnet core 2.0 exe to see if that makes a difference. We want to get there but not quite there yet for this application.

**Comment by mythz** [comment]
Are you running [ASP.NET Core on the .NET Framework](http://docs.servicestack.net/templates-corefx)? Because that requires .NET v4.7 and is the only reason for referencing **ServiceStack.Api.OpenApi.Core** NuGet package. If you're on classic ASP.NET Framework you would reference the **ServiceStack.Api.OpenApi** NuGet package instead.

**Comment by seertenedos** [comment]
We are using servicesstack selfhost for rest services. We are using netstandard 2.0 libraries and packages and we build many shared packages on our side between our apps. We are moving to dotnet core 2 or 2.1 but our apps are still running in 4.6.1 which fully supports netstandard 2.0 and this was working fine with servicesstack 5.0.2.

If we reference the other non .core version you end up with a heap of issues as netstandard 2.0 in the other packages references a different DLL than 4.6.1 in those packages causing the system to not build when referencing netstandard 2 packages that then reference servicesstack. Referencing the core version is a easy fix that works every where.

**Comment by mythz** [comment]
All ASP.NET Core Apps are self-hosting Console Apps, so you're just running an [ASP.NET Core App on the .NET Framework](http://docs.servicestack.net/templates-corefx) which requires referencing the `.Core` NuGet packages. The page also includes .NET Framework v4.7 templates pre-configured with the correct dependencies for running on the .NET Framework.

There's nothing wrong with the Swagger templates. I've retested them again by creating a new [web-corefx](https://github.com/NetFrameworkCoreTemplates/web-corefx) and changing all the target frameworks to `net461`, then added the ServiceStack.Api.OpenApi.Core dependency:

```xml
    <PackageReference Include="ServiceStack.Api.OpenApi.Core" Version="5.*" />
```

And enabled it by registering the plugin in Startup.cs:

```csharp
Plugins.Add(new OpenApiFeature());
```

Which works as expected. I've uploaded a working [ASP.NET Core v4.6.1 App with OpenApi in this repo](https://github.com/mythz/SwaggerTest).

You may have another issue, but nothing is wrong with the Open API packages on MyGet.

If you want me to be able to identify the issue I'll need a [stand-alone repro I can run locally to reproduce the issue](https://github.com/ServiceStack/Issues#servicestack-issues). If preferred you can send a pull-request to my SwaggerTest repo that shows the issue.
