### ISSUE TITLE
Possibly a problem with ExecuteSql parameter expansion for PostgreSQL

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#622]
Hi!
I'm having trouble running a very simple `ExecuteSQL` update query using OrmLite, to the point where I'm unsure if this could be a bug, but I fail to see how the example is incorrect.
I'm doing a simple
```
Db.ExecuteSql("UPDATE my_entity SET at = now() WHERE id = ANY (@ids)", new {ids = new int[] { }});
```
and it fails with an exception
```
Npgsql.PostgresException: '42703: column "ids" does not exist'
```
But as far as I can tell by the docs [1], that should be a supported syntax for parameter expanions in sql, and yet it appears that the string is sent diretly to PostgreSQL - who doesn't find the `ids` column.

One of the surprising things is that PostgreSQL apparently ignores the `@` in `@ids` and just tries to find the `ids` column - but that is how PostgreSQL (9.5 at least) behaves.
I have verified with `psql` and the query `UPDATE my_entity SET at = now() WHERE id = ANY (@ids)` gives the same error message there.
```
test=> UPDATE my_entity SET at = now() WHERE id = ANY (@ids);
ERROR:  column "ids" does not exist
LINE 1: UPDATE my_entity SET at = now() WHERE id = ANY (@ids);
                                                         ^
HINT:  Perhaps you meant to reference the column "my_entity.id".
```

I would have expected the generated SQL to be:
```
test=> UPDATE my_entity SET at = now() WHERE id = ANY (ARRAY[]::integer[]);
UPDATE 0
```
and yes, in the actual code I have an array, but the error doesn't depend on that.

I've made a .Net Core selfhosted reproduction of the issue [2]
You'll need to add an `appsettings.txt` with
```
DatabaseConnectionString Server=localhost;Port=5433;Database=test;User Id=test;Password=ASecretPassword;CommandTimeout=20;
```
and of course make that database and user in PostreSQL first.

[1] https://github.com/ServiceStack/ServiceStack.OrmLite#custom-insert-and-updates
[2] https://github.com/veridit/OrmLitePostgresExecuteSqlParameter

**Comment by mythz** [comment]
RDBMS's don't support array parameters natively, OrmLite needs to rewrite the SQL and split the parameter into multiple DB parameters, e.g. 

```csharp
Db.ExecuteSql("UPDATE my_entity SET at = now() WHERE id IN (@ids)", new {ids = new [] {1,2,3 }})
```

Which gets rewritten to:

```csharp
Db.ExecuteSql("UPDATE my_entity SET at = now() WHERE id IN (@v0,@v1,@v2)", 
    new { v0=1, v1=2, v2=3}})
```

The existing version of OrmLite [only worked with Select statements](https://github.com/ServiceStack/ServiceStack.OrmLite#parametrized-in-values) but the latest version on [v5.1.1 on MyGet](http://docs.servicestack.net/myget) now also rewrites `ExecuteSql()` statements.

Note: this feature does a strict rewrite into multiple individual DB params, it doesn't do array casting or infer the query is for native PostgreSQL features as you've assumed. 

The [Custom AutoQuery solution in TechStacks](https://github.com/NetCoreApps/TechStacks#extensible-autoquery-services) shows an alternative solution where you can use `SqlInValues()` to generate a list of escaped string values or generate a comma-delimited list for integer values.

```csharp
if (states.Length > 0)
{
    var labelSlugs = states.Where(x => x != "closed" && x != "open")
        .Map(x => x.GenerateSlug());
    if (labelSlugs.Count > 0)
        q.And($"ARRAY[{new SqlInValues(labelSlugs).ToSqlInString()}] && labels");
}

if (!request.AnyTechnologyIds.IsEmpty())
{
    var techIds = request.AnyTechnologyIds.Join(",");
    var orgIds = request.AnyTechnologyIds.Map(id => GetOrganizationByTechnologyId(Db, id))
        .Where(x => x != null)
        .Select(x => x.Id)
        .Join(",");
    if (string.IsNullOrEmpty(orgIds))
        orgIds = "NULL";

    q.And($"(ARRAY[{techIds}] && technology_ids OR organization_id in ({orgIds}))");
}
```

**Comment by jhf** [comment]
`SqlInValues` and `ToSqlInString` does the job neatly.

I would have expected `ExecuteSql` to be affected by `PostgreSqlDialect.Provider` - and hence work consistently in the same way as `Select`.

And in the latest v5.1.1 there is at least an expansion, so I get the syntax error from PostgreSQL for the generated sql `UPDATE my_entity SET at = now() WHERE id = ANY ($1,$2)`, instead of just passing in the sql `UPDATE my_entity SET at = now() WHERE id = ANY (@ids)` where it just appears that parameter expansion is broken.

Thank you for the quick response.
