### ISSUE TITLE
FromJson<JsonObject>

### ISSUE THREAD

**Issue by hgp7369** [ServiceStack/Issues#623]
`var json = "{\"Name\":\"\"}";
 var obj = json.FromJson<JsonObject>();
 var name = obj .Get("Name");
`
this name is  "​"   "? has \u200b?

**Comment by mythz** [comment]
Should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/b6ff9fef168874353c6d57a15b9cfa84e0e98a35). 

This change is available from v5.1.1 that's now [available on MyGet](http://docs.servicestack.net/myget).

thx for reporting!

**Comment by hgp7369** [comment]
`public static T ParseInheritedJsonObject<T>(ReadOnlySpan<char> value) `
do not need to modify  `var mapValue = elementValue.ToString();` to `var mapValue = elementValue.Value();`?

**Comment by mythz** [comment]
Yep, changed in [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/1dac9392437c78259563a650c39ece968c3f5c9e), which is also available in v5.1.1.
