### ISSUE TITLE
ServiceStack.Api.OpenApi uses wrong nested type to render specification.

### ISSUE THREAD

**Issue by pirovorster** [ServiceStack/Issues#626]
Using:
ServiceStack: 5.1
ServiceStack.Api.OpenApi: 5.1

I have 2 Service Stack Post definitions.

```
public sealed class AddProgramCommand : IReturn<AddProgramResponse>, IPost
	{
		[ApiMember(ParameterType = "body")]
		public ProgramDto Program { get; set; }

		public class ProgramDto 
		{
			public string Description { get; set; }
			...
		}
	}

```
```
public sealed class UpdateProgramCommand : IReturn<UpdateProgramResponse>, IPost
	{
		[ApiMember(ParameterType = "body")]
		public ProgramDto Program { get; set; }

		public class ProgramDto 
		{
			public int Id {get;set;}
			public string Description { get; set; }
			...
		}
	}
```
On the OpenApi documentation the UpdateProgramCommand uses the definition of AddProgramCommand.ProgramDto to render the specification:

![image](https://user-images.githubusercontent.com/6638988/43391992-9c554850-93f2-11e8-8bd8-fab7163f11d1.png)

As soon as I rename UpdateProgramCommand.ProgramDto to UpdateProgramCommand.ProgramXDto it shows the correct definition.

**Comment by mythz** [comment]
Each DTO needs to be uniquely named including inner classes and you should avoid using inner classes In order for your Services to be accessible across all languages.
