### ISSUE TITLE
OpenAPI feature does not conform to the specification

### ISSUE THREAD

**Issue by MortenChristiansen** [ServiceStack/Issues#627]
We are using the `OpenApiFeature` plugin and are customizing it to respect the different .NET data annotation attributes such as `[Range(1,2)]` as described [here](https://forums.servicestack.net/t/maxlength-property/4697/2). The problem is that the properties `MinLength`, `MaxLength`, `Minimum` and `Maximum` on `OpenApiDataTypeSchema` are strings. According to the [spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#user-content-parameterMaximum), they are supposed to be integers/numbers and as a result, our generated spec does not validate.

**Comment by mythz** [comment]
I've updated the properties to match the spec in [this commit](https://github.com/ServiceStack/ServiceStack/commit/f0e7b0c9c7ee98ba5cec6aeb14352b0d7e106960).

This change is available from v5.1.1 that's now [available on MyGet](http://docs.servicestack.net/myget).
