### ISSUE TITLE
Lambda Where(x => x.datetime_open.Date == date.Date) is Not Working

### ISSUE THREAD

**Issue by StevenLiSiwei** [ServiceStack/Issues#629]
Hi Author,

I am your customer who purchased servicestack.ormlite (lisiwei_inbox@hotmail.com). 

Basically, I wants to get the minimum id for a particular date, id is a primary key, however I am getting Object reference not set to an instance of an object when I have Where Clause. it is fully working without where. Please help.

`db.Single<int>(db.From<InvoiceEntity>().Where(x=>x.datetime_open.Date == date.Date).Select(x => Sql.Min(x.id)));`

**Comment by StevenLiSiwei** [comment]
I tried both scalar and single, none of them are working.

**Comment by mythz** [comment]
You can't use C# property access on server column types, you'd instead need to use a date range, e.g:

```csharp
db.From<InvoiceEntity>()
  .Where(x => x.datetime_open >= date.Date && x.datetime_open < date.Date.AddDays(1));
```

**Comment by StevenLiSiwei** [comment]
Thank you @mythz for your input
