### ISSUE TITLE
Cannot update ServiceStack.OrmLite.MySql package from 5.1.0 to 5.2.0

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#633]
When updating on latest ServiceStack version 5.2.0 (package source: nuget.org) an error is thrown on Package Manager Console.

I am targeting .NET Framework 4.6.1.

Command:
> PM> Update-Package ServiceStack.OrmLite.MySql

Result:
> ...
> Update-Package : Failed to add reference. The package 'MySql.Data' tried to add a framework reference to 'System.ComponentModel' which was not found in the GAC. This is 
> possibly a bug in the package. Please contact the package owners for assistance.
> At line:1 char:1
> + Update-Package ServiceStack.OrmLite.MySql
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
>  
> Time Elapsed: 00:03:34.4348279

Thank you.

**Comment by mythz** [comment]
The issue is with the underlying `MySql.Data` package which has been upgraded to a major version. 

I'm able to add it to an existing .NET v4.6.1 project without issue. Can you try removing the package and reinstalling it?

**Comment by labilbe** [comment]
I still have the problem.

Maybe this can help.
<pre>
PM> install-Package ServiceStack.OrmLite.MySql


Attempting to gather dependency information for package 'ServiceStack.OrmLite.MySql.5.2.0' with respect to project 'Presentation\Ksm.Gecko.Gui.WebMvc', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 14,93 sec
Attempting to resolve dependencies for package 'ServiceStack.OrmLite.MySql.5.2.0' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'ServiceStack.OrmLite.MySql.5.2.0'
Resolved actions to install package 'ServiceStack.OrmLite.MySql.5.2.0'
Retrieving package 'Google.Protobuf 3.5.1' from 'nuget.org'.
Retrieving package 'ServiceStack.OrmLite.MySql 5.2.0' from 'nuget.org'.
Retrieving package 'MySql.Data 8.0.12' from 'nuget.org'.
Adding package 'Google.Protobuf.3.5.1' to folder 'D:\Projets\gecko\src\packages'
Added package 'Google.Protobuf.3.5.1' to folder 'D:\Projets\gecko\src\packages'
Added package 'Google.Protobuf.3.5.1' to 'packages.config'
Successfully installed 'Google.Protobuf 3.5.1' to Ksm.Gecko.Gui.WebMvc
Adding package 'MySql.Data.8.0.12' to folder 'D:\Projets\gecko\src\packages'
Added package 'MySql.Data.8.0.12' to folder 'D:\Projets\gecko\src\packages'
Install failed. Rolling back...
Package 'MySql.Data.8.0.12 : Google.Protobuf [3.5.1, )' does not exist in project 'Ksm.Gecko.Gui.WebMvc'
Removed package 'Google.Protobuf.3.5.1' from 'packages.config'
Removing package 'MySql.Data.8.0.12 : Google.Protobuf [3.5.1, )' from folder 'D:\Projets\gecko\src\packages'
Removed package 'MySql.Data.8.0.12 : Google.Protobuf [3.5.1, )' from folder 'D:\Projets\gecko\src\packages'
Removing package 'Google.Protobuf.3.5.1' from folder 'D:\Projets\gecko\src\packages'
Removed package 'Google.Protobuf.3.5.1' from folder 'D:\Projets\gecko\src\packages'
Executing nuget actions took 2,07 min
install-Package : Failed to add reference. The package 'MySql.Data' tried to add a framework reference to 'System.ComponentModel' which was not found in the GAC. This is 
possibly a bug in the package. Please contact the package owners for assistance.
At line:1 char:1
+ install-Package ServiceStack.OrmLite.MySql
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 
Time Elapsed: 00:02:20.9034274
PM> 
</pre>

**Comment by mythz** [comment]
It says it's failing to install MySql.Data, can you try installing that package directly first.

**Comment by mythz** [comment]
The only related reported error I can see is in https://bugs.mysql.com/bug.php?id=88838

> Please add "<Reference Include="System.Runtime"/>" in your csproj file

So maybe add `<Reference Include="System.Runtime"/>` and `<Reference Include="System.ComponentModel"/>`  to your .csproj to see if it helps?

**Comment by labilbe** [comment]
Yes, it fixes the problem!
Thank you very much for your help!
