### ISSUE TITLE
Newline handling inconsistent with JsonObject serialization

### ISSUE THREAD

**Issue by crfroehlich** [ServiceStack/Issues#637]
Newlines (any escape characters) are not handled correctly when they are at the top level of any JSON object, but they are handled correctly whenever they are nested.

I have a simple class, like:

```
[Route("/foo/{Id}", "PATCH")]
public class Foo
{
  public string Id {get; set]
  public JsonObject Bar {get; set]
}

public Patch(Foo request)
{
     //update database
}
```

If I make an API call from my JavaScript client in the browser, something like:
```
request.patch('foo/123',{ data: { Bar:

{ text: "with\nline\nbreaks" }
}}).then(response => console.log(response.Bar.text)) //yields "with\\nline\\nbreaks"
```
wheras
```
request.patch('foo/123',{ data: { Bar:

{ a: { text: "with\nline\nbreaks" } }
}}).then(response => console.log(response.Bar.a)) //yields {text: "with↵line↵breaks"}
```

The same is true for property names: first level property names get an extra `\` while everything nested serializes and deserializes just fine.

**Comment by mythz** [comment]
`JsonObject` is a [wrapper around Dictionary<string,string>](https://github.com/ServiceStack/ServiceStack.Text/blob/fa49d786d34b651803998714c0591f72d08a198b/src/ServiceStack.Text/JsonObject.cs#L77) where values are a wrapper around a `string` not a nested object so the value of `Bar["text"]["a"]` is a `{\"text\":\"line\\nbreak\"}` where it only knows to escape it as a string, i.e. it can't double-escape the strings of the serialized nested object it contains.

So you shouldn't use `JsonObject` for serializing nested objects. You should either return a nested typed object or as a generic dictionary collection like `Dictionary<string, Dictionary<string, string>>`.

As [ServiceStack uses a different object serializer](http://docs.servicestack.net/customize-json-responses#accept-arbitrary-javascript-or-json-objects) to handle `object` types you can change your DTOs to `object` if you want to support nested types:

```csharp
[Route("/foo/{Id}", "PATCH")]
public class Foo
{
  public string Id {get; set]
  public object Bar {get; set]
}
```
