### ISSUE TITLE
IndexOutOfRangeException in ServerEventsClient

### ISSUE THREAD

**Issue by magicxor** [ServiceStack/Issues#638]
### Steps to reproduce:

1) Clone and run https://github.com/kljensen/node-sse-example - it produces valid SSE (see [Data-only messages](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#Event_stream_format#Examples))
2) Create and run a simple console app:
```
using System;
using ServiceStack;

namespace SseBug
{
    class Program
    {
        static void Main(string[] args)
        {
            new ServerEventsClient("http://127.0.0.1:8080/")
            {
                OnException = exception => Console.WriteLine($"OnException: {exception.ToString()}"),
                EventStreamPath = "/events",
            }.Start();
            Console.ReadLine();
        }
    }
}
```
3) You will get the following exception on every event:
```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at ServiceStack.ServerEventsClient.ProcessEventMessage(ServerEventMessage e)
   at ServiceStack.ServerEventsClient.<>c__DisplayClass100_0.<ProcessResponse>b__0(Task`1 t)
```

Probably there is a bug in [ServerEventsClient](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Client/ServerEventsClient.cs#L624).
My workaround was to replace
```
e.Json = parts[1];
```
with
```
e.Json = e.Data;
```
I'm not sure it's a good idea, but the problem has gone after this quick fix.

**Comment by mythz** [comment]
ServiceStack's [Server Events](http://docs.servicestack.net/server-events) is only designed to be used with one of the [Server Events client](http://docs.servicestack.net/server-events#server-event-clients). e.g. for JavaScript use either the [TypeScript Server Events Client](http://docs.servicestack.net/typescript-server-events-client) or the [jQuery Events client](http://docs.servicestack.net/javascript-server-events-client).

I've added a short-circuit to handle invalid messages not sent with our Server Events client in [this commit](https://github.com/ServiceStack/ServiceStack/commit/3bd0be764bd8d5cf014952512e4c6a138fdb4a65) but you should be using one of clients.
