### ISSUE TITLE
Inconsistency between SetCookie extension methods.

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#639]
I've just been bitten by an inconsistency between [1] 
```
public static void SetCookie(this IResponse response, string cookieName, string cookieValue, TimeSpan expiresIn)
```
and [2]
```
public static void SetCookie(this IResponse response, string cookieName, string cookieValue, DateTime expiresAt, string path = "/")
```

The former results in a `path=;` that causes the latest Chrome version to throw away the cookie - only when doing CORS requests - 
while the latter results in a `path=/;` that keeps the cookie - for regular page loads and CORS requests.
The mere difference between a `TimeSpan` and a `DateTime` should not lead to drastically different and surprising behaviour between page loads and CORS requests. I strongly feel that the correct solution is to have a
```
public static void SetCookie(this IResponse response, string cookieName, string cookieValue, TimeSpan expiresIn, string path = "/")
```
such that the two calls work consistently. 
Because we looked in the wrong place, since it worked for a regular page load, this caused us quite a bit of debugging.
I incorrectly assumed that the cookie behaviour was the same for regular page loading and CORS, regardless of the path in the cookie, switching to always `path=/;` makes it so.

[1] https://github.com/ServiceStack/ServiceStack/blob/0b84a5a638d4230e6211eba554796980fcdc1f3b/src/ServiceStack/HttpResponseExtensions.cs#L179
[2] https://github.com/ServiceStack/ServiceStack/blob/0b84a5a638d4230e6211eba554796980fcdc1f3b/src/ServiceStack/HttpResponseExtensions.cs#L196

**Comment by mythz** [comment]
Agreed, should be resolved with [this commit](https://github.com/ServiceStack/ServiceStack/commit/9d6ea24a3ee3171657add616480312efb64a0170).
