### ISSUE TITLE
Parsing of empty string as object results in Unicode character 0x200B

### ISSUE THREAD

**Issue by joergrosenkranz** [ServiceStack/Issues#641]
When parsing an empty JSON string into an object variable, the resulting string is not empty, but contains the Unicode character 0x200B.

Repro:
https://gistlyn.com/?gist=5728d98664ecd14159273a3a21b14b49&collection=2cc6b5db6afd3ccb0d0149e55fdb3a6a

**Comment by joergrosenkranz** [comment]
Seems to be related to #623.

**Comment by joergrosenkranz** [comment]
Added pull request https://github.com/ServiceStack/ServiceStack.Text/pull/515

**Comment by mythz** [comment]
A new version with your PR is available from v5.4.1 that's now [available on MyGet](http://docs.servicestack.net/myget).
