### ISSUE TITLE
Handling of I in turkish locale

### ISSUE THREAD

**Issue by joergrosenkranz** [ServiceStack/Issues#642]
The handling of I and i in turkish locale is different to almost all other locales. See for instance this blog entry: https://blogs.msdn.microsoft.com/deeptanshuv/2004/09/04/the-case-of-turkish-turkish-i/

We have found issues when trying do do requests to a request class containing an Id property. They result in error messages like 'Could not find property Id on ...'.

A repro of this behavior of the RestPath class can be found here: https://gistlyn.com/?gist=5203b01ff98747594017b986160035c9&collection=2cc6b5db6afd3ccb0d0149e55fdb3a6a

**Comment by mythz** [comment]
Should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack/commit/185e35f5022e78c56bd0bdf524fbec72cadbf035).

This change is available from v5.4.1 that's now [available on MyGet](http://docs.servicestack.net/myget).
