### ISSUE TITLE
Side-by-Side Versions and Licensing

### ISSUE THREAD

**Issue by remkm01** [ServiceStack/Issues#643]
Environment Information:
Windows 2012 R2
Runtime: .NET Framework 4.6.x

Applications: MS ASP.NET MVC and Web API
ServiceStack: ServiceStack Redis client

We currently have multiple versions of ServiceStack Redis clients used by various ASP.NET applications (all hosted in IIS). The applications are using the appSettings to register the license.    However, we are running into issues running side by side on the same server, in a nested application hierarchy.  Based on the call stack, it looks like the ServiceStack is using the appSettings when constructing LicenseUtils even though in code we specify the LicenseKeyText.

Here is the call stack we are seeing.  This is from an application using 5.1 client, but sees the appSettings license from a 4.5 client.  In the 5.1 client, we specify the license text via code, but it is never gets there because the Static constructor in LicenseUtils is reading the appSettings first.

[LicenseException: This license has expired ... and is not valid for use with this release. Please see servicestack.net or contact team@servicestack.net for more details.]    ServiceStack.LicenseUtils.ValidateLicenseKey(LicenseKey key) +288    ServiceStack.LicenseUtils.RegisterLicense(String licenseKeyText) +550    ServiceStack.Net40PclExport.RegisterLicenseFromConfig() +277
ServiceStack.LicenseUtils..cctor() +155**
--

Is there a way to run side by side?

**Comment by mythz** [comment]
There can only be 1 license key registered per App Domain / .NET process. I'm not clear how the license key registered in 1 App Domain can be affecting the other? Are they running in different App Domains?

By default it will automatically look for the License Key in appSettings:

```xml
<appSettings/>
    <add key="servicestack:license" value="{licenseKeyText}" />
</appSettings>
```

If you didn't want that you could either register the license key in-line:

```csharp
Licensing.RegisterLicense(licenseKeyText);
new AppHost().Init();
```

Or change to use a different key name, i.e.:

```xml
<appSettings/>
    <add key="servicestack_license" value="{licenseKeyText}" />
</appSettings>
```

Then read it from the configuration manually, e.g:

```csharp
Licensing.RegisterLicense(ConfigurationSettings.AppSettings["servicestack_license"]);
new AppHost().Init();
```

**Comment by remkm01** [comment]
That is what I figured…

Here is an example structure:
From IIS
                \ <-- Root
                --\Application A

The root is using the Redis 5.1 client, which the license key is supplied via code. The Redis client at this level is used within an HttpModule.  When accessing the root, everything works as expected.

Application A uses Redis 4.5 client, which the license key is supplied via appSettings.

When Application A is accessed, the HttpModule inherited from the root executes but reads the license key from appSettings defined in the Application A web.config before the code supplies the license key, if that makes sense.

**Comment by mythz** [comment]
Right so the License Key can only be registered **once on Startup** and is applicable across the entire App Domain, so there can only be 1 license key which can't be registered/changed at runtime.

There is no other solution, an App Domain can only have 1 License Key registered, if you need multiple License Keys they'll need to be in different App Domains.
