### ISSUE TITLE
Issue with using ServiceStack.HttpHandlerFactory with IIS and ServiceStack.Core package

### ISSUE THREAD

**Issue by JothibPixPerPix** [ServiceStack/Issues#644]
Greetings,
I have a fairly large visual studio solution I am working on (~100 projects) and have recently been setting up the projects to make nuget packages out of them while migrating the code base to .Net standard from .Net framework. In doing so I changed all the references to the .Core nugets because of compatability issues, referencing [this post](https://stackoverflow.com/questions/49417843/why-am-i-getting-error-the-type-ireturn-is-defined-in-an-assembly-that-is-n/49417944#49417944). What I discovered is that doing this basically breaks the compatibility with the ServiceStack HttpHandlerFactory. It seems there is an override on the System.Web namespace in the ServiceStack main package which breaks the usage of IHttpHandlerFactory as usable handler for IIS.

Here is a .csproj with the settings used to cause the `ServiceStack.HttpHandlerFactory, ServiceStack does not implement IHttpHandlerFactory or IHttpHandler.` error.
[ServiceStackFailingIISHost.zip](https://github.com/ServiceStack/Issues/files/2416316/ServiceStackFailingIISHost.zip)

**Comment by mythz** [comment]
As detailed in the answer the `.Core` packages only contains `.netstandard2.0` builds which is **only** for running [ASP.NET Core Apps on the .NET Framework](http://docs.servicestack.net/templates-corefx).

If you want to run classic ASP.NET Web Applications you **must** use the normal **ServiceStack** NuGet packages. If you need the same projects to support both .NET Framework and .NET Standard / .NET Core dependencies you must multi-target.
