### ISSUE TITLE
Multiple octets being sent for one message

### ISSUE THREAD

**Issue by stevus** [ServiceStack/Issues#646]
using IServerEvents NotifyChannel, I am seeing two events where one is getting both octets sent before it, causing the first message to be incorrectly parsed. Not sure if this something being caused by the ServiceStack library?

```
5e
 5e
id: 87 
data: Projection@Updated {"id":"0c5599ab7a3c42f5b625cf3c141564b8","streamRevision":35}

 id: 88 
data: Projection@Updated {"id":"a5d22a85162a40de8ccc76445e0c796d","streamRevision":35}
```

**Comment by mythz** [comment]
If there’s 2 events I’m assuming you’re calling it twice, please provide a stand-alone repro in order for us to be able to identify it as an issue.
