### ISSUE TITLE
ServiceStackVS extension error adding service reference

### ISSUE THREAD

**Issue by rcadtec** [ServiceStack/Issues#647]
When attempting to 'Add ServiceStack Reference' to a .Net Console App .Net Framework v4.7.1 using the ServiceStackVS extension an error message is returned stating:

"The process cannot access the file 'C:\ConsoleApp1\ServiceReference1.dtos.cs' because it is being used by another process."

The same functionality works fine for .Net core console apps.

ServiceStackVS: v1.0.44
Visual Studio 2017: v15.8.2

**Comment by mythz** [comment]
There is a lock on that file, restart VS to see if it releases the lock.

**Comment by rcadtec** [comment]
I've restarted my machine, setup a brand new project and still receive the same error, a colleague is also receiving the same. (.net core console apps are fine)

The file seems to be created correctly during the process however the ServiceStack references are not added so the project still fails to build.

**Comment by mythz** [comment]
I'll need to investigate/test further, in the mean-time you can use [@servicestack/cli and csharp-ref](http://docs.servicestack.net/add-servicestack-reference#installation) to download and update ServiceStack References from the command-line.

**Comment by mythz** [comment]
I've just added an published an updated [ServiceStackVS v1.0.45 on Visual Studio Market Place](https://marketplace.visualstudio.com/items?itemName=Mythz.ServiceStackVS) where I've been able to create 4 new Console Apps and use Add ServiceStack Reference without seeing this issue so I think it should be resolved with the latest version.
