### ISSUE TITLE
OpenAPI spec merges referenced definition types

### ISSUE THREAD

**Issue by MortenChristiansen** [ServiceStack/Issues#649]
We have a problem where the generated OpenAPI spec merges nested types with the same name. Consider the following two request types. Notice that only one of the `PositionDto.PositionType` fields are nullable.

```csharp
public class ChangeEmployeesPositionCommand : IReturnVoid
{
    public Guid EmployeeId { get; set; }
    public Guid InstitutionId { get; set; }
    public PositionDto Position { get; set; }

    public class PositionDto
    {
        public PositionType PositionType { get; set; }
        public string Title { get; set; }
    }
}

public class HireEmployeeCommand : IReturnVoid
{
    public Guid InstitutionId { get; set; }
    public Guid? DepartmentId { get; set; }
    public Guid EmployeeId { get; set; }
    public PositionDto Position { get; set; }

    public class PositionDto
    {
        public PositionType? PositionType { get; set; }
        public string Title { get; set; }
    }
}

public enum PositionType
{
    PedagogueAssistant,
    Pedagogue,
    Boss,
    Janitor
}

```
Only a single definition gets created for this type. We have some code that checks for non-nullable value types and for example marks them as required, so they would not be the same type in the OpenAPI spec anymore. I need a way to tell ServiceStack to generate separate definitions for the two types - or even better, SS needs to consider modificiations in `ApiDeclarationFilter` to `OpenApiDataTypeSchema` when determining whether types are identical.

The complete set of properties which we modify on `OpenApiDataTypeSchema` are:

* Format
* Enum
* Pattern
* MinLength
* MaxLength
* Maximum
* Minimum
* Required

If any of these are changed, we would need it to to be treated as a different type.

**Comment by mythz** [comment]
Many languages and metadata support features require that each DTO should be uniquely named, we also highly discourage use of inner classes which are not supported in most languages ServiceStack supports where they need to be extracted into the global namespace where duplicate names will also result in conflict. 

You'll need to rename your DTOs so they're not unique and we highly recommend against using inner classes which results in poorer interoperability of your Services.

**Comment by woutervanvliet** [comment]
True on Form data and query strings, but REST api's consuming JSON data should very much be able to receive nested objects.

**Comment by mythz** [comment]
@woutervanvliet Right true for any serialization format (i.e. nested types, not inner classes), I was just referring to HTTP/HTML (e.g. forms) which only knows of URI's, QueryString and FormData Content-Types which extends to HTTP utils like curl/wget which natively support sending QueryString/FormData arguments.

**Comment by woutervanvliet** [comment]
curl can also perfectly fine & natively be used to send JSON data, but that's not really the point.

A bit more on topic, merging types seems pretty much the least desirable behaviour as this almost always will result in unexpected behaviour. I guess unique names for Dto's as a solution could kinda make sense, at least if any other solution is less practical. But there should be some way to enforce this. Throwing an exception instead of merging would make sound alright.

Alternatively, and I have no clue whether this is possible, the entire namespace and class(ses) a type is nested in could be considered when generating a name.

**Comment by mythz** [comment]
curl supports JSON like any other text Content Type but it's not the default, FormData is. 

The [purpose of DTOs](http://docs.servicestack.net/service-complexity-and-dto-roles#the-simple-poco-life) is to define your public Service Contract, the optimal solution is to have your DTOs match the serialization and API as closely as possible. So if your APIs need to support QueryString and FormData requests they should be flat. As mentioned earlier ServiceStack supports nested types but every other client is going to require customization for being able to send complex types. 

Any workaround to support C# language features are a hack with surprising behavior of when, where and how it's supported. Customizations like changing the Type names would require participation from every serializer you want supported, many implementations of which can't be configured to support it.

My previous comment contains the current recommendations i.e. pull the inner classes out into first class DTO so it more correctly models your Service Contract with how metadata services, serializers and external clients sees your Services. Other solutions could include using `[DataContract]` and `[DataMember]` attributes which can change the DTO name in serializers that support it (most do).
