### ISSUE TITLE
Unable to SignIn to forums after renewing licence

### ISSUE THREAD

**Issue by zeko77** [ServiceStack/Issues#650]
I have renewed my licence on September 28, 2018, and currently posses active subscription.
When I try to sign in to forums, i get an error : You can't log in until s 23, 2019. The reason you were suspended: Your ServiceStack subscription has expired. A valid subscription is required to post to this forum.
This might be an overkill to report as an issue, but I could not find any other means to report this.

**Comment by mythz** [comment]
FYI our contact details are listed on https://servicestack.net/pricing#faq

Can you send an email to team@servicestack.net with your Username/Email please.

**Comment by mythz** [comment]
FYI I found your account on Discourse, you should be able to login now.
