### ISSUE TITLE
Masked quotes in strings are not removed when deserializing into object

### ISSUE THREAD

**Issue by joergrosenkranz** [ServiceStack/Issues#651]
When a DTO contains an object field and this field receives an string containing quotes, the masking of the quotes is not removed during deserialization. It works if the receiving property is of type string.

I have attached a repro in [ServiceStackSerialization.zip](https://github.com/ServiceStack/Issues/files/2557069/ServiceStackSerialization.zip)

**Comment by mythz** [comment]
FYI you can resolve this by switching to use the previous impl with:

    SetConfig(new HostConfig { UseJsObject = false });

Still looking into the issue using the latest impl...

**Comment by mythz** [comment]
This should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack/commit/71ebec8a516bbfd61193e7ab25a98acbfbd1c1f7).

This change is available from v5.4.1 that's now [available on MyGet](http://docs.servicestack.net/myget).

**Comment by joergrosenkranz** [comment]
Is the new code in https://github.com/ServiceStack/ServiceStack/blob/71ebec8a516bbfd61193e7ab25a98acbfbd1c1f7/src/ServiceStack.Common/JSON.cs#L43 ever reached? Seems like the return before has to be removed.

**Comment by mythz** [comment]
That was just an error picking lines for the commit, the end version has the final source:

https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Common/JSON.cs#L52
