### ISSUE TITLE
JsonSerializer.SerializeToStream / JsonSerializer.SerializeToString throws "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by danielHalan** [ServiceStack/Issues#656]
Recently we have experienced an exception on certain objects when performing serializing, i.e.
ServiceStack.Text.JsonSerializer.SerializeToStream(obj, output);
or
var str = ServiceStack.Text.JsonSerializer.SerializeToString(obj);

throws following exception,
``
System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.Text.Json.JsonWriter`1.WriteObject(TextWriter writer, Object value)
   at ServiceStack.Text.Common.WriteType`2.WriteProperties(TextWriter writer, Object value)
   at ServiceStack.Text.Common.WriteType`2.WriteLateboundProperties(TextWriter writer, Object value, Type valueType)
   at ServiceStack.Text.Common.WriteType`2.WriteAbstractProperties(TextWriter writer, Object value)
   at ServiceStack.Text.Common.WriteListsOfElements`2.WriteGenericArrayMultiDimension(TextWriter writer, Array array, Int32 rank, Int32[] indices)
   at ServiceStack.Text.Common.WriteListsOfElements`2.WriteGenericArray(TextWriter writer, Array array)
   at ServiceStack.Text.Common.WriteListsOfElements`2.WriteArray(TextWriter writer, Object oArrayValue)
   at ServiceStack.Text.Common.WriteType`2.WriteProperties(TextWriter writer, Object value)
   at ServiceStack.Text.Json.JsonWriter.WriteLateBoundObject(TextWriter writer, Object value)
   at ServiceStack.Text.Common.WriteType`2.WriteProperties(TextWriter writer, Object value)
   at ServiceStack.Text.Common.WriteListsOfElements`2.WriteGenericIList(TextWriter writer, IList`1 list)
   at ServiceStack.Text.Common.WriteListsOfElements`2.WriteList(TextWriter writer, Object oList)
   at ServiceStack.Text.Json.JsonWriter`1.WriteRootObject(TextWriter writer, Object value)
   at ServiceStack.Text.JsonSerializer.SerializeToString[T](T value)
   at ...EventSerializer.Serialize[T](Stream output, T obj) in ...\EventSerializer.cs:line 87 
``

Also to note, is the object can be successfully serialized when using ".ToJsv()" object-extension.

What can be the root cause of this error? and how can one further diagnose the cause.

Version of ServiceStack that is used, v4.0.46.

**Comment by mythz** [comment]
Please provide a stand-alone example I can run to repro the issue and can you confirm that it's still an issue with the latest v5.4.0 release.

**Comment by danielHalan** [comment]
I've now setup a separate Console Application and re-creating the Object by Parsing the "Jsv" produced on the object above, (using .FromJsv<T>()), and then run ServiceStack.Text.JsonSerializer.SerializeToString(obj); on that object. with results in no exception thrown. 

Not sure if there is something lost in the Jsv translation that causes the issue, or if has something to do with the global process-state/configuration.

Any hints on what could a generate a Null-exception inside ServiceStack.Text.Json.JsonWriter`1.WriteObject(TextWriter writer, Object value) ?

**Comment by mythz** [comment]
There's no chance to identify what the issue is without a repro, code that causes the Exception or even the Type you're trying to serialize. Could be anything like trying to serialize a non-serializable type, e.g. a Type with cyclical dependencies which isn't supported. It might already be resolved, can you repro it with the latest release? 

The only thing the Exception says is that it's thrown from within [JsonWriter.WriteObject](https://github.com/ServiceStack/ServiceStack.Text/blob/master/src/ServiceStack.Text/Json/JsonWriter.Generic.cs#L198).

If it helps, the [latest v5.4.1 pre-release packages on MyGet have source-link enabled](https://forums.servicestack.net/t/v5-4-1-now-hosting-source-link-enabled-packages/6728) which lets you easily debug into the framework source code.

**Comment by danielHalan** [comment]
After trial & error testing I've found the Property that causes the crash, whats strange is that this property has not been changed for more then 8 months, and the same code is working in a different environment. 

About the Property that causes the crash. 

It's a Array of an Interface, where a concrete class is being set, i.e.

``
public class MainObject { 
 public IManager[] Managers { get; set; }
}
``

which then contains an array of class...

``
public class Manager : IManager { 
    public Guid UserId { get; set; }
    public bool Active { get; set; }

    public CaseManager() { 
    }

    public CaseManager(Guid userId) {
      UserId = userId;
    }
}
``

Now the crash occurs if there are ANY items in the array, but if one initialized an empty array or Null, then there is no Crash.

Also to note, is that there are other properties that are Interface's in same namespace, with concrete classes in same namespace as "Manager", which there is no issue with.

**Comment by mythz** [comment]
Do you have a repro I can run that fails with the latest version?

**Comment by danielHalan** [comment]
I've re-tested the above using the latest v5.4.1 and then there was no crash, everything worked fine. 
But, with v5.4.1 there is a noticeable performance hit, where in v4.0.46 larger objects would take less then 1 sec to serialize, using 5.4.1 it took ~**33 sec**, also tried 5.4.0 (just in case there was some debug-info in the pre-release)  with same result.

Due haven't been able to reproduce the issue outside the application I'm running, would it be possible to take the discussion in PM, and I could share more complete objects or we could have a share-screen session. you can e-mail me at my handle-name at gmail.

**Comment by mythz** [comment]
If you want to report a perf issue please submit a benchmark that can be run locally which shows the issue.

As this issue can’t be reproduced with the latest version there’s nothing for me to resolve, feel free to reopen if you have a stand-alone repro showing the issue.

**Comment by danielHalan** [comment]
Due need to solve this issue urgently, can not upgrade to latest version (esp. due the performance issue that needs to be investigated further)

Is there any possibility to get any leads on what could be the issue based on the findings above? that is, when removing all items in an array, the object can be serialized. 

Also what global/static settings could there be that could affect serializing, as noted before, this issue is specific to a certain "process". 
Just to prove this point I created a clean Console App with SS v4.0.46. where I setup a exact copy of the Class and Serialize it, without any issues.

**Comment by mythz** [comment]
I'd recommend checking out the [v4.0.46 source code](https://github.com/ServiceStack/ServiceStack.Text/releases/tag/v4.0.46) to help debug the issue.

Here's what [JsonWriter.WriteObject](https://github.com/ServiceStack/ServiceStack.Text/blob/v4.0.46/src/ServiceStack.Text/Json/JsonWriter.Generic.cs#L191) looked like in v4.0.46. 

But I don't have any further insights to add into a random Exception occurring in an unknown environment with a ~3.5 year old library that's no longer reproducible. An [MVCE/repro](https://github.com/ServiceStack/Issues#servicestack-issues) is absolutely needed in order to identify and resolve any issue.

**Comment by danielHalan** [comment]
Thanks for the reference to source code, was able to locate the issue and solve it. 

Root cause was that when JsonSerializer.DeserializeFromStream was called first time, it would initiate the static creation of "JsonWriter.Instance = new JsWriter<JsonTypeSerializer>()", which in turn calls JsConfig() constructor which calls LicenseUtils.Init(), which then uses JsConfig<DateTime>, which creates a Cached DateTime Serializer, but the issue is that when the JsonWriter<DateTime> is setup the JsonWriter.Instance is **null** and therefor it skips to initiate "CacheFn" which later will be NULL next time a object needs to serialize a DateTime. That is, the NULL Reference Exception was thrown when trying to serialize "DateTime"-type. 

The solution is to ensure that JsConfig is initialized (constructor is called) before starting to Serialize, i.e. calling RuntimeHelpers.RunClassConstructor(typeof(JsConfig).TypeHandle) or access any Method/Attribute of JsConfig...
