### ISSUE TITLE
ServiceStack.Common.DictionaryExtensions without namespace

### ISSUE THREAD

**Issue by majood** [ServiceStack/Issues#658]
Hello, 

Is there any good reason why `ServiceStack.Common.DictionaryExtensions` is not namespaced?
We had previously implemented our own `Merge` and by coincidence when updating ServiceStack.Redis, it is now defaulting to the one from DictionaryExtensions because it is not namespaced.

Scary thing is that there is no warning or any way to detect this, other than that the functionality broke.

**Comment by mythz** [comment]
Rationale addressed in https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/31582678-move-all-extension-methods-into-separate-namespace

**Comment by majood** [comment]
Hmm, ok! Thanks!
Are the extensions in global namespace documented somewhere so that we can check if we have any other duplications?
Or, what's the suggested way of finding out where we might have this kind of problem?

**Comment by mythz** [comment]
There's none in the "Global" Namespace, most are in the `ServiceStack` namespace.

You'll be able to find most extensions by looking in the https://github.com/ServiceStack/ServiceStack/ and https://github.com/ServiceStack/ServiceStack.Text repos and clicking `T` 

To bring up GitHub's File Find feature, e.g: https://github.com/ServiceStack/ServiceStack/find/master

They're mostly in classes ending with `Extensions` or `Utils`.

**Comment by majood** [comment]
Hm, maybe there is a bit of misunderstanding.
We don't have a problem with the ones that are in the `ServiceStack` namespace. I see that most extensions are in that namespace.

Except [DictionaryExtensions](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Common/DictionaryExtensions.cs), which is in the global namespace and not in `ServiceStack` namespace. It is that one that is causing us the headache since it is being used without even being referenced in the file, and we were wondering whether there are other extensions not in `ServiceStack` namespace so that we can check for duplications.

So, shouldn't `DictionaryExtensions` also be in `ServiceStack` namespace?

**Comment by mythz** [comment]
Right that was an unintentional oversight, there shouldn't be anything in the global namespace, resolved with [this commit](https://github.com/ServiceStack/ServiceStack/commit/8b08e522a2677fe8b379b65c659ac441cccb0e71).

This change is available from v5.4.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Comment by majood** [comment]
Great, thank you!
By the way, when is the official v5.4.1 release coming?

**Comment by mythz** [comment]
v5.4.1 is already on MyGet, estimating the next v5.5 to be released on NuGet within 1-2 weeks
