### ISSUE TITLE
IndexOutOfRangeException at JsonTypeSerializer WriteEnumMember 

### ISSUE THREAD

**Issue by maggarwal** [ServiceStack/Issues#659]
I am getting IndexOutOfRangeException, See stack trace
{"ResponseStatus":{"ErrorCode":"IndexOutOfRangeException","Message":"Index was outside the bounds of the array.","StackTrace":" at ServiceStack.Text.Json.JsonTypeSerializer.WriteEnumMember(TextWriter writer, Object enumValue)\r\n at ServiceStack.Text.Common.WriteType2.WriteProperties(TextWriter writer, Object instance)\r\n at ServiceStack.Text.Common.WriteListsOfElements2.<>c__DisplayClass1_0.<.cctor>b__0(TextWriter writer, Object obj)\r\n at ServiceStack.Text.Common.WriteListsOfElements2.WriteGenericIList(TextWriter writer, IList1 list)\r\n at ServiceStack.Text.Common.WriteListsOfElements2.WriteIList(TextWriter writer, Object oList)\r\n at ServiceStack.Text.Common.WriteType2.WriteProperties(TextWriter writer, Object instance)\r\n at ServiceStack.Text.Common.WriteType`2.WriteProperties(TextWriter writer, Object instance)\r\n at ServiceStack.Text.JsonSerializer.SerializeToStream(Object value, Type type, Stream stream)\r\n at ServiceStack.Text.JsonSerializer.SerializeToStream[T](T value, Stream stream)\r\n at ServiceStack.Serialization.JsonDataContractSerializer.SerializeToStream[T](T obj, Stream stream)\r\n at ServiceStack.Host.ContentTypes.<>c.<.ctor>b__36_0(IRequest r, Object o, Stream s)\r\n at ServiceStack.Host.ContentTypes.<>c__DisplayClass30_0.b__0(IRequest httpReq, Object dto, Stream stream)\r\n at ServiceStack.HttpResponseExtensionsInternal.d__7.MoveNext()"}}

**Comment by maggarwal** [comment]
[AssemblySet2.zip](https://github.com/ServiceStack/Issues/files/2954291/AssemblySet2.zip)

**Comment by maggarwal** [comment]
Please use license certificate ID as password for the zip file.

1. There is a linqpad query that shows the issue.
2. Data file is data.file, which is binary serialized data which is causing the issue.

**Comment by mythz** [comment]
Closing as this was already addressed in priority support.
