### ISSUE TITLE
Unable to run AspNet Core (Full framework) & Oracle Provider

### ISSUE THREAD

**Issue by davidrevoledo** [ServiceStack/Issues#660]
I'm creating a new AspNet Core application (WebApi  Full framework target) I'm opening a new connection to Oracle and I get the error "Unable to find the requested .Net Framework Data Provider. It may not be installed."

I'm moving an existing application using the same connection (AspNet WebApi2) and here is is working wel..

- Installed Oracle.ManagedDataAccess 

and tried with same configuration in webapi2.

```XML
<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <system.data>
        <DbProviderFactories>
            <remove invariant="Oracle.ManagedDataAccess.Client" />
            <add name="ODP.NET, Managed Driver" invariant="Oracle.ManagedDataAccess.Client" description="Oracle Data Provider for .NET, Managed Driver" type="Oracle.ManagedDataAccess.Client.OracleClientFactory, Oracle.ManagedDataAccess, Version=4.122.18.3, Culture=neutral, PublicKeyToken=89b483f429c47342" />
        </DbProviderFactories>
    </system.data>
</configuration>
```

thanks.

**Comment by mythz** [comment]
Hi,

Oracle is an [unofficial provider that's developed and maintained by the community](https://github.com/ServiceStack/ServiceStack.OrmLite#8-flavours-of-ormlite-is-on-nuget), you can try reaching them by posting in either the Customer Forums https://forums.servicestack.net/ or [StackOverflow](https://stackoverflow.com/questions/ask).
