### ISSUE TITLE
Unable to listen to sqs messages from docker container

### ISSUE THREAD

**Issue by vyommalhotra** [ServiceStack/Issues#661]
I am running a simple dot net core console application created with Service Stack .Net Core Console template. The application simply consumes SQS threads using servicestack mqserver. The application works fine debugging in visual studio, however when I run the application as a docker container, it does not seem to be picking up messages from sqs.  

It looks like the mq worker threads are exiting shortly after the application starts.
This is what I see when running as docker container:

`

> DEBUG: Starting MQ Handler Worker: 6b2fdde3ed5fmq:OnTrackingEmailSentRequest.priorityq...
> 
> DEBUG: Starting MQ Handler Worker: 6b2fdde3ed5fmq:OnTrackingEmailFailedToDeliverRequest.inq...
> 
> DEBUG: Starting MQ Handler Worker: 6b2fdde3ed5fmq:OnTrackingEmailFailedToDeliverRequest.priorityq...
> 
> DEBUG: Started Background Thread: SqsMqServer MQ Server 1
> Loaded '/root/.nuget/fallbackpackages2/microsoft.net.http.headers/2.2.0/lib/netstandard2.0/Microsoft.Net.Http.Headers.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
> Loaded '/root/.nuget/fallbackpackages/system.runtime.compilerservices.unsafe/4.5.1/lib/netcoreapp2.0/System.Runtime.CompilerServices.Unsafe.dll'. Module was built without symbols.
> 
> Hosting environment: Development
> 
> Content root path: /app
> 
> Now listening on: http://[::]:80
> 
> Application started. Press Ctrl+C to shut down.
> 
> The thread 120 has exited with code 0 (0x0).
> 
> The thread 0x78 has exited with code 0 (0x0).
> 
> The thread 128 has exited with code 0 (0x0).
> 
> The thread 0x80 has exited with code 0 (0x0).`

**Comment by mythz** [comment]
You likely have runtime dependency loading issue, please see this existing answer for potential workarounds:

https://stackoverflow.com/a/55329952/85785

**Comment by vyommalhotra** [comment]
I don't see any runtime dependency loading failures in the debug logs. It looks like it should be working as it works when I run the application locally? 
Sorry, I don't see how those existing answers are relevant to my situation. The application is only not operating as expected when spun up with docker.

**Comment by mythz** [comment]
ok I thought I saw a `System.Runtime.CompilerServices.Unsafe` error from your initial/pre-edited post.

Can you try upgrading to the [latest v5.5 release](https://docs.servicestack.net/releases/v5.5) in case it is a runtime assembly loading issues that may be resolved with later dependencies.

Can you get it to work locally with Docker or not at all? Does the website stay up (i.e. can you view /metadata) or is the whole App being shutdown after its run? 

The [debugging docs](https://docs.servicestack.net/debugging) may be able to help, turn on `StrictMode` to throw StartUp Errors:

```csharp
SetConfig(new HostConfig {
    StrictMode = true
})
```

Or see if there are any [Startup Errors in ?debug=requestinfo](https://docs.servicestack.net/debugging#request-info)

**Comment by vyommalhotra** [comment]
I updated to v5.5. The web application stays up and I can access /metadata. I turned on StrictMode and don't see any StartupErrors in ?debug=requestinfo. I tried debugging with docker support in visual studio as well as building and running the docker container through command line. The docker image is for linux so the container runs on MobyLinuxVM in Hyper-V.

**Comment by mythz** [comment]
ok sounds like it's staying up and there are no Startup Errors. 

If you put together a small stand-alone repro (i.e. just 1 test MQ) that I can run locally to repro the issue I can take a look from here.

**Comment by vyommalhotra** [comment]
I just debugged through the mqserver setup once again and realized the issue is in the QueueNames.QueuePrefix. I was using the machine name as the prefix for my testing environment however, the machine name is not the same when spun up in docker. So it is not registered to the right queue. It works now, thank you for the quick replies.

**Comment by mythz** [comment]
ok great, glad to hear you've got it resolved 👍
