### ISSUE TITLE
ServiceStack.OrmLite-Specified method is not supported

### ISSUE THREAD

**Issue by pedoc** [ServiceStack/Issues#662]
ex:
db.GetAllAsync(item->item.someStr.Replace("_","").Length>10)
with thorw `Specified method is not supported` exception,but ef core work fine

**Comment by mythz** [comment]
If you want to report an issue we need a [minimal stand-alone repro we can run](https://github.com/ServiceStack/Issues#servicestack-issues) including full Exception details.

But trying to use an EF feature that's not documented anywhere in OrmLite is a feature request, not an issue.

This Issue Tracker is only for reporting reproducible bugs, please use [UserVoice if you would like to propose a feature request](https://servicestack.uservoice.com/forums/176786-feature-requests).
