### ISSUE TITLE
Licensing question for ServiceStack.Redis

### ISSUE THREAD

**Issue by bobekhj** [ServiceStack/Issues#663]
Hello,

Just purchased a license. I'd like to use the environment variable option to register it on each machine that runs the application. My question is, if I have X amount of servers running the applications with the Nuget package, on different environments, do I need to register the license on the servers that builds (and deploys) the application or on the actual production servers that run the application? So, if for example I have 5 IIS servers in production, 3 IIS servers in test and 2 in development, I need to add the license to environment variable on all 10 servers? And since I am a single developer here, I can reuse the same license for all 10?

Thank you.

**Comment by mythz** [comment]
Hi,

It needs to be added on the same machine where the software is run (more specifically when the [free quotas are exceeded](https://servicestack.net/download#free-quotas)).

It's not needed for builds, unless it's also running CI tests which exceeds the free quotas.

You can reuse the same developer license key in all machines your deploying/running your software.

Hope that helps!
