### ISSUE TITLE
Update-Package error when updating from v5.4.0 to v5.5.0

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#665]
### Environment
Windows 10
.NET Framework 4.6.1
Visual Studio 2015 v14.0.25431.01 Update 3

### Steps to reproduce the behavior
On a ASP.NET MVC with ServiceStack v5.4.0 installed (functionnal), launch `Update-Package ServiceStack` command.

### Result
<pre>
PM> Update-Package ServiceStack

Attempting to gather dependency information for multiple packages with respect to project 'Tests\Ksm.Gecko.Services.Tests', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 10,04 sec
Attempting to resolve dependencies for multiple packages.
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'ServiceStack 5.4.0'
Resolving dependency information took 0 ms
Resolving actions install multiple packages
Retrieving package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from 'nuget.org'.
Retrieving package 'System.Memory 4.5.2' from 'nuget.org'.
Retrieving package 'ServiceStack.Interfaces 5.5.1' from 'ServiceStack MyGet feed'.
Retrieving package 'ServiceStack.Text 5.5.1' from 'ServiceStack MyGet feed'.
Retrieving package 'ServiceStack.Client 5.5.1' from 'ServiceStack MyGet feed'.
Retrieving package 'ServiceStack.Common 5.5.1' from 'ServiceStack MyGet feed'.
Retrieving package 'ServiceStack 5.5.1' from 'ServiceStack MyGet feed'.
  GET https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Interfaces',Version='5.5.1')
  GET https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Common',Version='5.5.1')
  GET https://www.myget.org/F/servicestack/Packages(Id='ServiceStack',Version='5.5.1')
  GET https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Client',Version='5.5.1')
  GET https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Text',Version='5.5.1')
Removed package 'ServiceStack 5.4.0' from 'packages.config'
  OK https://www.myget.org/F/servicestack/Packages(Id='ServiceStack',Version='5.5.1') 783ms
  OK https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Common',Version='5.5.1') 783ms
  OK https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Interfaces',Version='5.5.1') 783ms
  OK https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Client',Version='5.5.1') 783ms
  GET https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Common/5.5.1
  GET https://www.myget.org/F/servicestack/api/v2/package/ServiceStack/5.5.1
  GET https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Client/5.5.1
  GET https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Interfaces/5.5.1
Successfully uninstalled 'ServiceStack 5.4.0' from Ksm.Gecko.Services.Tests
Removed package 'ServiceStack.Common 5.4.0' from 'packages.config'
  OK https://www.myget.org/F/servicestack/api/v2/package/ServiceStack/5.5.1 2151ms
Installing ServiceStack 5.5.1.
  OK https://www.myget.org/F/servicestack/Packages(Id='ServiceStack.Text',Version='5.5.1') 2935ms
  GET https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Text/5.5.1
Successfully uninstalled 'ServiceStack.Common 5.4.0' from Ksm.Gecko.Services.Tests
Removed package 'ServiceStack.Client 5.4.0' from 'packages.config'
Successfully uninstalled 'ServiceStack.Client 5.4.0' from Ksm.Gecko.Services.Tests
Removed package 'ServiceStack.Text 5.4.0' from 'packages.config'
Successfully uninstalled 'ServiceStack.Text 5.4.0' from Ksm.Gecko.Services.Tests
Removed package 'System.Memory 4.5.1' from 'packages.config'
Successfully uninstalled 'System.Memory 4.5.1' from Ksm.Gecko.Services.Tests
Removed package 'System.Runtime.CompilerServices.Unsafe 4.5.0' from 'packages.config'
Successfully uninstalled 'System.Runtime.CompilerServices.Unsafe 4.5.0' from Ksm.Gecko.Services.Tests
Removed package 'ServiceStack.Interfaces 5.4.0' from 'packages.config'
Successfully uninstalled 'ServiceStack.Interfaces 5.4.0' from Ksm.Gecko.Services.Tests
  OK https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Interfaces/5.5.1 3745ms
Installing ServiceStack.Interfaces 5.5.1.
  OK https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Common/5.5.1 3874ms
Installing ServiceStack.Common 5.5.1.
  OK https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Client/5.5.1 8937ms
Installing ServiceStack.Client 5.5.1.
Adding package 'ServiceStack.Interfaces.5.5.1' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Interfaces.5.5.1' to folder 'D:\Projets\gecko\src\packages'
  OK https://www.myget.org/F/servicestack/api/v2/package/ServiceStack.Text/5.5.1 7560ms
Installing ServiceStack.Text 5.5.1.
Added package 'ServiceStack.Interfaces.5.5.1' to 'packages.config'
Successfully installed 'ServiceStack.Interfaces 5.5.1' to Ksm.Gecko.Services.Tests
Adding package 'System.Runtime.CompilerServices.Unsafe.4.5.2' to folder 'D:\Projets\gecko\src\packages'
Added package 'System.Runtime.CompilerServices.Unsafe.4.5.2' to folder 'D:\Projets\gecko\src\packages'
Added package 'System.Runtime.CompilerServices.Unsafe.4.5.2' to 'packages.config'
Successfully installed 'System.Runtime.CompilerServices.Unsafe 4.5.2' to Ksm.Gecko.Services.Tests
Adding package 'System.Memory.4.5.2' to folder 'D:\Projets\gecko\src\packages'
Added package 'System.Memory.4.5.2' to folder 'D:\Projets\gecko\src\packages'
Added package 'System.Memory.4.5.2' to 'packages.config'
Successfully installed 'System.Memory 4.5.2' to Ksm.Gecko.Services.Tests
Adding package 'ServiceStack.Text.5.5.1' to folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Text.5.5.1' to folder 'D:\Projets\gecko\src\packages'
Install failed. Rolling back...
Package 'ServiceStack.Text 5.5.1' does not exist in project 'Ksm.Gecko.Services.Tests'
Removed package 'System.Memory 4.5.2' from 'packages.config'
Removed package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from 'packages.config'
Removed package 'ServiceStack.Interfaces 5.5.1' from 'packages.config'
Package 'ServiceStack.Interfaces 5.4.0' already exists in folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Interfaces 5.4.0' to 'packages.config'
Package 'System.Runtime.CompilerServices.Unsafe 4.5.0' already exists in folder 'D:\Projets\gecko\src\packages'
Added package 'System.Runtime.CompilerServices.Unsafe 4.5.0' to 'packages.config'
Package 'System.Memory 4.5.1' already exists in folder 'D:\Projets\gecko\src\packages'
Added package 'System.Memory 4.5.1' to 'packages.config'
Package 'ServiceStack.Text 5.4.0' already exists in folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Text 5.4.0' to 'packages.config'
Package 'ServiceStack.Client 5.4.0' already exists in folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Client 5.4.0' to 'packages.config'
Package 'ServiceStack.Common 5.4.0' already exists in folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack.Common 5.4.0' to 'packages.config'
Package 'ServiceStack 5.4.0' already exists in folder 'D:\Projets\gecko\src\packages'
Added package 'ServiceStack 5.4.0' to 'packages.config'
Removing package 'ServiceStack.Text 5.5.1' from folder 'D:\Projets\gecko\src\packages'
Removed package 'ServiceStack.Text 5.5.1' from folder 'D:\Projets\gecko\src\packages'
Removing package 'System.Memory 4.5.2' from folder 'D:\Projets\gecko\src\packages'
Removed package 'System.Memory 4.5.2' from folder 'D:\Projets\gecko\src\packages'
Removing package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from folder 'D:\Projets\gecko\src\packages'
Removed package 'System.Runtime.CompilerServices.Unsafe 4.5.2' from folder 'D:\Projets\gecko\src\packages'
Removing package 'ServiceStack.Interfaces 5.5.1' from folder 'D:\Projets\gecko\src\packages'
Removed package 'ServiceStack.Interfaces 5.5.1' from folder 'D:\Projets\gecko\src\packages'
Executing nuget actions took 47,66 sec
Update-Package : Failed to add reference. The package 'ServiceStack.Text' tried to add a framework reference to 'System.Threading' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
  Reference unavailable.
At line:1 char:1
+ Update-Package ServiceStack
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.UpdatePackageCommand
 
Time Elapsed: 00:00:57.8456600
PM> 
</pre>

### Tries

- Execute `nuget.exe locals all -clear`
- Change nuget feed on MyGet

No changes.

**Comment by mythz** [comment]
Sounds like a NuGet issue on upgrade, try uninstalling and reinstalling the packages.

**Comment by labilbe** [comment]
I tried, without success (same error).
After that, I tried to update from Visual Studio 2017 and it worked.
One difference between my VS2015 and my VS2017 is the Package Console Version Package Manager Console Host Version 3.6.0.2511 vs 4.9.3.5777.

**Comment by mythz** [comment]
Can you provide a small stand alone project on GitHub that shows the error please.
