### ISSUE TITLE
AlwaysSendBasicAuthHeader doesn't work as expected

### ISSUE THREAD

**Issue by c0shea** [ServiceStack/Issues#666]
I'm constructing a service client and specifying the `AlwaysSendBasicAuthHeader` property. However, it doesn't work. The client still sends a request without the `Authorization` header as if this option was set to false, which returns HTTP 401, and then the client retries with the `Authorization: Basic xxx` header specified.

```
var api = new JsvServiceClient(Api.UrlDev)
{
    Credentials = new NetworkCredential(Api.KeyTest, ""),
    AlwaysSendBasicAuthHeader = true
};
```

It looks like the problem is in [ServiceClientBase](https://github.com/ServiceStack/ServiceStack/blob/2693bb90bc9221fd4f3442b5ae7aaa86d3a34d88/src/ServiceStack.Client/ServiceClientBase.cs#L909). Since the Credentials property has a value, it breaks out of the else if statement and never makes it to the last condition that checks `AlwaysSendBasicAuthHeader`.

**Comment by mythz** [comment]
It only sends 1 Authentication method and `AlwaysSendBasicAuthHeader` is only used to send the `UserName` and `Password`, not credentials.

You can send an API Key using the `BearerToken` instead:

```csharp
var api = new JsvServiceClient(Api.UrlDev)
{
    BearerToken = Api.KeyTest
};
```
