### ISSUE TITLE
web new does not work if launched from E:\

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#671]
Executing command from `E:\Projects` does not work.
![sshot-1](https://user-images.githubusercontent.com/54315/57144595-a83a0080-6dc1-11e9-9935-5eff3f45a6cc.png)
If I execute same command from `C:\temp` it works.

Windows 7 x64.
I tried to execute the command from conEMU and cmd (as administrator). Same results.
web tool v0.0.24

**Comment by mythz** [comment]
This should be fixed with the latest `v0.0.25` that's now on NuGet. Update with:

    $ dotnet tool update -g web

**Comment by labilbe** [comment]
I tested with `v0.0.25` and it works like a charm! Thank you @mythz .
