### ISSUE TITLE
VS 2015: ServiceStackVS extension latest update broken

### ISSUE THREAD

**Issue by mbouchard1980** [ServiceStack/Issues#673]
The latest update of ServiceStackVS seems to introduce a bug in VS 2015.
The option "Add ServiceStack Reference" is no longer appearing in project context menu.
In addition, the ability to update ServiceStack References is broken too.

Where can I download previous version of ServiceStackVS ?

**Comment by mythz** [comment]
Looks like Visual Studio [doesn't let you access previous versions](https://marketplace.visualstudio.com/items?itemName=Mythz.ServiceStackVS).

We'll look into seeing if we can identify and resolve this issue or see if we can build a previous version, in the meantime you can use Update ServiceStack References using [the .NET Core web tool](https://docs.servicestack.net/web-tool) which you can install with:

    $ dotnet tool install --global web 
 
You can then run [within Visual Studio by using it as an external tool](https://docs.servicestack.net/web-tool#integrate-with-visual-studio).

**Comment by mythz** [comment]
Hi, we've re-built an existing version you can install instead:

 - [ServiceStackVS.vsix](https://github.com/ServiceStack/ServiceStackVS/raw/master/dist/2018/ServiceStackVS.vsix)

You'll also want to disable auto updates:

![image](https://user-images.githubusercontent.com/89361/57964624-05779b00-7906-11e9-930f-a7a7ff1904cc.png)

**Comment by mbouchard1980** [comment]
Thanks it will be very helpful... Bests regards

Le sam. 18 mai 2019 00 h 45, Demis Bellot <notifications@github.com> a
écrit :
