### ISSUE TITLE
Dart Client: Bug in mapping code

### ISSUE THREAD

**Issue by tobiaszuercher** [ServiceStack/Issues#674]
Hi

The mapping from json to response dtos is not working in dart. I stripped the problem from our business app down to a minimal sample providing a backend and describing the call to it using the generated dtos and JsonServiceClient: [https://github.com/tobiaszuercher/dart-ref-repo](https://github.com/tobiaszuercher/dart-ref-repo).

Since we don't have any problems with the same backend and typescript's JsonServiceClient using the same API im considering this as a bug.

**Comment by mythz** [comment]
Thanks for the repro, but Dart has no reflection and requires all types to be known and generated up front, the [limitation and solution is described in the docs](https://docs.servicestack.net/dart-add-servicestack-reference#generating-unknown-types).

The issue in this is you're using open generics to return a `List<FooListDto>` but `List<FooListDto>` does not appear anywhere in your Service Contract so no type converter was generated for it. The solution is to create a DTO with all missing runtime types not used in your Service contract, i.e:

```csharp
public class UnknownTypes
{
    public List<FooListDto> FooListDtos { get; set; } 
}

public class FooService : Service
{
    public object Any(UnknownTypes request) => request;
}
```

Which will generate a type converter for `List<FooListDto>` and resolve this issue.

I've made this issue and solution easier to discover in [this commit](https://github.com/ServiceStack/servicestack-dart/commit/a3c8d6a59a41df80592d039bcd01feea2c4f6f57) where it will throw an error of the missing type and refer you to the docs URL.
