### ISSUE TITLE
AssignRolesService.Post(AssignRoles) not working

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#675]
My code regressed on this call
`using (var arsSvc = HostContext.ResolveService<AssignRolesService>())
    arsSvc.Post(new AssignRoles {Roles = model.RoleNames, UserName = userName});`

I am now using `UserAuthRole` table (distinct table provided with ServiceStack).

ServiceStack v5.4.0
Framework v4.6.1

Error thrown is `Invalid Role`

Thank you.

**Comment by mythz** [comment]
You shouldn't use call the `AssignRoles` Service for this, it's just a [wrapper around AuthRepository APIs](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/Auth/AssignRolesService.cs#L18-L22) which you should use directly instead:

```csharp
var userAuth = AuthRepository.GetUserAuthByUserName(userName);
if (userAuth != null)
{
    AuthRepository.AssignRoles(userAuth, roles:model.RoleNames);
}
```

**Comment by labilbe** [comment]
Thank you very much mythz.

I ended up with:

```cs
    model.UserNames.Select(p => AuthRepository.GetUserAuthByUserName(p)).Where(p => p != null).Each(p =>
    {
        if (model.Assign)
            AuthRepository.AssignRoles(p, model.RoleNames);
        else
            AuthRepository.UnAssignRoles(p, model.RoleNames);
    });`
