### ISSUE TITLE
Unbale to login to forum

### ISSUE THREAD

**Issue by ganeshan** [ServiceStack/Issues#676]
Hi, I renewed my subscription, and registered under "Register Licensed Developers", with my email, and github account. When I try to login, I get error message , saying my account is not activated. Please help.

**Comment by mythz** [comment]
I've re-run the sync scripts, can you try logging in again?

**Comment by mythz** [comment]
It doesn't look like your user account is blocked anymore so you should be able to login, reply back to this thread if you have any issues.
