### ISSUE TITLE
Wrong dto generated when class extends Dictionary

### ISSUE THREAD

**Issue by rcleroux** [ServiceStack/Issues#677]
I have a dto "IdentifierCollection" which is declared like

```
public class IdentifierCollection : Dictionary<Guid, string>{
}
```

If I include it in a request / response such as

```
public class MyQuery : IReturnVoid{
  public IdentifierCollection identifiers {get;set;}
}
```

And then I generate the typescript dtos with

`typescript-ref`

The generated output is like

```
export class IdentifierCollection extends any
{
    public constructor(init?:Partial<IdentifierCollection>) { super(init); (<any>Object).assign(this, init); }
}
```

which is invalid.

I would expect something like this to be generated

```
interface IDictionary<TValue> {
  [key:string] : TValue
}

export class IdentifierCollection implements IDictionary<string>
{
    [key: string]: string;
    public constructor(init?:Partial<IdentifierCollection>) { (<any>Object).assign(this, init); }
}
```

**Comment by mythz** [comment]
TypeScript Native Types returns `any` for extending declaration types it doesn't support like sub classing dictionaries. But I've added support for extending dictionaries where it should now generate:

```ts
export class Dictionary<T> { [Key: string]: T; }

export class IdentifierCollection extends Dictionary<string>
{
    public constructor(init?: Partial<IdentifierCollection>) { super(); (Object as any).assign(this, init); }
}
```

But I'd highly recommend trying to extend intrinsic types like dictionaries which can fail in different languages and serializers. 

This change is available in the [latest v5.5.1 on MyGet](https://docs.servicestack.net/myget).
