### ISSUE TITLE
ServiceStack Azure App Service handler not working

### ISSUE THREAD

**Issue by RodrigoSedano** [ServiceStack/Issues#679]
We are using ServiceStack for our ASP.Net Web Application hosted in Azure using App Services. Our ServiceStack implementation is based on this documentation https://docs.servicestack.net/servicestack-side-by-side-with-another-web-framework.

We have a problem that occasionally happens after the deploy of the Web application to our production environment which one runs using 4 instances. The deployment pipeline deploys the Web application to a staging slot and then it swaps it to the production slot to avoid downtime. We can see that the handler is not responding on some of the instances and the calls to our ServiceStack web service respond with 404 errors (see attached image).

We have contacted Microsoft support but so far it doesn't seem to be a problem with their services. We have also look at the configuration in our Web.Config but everything looks correct there. Every time that we get this problem, we need to restart the web application in order to do the ServiceStack handler work again. 

I would like to get some help to know if there is something wrong with our implementation or if there is know issues about ServiceStack unning on Azure App Service.

Our ServiceStack is licensed to Visma with Premium Support.  

![404 Error](https://user-images.githubusercontent.com/52322252/60345128-95eed400-99b8-11e9-967e-f2bfb194c4ac.PNG)

**Comment by mythz** [comment]
Potentially this could be due to a Startup Exception during your AppHost initialization.

You can [enable StrictMode](https://docs.servicestack.net/debugging#strictmode) to have Startup Exceptions rethrown so they're more visible in ASP.NET error pages, e.g:

```csharp
Env.StrictMode = true;
new AppHost().Init();
```

Closing this issue here as it's currently being handled in a premium support incident.
