### ISSUE TITLE
Bug: SerializeToString

### ISSUE THREAD

**Issue by vzsoft** [ServiceStack/Issues#684]
Hi
Bug in JsonSerializer and TypeSerializer=> 'TimeSapn.MinValue'

Error: System.OverflowException: 'Negating the minimum value of a twos complement number is invalid.'

Sample:
```javascript  
            Class1 c1 = new Class1()
            {
                TimeS = TimeSpan.MinValue,
            };
            var srializdeT = TypeSerializer.SerializeToString(c1, typeof(Class1));
            var srializde = JsonSerializer.SerializeToString(c1, typeof(Class1));
```

**Comment by mythz** [comment]
TypeSerializer (JSV) and JsonSerializer (JSON) are 2 different serialization formats that should never be used together or expected to work.

Note: I don't see your GitHub user account listed as a [support contact](https://servicestack.net/account/support). As you don't have your email published on your GitHub profile please add your GitHub User Account as a registered support contact.

**Comment by mythz** [comment]
Reopening as issue exists when using just JSON

**Comment by vzsoft** [comment]
> TypeSerializer (JSV) and JsonSerializer (JSON) are 2 different serialization formats that should never be used together or expected to work.

i know, 2 serialization error convert 'TimeSapn.MinValue'

**Comment by mythz** [comment]
Resolved in this commit https://github.com/ServiceStack/ServiceStack.Text/commit/112e7d51f8ccdbaba545dec03525e55dba27daa9
