### ISSUE TITLE
Problem: Deserialize DateTimeOffset.MaxValue

### ISSUE THREAD

**Issue by vzsoft** [ServiceStack/Issues#685]
Hi

try  Deserialize model but not Equal DateTimeOffset.MaxValue

Error: 
NUnit.Framework.AssertionException: '  Expected: 9999-12-31 23:59:59.999+00:00
  But was:  9999-12-31 23:59:59.9999999+00:00

```javascript
            Class1 c1 = new Class1()
            {
                DateO = DateTimeOffset.MaxValue
            };
            var srializde = JsonSerializer.SerializeToString(c1, typeof(Class1));
            var deserialized = JsonSerializer.DeserializeFromString<Class1>(srializde);
            Assert.AreEqual(deserialized.DateO, c1.DateO);
```

**Comment by mythz** [comment]
I've hardcoded Min/Max contents which will resolve this text in [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/e0b9860a8a0720ae12f23fe3539eab7710f0447d). But lossy formats like Date's can sometimes lose precision between round trips.
