### ISSUE TITLE
Duplicate key issue in ServiceStack.Redis & ServiceStack.Redis.Core library

### ISSUE THREAD

**Issue by prasantapaul** [ServiceStack/Issues#686]
Hi,

We have purchased the Business Developer (Redis) license and using both _ServiceStack.Redis_ & _ServiceStack.Redis.Core_ library in our different projects.

Recently we countered a duplicate key issue while connecting Google Memorystore Redis through the _ServiceStack.Redis_ & _ServiceStack.Redis.Core_ library. 

The error message is given below:
_An item with the same key has already been added. Key: used_memory_rss_

It seems that Google has introduced a new section in **Info** with the few keys which are same as keys under _Memory_ section (screenshot below).

![image](https://user-images.githubusercontent.com/28052896/64419379-6d6f0e80-d0ba-11e9-9e66-8b849357b52f.png)

From the codebase in Github we found that the keys are beings inserted in a dictionary object (**_RedisNativeClient.cs_**). As there are duplicate keys so the following code block is throwing the above-mentioned error.

```
public Dictionary<string, string> Info
       {
           get
           {
               var lines = SendExpectString(Commands.Info);
               var info = new Dictionary<string, string>();

               foreach (var line in lines
                   .Split(new[] { "\r\n" }, StringSplitOptions.RemoveEmptyEntries))
               {
                   var p = line.IndexOf(':');
                   if (p == -1) continue;


                   info.Add(line.Substring(0, p), line.Substring(p + 1));
               }

               return info;
           }
       }
```

Could you please fix this for both _ServiceStack.Redis_ & _ServiceStack.Redis.Core_ library and release the updated version in **nuget** asap. We are unable to run our applications (which are in production server) without this fix.

Thanks.

**Comment by mythz** [comment]
This should be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/d035c235255c3476f3c8b0a9b44a6201b413fa09). This change is available from v5.6.1+ that's [now on MyGet](https://docs.servicestack.net/myget).

**Comment by prasantapaul** [comment]
Hi Demis,

Thanks for the update. When this issue fix will be available on original
nuget version because my project is referencing that one?

Thanks,
Prasanta

**Comment by mythz** [comment]
Not until the next major release which wont be this month.

You will need to use reference the packages on MyGet to get this fix.
