### ISSUE TITLE
SqlListLazy

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#687]
Hi,
When we are running some truly complex query SQL, using longer `WITH ... SELECT ..` queries to fetch a lot of data. It would have been really practical to have `SqlListLazy` available in the standard API for ServiceStack OrmLite.

**Comment by mythz** [comment]
The issue tracker is for reporting reproducible issues only, if you want to propose a feature please submit it to [User Voice](https://servicestack.uservoice.com/forums/176786-feature-requests) with a clear example of the missing proposed API and how it differs from OrmLite's
`SelectLazy<T>(this IDbConnection, SqlExpression<T>)` API.

**Comment by jhf** [comment]
> The issue tracker is for reporting reproducible issues only

Ok.

> if you want to propose a feature please submit it to [User Voice](https://servicestack.uservoice.com/forums/176786-feature-requests) with a clear example of the missing proposed API and how it differs from OrmLite's existing APIs like `SelectLazy<T>(this IDbConnection, SqlExpression<T>)`.

I have done that here https://servicestack.uservoice.com/forums/176786-feature-requests/suggestions/38727511-add-sqllistlazy-to-ormlite looking forward to your feedback there.
Do you tag/mark such very specific requests from licensed customers?

**Comment by mythz** [comment]
No it's expected issues / feature requests to be from Customers, features are prioritized by demand.
