### ISSUE TITLE
Ambiguous call for ToHashSet() when on net472+

### ISSUE THREAD

**Issue by marko444** [ServiceStack/Issues#688]
What do you recommend to do in this situation? Will this be solved by ServiceStack?

Repro:

```
using System.Collections.Generic;
using System.Linq;
using ServiceStack;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            var x = new List<int>().ToHashSet();
        }
    }
}
```

> CS0121	The call is ambiguous between the following methods or properties: 'System.Linq.Enumerable.ToHashSet<TSource>(System.Collections.Generic.IEnumerable<TSource>)' and 'ServiceStack.EnumerableExtensions.ToHashSet<T>(System.Collections.Generic.IEnumerable<T>)'

**Comment by mythz** [comment]
Remove one of the namespaces so it's no longer ambiguous. If you ever need both namespaces you can create the HashSet normally:

```csharp
var x = new HashSet<int>(new List<int>());
```
