### ISSUE TITLE
Grpc service client User-Agent breaks GrpcClient

### ISSUE THREAD

**Issue by ludydoo** [ServiceStack/Issues#691]
I stumbled on this while trying the integration tests

Steps to reproduce:

1. web new grpc
2. run integration tests

Result:

```
System.FormatException
  HResult=0x80131537
  Message=The format of value '5,71' is invalid.
  Source=System.Net.Http
  StackTrace:
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index) in /_/src/System.Net.Http/src/System/Net/Http/Headers/HttpHeaderParser.cs:line 73
```

The reason is because

ServiceStack.GrpcServiceClient

public string UserAgent { get; set; } = ".NET gRPC Client " + Env.ServiceStackVersion;

Is actually

`.NET gRPC Client 5,71`

ServiceStack.GrpcServiceClient.PrepareRequest

```
                if (UserAgent != null)
                    headers.Add(HttpHeaders.UserAgent, UserAgent);
```

If I do 

var client = new GrpcServiceClient();
client.UserAgent = "test"

Then it works

It seems like the User-Agent header has a specific parser that does not allow for that kind of custom values.

**Comment by mythz** [comment]
Should now be resolved in the latest v5.7.1, as you've already got v5.7.1 installed you'll need to [clear your NuGet packages cache](https://docs.servicestack.net/myget#redownloading-myget-packages).
