### ISSUE TITLE
ServiceStack OrmLite order by error

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#693]
### Behavior
In some cases Select() method does not return rows in correct order (order is messed up).

### Configuration
ServivceStack v.5.7.0
Framework .NET 4.6.1
Visual Studio 2015 Update 3
Windows 10
SQL Server 2008 (legacy database so I use **SqlServer2008Dialect**)

### Steps to reproduce the behavior
Build a select expression with a join. paginate the expression so ServiceStack.OrmLite will generate a call to `ROW_NUMBER()` SQL Server function. Attach an `ORDER BY` expression.

The resulting incorrect query is :

> `SELECT * FROM (SELECT  "SAV"."Observations", "SAV"."Message SAV", "SAV"."Type garantie", "SAV"."Prix achat", "SAV"."CreatedAtUtc", "SAV"."Identifiant", "SAV"."Devis", "SAV"."Couleur", "SAV"."Vendu", "SAV"."Infos", "SAV"."Poste", "SAV"."Phase", "SAV"."HandrailNumber", "SAV"."Garantie", "SAV"."Nb présentation", "SAV"."Compteur", "SAV"."IsDelegateLacquering", "SAV"."IsExhibition", "SAV"."IsRefurbished", "SAV"."Date garantie", "SAV"."Message laquage", "SAV"."Départ SG", "SAV"."Message fabrication", "SAV"."Motif", "SAV"."Modèle", "SAV"."Position", "SAV"."Forme", "SAV"."Marque", "SAV"."Texte relance", "SAV"."SectionNumber", "SAV"."Prix vente", "SAV"."N°série", "SAV"."Etat", "SAV"."Message magasin", "SAV"."TrailingNumber", "SAV"."Nb passage", (CASE WHEN "SAV"."Type garantie" IS NOT NULL AND "SAV"."Type garantie" IN ('A', 'AT') THEN 1 ELSE 0 END) AS HasAutomatism, (CASE WHEN "SAV"."Marque" IS NOT NULL AND "SAV"."Marque" IN ('1','2','P') AND "SAV"."Garantie" = 1 THEN 1 ELSE 0 END) AS HasSideCover, (CASE WHEN (("SAV"."Marque" IS NOT NULL AND "SAV"."Marque" = 'K' AND "SAV"."Garantie" = 1) OR (EXISTS(SELECT "BatchTypeId" FROM "Batch" WHERE "Batch"."ProductId" = "SAV"."Compteur" AND "Batch"."BatchTypeId" = 'RailAccessory'))) THEN 1 ELSE 0 END) AS HasRail, ROW_NUMBER() OVER (
ORDER BY "SAV"."N°série") As RowNum  
FROM "SAV" LEFT JOIN "Batch" ON ("SAV"."Compteur" = "Batch"."ProductId")
WHERE (("SAV"."Date garantie" >= @0) AND ("SAV"."Date garantie" <= @1))
GROUP BY "SAV"."Observations", "SAV"."Message SAV", "SAV"."Type garantie", "SAV"."Prix achat", "SAV"."CreatedAtUtc", "SAV"."Identifiant", "SAV"."Devis", "SAV"."Couleur", "SAV"."Vendu", "SAV"."Infos", "SAV"."Poste", "SAV"."Phase", "SAV"."HandrailNumber", "SAV"."Garantie", "SAV"."Nb présentation", "SAV"."Compteur", "SAV"."IsDelegateLacquering", "SAV"."IsExhibition", "SAV"."IsRefurbished", "SAV"."Date garantie", "SAV"."Message laquage", "SAV"."Départ SG", "SAV"."Message fabrication", "SAV"."Motif", "SAV"."Modèle", "SAV"."Position", "SAV"."Forme", "SAV"."Marque", "SAV"."Texte relance", "SAV"."SectionNumber", "SAV"."Prix vente", "SAV"."N°série", "SAV"."Etat", "SAV"."Message magasin", "SAV"."TrailingNumber", "SAV"."Nb passage") AS RowConstrainedResult WHERE RowNum > 40 AND RowNum <= 80`

Simplified query should be something like that

> `SELECT * FROM (SELECT  "SAV"."N°série", "SAV"."Observations", ROW_NUMBER() OVER (
ORDER BY "SAV"."N°série") As RowNum  
FROM "SAV" LEFT JOIN "Batch" ON ("SAV"."Compteur" = "Batch"."ProductId")
WHERE (("SAV"."Date garantie" >= @0) AND ("SAV"."Date garantie" <= @1))
GROUP BY "SAV"."N°série", "SAV"."Observations") AS RowConstrainedResult WHERE RowNum > 40 AND RowNum <= 80`

### Notes
In my case, adding manually `ORDER BY RowNum` does the trick but I cannot use it directly inside code.

Thank you very much for your help!

**Comment by mythz** [comment]
I'd suggest you use Custom SQL or client sorting as the RowNum windowing function is a necessary hack for legacy SQL Server databases which I don't want to change to preserve backward compatibility.

**Comment by labilbe** [comment]
Ok. I finally ended up with the followiing method:

```
List<Product> products;
// HACK Remove this when upgrading to another SQL Server Database version
var selectStatement = ev.ToMergedParamsSelectStatement();
if (selectStatement.Contains("RowNum"))
{
    selectStatement += " ORDER BY RowNum";
    products = db.SqlList<Product>(selectStatement);
}
else
    products = db.Select(ev);
```
