### ISSUE TITLE
Unable to deploy to Azure App service

### ISSUE THREAD

**Issue by Sparx92** [ServiceStack/Issues#697]
Hi,

**Steps to reproduce:**
1. Create a new blank ASP.NET 4.7.2 project
1. Install The ServiceStack 5.7.0 Nuget (which has a dependency on System.ComponentModel.Annotations)
1. Deploy this project in GitHub
1. In Azure, create an App Service which's Runtime stack is ASP.NET V4.7
1. Once the App Service is created, go to its Deployment center and configure it to use the previously created Github repo 
* At this point, the build process will start, and it will fail with the following exception:

`CSC : error CS1703: Multiple assemblies with equivalent identity have been imported: 'D:\home\site\repository\packages\System.ComponentModel.Annotations.4.4.1\lib\net461\System.ComponentModel.Annotations.dll' and 'D:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.7.2\Facades\System.ComponentModel.Annotations.dll'. Remove one of the duplicate references. [D:\home\site\repository\SitefinityWebApp.csproj]
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\SitefinityWebApp.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d76cd3c69223fa";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"`

*This issue was originally reproduced in Sitefinity CMS, however it is present in every .NET 4.7 app using the ServiceStack 5.7.0 Nuget package.*

Thank you,
Stefan

**Comment by mythz** [comment]
This looks like a known dotnet SDK issue:
https://github.com/dotnet/sdk/issues/1539#issuecomment-362691359

There's a potential workaround in:
https://stackoverflow.com/a/44648397/85785

**Comment by mythz** [comment]
I've replaced it with a framework reference in [this commit](https://github.com/ServiceStack/ServiceStack/commit/118652785f4e8fc3034f013a39a9e0e30eee8111) which is available from v5.7.1 that's [now available on MyGet](https://docs.servicestack.net/myget).

I'm assuming this should resolve it as it's no longer referencing the .NET Standard Library in .NET Framework builds. Please let me know if it doesn't resolve the issue.
