### ISSUE TITLE
Extension method AppSettingsUtils.GetConnectionString runs into infinite loop

### ISSUE THREAD

**Issue by joergrosenkranz** [ServiceStack/Issues#703]
Runtime: .NET Core 3.1

The call to GetConnectionString in [this line](https://github.com/ServiceStack/ServiceStack/blob/6775e70fd67e5a75c2e71e828af083c5e0ffb9dc/src/ServiceStack/Configuration/AppSettingsBase.cs#L201) calls the function itself, when it was called on a NetCoreAppSettings instance.

**Comment by mythz** [comment]
Now fixed in the latest v5.8.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

Thanks for reporting!
