### ISSUE TITLE
MissingMethodException Error in ServiceStack Autoquery

### ISSUE THREAD

**Issue by Olushola** [ServiceStack/Issues#706]
I am having this error after migrating to v5.8.1
Before then the code was working perfectly

My service looks like this:

		public object Get(FindCategories req) {
			var qry = AutoQuery.CreateQuery(req, base.Request);
			qry.Where(x => x.IsActive == true);

			return AutoQuery.Execute(req, qry);
		}

My DTO:

	[Route("/Categories", "Get")]
	public partial class FindCategories : QueryDb<Category> {
		public bool? WithReferences { get; set; } = true;
	}

And my Type:

    public class Category : BaseEntity {
        public string Name { get; set; }
        public bool IsManagerial { get; set; }
        public int PriorityLevel { get; set; }
        public Decimal Budget { get; set; }
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
    }

Please help!

**Comment by mythz** [comment]
A change was added to `IAutoQueryDb` to make add an additional optional parameter, e.g:

//v5.8
```csharp
public interface IAutoQueryDb
{
    SqlExpression<From> CreateQuery<From>(IQueryDb<From> dto, Dictionary<string, string> dynamicParams, IRequest req = null);

    QueryResponse<From> Execute<From>(IQueryDb<From> model, SqlExpression<From> query);
}
```

//v5.8.1
```csharp
public interface IAutoQueryDb
{
    SqlExpression<From> CreateQuery<From>(IQueryDb<From> dto, Dictionary<string, string> dynamicParams, IRequest req = null, IDbConnection db = null);

    QueryResponse<From> Execute<From>(IQueryDb<From> model, SqlExpression<From> query, IRequest req = null, IDbConnection db = null);
}
```

Unfortunately this is only a source compatible change, not a binary compatible one so you'll need to recompile all your libraries against the latest packages by [completely removing your previous NuGet cache](https://docs.servicestack.net/myget#redownloading-myget-packages).

    $ nuget locals all -clear

If you have .NET Framework projects with their own `packages` folder they should be removed as well, e.g:

    $ rd /q /s packages

Note related, but note it's recommended to also include the `IRequest` in your execute method, e.g:

    $ return AutoQuery.Execute(req, qry, base.Request);

**Comment by Olushola** [comment]
I followed the instructions and cleared the caches but the error persists.
I had to downgrade to v5.8.0

**Comment by mythz** [comment]
ok but missing method exceptions is due to one of your projects binary being built against one version whilst being hosted with another. All projects need to be rebuilt against the latest version.

If you can provide a stand-alone repro (e.g. on GitHub) I'll be able to identify and resolve the issue.
