### ISSUE TITLE
Error on MvcApplication.Application_Start()

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#708]
Project runs OK on my dev machine (VS2015, WIN10, ServiceStack 5.8).
If I build the project on same machine and deploy on my dev IIS it runs OK too.

When I commit changes and run a staging build the build is successfull (VS2015, WIN7, ServiceStack 5.8). When I test the staging website an error is thrown (Cannot load file or assembly'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51').

I tried to find the origin and it "seems to be" that line in LicenseUtils.cs:
`if (int.TryParse(subId, out var subIdInt) && revokedSubs.Contains(subIdInt))`

![sshot-1](https://user-images.githubusercontent.com/54315/73854219-6ea39380-4832-11ea-8413-aaff1d52d09f.png)

The project is compiled using the target Microsoft.NET Framework v4.6 since the production server is a Windows 2008 SP2.

Here is the package.config file of my web project
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net46" />
  <package id="bootstrap" version="3.4.1" allowedVersions="[3.4.1]" targetFramework="net46" />
  <package id="Bootstrap.Datepicker" version="1.8.0.1" targetFramework="net46" />
  <package id="bootstrap.less" version="3.3.5" targetFramework="net46" />
  <package id="Bootstrap.v3.Datetimepicker" version="4.17.45" targetFramework="net46" />
  <package id="Bootstrap.v3.Datetimepicker.CSS" version="4.17.45" targetFramework="net46" />
  <package id="bootstrap-colorpicker" version="2.3.2" targetFramework="net46" />
  <package id="bootstrap-select" version="1.13.12" targetFramework="net46" />
  <package id="Bundler" version="1.1.31" targetFramework="net46" />
  <package id="cldrjs" version="0.5.1" targetFramework="net46" />
  <package id="Common.Logging" version="3.3.1" targetFramework="net46" />
  <package id="Common.Logging.Core" version="3.3.1" targetFramework="net46" />
  <package id="DotNet.Highcharts" version="4.0" targetFramework="net46" />
  <package id="Handlebars.js" version="4.0.0" targetFramework="net46" />
  <package id="jQuery" version="3.4.1" targetFramework="net46" />
  <package id="jquery.ns-autogrow" version="1.1.6" targetFramework="net46" />
  <package id="jQuery.TimeAgo" version="1.1.01" targetFramework="net46" />
  <package id="jQuery.UI.Combined" version="1.12.1" targetFramework="net46" />
  <package id="jquery-globalize" version="1.4.2" targetFramework="net46" />
  <package id="knockoutjs" version="3.5.1" targetFramework="net46" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.7" targetFramework="net46" />
  <package id="Microsoft.AspNet.Razor" version="3.2.7" targetFramework="net46" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net46" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.7" targetFramework="net46" />
  <package id="Microsoft.Bcl" version="1.1.10" targetFramework="net46" />
  <package id="Microsoft.Bcl.Build" version="1.0.21" targetFramework="net46" />
  <package id="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" version="2.0.1" targetFramework="net46" />
  <package id="Microsoft.CSharp" version="4.7.0" targetFramework="net46" />
  <package id="Microsoft.Net.Compilers" version="2.4.0" targetFramework="net46" developmentDependency="true" />
  <package id="Microsoft.Net.Http" version="2.2.29" targetFramework="net46" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net46" />
  <package id="Moment.js" version="2.9.0" targetFramework="net46" />
  <package id="ncalc" version="1.3.8" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="5.0.4" targetFramework="net46" />
  <package id="NLog" version="4.6.7" targetFramework="net46" />
  <package id="NLog.Web" version="4.9.0" targetFramework="net46" />
  <package id="PagedList" version="1.17.0.0" targetFramework="net46" />
  <package id="PagedList.Mvc" version="4.5.0.0" targetFramework="net46" />
  <package id="Quartz" version="2.6.2" allowedVersions="[2.6.2]" targetFramework="net46" />
  <package id="Serilog" version="2.9.0" targetFramework="net46" />
  <package id="Serilog.Formatting.Compact" version="1.0.0" targetFramework="net46" />
  <package id="Serilog.Sinks.File" version="4.0.0" targetFramework="net46" />
  <package id="Serilog.Sinks.PeriodicBatching" version="2.1.1" targetFramework="net46" />
  <package id="Serilog.Sinks.Seq" version="4.0.0" targetFramework="net46" />
  <package id="SerilogWeb.Classic" version="5.0.52" targetFramework="net46" />
  <package id="ServiceStack" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Api.Swagger" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Client" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Common" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Interfaces" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Mvc" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.NetFramework" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.OrmLite" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Redis" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Seq.RequestLogsFeature" version="5.1.0" targetFramework="net46" />
  <package id="ServiceStack.Server" version="5.8.0" targetFramework="net46" />
  <package id="ServiceStack.Text" version="5.8.0" targetFramework="net46" />
  <package id="showdownjs" version="1.9.1" targetFramework="net46" />
  <package id="System.Buffers" version="4.4.0" targetFramework="net46" />
  <package id="System.ComponentModel.Annotations" version="4.4.1" targetFramework="net46" />
  <package id="System.Memory" version="4.5.3" targetFramework="net46" />
  <package id="System.Net.Http" version="4.3.4" targetFramework="net46" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.7.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net46" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net46" />
  <package id="System.Web.Http.Common" version="4.0.20126.16343" targetFramework="net46" />
  <package id="TinyMCE" version="5.1.6" targetFramework="net46" />
  <package id="Twitter.Typeahead" version="0.11.1" targetFramework="net46" />
  <package id="typeahead.js-bootstrap.css" version="0.0.4" targetFramework="net46" />
  <package id="WebGrease" version="1.5.2" targetFramework="net46" />
</packages>`

**Comment by labilbe** [comment]
The project is working on the production environment (no error). So the only environment where the bug occurs is the staging one.

**Comment by mythz** [comment]
These issues are [runtime binding issues](https://docs.servicestack.net/templates-corefx#troubleshooting). They're unique to each project. You'd need to upload a repro on GitHub (and post the link here) in order for us to be able to try to resolve the issue.

The best thing you can try is upgrading the .NET Framework version to see if that resolves it.

**Comment by labilbe** [comment]
In the docs, it says Windows 2008 SP2 is limited to framework 4.6.
I don't know how it handles a .NET Framework superior.

Thank you for your link. I will try different things and post the solution when I'm done.

**Comment by mythz** [comment]
Closing Issue as it's a per project issue and nothing actionable can be done.
