### ISSUE TITLE
UpdateEventSubscriber responds 200 but doesn't update subscription

### ISSUE THREAD

**Issue by lomithrani** [ServiceStack/Issues#710]
Servicestack `v5.8.0` `netcoreapp3.1 x64`  `ss-utils.js`

Registering as such:

```
container.Register<IServerEvents>(new MemoryServerEvents());
Plugins.Add(
new ServerEventsFeature()
            {
                HeartbeatInterval = TimeSpan.FromSeconds(10),
                IdleTimeout = TimeSpan.FromSeconds(21),
                LimitToAuthenticatedUsers = true,
                ValidateUserAddress = false,      
                OnSubscribe = (ev) =>{ //stuff },               
                OnUnsubscribe = (ev) => { //stuff }
            });
```
I'm initialising the  the client 

```
 $scope.SSE = new EventSource("/event-stream?channel=editDocs", { withCredentials: true });

        $($scope.SSE).handleServerEvents({
            handlers: {
                onConnect: function (sub) {

                },
                onJoin: function (user) {

                },
                onLeave: function (user) {

                },
                onMessage: function (msg, e) { 
                },
                ValidationObj: function (obj, e) {
                },
                EditDocEvent: function (obj, e) {
                    switch (obj.Method) {
                        case "add":
                            //stuff
                            break;
                        case "remove":
                          //stuff
                            break;
                        default:
                        // code block
                    }
                    $scope.$apply();
                }
            },
            receivers: {
            },
        });
```

Everything works fine until then  but then I want to update the subscription's channels doing that :

` $.ss.subscribeToChannels([id_doc], (success) => console.log(success), (error) => console.log("error"));`

![image](https://user-images.githubusercontent.com/900881/74340884-1545e200-4da7-11ea-8880-27c13664012e.png)

and get this response

![image](https://user-images.githubusercontent.com/900881/74341324-cf3d4e00-4da7-11ea-8856-30322c918829.png)

And a call to /event-subscribers will still say that I'm only registered to /editDocs and not both channels. 

I might be wrong but I don't think this is the expected behavior.

Thanks a lot for your hard work !

**Comment by lomithrani** [comment]
If I take the subId from the heartbeat and make the same call with add /subId (to match servicestack service)  it does update my subscription.

**Comment by lomithrani** [comment]
changing the following in ss-utils.js seems to fix my issue
```
$.ss.updateSubscriber = function (data, cb, cbError) {
        if (!$.ss.updateSubscriberUrl)
            throw new Error("updateSubscriberUrl was not populated");
        return $.ajax({
            type: "POST",
            url: `${$.ss.updateSubscriberUrl}/${$.ss.eventOptions.id}`,
            data: data,
            dataType: "json",
            success: function (r) {
                $.ss.updateSubscriberInfo(data.SubscribeChannels, data.UnsubscribeChannels);
                r.channels = $.ss.eventChannels;
                if (cb != null)
                    cb(r);
            },
            error: function (e) {
                $.ss.reconnectServerEvents({ errorArgs: arguments });
                if (cbError != null)
                    cbError(e);
            }
        });
    };
```

**Comment by mythz** [comment]
Thanks for reporting this! the issue is on the server when constructing the updateSubscriberUrl which should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack/commit/1628acebaafbddc457b787843c8840ea8b41c50f).

Note: don't register `MemoryServerEvents` as it's pre-registered by default:

```csharp
//container.Register<IServerEvents>(new MemoryServerEvents());
```

The `OnSubscribe/OnSubscribeAsync` is only fired when a new subscription is created not updated, it also only fires the [onUpdate](https://docs.servicestack.net/server-events#onupdate-notification) event on the client.

This change is available in the latest v5.8.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Comment by lomithrani** [comment]
Thank you very much !  What would you suggest to do server side (as I do some logic on subscribe and unsubscribe) ? Is there any event fired when this update is made ?

**Comment by mythz** [comment]
I've added a `OnUpdateAsync` server event on `ServerEventsFeature` you can use to invoke custom logic when a subscription is updated.

This change is now available from v5.8.1 on MyGet, if you already have v5.8.1 installed you'll need to [clear your NuGet packages cache](https://docs.servicestack.net/myget#redownloading-myget-packages) to download the latest version.

**Comment by lomithrani** [comment]
@mythz Perfect , just a small issue there that I could solve with some logic on my side but I think it might be useful to add we are missing which channels we unsubscribe from during the updates.

**Comment by mythz** [comment]
In `IEventSubscription` the active channels are maintained in `Channels` whilst `MergedChannels` contains both active and previously subscribed channels, so the difference of `MergedChannels-Channels`  contains the list of unsubscribed channels during the update.
