### ISSUE TITLE
Exclude Enums in metadata / include descriptions on Enum values

### ISSUE THREAD

**Issue by Zedoari** [ServiceStack/Issues#711]
In ServiceStack version 5.5.0 Enum types weren't documented in Metadata by themselves. That's why we used ApiAllowableValues attibute to specify all Enum values.
In version 5.8.0 Enum properties are also documented by themselves in a separate table.

---------------------
RequestName
The following routes are available for this service:
PATCH	/api/request	Description

**RequestName** Parameters:

NAME | PARAMETER | DATA TYPE | REQUIRED | DESCRIPTION
------------ | ------------- | ------------- | ------------- | -------------
Id | path | uuid | Yes | Identifier.
Priority | query | Priority | No | New priority. <br/>**Allowable Values:** <br/>**- Lowest** - Trigger background job with Lowest priority.<br/>**- Low** - Trigger background job with Low priority.<br/>**-Medium** - Trigger background job with Medium priority.<br/>**-High** - Trigger background job with High priority.<br/>**- Highest** - Trigger background job with Highest priority.<br/>

**Priority** Enum:

NAME | VALUE
------------ | -------------
Lowest | 0
Low | 25
Medium | 50
High | 75
Highest | 100

---------------------

There are two acceptable solutions to solve this duplication problem:
1. add descriptions to enum values (currently "Description" attribute on values does nothing),
2. exclude Enums to have their values specified in separate table.

Is there a way to implement the first or solution (first one is preferable).

**Comment by mythz** [comment]
I've updated it to include the description in the Enum table and to only show Allowable values in the description if the property is **not** an Enum (e.g. a string).

So with different styles of Enums it now looks something like:

![image](https://user-images.githubusercontent.com/89361/74454251-9348dc80-4ebe-11ea-80f5-f668af4a131c.png)

You can use the `[Description]` or `[ApiMember]` attributes to annotate your enum members with a description.

This change is available from v5.8.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Comment by Zedoari** [comment]
Thanks. Just one remark..
Nullable Enum allowable values still show. Although maybe it would be best to still display ApiAllowableValues on enums and developers can delete them if they're not necessary.

**Comment by mythz** [comment]
I've restored the behavior of displaying Allowable Values when annotated with `[ApiAllowableValues]`.

This change is available from the latest v5.8.1 that's now [available on MyGet](https://docs.servicestack.net/myget).
