### ISSUE TITLE
"x new vuetify-nuxt-netfx ProjectName" fails

### ISSUE THREAD

**Issue by richardwhatever** [ServiceStack/Issues#715]
Running 
`x new vuetify-nuxt-netfx ProjectName `
fails with 
`FATAL  Cannot import module 'ts-node'`

Environment
- Windows 10
- node v12.16.1
- npm 6.14.2
- x 0.0.7

Please advise.

**Comment by mythz** [comment]
Looks like the issue was needing to [delete tsconfig.json](https://github.com/NetFrameworkTemplates/vuetify-nuxt-netfx/commit/ab497fb6ec610b1c88a04e1b710a8b949caa8221). I've just published a new release so if you create a new template it should build without issue.
