### ISSUE TITLE
JSON polymorphism deserialization doesn't work for type that is not first property.

### ISSUE THREAD

**Issue by rosieks** [ServiceStack/Issues#722]
JSON polymporphism deserialization doesn't work when `__type` is not first property. Eg:

```
    { "Name": "Fido", "__type": "ServiceStack.Text.Tests.JsonTests.Dog" }
```

There is already [test for such case](https://github.com/ServiceStack/ServiceStack.Text/blob/69085b6f6e6bfd9f61dca4b8010be4842b0d9cfc/tests/ServiceStack.Text.Tests/JsonTests/PolymorphicInstanceTest.cs#L36) but I think that it's wrong. Bellow is correct one:

```
[Test]
public void Can_deserialise_polymorphic_list_exact_with_no_side_effect_for_bad_type_position()
{
    var dog = 
          JsonSerializer.DeserializeFromString<Animal>(
              @"{""Name"":""Fido"",""__type"":"""
              + typeof(Dog).ToTypeString() + @"""}");

    Assert.That(dog.Name, Is.EqualTo(@"Fido"));
}
```

When I call deserialize with Animal it returns null. While if the __type is a first property then it works fine.

**Comment by mythz** [comment]
This restriction is by design, it needs to be in the first position to be able to determine what Type it should be deserialized to. The recommendation is to [not use inheritance in DTOs](https://stackoverflow.com/a/10759250/85785).
