### ISSUE TITLE
problems with serialization of string with numbers

### ISSUE THREAD

**Issue by jaimetg81** [ServiceStack/Issues#724]
I work with ServiceStack for .Net Ver 4.5.0 

I found a problem in servicestack serialization process with objects that contains string properties with numbers. For example:

I have an object like this:

class Package
{
   string version;
   string name;
   int id;
}

When i try to convert with ServiceStack.Text.JsonSerializer.SerializeToString(Package);
obtain:

{
    "version": 1.8.30.1,
    "name":"testVersion",
    "id": 2351
} 

This is a malformed Json because the version value is a wrong number, the correct value must be "1.8.30.1"

I applied a workaround through RawSerializeFn, but i guess it's possible a best solution through servicestack. I was downloaded the servicestack's code from git hub and try to correct this and found the problem. The core of the problem is based in a section of the serialization process that verify if the value is a decimal number or a string, the process looks for the first dot in the string and assumes that the rest are numbers without dots.

**Comment by mythz** [comment]
Please provide a stand-alone repro that can be run locally to repro the issue.

**Comment by jaimetg81** [comment]
I updated the ServiceStack nuget and the issue was fixed, anyway thanks.
