### ISSUE TITLE
serialization problem with backslashes

### ISSUE THREAD

**Issue by jaimetg81** [ServiceStack/Issues#725]
I'm Working with the latest version of servicestack.text for .net  Ver 5.8.0

I found a issue with serialization for objects with properties that contains escaped chars "\".
For example my object contains a property like this:    string folder = "test folder \ example"

After serialization the result is =   "folder": "test folder \\\ example".
For any case that i use the "\\" and the times what i used this, the serialization process duplicate the backslashes.

I attach a file with standalone test with this.
[Program.txt](https://github.com/ServiceStack/Issues/files/4732705/Program.txt)

**Comment by mythz** [comment]
ServiceStack.Text is a typed JSON serializer which is designed to deserialize into known types, this is the behavior of `JsonObject` which wraps a string Dictionary and has to coerce its string values. 

If you want to parse arbitrary JSON it's recommended to use [JSON.parse()](https://github.com/ServiceStack/ServiceStack.Text#js-utils) instead.
