### ISSUE TITLE
Checking if session exists Flutter

### ISSUE THREAD

**Issue by ochamo** [ServiceStack/Issues#726]
Hello, I am using servicestack-dart in my flutter app, the problem I currently have is that I cannot check if an user has already logged in, is there any method that is not documented I could use for this. The session right now only stays until the app is running on foreground, when I push my to the background and left it there, the app restarts and returns to the root route of it. Could you please help with this?

**Comment by mythz** [comment]
This [issue tracker is only for reproducible bugs/issues only](https://github.com/ServiceStack/Issues#you-can-view-existing-issues-or-report-a-new-issue).

Please ask any other technical support questions on the [Customer Forums](https://forums.servicestack.net) or [post on StackOverflow](https://stackoverflow.com/questions/ask?tags=servicestack)
