### ISSUE TITLE
.NET Core templates are out of date

### ISSUE THREAD

**Issue by EatonZ** [ServiceStack/Issues#729]
I created a .NET Core 3.1 Empty Website using your dotnet tool and I noticed the content in Program.cs is out of date. Changes were made that are described [here](https://andrewlock.net/exploring-the-new-project-file-program-and-the-generic-host-in-asp-net-core-3/#changes-in-program-cs-from-2-x-to-3-0).

It's possible other files may be outdated too, so you may want to consider doing a file compare with a fresh .NET Core 3.1 project to copy over anything else new/changed.

**Comment by mythz** [comment]
Are you not not seeing [Program.cs](https://github.com/NetCoreTemplates/web/blob/master/MyApp/Program.cs)?

```csharp
public class Program
{
    public static void Main(string[] args)
    {
        BuildWebHost(args).Run();
    }

    public static IWebHost BuildWebHost(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseModularStartup<Startup>()
            .Build();
}
```

This is what it should be, ServiceStack .NET Core projects follow the [Modular Startup](https://docs.servicestack.net/modular-startup) which allows [mixing features](https://docs.servicestack.net/mix-tool), a feature unique to ServiceStack.

**Comment by EatonZ** [comment]
@mythz So you are using the old way for a reason?
The new way, when modified to use your `UseModularStartup`, appears to work just fine. Let me know if I am missing/misunderstanding something.

```
public class Program
{
    public static void Main(string[] args)
    {
        CreateHostBuilder(args).Build().Run();
    }

    public static IHostBuilder CreateHostBuilder(string[] args) =>
        Host.CreateDefaultBuilder(args)
            .ConfigureWebHostDefaults(webBuilder =>
            {
                webBuilder.UseModularStartup<Startup>();
            });
}
```

**Comment by mythz** [comment]
Ok yeah, `UseModularStartup` is an extension method off `IWebHostBuilder` which wasn't going to support `IHostBuilder` but can now see `IWebHostBuilder` is still being passed in & that I'm already using it for [.NET Core 3.1 Test projects](https://github.com/ServiceStack/ServiceStack/blob/master/tests/CheckWebCore/Program.cs), so there should be no issue.

I'll update the templates, thx for reporting 👍

**Comment by mythz** [comment]
ok all templates should now be updated.
