### ISSUE TITLE
JsonServiceClient fails with certain request DTO design (private setter + inheritance)

### ISSUE THREAD

**Issue by Uzivatel919** [ServiceStack/Issues#731]
Using following design

```
public abstract class Request
{
    protected Request(string key) => Key = key;

    public string Key { get; private set; }
}

public class Get : Request
{
    public Get(string key) : base(key) { }
}

```
and request like

```
var client = new JsonServiceClient(apiUrl);
await client.GetAsync(new Get("someKey"));
```

_ServiceStack_ fails to map the _Key_ property (on server side?).

Worth note that object like 

```
public class Set : Request
{
    public Set(string key, int[] data) : base(key)
    {
        Data = data;
    }

    public int[] Data { get; private set; }
}
```
will get the _Key_ property mapped. Likely because it has own property.

When design is changed to

```
public abstract class Request
{
    public string Key { get; set; }
}

public class Get : Request {}
```
property gets mapped.

Also worth note that _private setter_ design works using for instance _REST API_ client or similar way.

**Comment by mythz** [comment]
DTOs should be "Data Transfer Objects", i.e. they should be POCOs with public getters/setters & a parameterless constructor. 

Only public properties are serialized and public setters is required to deserialize properties. If you want to maintain a separate domain model with business logic and different accessibility you'll need to maintain them separate to DTOs, if maintaining separate models you could use [Auto Mapping Utils](https://docs.servicestack.net/auto-mapping) to help mapping between models.

**Comment by Uzivatel919** [comment]
I know what is common _DTO_ design. You can see in issue that _Set_ properties are perfectly set even on base even if it have no _parameterless constructor_ and _private setters_ on all properties. _Private setters_ are perfectly recognized and used by _ServiceStack_. That is for sure but this particular desing is does not work thus I thought it is a bug.

**Comment by mythz** [comment]
DTOs should be logicless POCO data container objects, their public shape is what's used to define their external service contract and their serialization model, by hiding their accessibility you're interfering with their serialization which only serializes and deserializes its public member properties. 

It doesn't "perfectly" handle non parameterless constructors either, it has to fallback to use [FormatterServices.GetUninitializedObject()](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.formatterservices.getuninitializedobject?view=netcore-3.1) which is a hack that bypasses running any constructors which can lead to invalid state, you shouldn't be reliant on it, use proper DTOs for your Service Models as they're intended.

**Comment by Uzivatel919** [comment]
Ok, ok. Thanks for guidelines. I do it like you say regardless of DTOs design. `FormatterServices.GetUninitializedObject(typeof)` cannot create abstract class so I guess this is it since all properties are held by abstract class.
