### ISSUE TITLE
Impossible to set `SameSite=Lax` with config or code for .Net  (not core)

### ISSUE THREAD

**Issue by jhf** [ServiceStack/Issues#734]
It should be possible to support `SameSite=Lax` with the configuration option `UseSameSiteCookies`.

The enum `System.Web.SameSiteMode` supports three states, `Lax`, `None` and `Strict`, however, the configuration option `SameSite` in SS is a binary value.
With Chrome 80+ the interpretation of a missing `SameSite` attribute is defaulted to `Lax` - the behaviour we need, but we can only get either `Strict` or `None`.

When running .Net Core we override `CookieOptionsFilter` in our `AppHost` but for .Net 4 the code https://github.com/ServiceStack/ServiceStack/blob/d9a001f8de931614a987a5133a3aa5733087889b/src/ServiceStack/Host/Cookies.cs#L172 only allows setting `Strict` or `None`.

When looking at the `SameSiteMode` attribute it has supported all three states for a long time https://docs.microsoft.com/en-us/dotnet/api/system.web.samesitemode?view=netframework-4.8&viewFallbackFrom=netframework-4.0 and still does.

Would it be possible to make `UseSameSiteCookies` ternary with null, and when null then set `Lax`?
This would be in line with the defaults of Chrome and Firefox, and be backwards compatible.

**Comment by mythz** [comment]
Yes I think this default behavior makes the most sense, `SameSiteMode` only exists from v4.7.2 as per the linked docs which we can't be referenced directly in our .NET Framework v4.5 builds but can be accessible with some initialization reflection if running on v4.7.2+. 

This default behavior has now been implemented from [this commit](https://github.com/ServiceStack/ServiceStack/commit/81cee65091d35a4c83db8433e79025068ad8bd85) which is available from the latest v5.9.3 that's now [available on MyGet](https://docs.servicestack.net/myget).
