### ISSUE TITLE
Support for redis ACL

### ISSUE THREAD

**Issue by schloempe** [ServiceStack/Issues#736]
Currently I cannot find settings for username. Can't use new ACL features of redis with ServiceStack?

**Comment by mythz** [comment]
Not yet, please register feature requests on https://servicestack.uservoice.com so we can measure, track & notify when implemented.

In the meantime you should be able to call untyped Redis APIs with the [generic Custom APIs](https://github.com/ServiceStack/ServiceStack.Redis#generic-apis-for-calling-custom-redis-commands).
