### ISSUE TITLE
ServiceStack.Redis - RedisTypedClient - suspected memory leak on "ids"

### ISSUE THREAD

**Issue by yury-kozlov** [ServiceStack/Issues#737]
Hopefully this is the right place to publish an issue...
We are using Redis 3.0.503 (on windows) and ServiceStack.Redis 5.5.0.
When running this code I expect the data to be inserted in redis and then deleted:
```
var typedClient = redisManager.GetClient().As<MyType>();
typedClient.SetValue("my-key", myData);
typedClient.RemoveEntry("my-key);
```
However, the data is not completely removed, leaving hashcodes of my data forever under this set: "ids:MyType".
Is this by design?

Note, that "MyType" has no "Id" field, and ServiceStack.Redis takes myData.GetHashCode() as Id.

**Comment by mythz** [comment]
`RemoveEntry` just removes the key, you'll need to use the Delete/DeleteById/DeleteByIds/DeleteAll APIs which removes the entry and the backing index.

**Comment by yury-kozlov** [comment]
When I use DeleteById, it only deletes associated member from id-set. But the data itself remains in the db.
```
            var myData = new MyData { Phone = "123", Name = "John" };
            var redisManager = new PooledRedisClientManager();
            var typedClient = redisManager.GetClient().As<MyData>();
            typedClient.SetValue("my-key", myData);
            typedClient.DeleteById(myData.GetHashCode());
```

**Comment by yury-kozlov** [comment]
A separate problem with typedClient is that for some reason it uses hash code if my data has no Id field, which is weird because hashcodes are inconsistent and may vary between application instances.

**Comment by mythz** [comment]
DeleteById should delete both the key and backing Id:

https://github.com/ServiceStack/ServiceStack.Redis/blob/2be9f017cf4bae6bc608926fdab6758558b1a719/src/ServiceStack.Redis/Generic/RedisTypedClient.cs#L432-L433

Your POCO is expected to have an `Id` property otherwise you can use the `[PrimaryKey]` attribute on the unique property you want to use for its Id instead.

**Comment by yury-kozlov** [comment]
I added "Id" field to my data model, but the problem still exists: when I call DeleteById() only id member is deleted from the set, leaving data itself in redis:

            var myData = new MyData { Id = 123, Name = "John" };
            var typedClient = new PooledRedisClientManager().GetClient().As<MyData>();
            typedClient.SetValue("my-key", myData);
            typedClient.DeleteById(123);
            var value = typedClient.GetValue("my-key");

**Comment by mythz** [comment]
Yeah because you're also saving it against your custom key, you'll need to remove it from your custom key.

Or you could use the implicit id & store/delete it with:

```csharp
typedClient.Store(myData);
typedClient.Delete(myData); // or DeleteById(myData.Id);
```

**Comment by yury-kozlov** [comment]
Ok. I understand my problem.
What is still confusing is that when I use "SetValue(customKey, myData)", there's an id generated in the set, which can only be deleted with typedClient.DeleteById(myData).
We used all the way SetValue and RemoveEntry in production, and now we face problems with huge junk data-sets with are no longer relevant.
Is it safe to delete those id-sets, if we don't use GetById api ?

**Comment by mythz** [comment]
The backing indexes serve a number of APIs for tracking entities like enumerating/deleting the collection of entities.

If you're only setting / retrieving / removing by a key you wont need the index set.

But if you're going to store an object against a custom key you'd be better of using the [ICacheClient](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack.Interfaces/Caching/ICacheClient.cs) Get/Set/Remove generic [caching APIs](https://docs.servicestack.net/caching) which wont maintain the index.

**Comment by yury-kozlov** [comment]
Thanks!
