### ISSUE TITLE
Error:ServiceStack.Redis.RedisResponseException: 'No more data, sPort: 22874, LastCommand: '

### ISSUE THREAD

**Issue by Zulphugarli** [ServiceStack/Issues#738]
Hi everyone, i have get this error:ServiceStack.Redis.RedisResponseException: 'No more data, sPort: 22874, LastCommand: '

I have two different programs,the one of them i get error and other i dont get error.

First program is console app which i dont get error: Code is below:

```csharp
  class Program
    {
        static void Main(string[] args)
        {
            string host = "*****";
            string key = "IDG";
            // Store data in the cache
            bool success = Save(host, key, "Hello World!");
            // Retrieve data from the cache using the key
            Console.WriteLine("Data retrieved from Redis Cache: " + Get(host, key));
            Console.Read();
        }

        private static bool Save(string host, string key, string value)
        {
            bool isSuccess = false;
            RedisClient redisClient = new RedisClient(host);
            isSuccess = redisClient.Set(key, value);          
            return isSuccess;
        }
        private static string Get(string host, string key)
        {
            RedisClient redisClient = new RedisClient(host);
            return redisClient.Get<string>(key);           
        }
    }
```

Second program is MVC app, which i get error: , code is below

        public void ConfigureHost(AppHostBase appHost, Container container)
        {
            var redisServerAddress = ServiceAddressSettings.GetServiceAddress(Models.ServiceType.RedisServer);           
            container.Register<IRedisClientsManager>(c => new PooledRedisClientManager(redisServerAddress));
            container.Register(c => c.Resolve<IRedisClientsManager>().GetCacheClient());
            container.Register<ICacheClient>(c =>
            (ICacheClient)c.Resolve<IRedisClientsManager>()
            .GetCacheClient())
            .ReusedWithin(Funq.ReuseScope.None);
            container.Register<IRedisClientFactory>(c => new RedisClientFactory());

            appHost.Plugins.Add(new SessionFeature());

            appHost.Plugins.Add(****
                {
                   ****
                }));

            container.RegisterValidators(typeof(ValidationBase<>).Assembly);

            appHost.ServiceExceptionHandler = (req, request, exception) =>
            {
                ********
                return DtoUtils.HandleException(req, request, exception);
            };

            appHost.ExceptionHandler = (req, res, name, exception) =>
            {
                ********
            };
            
            appHost.RequestFilters.Add((request, response, dto) =>
                {
                    
                    var session = request.GetSession();
                    var session1 = request.Cookies;
                   
            

            appHost.ResponseFilters.Add((request, response, dto) =>
                {
				********
                });
        }

**Comment by mythz** [comment]
You're registering `ICacheClient` you [should only be registering](https://docs.servicestack.net/caching#redis)

        container.Register(c => c.Resolve<IRedisClientsManager>().GetCacheClient());

This isn't enough to reproduce the error, see [Debugging Data Corruption Issues](https://github.com/ServiceStack/ServiceStack.Redis#debugging-data-corruption-issues) for what to look out for.

If you can put together a stand-alone repro I can run locally to repro the error I'll be able to identify the issue.

**Comment by Zulphugarli** [comment]
Mr Demis Bellot can we progress solving of problem over skype? because project is higher size and there are problem giving code to you by security side.I hope that you understand me

**Comment by mythz** [comment]
Then extract & create a small isolated stand-alone repo without any sensitive code. These typical cause of these errors are documented here, including how to help diagnose them:
https://github.com/ServiceStack/ServiceStack.Redis#debugging-data-corruption-issues

We don't provide Skype support, private email support is available with priority support incidents, if your License doesn't include any priority support incidents they can be purchased separately from https://servicestack.net/account/support

**Comment by Zulphugarli** [comment]
i try to create project but i see that i have an error related to ServiceStack.Interfaces .Error is below:
System.TypeLoadException: 'Could not load type 'ServiceStack.ServiceHost.IService' from assembly 'ServiceStack.Interfaces, Version=3.9.9.0, Culture=neutral, PublicKeyToken=null'.'


I try to different version of  ServiceStack.Interfaces but it does not solve problem.

https://github.com/Zulphugarli/RedisTest

I have publish code ,can you help me?


And also i have write my Configure method

**Comment by mythz** [comment]
Why are you referencing v3x packages? This [Issue Tracker is only for commercial customers of ServiceStack only](https://github.com/ServiceStack/Issues), what is the email of your Customer Account?

**Comment by Zulphugarli** [comment]
Your account hasn't been approved yet. You will be notified by email when you are ready to log in.
