### ISSUE TITLE
Why are you referencing v3x packages? 

### ISSUE THREAD

**Issue by Zulphugarli** [ServiceStack/Issues#739]
Why are you referencing v3x packages? This [Issue Tracker is only for commercial customers of ServiceStack only](https://github.com/ServiceStack/Issues), what is the email of your Customer Account? 

I can't find your email `zulphugarlisahib@gmail.com` or GitHub Username linked to an active subscription. You will need to have an active subscription to access support.

_Originally posted by @mythz in https://github.com/ServiceStack/Issues/issues/738#issuecomment-684214358_

Mr Demis Bellot what did you mean v3x packages?  i have registered from https://servicestack.net/ but then i want to login i see this notification "Your account hasn't been approved yet. You will be notified by email when you are ready to log in."

**Comment by mythz** [comment]
The [Customer Forums](https://forums.servicestack.net/) require a Customer Account purchased from: https://servicestack.net - [You need an active Subscription to use this Issue Tracker](https://github.com/ServiceStack/Issues). 

Either your email needs to have purchased an active license or your GitHub user/email needs to be registered on https://servicestack.net/account/support. Neither your email or GitHub user account is assigned to an Active subscription.
