### ISSUE TITLE
PatchAsync in JsonHttpClient always fails

### ISSUE THREAD

**Issue by mlandtved** [ServiceStack/Issues#744]
Using PatchAsync in JsonHttpClient always throws exception "Allowed HTTP methods 'PATCH' does not support the specified 'PUT' method". I believe it is caused by a bug in JsonHttpClient.cs

Current implementation
`public Task<TResponse> PatchAsync<TResponse>(IReturn<TResponse> requestDto, CancellationToken token = default) =>
            SendAsync<TResponse>(HttpMethods.Patch, ResolveTypedUrl(HttpMethods.Put, requestDto), requestDto);`
Should be changed to:
`public Task<TResponse> PatchAsync<TResponse>(IReturn<TResponse> requestDto, CancellationToken token = default) =>
            SendAsync<TResponse>(HttpMethods.Patch, ResolveTypedUrl(HttpMethods.Patch, requestDto), requestDto);`

**Comment by mythz** [comment]
This should be resolved from the latest v5.10.3+ that's now [available on MyGet](https://docs.servicestack.net/myget).

thx for reporting 👍
