### ISSUE TITLE
CsvSerializer - Better exceptions

### ISSUE THREAD

**Issue by EatonZ** [ServiceStack/Issues#745]
Is it possible to add better exceptions for CSV files that may not be up to snuff?
If I load [this CSV](https://github.com/ServiceStack/Issues/files/5648289/Bad.CSV.zip) with this code, I get this:
```
private sealed class CSVEntry
{
    
}

using (var csvFile = File.OpenRead("Bad CSV.csv"))
{
    var csvEntries = CsvSerializer.DeserializeFromStream<List<CSVEntry>>(csvFile);
}
```
![CSV Crash](https://user-images.githubusercontent.com/3020941/101271647-cbbded80-3752-11eb-8563-d607a698bf87.png)

That exception tells me nothing about the problem. It might be better to fix the code so an exception doesn't happen at all, though. Excel has no problem loading this file, so ServiceStack shouldn't either.😉

**Comment by mythz** [comment]
Excel doesn't have to try deserialize it into a type. The CSV Deserializer is not going to be able to gracefully handle all bad formats - this has a trailing `,` so has an empty/missing header which can't deserialize into a type and what causes the NRE Exception. You'll need to sanitize the input by removing the trailing `,` on all lines and making sure the column count matches the header count.

You're welcome to send a PR but I wont be expending more effort chasing handling bad CSV input.
