### ISSUE TITLE
Populating UserAuth.Meta dictionary prevents Session being saved to MemoryCacheClient

### ISSUE THREAD

**Issue by joeglover** [ServiceStack/Issues#746]
Steps to reproduce:

1. Using the x tool, create a new ServiceStack project from the **mvcauth** template
2. Locate the AppUser class, which inherits UserAuth
3. Add a constructor which adds an entry to the Meta dictionary, as per the code snippet below
4. Run the site and attempt to log in using credentials; restricted pages remain unavailable as the session has not been persisted in memory

Environment details:

- Windows Server 2019 Standard
- ServiceStack v5.10.3

`    // Custom UserAuth Data Model with extended Metadata properties`
`    public class AppUser : UserAuth`
`    {`
`        public AppUser()`
`        {`
`            this.Meta = new Dictionary<string, string> { { "test", "test" } };`
`        }`
`        public string ProfileUrl { get; set; }`
`        public string LastLoginIp { get; set; }`
`        public DateTime? LastLoginDate { get; set; }`
`    }`

**Comment by mythz** [comment]
Should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack/commit/0efcb5976a3fcdd17cf6672611fd60a1a050dfa3) where the `FromToken` flag to set the session was populated in the wrong API which is what prevented sessions from being persisted.

You'll need to [clear your NuGet packages cache](https://docs.servicestack.net/myget#redownloading-myget-packages) to download the latest v5.10.3 containing the fix.

thx for reporting!

**Comment by joeglover** [comment]
Thanks for the quick response! I've pulled the latest from MyGet and can confirm it's resolved the problem in my test project.

Any idea when this might become available as part of an official release via nuGet?

**Comment by mythz** [comment]
Usually NuGet releases wouldn’t be till next major release but may put out a patch release early next year.

**Comment by joeglover** [comment]
Ok, great. Having seen how you fixed the problem, I think I can figure out a workaround which will see us until then.

Thanks once again.
