### ISSUE TITLE
Registration service of auth feature with RavenDbUserAuthRepository throws NotSupportedException

### ISSUE THREAD

**Issue by zeko77** [ServiceStack/Issues#748]
Version: 5.10.5

Module: ServiceStack.Authentication.RavenDb

When I try to register new user via registration service of auth feature I get:
 "errorCode": "NotSupportedException",
"message": "Cannot set identity value 'UserAuths/2-A' on property 'Id' for type 'ServiceStack.Auth.UserAuth' because property type is not a string."

Probably due to usage of UserAuth instead of RavenUserAuth.

**Comment by zeko77** [comment]
I have customized your implementation that solves this by creating consistent Id every time Key property changes.
I have also addressed id parsing with included server tag. 
You can review changes on a fork:
https://github.com/zeko77/ServiceStack
branch: RavenDbRevision

**Comment by mythz** [comment]
Awesome! Can you [sign the Contributor License Agreement](https://docs.google.com/forms/d/e/1FAIpQLSc-vKvdOx5lXGqmy6fkdCj-N0pALkVCx7QHYXojAuDSv_enNA/viewform) and send a PR so I can merge this? thx.

**Comment by zeko77** [comment]
Sure. I will create integration tests and go through session code. As soon as I am done, I'll send PR.

**Comment by mythz** [comment]
thx for the PR! https://github.com/ServiceStack/ServiceStack/pull/1235

**Comment by zeko77** [comment]
Glad to be of assistance. ServiceStack is an excellent product that I have
been using for quite some time. Keep up the great work.
Best regards
