### ISSUE TITLE
ServiceStack.Text.Json: Improper string escaping in JSON serialization for dictionaries with composite keys.

### ISSUE THREAD

**Issue by SteveGuidi** [ServiceStack/Issues#752]
The `JsonSerializer.SerializeToString()` method will convert a dictionary's key to an escaped string if it is an arbitrary reference type, i.e. a custom type representing a composite key.  This is fine except that the serialization produces an improperly escaped string.  Consider the following example.

```
public class Container<TKey>
{
    public IDictionary<TKey, string[]> Data { get; set; } = new Dictionary<TKey, string[]>();
}

public class CompositeKey
{
    public CompositeKey(string name, bool value)
    {
        Name = name;
        Value = value;
    }


    public string Name { get; set; }
    public bool Value { get; set; }


    public override bool Equals(object obj)
    {
        return Name != null &&
               Name.Equals((obj as CompositeKey)?.Name);
    }

    public override int GetHashCode()
    {
        return Name?.GetHashCode() ?? 0;
    }
}

public class Test
{
    public static void Main()
    {
        Container<CompositeKey> c1 = new Container<CompositeKey>
        {
            Data = new Dictionary<CompositeKey, string[]>
            {
                { new CompositeKey("abc", false), new[] { "1","2","3"} },
                { new CompositeKey("bdf", true), new[] { "b","c","d"} },
                { new CompositeKey("ceg", false), new[] { "4","5","6"} },
            }
        };

        string serialized = JsonSerializer.SerializeToString(c1);
        Console.WriteLine("Serialized:");
        Console.WriteLine(serialized);

        Container<CompositeKey> c2 = JsonSerializer.DeserializeFromString<Container<CompositeKey>>(serialized);
        Console.WriteLine($"Deserialized key count: {c2.Data.Count}");
    }
}
```

The `Data` dictionary above is serialized to the following string.

`{"Data":{"{\"Name\":"abc",\"Value\":false}":["1","2","3"],"{\"Name\":"bdf",\"Value\":true}":["b","c","d"],"{\"Name\":"ceg",\"Value\":false}":["4","5","6"]}}`

Note that the first serialized key is the following: `"{\"Name\":"abc",\"Value\":false}"`

The component of the string `"abc"` does not have escaped quotation marks, so the string is prematurely terminated and the resulting deserialization will never succeed.

The string should be serialized as: `"{\"Name\":\"abc\",\"Value\":false}"`

**Comment by mythz** [comment]
[json](https://www.json.org/json-en.html) requires a string for its key so using a serialized reference type should be avoided, the serializer expects the key to be a scalar string value and I don't want to extend it to support reference type keys as strings which shouldn't be used.

I'd suggest instead to use a struct which is more appropriate for identity's like composite keys so they retain value type semantics, e.g:

```csharp
public struct CompositeKey
{
    public string Name { get; set; }
    public bool Value { get; set; }
    public CompositeKey(string name, bool value)
    {
        Name = name;
        Value = value;
    }

    public CompositeKey(string jsonKey)
    {
        Name = jsonKey.LeftPart(':');
        Value = jsonKey.RightPart(':').ConvertTo<bool>();
    }

    public bool Equals(CompositeKey other) => 
        Name == other.Name && Value == other.Value;

    public override bool Equals(object obj) => 
        obj is CompositeKey other && Equals(other);

    public override int GetHashCode()
    {
        unchecked
        {
            return ((Name != null ? Name.GetHashCode() : 0) * 397) 
                   ^ Value.GetHashCode();
        }
    }

    public override string ToString() => $"{Name}:{Value}";
}
```

Which follows the [Structs and Value Type behavior](https://github.com/ServiceStack/ServiceStack.Text#c-structs-and-value-types) where its `ToString()` value is used to serialize and its string constructor is used to deconstruct from a serialized json key.

I've added a test with a working example in [CompositeKeyIssue.cs](https://github.com/ServiceStack/ServiceStack.Text/blob/master/tests/ServiceStack.Text.Tests/Issues/CompositeKeyIssue.cs).

> Note: All Reference Type DTOs should have a parameter-less constructor to avoid the serializer from resorting to use `FormatterServices.GetUninitializedObject()` to create instances.
