### ISSUE TITLE
JSON.parse doesn't work well with an array of objects

### ISSUE THREAD

**Issue by LorneCash** [ServiceStack/Issues#753]
given the following string:
`var json = "[{a:1},{a:2}]"`

This works:
`var tests = (List<object>)JSON.parse(json );`

And this works:
`var tests = (List<object>)JSON.parse(json );`
`var test = (Dictionary<string, object>)test[0];`

But I can't have this or it throws an exception:
`var tests = (List<Dictionary<string, object>>)JSON.parse(json );`

**Comment by mythz** [comment]
This is [invalid JSON](http://json.org/):

```
var json = "[{a:1},{a:2}]"
```

Where all keys need to be quoted, i.e:

```csharp
var json = "[{\"a\":1},{\"a\":2}]";
```
