### ISSUE TITLE
Dart: Unable to set headers using requestFilters

### ISSUE THREAD

**Issue by rockgecko-development** [ServiceStack/Issues#757]
For Flutter apps, I use `JsonServiceClient.globalRequestFilter` to set the user-agent header. A recent change to the ServiceStack client lib has moved the call to `req.write(bodyStr)` _before_ the filters are called. It used to be after. I now get an error saying the request headers are immutable.

The Flutter documentation for the `write` method states:
>The client request headers can be modified until the client request body is written to or closed. After that they become immutable.

**Comment by mythz** [comment]
The latest release servicestack dart library has this update.
