### ISSUE TITLE
OpenApi showing petstore when additional slashes used in url

### ISSUE THREAD

**Issue by bdocrex** [ServiceStack/Issues#762]
When using the OpenApiFeature up to and including ServiceStack.Api.OpenApi v5.12, placing additional slashes before swagger-ui in the url will reveal the petstore demo page.

For example
http://mydomain.com//swagger-ui
http://mydomain.com/////swagger-ui

This can be reproduced using the selfhost sample
https://github.com/NetCoreTemplates/selfhost.git
Using a url that is not "localhost" and the following line added to the AppHost.Configure method:
`Plugins.Add(new OpenApiFeature());`

**Comment by mythz** [comment]
This should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack/commit/853ecb4863bae56ba015a656047378adc45bb63d).

This change is available from v5.12.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

thx for reporting 👍
