### ISSUE TITLE
Queries with OrderBy produces bad SQL in 5.12

### ISSUE THREAD

**Issue by dlj** [ServiceStack/Issues#763]
Hello

After updating to 5.12, queries with OrderBy started to add "AS" to the expression if a column had an Alias. 

Small test using SqlLite has been added. It also happens on SQLServer.

[OrmLite.OrderByProblem.zip](https://github.com/ServiceStack/Issues/files/7090750/OrmLite.OrderByProblem.zip)

**Comment by mythz** [comment]
This should be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.OrmLite/commit/b245e3184709cc5a7f91780ec8b6782234f11c90).

This change is available from v5.12.1+ that's now [available on MyGet](https://docs.servicestack.net/myget).

Thanks for the repro 👍
