### ISSUE TITLE
AutoQuery filtering should respect CustomSelect

### ISSUE THREAD

**Issue by AVee** [ServiceStack/Issues#767]
Currently AutoQuery seems to only partially respect CustomSelect attributes. They are used in select statements and order by clauses but not when applying filters. For filtering to work as expected a CustomSelect should be used when building the where clause as well.

I'll create a PR with a potential fix and a test shortly.

**Comment by mythz** [comment]
The PR for this feature was much appreciated, thx 👍 https://github.com/ServiceStack/ServiceStack/pull/1254

**Comment by AVee** [comment]
Thanks, that will allow us to do some nifty UI stuff 😁
