### ISSUE TITLE
IDbConnection.UpdateOnly does not work with request.ConvertTo()

### ISSUE THREAD

**Issue by labilbe** [ServiceStack/Issues#769]
Occurs in ServiceStack v5.13.1

`db.UpdateOnly(() => request.ConvertTo<Setting>());`

Error occurs in `void PrepareUpdateRowStatement<T>(IDbCommand dbCmd, Dictionary<string, object> args, string sqlFilter)` (Object reference not set to a reference of an object)

Expected behavior is an update on all rows of the table.

**Comment by mythz** [comment]
UpdateOnly method requires a Constructor Expression which is what OrmLite scans to determine which properties to update, e.g:

```csharp
db.UpdateOnly(() => new Setting { Id = ... }));
```

To update an instance you need to use what's been [renamed to UpdateOnlyFields in v5.13+](https://docs.servicestack.net/releases/v5_13#breaking-changes):

```csharp
db.UpdateOnlyFields(request.ConvertTo<Setting>(), onlyFields: p => new { p.Name, p.Age });
```
