### ISSUE TITLE
ServerEventsFeature WriteEventsAsync callback should use cancellation token

### ISSUE THREAD

**Issue by filipsky** [ServiceStack/Issues#774]
Hi, we have come across the situation that the ServerEventsFeature hangs randomly for long time on faulty network.
We tried to use cancellation token to mitigate the problem, but found out that the 
ServerEventsFeature.WriteEventsAsync callback does not use the callback

I understand we can't prepare the repro, so I will create a PR if you're interested

**Comment by mythz** [comment]
Thx for the PR! If needed this change is now available from v6.0.3+ that's now [available on MyGet](https://docs.servicestack.net/myget)
