### ISSUE TITLE
JwtAuthProviderReader problem with RequiresAudience 

### ISSUE THREAD

**Issue by catmanjan** [ServiceStack/Issues#775]
### Describe the issue

If I call JwtAuthProviderReader.GetValidJwtPayload on my JWT it works as expected.

The first item in the payload is {[aud, api://22a6b621-fc19-4e08-9cad-c4b64ab7105b]}

If I set jwt.Audience to api://22a6b621-fc19-4e08-9cad-c4b64ab7105b and jwt.RequiresAudience to true in my appsettings.json, JwtAuthProviderReader.GetValidJwtPayload now returns null and my services are returning the error:

{
    "responseStatus": {
        "errorCode": "TokenException",
        "message": "Invalid Audience: api://22a6b621-fc19-4e08-9cad-c4b64ab7105b",
        "errors": []
    }
}

### Reproduction

Set up JwtAuthProviderReader as normal, check everything is working

Now enable jwt.RequiresAudience and it no longer works

### Expected behavior

RequiresAudience should allow the token to be validated

### System Info

```shell
Servicestack 6, .NET 6
```

### Additional context

This probably isn't the place, but could you please enable my Servicestack forum account?

### Validations

- [X] Read the [docs](https://docs.servicestack.net).
- [X] Have an active ServiceStack License _(GitHub Username can be [registered on Support page](https://account.servicestack.net/account/support))_.

**Comment by catmanjan** [comment]
I just had quick look at the repo and I believe the issue is that HasInvalidAudience will never return false when RequiresAudience is true

**Comment by mythz** [comment]
Invalid Audiences should now be validated in [this commit](https://github.com/ServiceStack/ServiceStack/commit/97a10730028470f6c3f70912b60f7266c3294c0f).

This change is now available from [v6.1.1 on MyGet](https://docs.servicestack.net/myget)

**Comment by catmanjan** [comment]
Is the function meant to return true if any of the audiences don’t match
the configured audiences? I think this change will return false if any of
the audiences are correct

**Comment by mythz** [comment]
> I think this change will return false if any of
the audiences are correct

Right, multiple `aud` in JWT's is a niche case that I couldn't find any conclusive determination on what the correct default behavior should be in this case and the [spec is also vague](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.3):

> The interpretation of audience values is generally application specific.

What's your use case for having multiple audiences in a JWT?

**Comment by catmanjan** [comment]
Good point I just assumed it was part of spec, but I can see why that would be a problem!
