### ISSUE TITLE
 is not a valid ServiceStack endpoint or Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by AcarFurkan** [ServiceStack/Issues#778]
### Describe the issue

l use servicestach on androidstudio for flutter. but l tried wcf add reference same link and generation was good. same link throw error when l use servicestack 
<img width="644" alt="image" src="https://user-images.githubusercontent.com/65075121/178363144-c81e977d-35c1-4c1f-b405-091d631fc624.png">
<img width="644" alt="image" src="https://user-images.githubusercontent.com/65075121/178363171-90e58cf8-4a76-4bab-80fa-3e17c79cc632.png">
l am a beginner could you help me ??

### Reproduction

l am a beginner sorry l dont how to generate code.

### Expected behavior

I expect to be able to do the same thing I did when adding the add wcf reference in .net.(in dart)

### System Info

```shell
dart-flutter
```

### Additional context

<img width="644" alt="image" src="https://user-images.githubusercontent.com/65075121/178363476-c8308b20-8904-408a-8b75-ea2d1dfdb6b9.png">
<img width="644" alt="image" src="https://user-images.githubusercontent.com/65075121/178363490-c1b94ea2-73d5-49e6-8fdf-7d544ed79251.png">

### Validations

- [X] Read the [docs](https://docs.servicestack.net).
- [X] Have an active ServiceStack License _(GitHub Username can be [registered on Support page](https://account.servicestack.net/account/support))_.

**Comment by mythz** [comment]
The [Add ServiceStack Reference](https://docs.servicestack.net/add-servicestack-reference) feature is only for ServiceStack APIs, not WCF SOAP web services.

**Comment by AcarFurkan** [comment]
Do you have any suggestions for soap services?

**Comment by Layoric** [comment]
@AcarFurkan It is an uncommon use case I think, likely you would have to add additional support to your host using WSDL to support client generation like OpenAPI. Locking conversation since this is out of scope for this issues list and unrelated to ServiceStack.
