### ISSUE TITLE
TryAuthenticate method of CustomAuthProvider not getting executed

### ISSUE THREAD

**Issue by G-Shriya** [ServiceStack/Issues#785]
TryAuthenticate method of CustomAuthProvider which extends BasicAuthProvider and IAuthProvider not getting executed when:
Authentication with a particular username is done, page after successful authentication is refreshed and again logged in with correct same previous credentials, execution is not passing through TryAuthenticate and OnAuthenticated methods

**Comment by mythz** [comment]
Please complete the full issue template when opening priority issues here, confirming that you have an active subscription by registering your GitHub Username in your [Customer Account Support page](https://account.servicestack.net/account/support) and providing full context on [reproducible issues](https://github.com/ServiceStack/Issues#you-can-view-existing-issues-or-report-a-new-issue) including steps to repro and any Exception StackTraces where applicable.
