### ISSUE TITLE
Issue with session being null after refresh

### ISSUE THREAD

**Issue by G-Shriya** [ServiceStack/Issues#786]
### Describe the issue

https://github.com/ServiceStack/Issues/issues/399

Facing the same issue while using ServiceStack version 4.5

### Reproduction

https://github.com/ServiceStack/Issues/issues/399

### Expected behavior

https://github.com/ServiceStack/Issues/issues/399

### System Info

```shell
.NET 4.6.2
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
You've indicated your GitHub Username is registered but there's no such support contact registered with your GitHub username.

This report is also insufficient and does not contain a repro with the latest version of ServiceStack.
