### ISSUE TITLE
ServerEventsClient.cs Start Method using Send throws PlattformNotSupported Exception (on Mobile Platform)

### ISSUE THREAD

**Issue by oezyurt** [ServiceStack/Issues#787]
### Describe the issue

in our Android/iOS Core Net6 Project the method ServerEventsClient.Connect() throw an exception "PlattformNotSupported" 

```
client = new ServerEventsClient(this.BaseUri);
await client.Connect();

   at System.Net.Http.HttpClientHandler.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.Send(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.Send(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
```

### Reproduction

This ServiceStack code throw the exeception in class **ServerEventsClient**

<img width="1466" alt="2023-01-23_13h07_34" src="https://user-images.githubusercontent.com/123966081/215555994-80672bf7-a942-4c5c-88b5-7911ade8f280.png">

We implemented a Workaround that's work, but...
(Invoke Custom HttpClientHandler that override the Send Method)

```
client = new ServerEventsClient(this.BaseUri)
      {
          HttpClientHandlerFactory = (x) => { return this.HttpClientHandlerFactory?.Invoke(); },
      }
....
    internal class ServiceStackHttpClientHandler : HttpClientHandler
    {
        public ServiceStackHttpClientHandler()
        {
        }

        protected override HttpResponseMessage Send(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var task = this.SendAsync(request, cancellationToken);
            return task.GetAwaiter().GetResult();
        }
    }
```

in Android this workaround fire Warnings ...

Core6 throwing the Exception here:

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.AnyMobile.cs

<img width="933" alt="2023-01-30_19h09_04" src="https://user-images.githubusercontent.com/123966081/215559617-643d404b-3722-4a0c-ae45-ca0d37209598.png">

### Expected behavior

Please Fix the issue for Mobile Core Net6

### System Info

```shell
Visual Studio 22
ServiceStack v6.5
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
I've added an async `StartAsync()` overload in [this commit](https://github.com/ServiceStack/ServiceStack/commit/985079c5e1159c42ed52627114a5651a0fb01f60) which is now available in the latest [v6.5.1+ on MyGet](https://docs.servicestack.net/myget).

Can you try to see if using the new non-blocking `StartAsync()` method resolves this issue.

**Comment by oezyurt** [comment]
Thx, I think the ReStart Method includes the same issue ... the OnExceptionReceived Event includes the Restart()

**Comment by mythz** [comment]
I've updated .NET 6+ clients to call `StartAsync()` on Restart in [this commit](https://github.com/ServiceStack/ServiceStack/commit/46bb5e410a60874e316c65f1f81595ed3638736b), this change is now available on MyGet, you'll need to [clear your NuGet packages cache](https://docs.servicestack.net/myget#redownloading-myget-packages) to download the latest version.

**Comment by oezyurt** [comment]
Thx, i can confirm your commit fix the issue for me
