### ISSUE TITLE
servicestack.net/start-netfx download project returns '404 not found'

### ISSUE THREAD

**Issue by DigitalQuarter** [ServiceStack/Issues#790]
Downloading any of the .net framework projects returns 'HttpRequestException
Response status code does not indicate success: 404 (Not Found).'

Steps:

1. open url 'https://servicestack.net/start-netfx'
2. click on any of the displayed projects
3. excpected result: zip file starts downloading
   actual result: redirected to page that displays 'HttpRequestException
Response status code does not indicate success: 404 (Not Found).'

**Comment by mythz** [comment]
This should now be resolved, thanks for reporting!
