### ISSUE TITLE
ServiceStack.InputAttributeBase Step property is of type Int. Doesn't support decimals.

### ISSUE THREAD

**Issue by ImagineITDev** [ServiceStack/Issues#795]
### Describe the issue

public class InputAttributeBase : MetadataAttributeBase
{
    public string Type { get; set; }
    public string Value { get; set; }
    public string Placeholder { get; set; }
    public string Help { get; set; }
    public string Label { get; set; }
    public string Title { get; set; }
    public string Size { get; set; }
    public string Pattern { get; set; }
    public bool ReadOnly { get; set; }
    public bool Required { get; set; }
    public bool Disabled { get; set; }
    public string Autocomplete { get; set; }
    public string Autofocus  { get; set; }
    public string Min { get; set; }
    public string Max { get; set; }
    public int Step { get; set; } = int.MinValue; <- No support For Decimals
    public int MinLength { get; set; } = int.MinValue;
    public int MaxLength { get; set; } = int.MinValue;
    public string Accept  { get; set; }
    public string Capture  { get; set; }
    public bool Multiple { get; set; }
    public string[] AllowableValues { get; set; }
    public Type AllowableValuesEnum { get; set; }
    public string Options  { get; set; }
    public bool Ignore { get; set; }
    public string EvalAllowableValues { get; set; }
    public string EvalAllowableEntries { get; set; }
}

### Reproduction

N/A 

### Expected behavior

Should be string? "Any" or "0.1"

### System Info

```shell
ServiceStack Blazor Server / Tailwind.
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
`Step` has been changed to a `string` in [this commit](https://github.com/ServiceStack/ServiceStack/commit/3136d9e708437e9e29ae32e6a2467619d24c1590), this change is available from v6.10.1+ that's now [available in the Pre Release NuGet packages](https://docs.servicestack.net/pre-release).

**Comment by ImagineITDev** [comment]
Perfect! Thank you!
