### ISSUE TITLE
Free-quota limit on '6000 Redis requests per hour' error with Commercial License

### ISSUE THREAD

**Issue by VassiliSrithammavanh-KSO** [ServiceStack/Issues#799]
### Describe the issue

I purchased a COMMERCIAL license 11 days ago. Everything worked correctly during these 11 days.

But today, I get systematically the error message : "ServiceStack.LicenseException: The free-quota limit on '6000 Redis requests per hour' has been reached".

Then my computation fails.  

### Reproduction

The problem occurs systematically when I run my ServiceStack based application. 

### Expected behavior

Not to have such a limitation for my application, because it is a commercial license.

### System Info

```shell
ServiceStack.Redis 6.11.0, .NET6
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by VassiliSrithammavanh-KSO** [comment]
As explained in documentation:
- the license is in my App.config's <appSettings/> config section.
- the license  is also in System Environment variable SERVICESTACK_LICENSE
In spite of that, I get this '6000 Redis requests per hour' error.

**Comment by mythz** [comment]
As mentioned in the [Customer Forums](https://forums.servicestack.net/t/6000-redis-requests-per-hour-error-with-commercial-license/11884/2) this License Exception suggests that the License Key is not properly registered with the Application throwing the Exception.

If you have registered it with `SERVICESTACK_LICENSE`, make sure it's accessible from the App that's throwing the Exception. i.e. verify that the App that's throwing the Exception can access the environment variable with `Environment.GetEnvironmentVariable("SERVICESTACK_LICENSE")`.

**Comment by VassiliSrithammavanh-KSO** [comment]
Thank you for your support. I am going to check.
