### ISSUE TITLE
Bug in TypeSerializer when Serialize and Deserialize NameValueCollection

### ISSUE THREAD

**Issue by vzsoft** [ServiceStack/Issues#800]
### Describe the issue

Hi,
I got error in `TypeSerializer` when Deserialize type `NameValueCollection`
and  Serialize not correct 

### Reproduction

code in C#:
```javascript
            var nvc = new NameValueCollection();
            nvc.Add("A", "Test1");
            nvc.Add("B", "Test2");
            var text = TypeSerializer.SerializeToString(nvc); //result not correct 
            var deserialize = TypeSerializer.DeserializeFromString<NameValueCollection>(text); //Error
```

### Expected behavior

correct result in SerializeToString
`{A:Test1,B:Test2}`

### System Info

```shell
Windows 10
ServiceStack.Text 6.11
```

### Additional context

sry my english not good 

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
`NameValueCollection` is not a serializable class, but you can convert it to an Object Dictionary and serialize that:

```csharp
var text = TypeSerializer.SerializeToString(nvc.ToObjectDictionary()); 
var deserialize = TypeSerializer.DeserializeFromString<Dictionary<string,object>>(text); 
```

Although when dealing with adhoc or unstructured types like `Dictionary<string,object>` we recommend using the [JSON Utils](https://docs.servicestack.net/js-utils) in ServiceStack.Common instead, e.g:

```csharp
var json = JSON.stringify(nvc.ToObjectDictionary());
var fromJson = JSON.parse(json);
fromJson.PrintDump();
```

The ServiceStack.Text is better suited for de/serializing from known Types.
