### ISSUE TITLE
Redis Sentinel Failover

### ISSUE THREAD

**Issue by dhanson-opentable** [ServiceStack/Issues#802]
### Describe the issue

Unhandled exception when getting a ready-only client from PooledRedisClientManager when the first of multiple sentinel hosts is down.

### Reproduction

https://github.com/ServiceStack/ServiceStack/pull/1330

This PR includes two parts:
1. an integration test that shuts down the first of three sentinel hosts before attempting to get a read-only client and request a value from redis.
2. a simple fix, nearly identical to how the GetMasterHost function is implemented.

### Expected behavior

The library should catch the unhandled exception, trigger the error callback which will force the library to connect to the next available sentinel host.

### System Info

```shell
.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/7.0.306/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  3.1.426 [/usr/share/dotnet/sdk]
  6.0.412 [/usr/share/dotnet/sdk]
  7.0.306 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
Thanks for the PR! Can you please accept the [Contributor License Agreement](https://docs.google.com/forms/d/16Op0fmKaqYtxGL4sg7w_g-cXXyCoWjzppgkuqzOeKyk/viewform) so we can merge this, thanks.

**Comment by mythz** [comment]
Thanks, I've just merged the PR. We plan on releasing a new version on NuGet early next week.
