### ISSUE TITLE
Documentation Broken Link

### ISSUE THREAD

**Issue by Tobias-Werner-Recom** [ServiceStack/Issues#803]
### Describe the issue

I found a broken link in the documentation. In the documentation https://docs.servicestack.net/service-gateway#service-discovery under the section Designing for Microservices in the first paragraph the second link in the first sentence is broken. The link directs to https://channel9.msdn.com/events/Build/2016/C918 but the result is a generic page https://learn.microsoft.com/de-de/shows/.

Is this the right page to report this? I do not have a license linked to my account

### Reproduction

1. open https://docs.servicestack.net/service-gateway#service-discovery
2. click second link [designing for Microservices](https://channel9.msdn.com/events/Build/2016/C918)
3. resulting in page https://learn.microsoft.com/de-de/shows/. Only tested for Germany

### Expected behavior

Link to an article with theme designing for Microservices

### System Info

```shell
Firefox 122.0.1 (64-Bit), Location Germany
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
Thanks, I've removed the link from [this commit](https://github.com/ServiceStack/docs.servicestack.net/commit/bab1d3fbcbb1279d2f994817132a3d9ec39d742b). 

For any issues with docs you can click the **Edit this page on GitHub** link at the bottom of each page and edit the directly page on GitHub.
