### ISSUE TITLE
x Typescript Dto Generation wrong for classes with base class

### ISSUE THREAD

**Issue by Cynicszm** [ServiceStack/Issues#804]
### Describe the issue

We are using x version 8.0.0  with x ts <server>and the generated dtos are wrong for classes with a base class.

### Reproduction

1. x new mvc-bootstrap
2. build
3. x ts <url>
4. open generated dtos
5. check classes with a base class e.g. export class Booking extends AuditBase
6. Generated Booking class includes all the AuditBase properties instead of just the Booking properties 

### Expected behavior

I would expect any class with a base to be generated as

export ClassName extends BaseClass
{
   Only ClassName properties
}

### System Info

```shell
.NET 8, x version 8.0.0
```

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
Thanks for reporting, this issue has already been resolved in the [Pre Release packages](https://docs.servicestack.net/pre-release).
