### ISSUE TITLE
ServiceStack dotnet tool does not properly handle generics in generated Dart DTOs

### ISSUE THREAD

**Issue by luthda** [ServiceStack/Issues#808]
### Describe the issue

When using the ServiceStack dotnet tool with `x dart`as the command to generate Dart DTOs from a C# ServiceStack project, the generic class PagedResult<T> is not correctly converted to a generic type in Dart. Instead, the generated Dart code has the property results as type List<FooDto>, even though PagedResult<T> is a generic class designed to work with any type T. This breaks the intended flexibility of the generic type.

Additionally, the generated Dart type context includes the following issue:
```dart
'PagedResult<T>': TypeInfo(TypeOf.Class, create: () => PagedResult<T>()), 
```

This results in the error:
```
The name 'T' isn't a type, so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'T'.dart[non_type_as_type_argument](https://dart.dev/diagnostics/non_type_as_type_argument)
```

This error occurs because T is not defined as a type in the Dart context, and the generated code does not provide enough information for Dart to infer or handle the generic type correctly.

### Reproduction

1. Define the following classes in a C# ServiceStack project:

```c#
public class PagedResult<T>
{
    public int Page { get; set; }
    public int PageSize { get; set; }
    public long TotalResults { get; set; }

    public List<T> Results { get; private set; }

    public PagedResult()
    {
        Results = new List<T>();
    }

    public PagedResult(List<T> results, int page, int pageSize, long totalResults)
    {
        if (results == null)
        {
            Results = new List<T>();
        }
        else
        {
            Results = results;
        }

        Page = page;
        PageSize = pageSize;
        TotalResults = totalResults;
    }

    public PagedResult(List<T> results, PagedRequest request, long totalResults)
        : this(results, request.Page, request.PageSize, totalResults)
    {
    }
}

public abstract class PagedAndOrderedRequest : PagedRequest
{
    [ApiMember(AllowMultiple = false, DataType = "string", Description = "Comma- or semicolon separated list of fields to sort by. To change sort order add a '-' in front of the field", IsRequired = false, Name = "OrderBy", ParameterType = "query", Verb = "GET")]
    public string OrderBy { get; set; }
}

[Route("/foos", "GET"]
public class GetFoos : PagedAndOrderedRequest, IReturn<PagedResult<FooDto>>
{
    public string Query { get; set; }
}
```

2. Run the `x dart` to generate Dart DTOs.
3. Observe the generated Dart code for PagedResult<T>. Instead of correctly preserving the generic type T, the results property is of type List<FooDto>.
Generated Dart Code:
```dart

class PagedResult<T> implements IConvertible
{
    int? page;
    int? pageSize;
    int? totalResults;
    List<FooDto>? results; // should preserve generic type

    PagedResult({this.page,this.pageSize,this.totalResults,this.results});
    PagedResult.fromJson(Map<String, dynamic> json) { fromMap(json); }

    fromMap(Map<String, dynamic> json) {
        page = json['page'];
        pageSize = json['pageSize'];
        totalResults = json['totalResults'];
        results = JsonConverters.fromJson(json['results'],'List<FooDto>',context!); // should preserve generic type
        return this;
    }

    Map<String, dynamic> toJson() => {
        'page': page,
        'pageSize': pageSize,
        'totalResults': totalResults,
        'results': JsonConverters.toJson(results,'List<FooDto>',context!) // should preserve generic type
    };

    getTypeName() => "PagedResult<$T>";
    TypeContext? context = _ctx;
}

'PagedResult<T>': TypeInfo(TypeOf.Class, create:() => PagedResult<T>()), // in TypeContext _ctx with error as described
``` 

### Expected behavior

The generated Dart DTOs should maintain the generic nature of PagedResult<T>. The results property should remain generic as List<T>?, and the Dart type context should properly handle the generic type T.

### System Info

```shell
OS: macOS Sonoma 14.7.1
ServiceStack Version: 8.5.2
Project Type: .NET 8.0.11
dotnet tool:
- Version: 8.0.2
- ServiceStack: 8.53
- Framework: .NET 8.0.11
- OS: Unix 14.7.1
```

### Additional context

This issue limits the flexibility of the generated Dart DTOs for our project and requiring manual adjustments to restore the correct behavior.

Let me know if you need any further details!

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
Your GitHub username isn't listed as a registered support contact, please add it to your Customer Account's Registered Licensed Developers page: https://account.servicestack.net/account/support

**Comment by luthda** [comment]
@mythz added my GitHub account to our customer account

**Comment by mythz** [comment]
Thanks, although this might already be fixed as it looks like it's generating the correct class:

```dart
class PagedResult<T> implements IConvertible
{
    int? page;
    int? pageSize;
    int? totalResults;
    List<T>? results = [];

    PagedResult({this.page,this.pageSize,this.totalResults,this.results});
    PagedResult.fromJson(Map<String, dynamic> json) { fromMap(json); }

    fromMap(Map<String, dynamic> json) {
        page = json['page'];
        pageSize = json['pageSize'];
        totalResults = json['totalResults'];
        results = JsonConverters.fromJson(json['results'],'List<${runtimeGenericTypeDefs(this,[0]).join(",")}>',context!);
        return this;
    }

    Map<String, dynamic> toJson() => {
        'page': page,
        'pageSize': pageSize,
        'totalResults': totalResults,
        'results': JsonConverters.toJson(results,'List<T>',context!)
    };

    getTypeName() => "PagedResult<$T>";
    TypeContext? context = _ctx;
}
```

Can you try with v8.5.3+ that's available in our [pre release packages](https://docs.servicestack.net/pre-release).

**Comment by luthda** [comment]
Yes, with v8.5.3 the dtos are generated correctly.

Thanks!
