### ISSUE TITLE
Dart compilation error due to generic type parameter <T> in TypeContext

### ISSUE THREAD

**Issue by luthda** [ServiceStack/Issues#809]
### Describe the issue

Following the resolution of [#808](https://github.com/ServiceStack/Issues/issues/808), generic DTOs like PagedResult<T> are now correctly generated as Dart classes with a generic type parameter T. However, the generated TypeContext still contains a problematic entry:

```dart
'PagedResult<T>': TypeInfo(TypeOf.Class, create:() => PagedResult<T>()),
```
This line fails to compile in Dart because T is not defined as a concrete type in this context. The Dart compiler reports the following error:
```
The name 'T' isn't a type, so it can't be used as a type argument.
Try correcting the name to an existing type, or defining a type named 'T'.dart non_type_as_type_argument
```

Since we do not directly use PagedResult<T> in the Dart code (only its concrete implementations like PagedResult<FooDto>), our current workaround is to manually remove the above line from the generated TypeContext or run a post-processing script after the dto generation to achive the same result.

### Reproduction

1. Generate Dart DTOs for a ServiceStack project containing a generic C# class PagedResult<T>:
```csharp
public class PagedResult<T>
{
    public int Page { get; set; }
    public int PageSize { get; set; }
    public long TotalResults { get; set; }

    public List<T> Results { get; private set; }

    public PagedResult()
    {
        Results = new List<T>();
    }

    public PagedResult(List<T> results, int page, int pageSize, long totalResults)
    {
        if (results == null)
        {
            Results = new List<T>();
        }
        else
        {
            Results = results;
        }

        Page = page;
        PageSize = pageSize;
        TotalResults = totalResults;
    }

    public PagedResult(List<T> results, PagedRequest request, long totalResults)
        : this(results, request.Page, request.PageSize, totalResults)
    {
    }
}
```

2. After running x dart, the generated Dart code for PagedResult<T> appears correctly as a generic class:
```dart
class PagedResult<T> implements IConvertible {
    int? page;
    int? pageSize;
    int? totalResults;
    List<T>? results;

    PagedResult({this.page,this.pageSize,this.totalResults,this.results});
    PagedResult.fromJson(Map<String, dynamic> json) { fromMap(json); }

    fromMap(Map<String, dynamic> json) {
        page = json['page'];
        pageSize = json['pageSize'];
        totalResults = json['totalResults'];
        results = JsonConverters.fromJson(json['results'],'List<${runtimeGenericTypeDefs(this,[0]).join(",")}>',context!);
        return this;
    }

    Map<String, dynamic> toJson() => {
        'page': page,
        'pageSize': pageSize,
        'totalResults': totalResults,
        'results': JsonConverters.toJson(results,'List<T>',context!)
    };

    getTypeName() => "PagedResult<$T>";
    TypeContext? context = _ctx;
}
```

3. However, the TypeContext still includes:
```dart
'PagedResult<T>': TypeInfo(TypeOf.Class, create:() => PagedResult<T>()),
```

Attempting to compile this Dart code leads to the error described above.

### Expected behavior

As far as I understand, Dart’s type system doesn’t permit treating a bare type parameter like T as a concrete type at runtime without proper type constraints or context.

To potentially avoid this compilation error, it may be better if the code generation refrains from directly including a TypeContext entry for the generic definition PagedResult<T>. Instead, it could focus on generating entries only for concrete instantiations of the generic class, such as PagedResult<FooDto> or PagedResult<BarDto>. By registering each of these concrete types at compile time with fully resolved type parameters, Dart would have a clearer understanding of the referenced types, which might help maintain proper type safety and enable successful compilation.

### System Info

```shell
OS: macOS Sonoma 14.7.1
ServiceStack Version: 8.5.3 (pre-release)
Project Type: .NET 8.0.x
dotnet tool:
- Version: 8.0.2
- ServiceStack: 8.53
- Framework: .NET 8.0.x
- OS: Unix 14.7.1
```

### Additional context

This issue is related to [#808](https://github.com/ServiceStack/Issues/issues/808), which resolved a similar problem where the PagedResult<T> class was not previously generated as a generic type.

Currently, our solution is to remove the problematic line from the TypeContext. However, a long-term fix should ensure that the generated Dart code does not attempt to create TypeInfo entries for generic definitions that cannot be represented at runtime in Dart.

### Validations

- [X] Confirm [Issue is reproducible](https://github.com/ServiceStack/Issues#how-to-create-a-good-bug-report) from the information provided
- [X] Have an active commercial ServiceStack License _(GitHub Username is [registered on Support page](https://account.servicestack.net/account/support))_

**Comment by mythz** [comment]
Can you try with the latest v8.5.3 that's now available in pre-release packages. As you already have v8.5.3 installed you'll need to [Clear your NuGet packages cache](https://docs.servicestack.net/pre-release#clear-nuget-package-cache) to download the latest version.

```sh
dotnet nuget locals all --clear
```

**Comment by luthda** [comment]
Yes it works as expected and generates the following line in the TypeContext, which can be interpreted by Dart:
```dart
'PagedResult<T>': TypeInfo(TypeOf.GenericDef,create:() => PagedResult()),/*2*/
```

**Comment by luthda** [comment]
@mythz Kudos for the fast response time lately.

Keep up the good work!

**Comment by mythz** [comment]
Cool, also just noticed I left the `/*2*/` debug comments in output, they've now been removed in the latest v8.5.3+.
